pulibrary/figgy

config/valkyrie.yml
spec/change_set_persisters/plum_change_set_persister_spec.rb

It's more accurate, and the runtime is basically the same.

Test Postgres in CI

---

app/characterization_services/tika_file_characterization_service.rb
app/helpers/osd_modal_helper.rb
app/jobs/characterization_job.rb
app/models/file_set.rb
app/services/file_appender.rb
app/services/manifest_builder.rb
app/services/riiif_resolver.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/characterization_services/tika_file_characterization_service_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/derivative_services/jp2_derivative_service_spec.rb
spec/helpers/osd_modal_helper_spec.rb
spec/services/riiif_resolver_spec.rb

There's no need to manage two nodes per FileSet when we can just embed
it and get better performance even.

Embed FileMetadata inside FileSets

---

app/decorators/scanned_resource_decorator.rb
app/decorators/valkyrie/resource_decorator.rb
app/models/imported_metadata.rb
app/models/schema/dublin_core.rb
spec/views/catalog/show.html.erb_spec.rb

Resolves #20 and #93 by delegating ScannedResourceDecorator accessor methods to primary_imported_metadata (with the prefix "imported_") and explicitly exposing these prefixed values within "display_attributes".

Renders imported metadata for ScannedResources

---

Gemfile
Gemfile.lock
app/change_set_persisters/plum_change_set_persister.rb
app/change_sets/scanned_resource_change_set.rb
app/models/remote_record.rb
app/services/identifier_service.rb
app/validators/state_validator.rb
config/initializers/ezid.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/services/identifier_service_spec.rb
spec/support/stub_ezid.rb
spec/validators/state_validator_spec.rb

* Mint ARKs when records are completed
* Update ARK metadata when remote metadata is updated
Fixes #54

ARK minting

---

app/decorators/application_decorator.rb
app/decorators/scanned_resource_decorator.rb
app/decorators/valkyrie/resource_decorator.rb
app/models/remote_record.rb
app/services/manifest_builder.rb
app/services/manifest_builder/license_builder.rb
app/services/manifest_builder/manifest_service_locator.rb
app/services/manifest_builder/metadata_builder.rb
app/services/manifest_builder/see_also_builder.rb
spec/decorators/application_decorator_spec.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/models/remote_record_spec.rb
spec/services/manifest_builder/license_builder_spec.rb
spec/services/manifest_builder/manifest_service_locator_spec.rb
spec/services/manifest_builder/metadata_builder/metadata_object_spec.rb
spec/services/manifest_builder/metadata_builder_spec.rb
spec/services/manifest_builder/see_also_builder_spec.rb
spec/services/manifest_builder_spec.rb

Addresses #18 by:
- Exposing metadata in implementing the `MetadataBuilder` and locally overriding the `ManifestServiceLocator`
- Exposing the license restrictions for the resource
- Exposing links to other resources (using `see_also`)

Extending IIIF Manifest Support for Resource Metadata

---

app/models/mets_document/factory.rb
app/models/pudl3_mvw_mets_document.rb
spec/jobs/ingest_mets_job_spec.rb

Add PUDL3 support to IngestMETS

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
valhalla/app/assets/javascripts/valhalla/valhalla.js
valhalla/valhalla.gemspec

The newer version of jQuery UI has some performance problems that make
it so the file manager doesn't render when there's many pages.

Use faster jQuery UI

---

app/helpers/osd_modal_helper.rb
app/services/manifest_builder.rb
app/services/riiif_resolver.rb
spec/features/file_manager_spec.rb
spec/helpers/osd_modal_helper_spec.rb
spec/services/manifest_builder/cantaloupe_helper_spec.rb

Resolves #132 by raising Valkyrie::Persistence::ObjectNotFoundError when derivatives cannot be loaded for a FileSet (and handles this by generating an empty <span> for the OpenSeadragon modal)

Raises errors for cases where FileSet derivatives cannot be loaded

---

.rubocop.yml
app/change_set_persisters/plum_change_set_persister.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb

Resolves #83 by extending the IndexingAdapter to propagate permissions and state for member resources during a save

Extends IndexingAdapter to save metadata for member resources

---

Gemfile
Gemfile.lock
app/assets/javascripts/derivative_form.es6
app/assets/javascripts/figgy_boot.es6
app/controllers/file_sets_controller.rb
app/models/ability.rb
circle.yml
config/routes.rb
spec/controllers/file_sets_controller_spec.rb
spec/features/file_manager_spec.rb
spec/features/root_spec.rb
spec/support/capybara.rb
spec/support/capybara_poltergeist.rb
spec/support/capybara_selenium.rb
spec/views/scanned_resources/file_manager.html.erb_spec.rb
valhalla/app/views/valhalla/base/_file_manager_derivatives.html.erb
valhalla/app/views/valhalla/base/_file_manager_member.html.erb

Resolves #64 by adding a route for updating FileSet derivatives and providing a jQuery extension for the File Management interface

Extends the File Management interface for regenerating derivatives

---

app/change_sets/scanned_resource_change_set.rb
app/decorators/scanned_resource_decorator.rb
spec/change_sets/scanned_resource_change_set_spec.rb
spec/services/manifest_builder/cantaloupe_helper_spec.rb

1. Runs more efficient queries in decorator.
2. Ensures prepopulate! doesn't mess up dirty tracking.

Speed up Figgy

---

app/assets/javascripts/form/save_work_control.es6
app/controllers/ephemera_folders_controller.rb
spec/controllers/ephemera_folders_controller_spec.rb
valhalla/app/views/valhalla/base/_form_progress.html.erb

Add Save and Create Another.

---

Gemfile
Gemfile.lock
app/change_set_persisters/plum_change_set_persister.rb
app/change_set_persisters/plum_change_set_persister/publish_message.rb
app/decorators/collection_decorator.rb
app/decorators/file_set_decorator.rb
app/decorators/scanned_resource_decorator.rb
app/services/manifest_event_generator.rb
app/services/messaging_client.rb
config/config.yml
config/initializers/figgy.rb
config/routes.rb
spec/change_set_persisters/plum_change_set_persister/publish_message/factory_spec.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/controllers/file_sets_controller_spec.rb
spec/decorators/collection_decorator_spec.rb
spec/decorators/file_set_decorator_spec.rb
spec/services/manifest_event_generator_spec.rb
spec/services/messaging_client/config_spec.rb
spec/services/messaging_client_spec.rb
spec/support/maximize_screen.rb
spec/support/stub_rabbit.rb

Resolves #104 by adding support for RabbitMQ messaging for the creation, updates, and deletion of Figgy resources
In addition to the improvements identified by @tpendragon , the following must be addressed:

Adds support for RabbitMQ messaging 

---

app/views/catalog/_ephemera_box_home.html.erb

Resolves #188 as an improper invocation of `ephemera_project_add_box` triggered certain breaking functional tests in which Selenium (and headless Chrome) are used

Fixes breaking feature tests for Selenium due to ephemera_project_add_box invocation

---

app/change_set_persisters/plum_change_set_persister.rb
app/decorators/ephemera_folder_decorator.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb

Ensures that updating EphemeraFolders publishes RabbitMQ messages

---

app/change_set_persisters/plum_change_set_persister/publish_message.rb

Extending the PlumChangeSetPersister::Characterize pattern to PublishCreatedMessage

---

.rubocop.yml
app/jobs/ingest_mets_job.rb
app/models/mets_document.rb
config/initializers/valkyrie.rb
spec/jobs/ingest_mets_job_spec.rb

Copying directly should result in far fewer disk operations and a faster
ingest.

Avoid tmp files for IngestMETSJob

---

lib/tasks/vocab.rake

This way if solr fails it won't import.

Add transaction safety to vocab import.

---

app/assets/javascripts/figgy_boot.es6

Fixes the subject selector not having categories collapsed by default.

Start all optgroups as closed.

---

Gemfile.lock
app/change_set_persisters/plum_change_set_persister.rb
app/change_set_persisters/plum_change_set_persister/cleanup_derivatives.rb
app/change_set_persisters/plum_change_set_persister/propagate_visibility_and_state.rb
app/decorators/ephemera_box_decorator.rb
app/decorators/ephemera_field_decorator.rb
app/decorators/ephemera_folder_decorator.rb
app/decorators/ephemera_project_decorator.rb
app/decorators/file_set_decorator.rb
app/decorators/scanned_map_decorator.rb
app/decorators/scanned_resource_decorator.rb
app/decorators/valkyrie/resource_decorator.rb
app/decorators/vector_work_decorator.rb
app/derivative-services/image_derivative_service.rb
app/derivative-services/jp2_derivative_service.rb
app/derivative-services/plum_derivative_service.rb
app/derivative-services/scanned_map_derivative_service.rb
app/jobs/cleanup_derivatives_job.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/decorators/solr_node_spec.rb
spec/derivative_services/image_derivative_service_spec.rb
spec/derivative_services/jp2_derivative_service_spec.rb
spec/derivative_services/plum_derivative_service_spec.rb
spec/derivative_services/scanned_map_derivative_service_spec.rb

- Updating Valkyrie to https://github.com/samvera-labs/valkyrie/commit/dfcf1959b8399441a612d826b29cd1b44da10702
- Resolves #147 by extending the derivative services and implementing the CleanupDerivatives handler for the PlumChangeSetPersister

Implements CleanupDerivatives change set persister handler and CleanupDerivativesJob

---

app/services/manifest_builder/child_record_property_builder.rb
app/services/manifest_builder/manifest_service_locator.rb
spec/services/manifest_builder_spec.rb

It's expensive to determine if an object needs a multi-part viewing hint
or not, and the information isn't useful for a collection sub-manifest.

Don't render viewing hint for collection children.

---

app/assets/stylesheets/components/form.scss
spec/features/ephemera_folder_spec.rb
valhalla/app/views/valhalla/base/_form_progress.html.erb

Resolves #376 by exposing a "Delete" button within the form used for editing:

Ensures that users can delete Ephemera Folders when editing

---

config/config.yml
config/initializers/devise.rb
spec/support/capybara_selenium.rb
spec/support/features/session_helpers.rb
spec/support/reset_auth.rb

Separate CAS host and URL for the Omniauth config.

---

app/services/manifest_builder/faster_iiif_manifest.rb
app/services/manifest_builder/manifest_service_locator.rb
app/services/manifest_builder/rendering_builder.rb
spec/services/manifest_builder_spec.rb

Ensures that Collections are built using the LicenseBuilder and RenderingBuilder

---

app/change_sets/ephemera_folder_change_set.rb
spec/factories/ephemera_folder.rb
spec/features/ephemera_box_spec.rb
spec/features/ephemera_folder_spec.rb
valhalla/app/controllers/concerns/valhalla/resource_controller.rb

Resolves #440 by ensuring that ChangeSet validations are propagated from the Controller for cases where resources have already been persisted with invalid data

Ensures that ChangeSet validation errors are rendered on resource edit forms

---

app/change_sets/ephemera_box_change_set.rb
app/controllers/ephemera_boxes_controller.rb
app/decorators/ephemera_box_decorator.rb
app/models/ephemera_box.rb
app/views/catalog/_admin_controls_ephemera_box.html.erb
app/views/catalog/_members_ephemera_project.html.erb
app/views/catalog/_resource_attributes_ephemera_box.html.erb
app/views/catalog/_resource_attributes_ephemera_term.html.erb
app/views/ephemera_boxes/attach_drive.html.erb
config/routes.rb
spec/change_sets/ephemera_box_change_set_spec.rb
spec/controllers/ephemera_boxes_controller_spec.rb
spec/views/catalog/_admin_controls_ephemera_box.html.erb_spec.rb
spec/views/catalog/_members_ephemera_project.html.erb_spec.rb

* Adds a drive barcode field to ephemera boxes
* Displays drive barcode in box list
* Adds buttons for attaching and removing drives
Fixes #495

Adding ephemera hard drive management

---

app/indexers/ephemera_folder_indexer.rb
config/initializers/valkyrie.rb
spec/controllers/catalog_controller_spec.rb

Resolves #494 by implementing an indexer for the EphemeraFolders supporting the following:

Implements an indexer for the EphemeraFolders for cases where the folders should be hidden

---

app/assets/javascripts/figgy_boot.es6
app/assets/javascripts/metadata_form.es6
app/views/scanned_maps/file_manager.html.erb
spec/features/file_manager_spec.rb

Adds javascript to re-enable broken geo metadata Extract button in scanned map file manager.
Closes #571

Fix extract metadata functionality

---

app/change_sets/ephemera_folder_change_set.rb
spec/change_sets/ephemera_folder_change_set_spec.rb
spec/features/ephemera_folder_spec.rb

Resolves #570 by ensuring that users can sort the FileSets for any given EphemeraFolder

Ensures that users can sort the FileSets for any given EphemeraFolder

---

.rubocop.yml
app/assets/javascripts/figgy_boot.es6
app/assets/javascripts/file_set_form.es6
app/controllers/file_sets_controller.rb
app/services/file_appender.rb
app/services/file_appender/file_resource_adapter.rb
app/services/file_appender/file_resources.rb
app/services/resource_detector.rb
app/views/catalog/_admin_controls_file_set.html.erb
spec/controllers/file_sets_controller_spec.rb
spec/services/file_appender/file_resource_adapter_spec.rb
spec/services/file_appender/file_resources_spec.rb

Resolves #605 by addressing the following:
- Restructuring FileSetsController#update in parity with Valhalla::ResourceController#update
- Uses the services FileResources and FileResourceAdapter to ensure that file metadata is properly copied when files are added or updated for FileSets
- Ensures that the "Update Files" button on the FileSet catalog View is disabled by default
- Ensures that file labels and names are updated when files in FileSets are updated

Extends the `FileAppender` Service to improve file updates for FileSets

---

app/assets/stylesheets/components/show.scss

Move data table sorting icon.

---

app/change_set_persisters/plum_change_set_persister.rb
app/change_set_persisters/plum_change_set_persister/apply_visibility_by_date.rb
app/change_sets/concerns/visibility_property.rb
app/views/records/edit_fields/_source_metadata_identifier.html.erb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/factories/scanned_resource.rb
spec/fixtures/files/bibdata/123456789.jsonld

Closes #691.
This adds a new checkbox to automatically set visibility/rights statement based on what the date of the object is. The checkbox looks like this:

Set visibility based on Date Created

---

app/models/structure_node.rb
spec/models/structure_spec.rb

Having a bunch of empty updated_at/created_at values when saving to postgres was making it take even longer to parse in Valkyrie.

Dont create empty updated at

---

app/change_sets/ephemera_folder_change_set.rb
app/decorators/ephemera_folder_decorator.rb
app/decorators/valkyrie/resource_decorator.rb
app/services/manifest_builder.rb
spec/decorators/ephemera_folder_decorator_spec.rb
spec/services/manifest_builder_spec.rb

Progresses towards a resolution for #756 and addresses some existing bugs:
- An `alias` typographic error
- The casting of all `genre` attribute values for `EphemeraFolders` into `Valkyrie::IDs`

Ensuring that linked vocabulary terms only have their labels exposed in IIIF Manifests

---

app/jobs/missing_thumbnail_job.rb
app/queries/find_missing_thumbnail_resources.rb
config/initializers/valkyrie.rb
lib/tasks/bulk.rake
spec/jobs/missing_thumbnail_job_spec.rb
spec/queries/find_missing_thumbnail_resources_spec.rb

Provides a Rake task which resolves #781

Implementing the MissingThumbnailJob for linking MVWs to member thumbnails when `thumbnail_id` values are missing or deleted

---

app/services/geo_resources/discovery/document_builder/document_path.rb
app/services/geo_resources/discovery/document_builder/iiif_builder.rb
spec/services/geo_resources/discovery/document_builder_spec.rb

GeoBlacklight document builders assumed that a map set's thumbnail id pointed to a ScannedMap. The thumbnail id should be the id for a file set instead.
Closes #855

Scanned map thumbnail_id points to a file set

---

app/models/controlled_vocabulary.rb

Remove reference to 'Vocab' class; cannot find this class
Add explanation of 'notable'

Small updates to inline docs of controlled_vocabulary

---

app/controllers/application_controller.rb

Should stop tons of guests being created. For Figgy we don't care about
saving non-logged in searches and things.
Closes #858

Force guest user to use the first available

---

Gemfile
config/initializers/datadog.rb

Staging wasn't in our datadog quote, and this throws errors if the agent
isn't installed.

No datadog in staging.

---

app/services/manifest_builder/manifest_service_locator.rb
app/services/manifest_builder/sequence_builder.rb
app/services/manifest_builder/start_canvas_builder.rb
spec/services/manifest_builder_spec.rb

Add Start Canvas

---

Gemfile
app/adapters/instrumented_adapter.rb
config/initializers/datadog.rb
config/initializers/valkyrie.rb
spec/adapters/instrumented_adapter_spec.rb

Gives us nice profiling of traces on Datadog to tell how much time is spent in Valkyrie for MetadataAdapters.

Instrument Valkyrie via Datadog

---

app/controllers/ephemera_boxes_controller.rb
app/controllers/ephemera_projects_controller.rb
app/decorators/ephemera_box_decorator.rb
app/decorators/ephemera_project_decorator.rb
app/models/folder_data_source.rb
app/queries/count_members.rb
app/views/catalog/_folder_actions.html.erb
app/views/catalog/_members_ephemera_box.html.erb
config/initializers/valkyrie.rb
config/routes.rb
spec/controllers/ephemera_boxes_controller_spec.rb
spec/controllers/ephemera_projects_controller_spec.rb
spec/queries/count_members_spec.rb
spec/views/catalog/_members_ephemera_box.html.erb_spec.rb
spec/views/catalog/_members_ephemera_project.html.erb_spec.rb

Load folder data asynchronously.

---

app/controllers/fixity_dashboard_controller.rb
app/views/catalog/_fixity_dashboard_home.html.erb
spec/controllers/fixity_dashboard_controller_spec.rb
spec/views/catalog/_home_text.html.erb_spec.rb

Make fixity dashboard viewable only by admins

---

valhalla/app/javascript/app.vue

This prevents blocking user from interacting with Filemanager and thus provides a temporary workaround for #920

Places Vue Filemanager status alert in unobtrusive place

---

app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb
app/change_sets/concerns/remote_metadata_property.rb
app/change_sets/raster_resource_change_set.rb
app/change_sets/scanned_map_change_set.rb
app/change_sets/vector_work_change_set.rb
app/decorators/geoblacklight_metadata_decorator.rb
app/decorators/raster_resource_decorator.rb
app/decorators/scanned_map_decorator.rb
app/decorators/vector_work_decorator.rb
app/models/imported_metadata.rb
app/models/raster_resource.rb
app/models/scanned_map.rb
app/models/vector_work.rb
app/services/geo_resources/discovery/document_builder.rb
app/services/geo_resources/discovery/document_builder/iiif_builder.rb
app/services/geo_resources/discovery/document_builder/relationship_builder.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/change_sets/raster_resource_change_set_spec.rb
spec/change_sets/vector_work_change_set_spec.rb
spec/decorators/raster_resource_decorator_spec.rb
spec/decorators/scanned_map_decorator_spec.rb
spec/decorators/vector_work_decorator_spec.rb
spec/fixtures/files/bibdata/9637153.jsonld
spec/fixtures/files/bibdata/9649080.jsonld
spec/services/geo_resources/discovery/document_builder_spec.rb
spec/services/plum_scanned_map_importer_spec.rb

- Geo resources now use imported metadata to store metadata from Voyager. Allows for adding additional metadata on the resource such as additional non-LC subject terms and place names.
- Implements a decorator for generating geoblacklight documents. Decorator merges, and deduplicates, imported with non-imported data. 
Closes #925

Use imported metadata in geo resources

---

app/characterization_services/geo_characterization_service.rb
app/characterization_services/scanned_map_characterization_service.rb
app/decorators/file_set_decorator.rb
app/models/file_metadata.rb
app/models/file_set.rb
config/config.yml
spec/characterization_services/scanned_map_characterization_service_spec.rb

- Add processing note property to file metadata.
- Creates characterization service to add boilerplate text into the field for scanned map original files.
- Makes the existing x_resolution, y_resolution, and bits_per_sample properties visible in the file set view.
Closes #930

Add processing note for scanned map images

---

.rubocop.yml
app/models/ability.rb
spec/requests/scanned_resource_spec.rb
valhalla/app/controllers/valhalla/downloads_controller.rb

Ensures that users need not be authenticated in order to download derivatives in the PDF

---

spec/support/stub_rabbit.rb

Quiets bunny warnings when running tests.
Closes #992

Stub rabbit on CleanupDerivativesJob and CreateDerivativesJob

---

.rubocop.yml
spec/jobs/create_derivatives_job_spec.rb
spec/services/event_generator/geoserver_event_generator_spec.rb
spec/services/geoserver_messaging_client_spec.rb

Stubbing bunny in CreateDerivativesJob and CleanupDerivativesJob revealed some methods without test coverage. The resulting decrease in coverage was small enough to not trigger a failure. This PR adds specs to bring Figgy back up to 💯.
Closes #1011

Add specs for methods without test coverage

---

app/models/controlled_vocabulary.rb
app/models/draft_publish_workflow.rb
app/models/search_builder.rb
config/locales/en.yml
spec/models/draft_publish_workflow_spec.rb

It's nearly identical to the folder workflow; the only difference is the names of the states / transitions.

Add a simple draft-publish workflow for use with plates (SimpleResource), refs #1031

---

app/models/ability.rb
spec/models/ability_spec.rb
valhalla/app/controllers/valhalla/downloads_controller.rb

- Allows geo thumbnails and external metadata to be anonymously downloaded regardless of the visibility of the parent resource.
- Allows geo files (shapefiles, raster datasets, scanned map tiffs) to be anonymously downloaded when the parent resource is open (public). 
- Reorganizes and partially alphabetizes methods in Ability class.
Because of the way CanCanCan works in conjunction with Figgy; allowing anonymous downloading for different files on a file set required adding an attribute to the FileWithMetadata struct to hold the parent file set id
Closes #1025

Modify permissions to allow for anonymous downloading of geo files

---

Gemfile
Gemfile.lock

Originally reported by @roelmoon and scoped within https://github.com/samvera/browse-everything/issues/204

Using an upstream bug resolution in order to ensure that file system paths for `browse-everything` with punctuation can be resolved

---

app/change_sets/ephemera_box_change_set.rb
app/change_sets/ephemera_folder_change_set_base.rb
app/change_sets/media_resource_change_set.rb
app/change_sets/raster_resource_change_set.rb
app/change_sets/scanned_map_change_set.rb
app/change_sets/scanned_resource_change_set.rb
app/change_sets/simple_resource_change_set.rb
app/change_sets/vector_resource_change_set.rb
app/decorators/ephemera_box_decorator.rb
app/decorators/ephemera_folder_decorator.rb
app/decorators/valkyrie/resource_decorator.rb
app/indexers/ephemera_folder_indexer.rb
app/models/ability.rb
app/models/book_workflow.rb
app/models/box_workflow.rb
app/models/draft_publish_workflow.rb
app/models/folder_workflow.rb
app/models/search_builder.rb
app/models/workflow_registry.rb
config/initializers/workflows.rb
spec/decorators/ephemera_box_decorator_spec.rb
spec/decorators/ephemera_folder_decorator_spec.rb
spec/decorators/valkyrie/resource_decorator_spec.rb
spec/factories/simple_resource.rb
spec/models/book_workflow_spec.rb
spec/models/box_workflow_spec.rb
spec/models/draft_publish_workflow_spec.rb
spec/models/folder_workflow_spec.rb
spec/models/workflow_registry_spec.rb

Refactor `Ability` and `EphemeraFolderIndexer` to call the new logic instead of duplicating with one another.
refs @1040

Push state-based visibility logic into workflow classes and decorators

---

app/jobs/ingest_geoportal_record_job.rb
spec/jobs/ingest_geoportal_record_job_spec.rb

- Removes unnecessary logging.
- Tests for error in reading fgdc record.
- Brings test coverage back to 💯.
Hopefully we can remove this job in the near future.
Closes #1041

Increase test coverage for ingest geoportal record job

---

app/helpers/catalog_helper.rb
app/views/catalog/_admin_controls_default.html.erb
app/views/catalog/_admin_controls_ephemera_box.html.erb
app/views/catalog/_admin_controls_ephemera_folder.html.erb
app/views/catalog/_admin_controls_ephemera_term.html.erb
app/views/catalog/_admin_controls_file_set.html.erb
spec/views/catalog/_admin_controls_default.html.erb_spec.rb
spec/views/catalog/_admin_controls_ephemera_box.html.erb_spec.rb
spec/views/catalog/_admin_controls_ephemera_folder.html.erb_spec.rb
spec/views/catalog/_admin_controls_ephemera_term.html.erb_spec.rb
spec/views/catalog/_admin_controls_file_set.html.erb_spec.rb

Also encompasses permissions for:
* file management
* editing the logical structure
* downloading derivative files in FileSets
Resolves #795

Ensures that links for editing and deleting resources are only rendered for users with the appropriate permissions

---

app/change_sets/raster_resource_change_set.rb
app/change_sets/vector_resource_change_set.rb

- Groups coverage logically with cartographic projection and scale.
- Resolves conflict with rights statement dropdown.
Closes #1092

Move position of coverage on Vector and Raster edit pages

---

app/change_sets/scanned_map_change_set.rb
spec/change_set_persisters/plum_change_set_persister_spec.rb
spec/features/scanned_map_spec.rb
spec/fixtures/files/bibdata/10001789.jsonld

Coverage should come from Voyager metadata.
Closes #1090

Removes coverage from scanned map edit page

---

app/services/manifest_builder/thumbnail_builder.rb
spec/services/manifest_builder_spec.rb

When collection manifests have multi-volume works the thumbnail_id of
the MVW points to the scanned resource within it that has the thumbnail
it should use, rather than the FileSet. The thumbnail builder was
assuming it'd get back a FileSet, which caused an error to be thrown
while embedding thumbnails in those manifests. The error can be seen
here: https://app.honeybadger.io/projects/53391/faults/37473184
The change here iterates down thumbnail_ids until it finds a FileSet,
and if it doesn't it just doesn't append a thumbnail to the manifest.

Fix collection manifests with MVWs.

---

app/change_sets/archival_media_collection_change_set.rb
app/decorators/archival_media_collection_decorator.rb
app/models/archival_media_collection.rb
app/validators/bag_path_validator.rb
config/initializers/workflows.rb
spec/change_sets/archival_media_collection_change_set_spec.rb
spec/controllers/archival_media_collections_controller_spec.rb
spec/decorators/archival_media_collection_decorator_spec.rb
spec/decorators/collection_decorator_spec.rb
spec/shared_specs.rb
spec/shared_specs/decorators/collection_decorator.rb

- Adds DraftPublishWorkflow and identifier property to archival media collection.
- Modifies BagPathValidator to allow nil values so workflow state can be updated. Bag path is a required field, so the user must still enter an initial value in the form.
- Modifies BagPathValidator to test if a bag path directory actually exists.
Closes #1003 
Closes #1004

 Add workflow and identifier to archival media collection

---

app/controllers/file_sets_controller.rb
app/jobs/regenerate_derivatives_job.rb
spec/controllers/file_sets_controller_spec.rb
spec/jobs/regenerate_derivatives_job_spec.rb

- Adds RegenerateDerivativesJob to clean up existing derivatives before creating new ones.
- The FileSetsController `derivatives` method triggers this job instead of create derivatives job.
Closes #1168

Add job for regenerating derivatives

---

app/services/identifier_service.rb
spec/services/identifier_service_spec.rb

* Use catalog.princeton.edu instead of pulsearch.princeton.edu
* Use Figgy Blacklight show page instead of (non-existent) Valkyrie show page

Update ARK destination URLs 

---

Gemfile.lock

Updates `browse-everything` from upstream for ordering file entries

---

app/change_set_persisters/change_set_persister.rb

The `after_commit` handler runs a Characterize job for file sets and sends a file set created message. Neither of those are needed when deleting.
Closes #773

Don't run after commit change set handler on delete

---

Gemfile.lock

Updating `browse-everything` from upstream for supporting Team Drives

---

.circleci/config.yml

We think something changed in CircleCI and now the cached gem can't detect the simple-tiles shared library without this.

Reinstall simpler-tiles every time.

---

app/change_set_persisters/change_set_persister/publish_message.rb
app/decorators/file_set_decorator.rb
app/services/event_generator.rb
app/services/event_generator/composite_generator.rb
app/services/event_generator/geoblacklight_event_generator.rb
app/services/event_generator/geoserver_event_generator.rb
app/services/event_generator/manifest_event_generator.rb
app/services/manifest_builder.rb
app/validators/unique_archival_media_barcode_validator.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/services/event_generator/geoblacklight_event_generator_spec.rb
spec/support/stub_rabbit.rb

Send parent events as a new event type on update and don't send manifest
URL so DPUL won't try to reindex every time a FileSet changes.

Adjust FileSet events

---

app/decorators/scanned_map_decorator.rb
spec/features/scanned_map_spec.rb
spec/views/catalog/_resource_attributes_default.html.erb_spec.rb

Hide imported extent field on scanned maps

---

app/wayfinders/file_set_wayfinder.rb
spec/wayfinders/wayfinder_spec.rb

ScannedMaps are unable to generate a manifest without this in
production.

Add members relation to FileSetWayfinder

---

app/javascript/components/FilesetsForm.vue

fixes #1294 Tightens up form so that "Apply Changes" is not hidden on smaller screens when using foliation options.

Prevents "Apply Changes" from being hidden in OrderManager

---

app/controllers/downloads_controller.rb
config/environments/production.rb

Greatly improves the efficiency of downloading of full-res images by delegating down to nginx. The request comes in, authorizes in Figgy, and then passes to an internal path in nginx for handling the request.
This enables file resumption on server restart, HTTP Range requests, and download estimates when downloading in a browser.

Use X-Accel-Redirect for NGINX download

---

app/derivative-services/external_metadata_derivative_service.rb
config/initializers/valkyrie.rb
spec/derivative_services/external_metadata_derivative_service_spec.rb

Adds a derivative service for external geo metadata. Extracts metadata elements into parent vector or raster resource as soon as the file is characterized.
Closes #1308

Add derivative service to extract external geo metadata

---

app/controllers/concerns/geo_resource_controller.rb
app/derivative-services/external_metadata_derivative_service.rb
app/services/event_generator/geoblacklight_event_generator.rb
app/services/geo_metadata_extractor.rb
spec/derivative_services/external_metadata_derivative_service_spec.rb
spec/services/event_generator/geoblacklight_event_generator_spec.rb
spec/services/geo_metadata_extractor_spec.rb

- Sends a `record_updated` message after extracting external geo metadata.
- Sends UPDATED geoblacklight event message when a member is updated instead of MEMBER_UPDATED
Closes #1335

 Send updated message after extracting external geo metadata

---

app/services/ingest_folder_locator.rb
spec/services/ingest_folder_locator_spec.rb

Ensures that `IngestFolderLocator#folder_pathname` handles cases where the directory cannot be found

---

app/derivative-services/external_metadata_derivative_service.rb
spec/derivative_services/external_metadata_derivative_service_spec.rb

Fixes issue with incorrect visibility values when extracting geo metadata.
Closes #1360

Use model when generating external metadata parent ChangeSet

---

app/services/manifest_builder/thumbnail_builder.rb
spec/services/manifest_builder/thumbnail_builder_spec.rb

Ensures that the `ManifestBuilder::ThumbnailBuilder#file_set` handles cases where `ManifestBuilder::RootNode#file_set_presenters` returns empty Arrays

---

app/helpers/catalog_helper.rb
spec/helpers/blacklight_helper_spec.rb

Overriding `Blacklight::CatalogHelperBehavior#render_search_to_page_title_filter` in order to handle nil or empty facet parameter values

---

app/controllers/bulk_ingest_controller.rb
spec/controllers/bulk_ingest_controller_spec.rb

When no collections are selected in bulk ingest, the controller should set member_of_collection_ids  to an empty array instead of a nil value. Setting it to nil raises an exception.
Closes #1375

Set member_of_collection_ids to empty array instead of nil

---

app/jobs/ingest_archival_media_bag_job.rb
app/models/archival_media_bag_parser.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/change_sets/archival_media_collection_change_set_spec.rb
spec/jobs/ingest_archival_media_bag_job_spec.rb
spec/models/archival_media_bag_parser_spec.rb

And use it in the ingest job, but not the barcode uniqueness validator;
fixes #1393

Move bag validation from bag parser initializer to public method

---

app/services/geo_discovery/document_builder/document_helper.rb
app/services/geo_discovery/document_builder/document_path.rb
app/services/geo_discovery/document_builder/references_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

Use a link to a resource's catalog record instead of a link to Figgy in a geo resource's GeoBlacklight references.
Closes #1420

Use URL for catalog record in GeoBalcklight references field

---

app/services/manifest_builder/manifest_service_locator.rb
app/services/manifest_builder/thumbnail_builder.rb
spec/services/manifest_builder_spec.rb

Fixes a bug discovered in https://github.com/pulibrary/figgy/pull/1425

Ensures that MVW thumbnails are rendered by using member FileSets rather than just member resources

---

app/services/geo_discovery/document_builder/basic_metadata_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

Fixes issue where portion note is not displayed in the GeoBlacklight document title for scanned maps with imported metadata.
Partially addresses #1453

Add portion note to title of scanned maps with remote metadata

---

app/controllers/base_resource_controller.rb
app/services/manifest_builder.rb
app/views/records/edit_fields/_member_of_collection_ids.html.erb
lib/tasks/migrate.rake
spec/controllers/raster_resources_controller_spec.rb
spec/controllers/scanned_maps_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/controllers/vector_resources_controller_spec.rb
spec/shared_specs/controllers/base_resource_controller.rb

Resolves https://github.com/pulibrary/pomegranate/issues/362 by extending ManifestBuilder::CollectionNode in order to hide member resources when both the parent and members belong to the same Collection

Extends ManifestBuilder::CollectionNode in order to hide MVW members

---

app/services/pdf_generator/canvas_downloader.rb

Tests show that it's still readable, and the PDFs are smaller.

Scale down PDF image sizes.

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb

Google Cloud Identity now requires that domains be verifiable in order to provide authentication into Cloud services

Adding the <meta> element for domain verification by Google Cloud Identity

---

app/services/event_generator/composite_generator.rb
app/services/event_generator/geoserver_event_generator.rb
spec/services/event_generator/geoserver_event_generator_spec.rb

- Fires a GeoServer event for every child geo FileSet when a when a geo resource is updated.
- Allows message to propagate to all valid generators instead of just the first. This allows GeoBlacklight and GeoServer messages to both be generated when a resource is updated.
Closes #1348 
Also see: https://github.com/pulibrary/geoserver-worker/pull/3

Fire GeoServer events when parent resource is updated

---

app/services/manifest_builder.rb
spec/services/manifest_builder_spec.rb

It was displaying them as
```json
{
"@id": {"id": "bla"}
}
```
instead of 
```json
{
"@id": "bla"
}
```
and this fixes that.

Fix FileSet IDs in Canvas Resources.

---

app/services/manifest_builder.rb
spec/services/manifest_builder_spec.rb

Necessary for manifests to be considered valid.

Fix resource URL and canvas width/height type.

---

app/services/manifest_builder.rb
app/services/manifest_builder/canvas_builder.rb
spec/services/manifest_builder_spec.rb

I'm not sure if UV uses these, but we store things like "non-paged" via the order manager and should utilize that in the manifest. If UV -does- use these, this might be a good way to do photo albums.

Add viewing hint to canvases.

---

app/derivative-services/raster_resource_derivative_service.rb
app/derivative-services/vector_resource_derivative_service.rb
app/services/geo_discovery/document_builder/wxs.rb
app/services/geoserver_message_generator.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb
spec/services/geoserver_message_generator_spec.rb

- Sets the output projection for vector derivatives to EPSG:4326 to avoid shapefile projection issues in GeoServer. The modest gains in performance when using 3857 are mitigated by increased complexity in setting up new layers.
- Prefixes geo derivative names and ids with a letter to avoid XML validation errors with GeoServer WFS generated GML.
Closes #1659

Prefix geo derivative names and ids

---

app/services/geoserver_message_generator.rb
spec/services/geoserver_message_generator_spec.rb

Ensuring that exceptions are raised if the parent resource cannot be accessed in `GeoserverMessageGenerator`

---

.rubocop.yml
app/services/pdf_generator.rb
app/services/pdf_generator/canvas.rb
spec/services/pdf_generator_spec.rb

Implements PDFGenerator::Canvas#validate! to validate IIIF Manifest structure

---

spec/queries/find_by_string_property_spec.rb

refs #1676
There wasn't a bug (just a mock that was throwing off my other test) but do we still want this test?

Add a test for the case when find_by_string_property has no results

---

app/services/event_generator/geoserver_event_generator.rb
app/services/geoserver_message_generator.rb
spec/services/event_generator/geoserver_event_generator_spec.rb
spec/services/geoserver_message_generator_spec.rb

- Better handles conditions where a vector file set's parent resource no longer exists or when the member files are missing.
- Sends two messages to GeoServer on every delete. One for the public workspace and one for the restricted workspace. This will help to reduce manual cleanup on GeoServer because of anomalous events in Figgy. 
Tested this in staging, and was able to delete Vector Resources without error as well as a FileSet that had become separated from it's parent.
Closes #1669

Improve GeoServer delete message behavior

---

.rubocop.yml
app/jobs/ingest_mets_job.rb
app/models/mets_document.rb
app/models/mets_document/mods_document.rb
lib/tasks/import.rake
spec/fixtures/mets/scrapbooks.mets
spec/fixtures/mets/tsop_typed.mets
spec/fixtures/mets/tsop_typed_mvw_no_files.mets
spec/fixtures/mets/tsop_typed_no_files.mets
spec/jobs/ingest_mets_job_spec.rb
spec/models/mets_document/mods_document_spec.rb

This is necessary for ingesting items without MARC records

Implements the METSDocument::MODSDocument Class for appending MODS metadata attributes within IngestMETSJob

---

app/services/geo_discovery/document_builder/document_path.rb
app/services/geo_discovery/document_builder/iiif_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

It appears that a map set's thumbnail id _should_ be set to the id of a child scanned map. Changes here detect if the thumbnail id is a FileSet or a child member and returns the correct FileSet.
Closes #1726

Fix geoblacklight iiif references for map sets

---

app/queries/find_invalid_thumbnail_resources.rb
config/initializers/valkyrie.rb
lib/tasks/bulk.rake
spec/queries/find_invalid_thumbnail_resources_spec.rb

Resolves #1732 by addressing the following:
- Implements the `bulk:link_invalid_thumbnails` Rake task for linking resource thumbnails (where the IDs are corrupted)
- Implements the `FindInvalidThumbnailResources` query in order to find resources with these invalid thumbnail IDs

Implements the `bulk:link_invalid_thumbnails` Rake task for linking resources with invalid thumbnail IDs

---

app/models/title_with_subtitle.rb
spec/models/title_with_subtitle_spec.rb

It can read/write strings and rdf literals. it interpolates to "title:
subtitle"
fixes #1748

Add a valkyrie resource TitleWithSubtitle

---

app/change_sets/simple_resource_change_set.rb
app/decorators/ephemera_vocabulary_decorator.rb
app/decorators/scanned_resource_decorator.rb
app/models/mets_document.rb
app/models/mets_document/mods_document.rb
app/models/solr_document.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/fixtures/mets/pudl0100-lc-egx_0003.mets
spec/helpers/blacklight_helper_spec.rb
spec/jobs/ingest_mets_job_spec.rb
spec/models/mets_document/mods_document_spec.rb

Allows for transliterated actors and does the rendering for it. Due to a
bug in solr's conversion of RDF::Literals and nested objects together (tracked at https://github.com/samvera-labs/valkyrie/issues/596),
this PR also converts the catalog show page to use a record out of
Postgres instead of Solr. I doubt there'll be any noticeable performance implications, but we should keep an eye on it.
References #1612

Changes for PUDL0100

---

app/decorators/raster_resource_decorator.rb
app/decorators/scanned_map_decorator.rb
app/decorators/vector_resource_decorator.rb
spec/decorators/raster_resource_decorator_spec.rb
spec/decorators/scanned_map_decorator_spec.rb
spec/decorators/vector_resource_decorator_spec.rb

Loading show page from Postgres changes the behavior of empty attributes. When loaded from Solr, an empty attribute on the document returns nil. When loaded from Postgres, an empty attribute on the document returns an empty array. The `rendered_coverage` method assumed a nil value.
Closes #1823

Fix show page rendered coverage

---

app/controllers/reports_controller.rb
app/queries/find_identifiers_to_reconcile.rb
spec/controllers/reports_controller_spec.rb
spec/queries/find_identifiers_to_reconcile_spec.rb

Only include complete objects with BibIDs in the identifiers-to-reconcile report

---

app/services/manifest_builder.rb
app/services/manifest_builder/thumbnail_builder.rb
spec/services/manifest_builder_spec.rb

Should improve efficiency of manifest generation significantly.
Discovered via datadog: https://app.datadoghq.com/apm/resource/figgy/rack.request/68b3ff7466d9457a?start=1537461404405&end=1537465004405&paused=false&env=none&traceID=694789138216265633&spanID=6994033335916105774&graphType=span_list

Don't re-query for filesets in ManifestBuilder

---

app/views/catalog/_members_archival_media_collection.html.erb
app/views/catalog/_members_collection.html.erb
spec/features/archival_media_collection_spec.rb
spec/features/collections_spec.rb

gives number of members,
uses word "items" instead of "members", which was confusing
fixes #1781

Update link text for members of a collection

---

app/jobs/ingest_intermediate_file_job.rb
spec/change_sets/file_set_change_set_spec.rb
spec/jobs/ingest_intermediate_file_job_spec.rb

When testing #1592, it was discovered that `FileMetadata` for the original derivatives of a Resource were not deleted once an intermediate file was appended by IngestIntermediateFileJob, and the derivatives were regenerated.

Ensuring that derivative FileMetadata is deleted from FileSets when IngestIntermediateFileJob appends an intermediate file for a resource

---

spec/spec_helper.rb

Please see https://github.com/lostisland/faraday/blob/master/lib/faraday/connection.rb#L461

Introduces a work-around for Faraday HTTP proxy warnings using ENV['NO_PROXY']

---

Gemfile.lock

Closes #1928 
Integrates new patch in valkyrie-sequel: https://github.com/samvera-labs/valkyrie-sequel/commit/7fee37642d7c9a26c25342631758e098b8b8f812

Validate idle sequel connections

---

app/javascript/store/vuex/actions.js

I'm currently encountering the following issue when attempting to use the Order Manager within the staging environment:
```
TypeError: Cannot read property 'id' of null
at c.SET_RESOURCE (system.js:7782)
at vuex.esm.js:697
at vuex.esm.js:389
at Array.forEach (<anonymous>)
at vuex.esm.js:388
at c._withCommit (vuex.esm.js:495)
at c.commit (vuex.esm.js:387)
at Object.commit (vuex.esm.js:335)
at c.<anonymous> (actions.js:53)
at i (application-f6a645b52a30a87d8e5bd665521060a8656ca0a9b63626f1c9fdaafefd32d83c.js:29)
```
(please see https://figgy-staging.princeton.edu/concern/scanned_resources/e9f61f1b-8cd1-419d-bd53-49a7bce9e103/order_manager)

Handles cases where the resource passed to `loadImageCollectionGql` in the Order Manager is `null`

---

spec/jobs/ingest_archival_media_bag_job_spec.rb

Ensuring that the test cases for the general IngestArchivalMediaBagJob functionality use only one Bag fixture

---

app/decorators/file_set_decorator.rb
app/graphql/types/resource.rb
app/queries/find_members_with_inverse_relationship.rb
app/wayfinders/file_set_wayfinder.rb
app/wayfinders/scanned_map_wayfinder.rb
app/wayfinders/scanned_resource_wayfinder.rb
config/initializers/valkyrie.rb
spec/controllers/graphql_controller_spec.rb
spec/queries/find_members_with_inverse_relationship_spec.rb
spec/wayfinders/wayfinder_spec.rb

By pre-loading parents for FileSets in GraphQL queries it avoids running
an inverse query for every page to determine if something is a Geo
FileSet.

Reduce queries in GraphQL queries.

---

app/helpers/thumbnail_helper.rb
app/services/manifest_builder.rb
spec/controllers/graphql_controller_spec.rb

Passing the ID forces a re-load of every FileSet, which is unnecessary.

Thumbnails should use FileSet documents

---

app/javascript/store/vuex/actions.js
package.json

This bumps to LUX v1.0.2 which fixes this. Also tweaks some old action commits that have been changed since we moved off IIIF manifests.

fixes #1969 - Order Manager broken due to null thumbnail

---

app/change_set_persisters/change_set_persister/cleanup_pdfs.rb
app/controllers/scanned_resources_controller.rb
spec/change_set_persisters/change_set_persister/cleanup_pdfs_spec.rb
spec/requests/scanned_resource_spec.rb

Handles cases where the ChangeSetPersister::CleanupPdfs does not delete existing PDF metadata for resources when the files may have been deleted

---

app/views/catalog/_home_text.html.erb

Reported by Dan Walker: "adhering" is misspelled as "adhereing" in the home page text.

Fixing home page typo

---

app/services/voyager_updater/dump.rb
spec/services/voyager_updater/dump_spec.rb
spec/services/voyager_updater/event_spec.rb

Closes #2042. Because of the refactored Voyager Dump jobs, we have combined create_ids and update_ids into a single array of bib ids in update_ids. The job has been failing since the refactored bibdata events were deployed on Friday. Looking at the code it seems like the rake task is set up to process all of the Bibdata events and process them unless they have been previously processed. I think the failed jobs will be captured in the next nightly update after this branch is deployed

updates voyager updater tasks to process refactored bibdata dump format

---

app/queries/memory_efficient_all_query.rb
spec/queries/memory_efficient_all_query_spec.rb

This reverts commit d34d45afa838844420158ae20efa2175a7fe1127.
On staging, that commit resulted in only one batch of records reindexing.
```
I, [2018-11-12T10:32:13.258438 #6424]  INFO -- : Clearing Solr
I, [2018-11-12T10:32:13.299740 #6424]  INFO -- : Reindexing all records
I, [2018-11-12T10:32:15.326994 #6424]  INFO -- : Indexing 1000 records
I, [2018-11-12T10:32:22.463393 #6424]  INFO -- : Done
```
Reverting the commit on staging allows the full set of records to index

Revert "Lazy map resources in MemoryEfficientAllQuery"

---

app/resources/numismatic_issues/numismatic_issue.rb
app/resources/numismatic_issues/numismatic_issue_change_set.rb
app/resources/numismatic_issues/numismatic_issue_decorator.rb
app/resources/numismatic_issues/numismatic_issue_wayfinder.rb
app/views/catalog/_members_numismatic_issue.html.erb
spec/controllers/numismatic_citations_controller_spec.rb
spec/decorators/numismatic_issue_decorator_spec.rb

Closes #2177 
- Adds ability to attach citations to Numismatic Issues.
- Improves styling on Citations panel.

Add citations to NumismaticIssue

---

app/change_set_persisters/change_set_persister.rb

Fixes thread-safety when saving multiple resources through the same
ChangeSetPersister. Closes #2190
I can't figure out how to add a test to this.

No instance variables in ChangeSetPersister

---

app/resources/numismatic_issues/numismatic_issue.rb
app/resources/numismatic_issues/numismatic_issue_change_set.rb
app/resources/numismatic_issues/numismatic_issue_decorator.rb
app/views/base/_form.html.erb
app/views/base/_form_metadata.html.erb
app/views/base/_form_metadata_inner.html.erb
app/views/templates/new.html.erb
config/locales/simple_form.en.yml
spec/controllers/catalog_controller_spec.rb
spec/resources/numismatic_issue/numismatic_issue_change_set_spec.rb
spec/resources/numismatic_issue/numismatic_issues_feature_spec.rb

* Updates metadata views to support either an Array or a Hash for `primary_terms` — a Hash creates a section with the key as the label, and the values as field names.
* Updates the Numismatic Issue to use a `primary_terms` Hash to group fields in a similar order to the existing application
Fixes #2174 , Fixes #2129

Numismatic Issue form reorganization

---

app/services/pdf_generator.rb
app/services/pdf_generator/canvas_downloader.rb
spec/services/pdf_generator_spec.rb

This should assist with tracing the root of the cause for #2153

Ensuring that PDFGenerator errors are logged with the URL used in the request

---

app/resources/playlists/playlist_decorator.rb
spec/decorators/playlist_decorator_spec.rb

Ensures that the PlaylistDecorator does not display the members attribute

---

.solr_wrapper
Procfile

This allows running the application in development mode with only a single command, instead of having to run Solr in a separate window.

Updating Foreman config to run solr

---

.rubocop.yml
app/assets/stylesheets/components/show.scss
app/change_set_persisters/change_set_persister/apply_auth_token.rb
app/change_set_persisters/change_set_persister/update_auth_token.rb
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/resources/playlists/playlist_change_set.rb
app/resources/playlists/playlist_decorator.rb
app/views/catalog/_auth_link_default.html.erb
app/views/catalog/_authorized_link.html.erb
spec/change_set_persisters/change_set_persister_spec.rb
spec/resources/playlist/playlist_decorator_spec.rb

Also integrates a form on the catalog show view for regenerating the authorized links.  Resolves #2053 
As an authenticated user, the following is rendered:
As an anonymous user, only the link itself is rendered:

Extends ApplyAuthToken to support the manual regeneration of authorization tokens for Playlists

---

app/views/catalog/_authorized_link.html.erb

This was meant to have been removed in #2233

Removing the authorized_link attribute partial for Playlists

---

app/services/manifest_builder/image_builder.rb
app/services/manifest_builder/manifest_service_locator.rb
spec/services/manifest_builder_spec.rb

I'm not sure whether this will fix dpul altogether or if widget will have to be re-assembled after this fix. but they're pretty broken already so I think that's okay we'll just have to check and adjust them if needed (see pulibrary/pomegranate#441)
closes #2246

Add image id to manifests

---

app/services/manifest_builder.rb
spec/services/manifest_builder_spec.rb

Should halve our manifest build times, bringing them back to where they
were before playlists.

Don't check members twice in ManifestBuilder.

---

app/assets/stylesheets/application.scss

Simple tweak that allows any [LUX Design Tokens](https://pulibrary.github.io/lux/docs/#/Design%20Tokens)(color, font size, spacing, etc) to be used as variables in the Rails asset pipeline.

allows lux design tokens to be used as variables in figgy asset pipeline

---

app/services/bulk_ingest_service.rb
spec/services/bulk_ingest_service_spec.rb

Fixes issue with spaces in folder names during bulk ingest of material from the maplab.
Closes #2288

Handle invalid remote identifier values during bulk ingest

---

app/views/collections_mailer/owner_report.html.erb
spec/resources/collections/collections_mailer_spec.rb

* limiting collection report to 10 items per state (to avoid huge emails)
* adding links to view all items and the collection
Fixes #2348

Collection report improvements

---

app/controllers/graphql_controller.rb

It's not useful, and right now it's just throwing a log message since
the session is a null session.

Skip CSRF protection for GraphQL

---

app/controllers/graphql_controller.rb

There were effectively two instances of CSRF protection, and only one
was being skipped.

Fix CSRF Disabling

---

config/locales/simple_form.en.yml

fixes #841
I didn't use parenthesis because the meaning seems clear without
them and I think fewer characters is better

Add more descriptive labels for date range form fields

---

app/controllers/concerns/resource_controller.rb

Children are pulled in dynamically as part of the JS, it's not necessary
to load them here and will just unnecessarily slow things down.

Don't load children to render OrderManager

---

app/controllers/concerns/resource_controller.rb
app/resources/raster_resources/raster_resource_wayfinder.rb
app/resources/vector_resources/vector_resource_wayfinder.rb
spec/features/file_manager_spec.rb
spec/views/scanned_resources/file_manager.html.erb_spec.rb

Speeds up rendering significantly by avoiding N+1 queries.

Use cached parents for File Manager.

---

app/graphql/types/query_type.rb
spec/graphql/types/query_type_spec.rb

Ensures that cases where resources cannot be retrieved by ID for GraphQL queries are handled

---

app/graphql/types/query_type.rb
app/graphql/types/scanned_map_type.rb
app/graphql/types/scanned_resource_type.rb
app/queries/find_many_by_string_property.rb
config/initializers/valkyrie.rb
spec/graphql/types/query_type_spec.rb
spec/graphql/types/scanned_map_type_spec.rb
spec/graphql/types/scanned_resource_type_spec.rb
spec/queries/find_many_by_string_property_spec.rb

This provides a GraphQL query for retrieving multiple resources for a set of bib. IDs (this will be necessary for resolving pulibrary/orangelight/issues/1534).  This ensures that only a single query must be made using GraphQL in order to retrieve a set of thumbnail IDs for a set of bib. IDs.

Implementing the FindManyByStringProperty custom query and GraphQL ResourcesByBibIds query

---

public/uv/themes/uv-en-gb-theme/css/uv-seadragon-extension/theme.css

I should probably create a custom theme instead of this, but I can't
figure it out and all the documentation is gone since V3.
Closes #928

Adds a fallback of Arial to the UV theme.

---

app/models/schema/geo.rb
app/resources/scanned_maps/scanned_map.rb
app/resources/scanned_maps/scanned_map_change_set.rb
app/resources/scanned_maps/scanned_map_decorator.rb
app/services/geo_discovery/document_builder/relationship_builder.rb
app/views/records/edit_fields/_gbl_suppressed_override.html.erb
config/locales/en.yml
spec/resources/scanned_map/scanned_map_decorator_spec.rb
spec/resources/scanned_map/scanned_map_feature_spec.rb
spec/services/geo_discovery/document_builder_spec.rb

Scanned maps that are normally suppressed in a GeoBlacklight search can be made discoverable by setting the the gbl_suppressed_override property to true.
Closes #2393

 Make child scanned maps optionally discoverable

---

app/assets/javascripts/save_and_ingest_handler.es6

Stops requests from changing the field from auto-fill from running into
one another.

Abort outdated request in Save & Ingest

---

app/javascript/packs/auth_link_clipboard.js
app/views/catalog/_auth_link_default.html.erb
package.json
yarn.lock

Add clipboard.js and use it for "copy to clipboard" button on auth_link

---

app/javascript/components/playlist_member.vue

Disable all Track detach buttons when one is clicked

---

app/change_set_persisters/change_set_persister/check_fixity.rb
app/jobs/check_fixity_job.rb
app/jobs/check_fixity_recursive_job.rb
app/jobs/create_derivatives_job.rb

* Always queue fixity jobs at the lowest level so they don't compete with ingest, derivatives processing, etc.

Always queue fixity jobs as super_low priority

---

app/controllers/application_controller.rb
spec/resources/ephemera_box/ephemera_boxes_controller_spec.rb
spec/resources/ephemera_field/ephemera_fields_controller_spec.rb
spec/resources/ephemera_folder/ephemera_folders_controller_spec.rb
spec/resources/ephemera_project/ephemera_projects_controller_spec.rb
spec/resources/ephemera_term/ephemera_terms_controller_spec.rb
spec/resources/ephemera_vocabulary/ephemera_vocabularies_controller_spec.rb
spec/resources/file_set/file_sets_controller_spec.rb
spec/resources/raster_resource/raster_resources_controller_spec.rb
spec/resources/scanned_map/scanned_maps_controller_spec.rb
spec/resources/scanned_resource/scanned_resources_controller_spec.rb
spec/resources/vector_resource/vector_resources_controller_spec.rb
spec/shared_specs/controllers/base_resource_controller.rb
spec/support/matchers/redirect_to_not_found.rb

This should prevent a whole suite of Honeybadger errors, and avoid
displaying 500 errors to users when they can't do anything about it.
Closes #2534

Missing resources should redirect and error.

---

architecture-decisions/0002-queues.md

Will need to be rebased after #2545

Decision: Queue priorities and guidelines

---

.circleci/config.yml
Gemfile
Gemfile.lock
app/controllers/reports_controller.rb

This gets CI time from 10 minutes to 7 minutes.
That being said, I'm unsure it's worth it, since it ties us to Coveralls for sure. What -is- interesting, is using the Solr box in docker caused some indexing errors related to nested documents we had never seen before. The properties were definitely wrong and looked nested, so it's strange that our Solr hasn't been complaining.

Run specs in parallel in CircleCI

---

Gemfile
Gemfile.lock
spec/support/capybara.rb
spec/support/capybara_selenium.rb

This gem automatically takes a screenshot whenever a javascript-enabled
feature test fails. Occasionally very helpful for debugging.

Add capybara-screenshot

---

.rubocop.yml
app/change_set_persisters/change_set_persister/mint_identifier.rb
app/controllers/concerns/resource_controller.rb
spec/change_set_persisters/change_set_persister/mint_identifier_spec.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Resolves #2577 by addressing the following:
- Modifies `IdentifierService` to only mint/update ARKs for resources with updated titles when they have already been published
- Ensures that cases where PULFA ARK updates raise errors are handled by flashing an alert to clients and redirecting them to the edit form

Ensures that cases where PULFA ARK updates raise errors

---

app/graphql/types/resource.rb
spec/graphql/types/scanned_resource_type_spec.rb

Extends the GraphQL Types::Resource in order to ensure that invalid IIIF manifest URLs are handled

---

app/services/manifest_builder.rb
spec/services/manifest_builder_spec.rb

Handes cases where the FileSet derivative cannot be retrieved for Playlists in the ManifestBuilder

---

.rubocop.yml
app/resources/numismatic_issues/numismatic_issues_controller.rb
app/resources/numismatic_monograms/numismatic_monograms_controller.rb
spec/resources/numismatic_issues/numismatic_issues_controller_spec.rb
spec/resources/numismatic_monograms/numismatic_monograms_controller_spec.rb

Ensures that numismatic controllers handle cases where persisted NumismaticMonograms cannot be retrieved

---

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb
spec/change_set_persisters/change_set_persister_spec.rb

Without a pre-populated ChangeSet, it wasn't detecting array differences
appropriately.

Fix state/visibility propagation.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/bulk_edit.scss
app/controllers/bulk_edit_controller.rb
app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/jobs/bulk_update_job.rb
app/views/bulk_edit/resources_edit.html.erb
app/views/catalog/_sort_and_per_page.html.erb
app/views/collections/_bulk_edit_button.html.erb
config/routes.rb
spec/controllers/bulk_edit_controller_spec.rb
spec/features/bulk_edit_spec.rb
spec/jobs/bulk_update_job_spec.rb

- Bulk edit button displays on search results page when a collection facet
is selected.
- search params are passed around so we can retrieve the same results
set
- Bulk edit controller queues 1 update job per 50 resources
Closes #1860 
Closes #2494 
Closes #697 
Other functionality moved to #2586

Add bulk complete UI

---

.rubocop.yml
app/controllers/concerns/orangelight_document_controller.rb
app/resources/coins/coins_controller.rb
app/resources/coins/orangelight_coin_builder.rb
app/resources/numismatic_issues/numismatic_issue.rb
app/services/geo_discovery/document_builder.rb
app/services/orangelight_document.rb
app/validators/year_validator.rb
app/views/records/edit_fields/_numismatic_monogram_ids.html.erb
config/routes.rb
spec/resources/coins/coins_controller_spec.rb
spec/services/orangelight_document_spec.rb
spec/validators/year_validator_spec.rb

- Adds generic Orangelight document service and a builder for Coin resources.
- Fixes issue with nil values in numismatic monogram input.
- Increases flexibility of the year validator to accommodate BCE and years with less than four digits.

Add orangelight document builder for coins

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/characterize.rb
app/change_set_persisters/change_set_persister/cleanup_pdfs.rb
app/change_set_persisters/change_set_persister/create_file.rb
app/change_set_persisters/change_set_persister/publish_message.rb
app/change_sets/change_set.rb
app/resources/collections/collection_change_set.rb
app/resources/file_sets/file_set_change_set.rb
app/resources/numismatic_monograms/numismatic_monogram_change_set.rb
app/views/catalog/_workflow_controls_default.html.erb
spec/change_set_persisters/change_set_persister_spec.rb

The change_set_persister is re-used for multiple interactions with a
variety of ChangeSets. As such, tracking it there was leading to the
created_file_sets getting wiped, resulting in no characterization being
run.
Closes #2654

Track file sets being created on ChangeSet

---

app/graphql/types/query_type.rb
app/queries/find_many_by_property.rb
config/initializers/valkyrie.rb
spec/graphql/types/query_type_spec.rb
spec/queries/find_many_by_property_spec.rb

Adds new queries for orangelight ids rather than just bib_ids.
Closes #2655

 Add graphql queries for coins and orangelight ids

---

app/change_set_persisters/change_set_persister/cleanup_pdfs.rb
app/resources/scanned_maps/scanned_map_change_set.rb
spec/change_set_persisters/change_set_persister/cleanup_pdfs_spec.rb
spec/resources/scanned_maps/scanned_map_feature_spec.rb

- Adds PDF Type to scanned map
- Allows scanned map PDFs to be cleaned up
Closes #2694

Add PDF Type to scanned map form

---

.rubocop.yml
app/helpers/application_helper.rb
app/javascript/components/document_adder.vue
spec/features/playlist_spec.rb
spec/helpers/application_helper_spec.rb

Resolves #2502 by overriding `Blacklight::UrlHelperBehavior#link_back_to_catalog` to parse for cached query parameters stored from AJAX search requests and adding an `async` GET parameter to the DocumentAdder Vue Component.

Overrides Blacklight::UrlHelperBehavior#link_back_to_catalog in order to generate search result links from Playlists

---

app/services/cicognara_marc.rb
app/services/marc_record_enhancer.rb
spec/services/cicognara_marc_spec.rb
spec/services/marc_record_enhancer_spec.rb

* Manifest 856 should include a subfield q declaring it to be JSON/IIIF
* Close XML write to ensure valid XML
* DCL Number 024 should have "8" for first indicator
Fixes #2684

Cicognara MARC export improvements

---

.rubocop.yml
app/change_sets/change_set.rb
app/resources/name_with_places/name_with_place.rb
app/resources/name_with_places/name_with_place_change_set.rb
app/resources/scanned_resources/letter_change_set.rb
app/resources/scanned_resources/scanned_resource.rb
app/views/records/edit_fields/_recipient.html.erb
app/views/records/edit_fields/_sender.html.erb
config/routes.rb
spec/resources/scanned_resources/letter_change_set_spec.rb
spec/routing/letter_resource_spec.rb

Depends on #2726 
This enables some new functionality for nested forms, as well as an experimental method of grouping ChangeSet properties by feature. It's pretty similar to multiple inheritance, but all in one place - something to think about?
The form looks like this:

Letter Change Sets

---

.rubocop.yml
app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/values/viewer_configuration.rb
config/routes.rb
spec/helpers/application_helper_spec.rb
spec/requests/viewer_config_spec.rb
spec/routing/viewer_config_routes_spec.rb
spec/support/devise.rb
spec/values/viewer_configuration_spec.rb

Provides a proper solution for #2628 (which will ensure that external services, such as dpul.princeton.edu, can access the viewer with downloads disabled for Figgy resources)

Provides a route for dynamically generating Universal Viewer configuration settings

---

app/helpers/thumbnail_helper.rb
spec/graphql/types/resource_spec.rb

Instead of displaying a filler thumbnail, this just shows an empty space
if it can't resolve one.
Closes #2717

Don't display a filler thumbnail.

---

app/resources/coins/coin_decorator.rb
app/resources/coins/orangelight_coin_builder.rb
spec/services/orangelight_document_spec.rb

Generates a summary field for display in Orangelight search results.
Closes #2735
Closes pulibrary/orangelight#1606

Add pub_created_display field to coin document

---

.rubocop.yml
app/controllers/application_controller.rb
app/values/exhibit_viewer_configuration.rb
app/values/viewer_configuration.rb
config/routes.rb
spec/requests/viewer_exhibit_config_spec.rb
spec/routing/viewer_exhibit_config_routes_spec.rb
spec/values/exhibit_viewer_configuration_spec.rb

Implements a route and ApplicationController functionality for providing configurations to Universal Viewer installations which are embedded in digital exhibit platforms (this is necessary for https://github.com/pulibrary/pomegranate/issues/562)

Implements a route for providing Universal Viewer configurations for digital exhibit platforms

---

app/decorators/valkyrie/resource_decorator.rb
spec/decorators/valkyrie/resource_decorator_spec.rb

When the downloadable attribute is a nil value, `ResourceDecorator` will then delegate to the visibility and workflow state of the resource.

Ensures that ResourceDecorator#downloadable? handles cases where the "downloadable" attribute is nil

---

app/controllers/concerns/resource_controller.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Resolves #2724 by ensuring that, for cases where users try to create `ScannedResources` with invalid `ChangeSets`, the client is redirected to create a new `ScannedResource` and an error is flashed

Handles invalid change_set parameters for new ScannedResource forms

---

app/helpers/thumbnail_helper.rb
spec/helpers/thumbnail_helper_spec.rb

Resolves #2765 by ensuring that errors raised from the `QueryService` when generating thumbnail markup on search result views are handled by rendering the default thumbnail image

Handles errors raised when querying for resources during search result thumbnail generation

---

.rubocop.yml
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/components/form.scss
app/change_sets/change_set.rb
app/resources/coins/coin_decorator.rb
app/resources/name_with_places/name_with_place_change_set.rb
app/resources/numismatic_issues/numismatic_issue.rb
app/resources/numismatic_issues/numismatic_issue_change_set.rb
app/resources/numismatic_issues/numismatic_issue_decorator.rb
app/resources/numismatic_place/numismatic_place_change_set.rb
app/resources/scanned_resources/letter_change_set.rb
app/resources/scanned_resources/scanned_resource.rb
app/resources/scanned_resources/scanned_resource_decorator.rb
app/views/numismatic_issues/_place_fields.html.erb
app/views/numismatic_issues/edit_fields/_place.html.erb
app/views/records/edit_fields/_recipient.html.erb
app/views/records/edit_fields/_sender.html.erb
app/views/scanned_resources/_recipient_fields.html.erb
app/views/scanned_resources/_sender_fields.html.erb
config/locales/en.yml
spec/factories/scanned_resource.rb
spec/resources/numismatic_issues/numismatic_issue_change_set_spec.rb
spec/resources/scanned_resources/letter_change_set_spec.rb
spec/resources/scanned_resources/letter_feature_spec.rb

- Adds Cocoon gem for nested forms.
- Adjust styling to mimic hydra-editor multivalued fields.
- Makes all nested resource forms a collection. 
- This is a departure from the existing nested form implementation. This fixes an issue with deleting a nested resource and improves the UI. 
- The `place` property on numismatic issue is an example of a nested form where users can only add a single set of values. https://github.com/pulibrary/figgy/blob/5a8ac11b673e209ae91fcb50cb412fea5583e554/app/views/numismatic_issues/edit_fields/_place.html.erb
- This could also be enforced with a validator.

Add cocoon for nested forms

---

.rubocop.yml
app/adapters/bagit/bag_exporter.rb
app/adapters/bagit/bag_importer.rb
spec/adapters/bagit/bag_roundtrip_spec.rb

This does a few things:
1. Adds a test for Ephemera with Vocabularies
2. Stores all referenced objects, recursing deep, into the bag of the parent on export. This bag is considered a preservation artifact, so the hope is that it's self-contained.
3. Don't overwrite objects on import if they already exist.

Import/Export Dependent Objects into Bags

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/base_resource_controller.rb
app/controllers/bulk_ingest_controller.rb
app/values/browse_everything/resource.rb
app/values/browse_everything_file_paths.rb
spec/controllers/bulk_ingest_controller_spec.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb
spec/values/browse_everything_file_paths_spec.rb

This required some significant adjustments to the `browse-everything` branch which already integrated support for paginating Google Drive file entries: https://github.com/jrgriffiniii/browse-everything/compare/gdrive-paging-jrgriffiniii-rebased...jrgriffiniii:figgy-issues-1536-jrgriffiniii?expand=1
In order to retain backward compatibility with 1.x releases, this duplicates form fields and parameters passed in the `POST` request which disambiguate selected files from directories.  Additionally, this also provides a `BrowseEverything::Resource` class (which might be better suited for the `browse-everything` branch instead).  Resolves #1536

Updates the BulkIngestController and BaseResourceController for directories selected with browse-everything

---

app/models/pending_upload.rb

Resolves #2837 (but this should be more properly resolved by ensuring that the legacy arguments are still handled on https://github.com/samvera/browse-everything)

Updates `PendingUpload#copied_file_name` to pass the auth. headers using another parameter key

---

app/controllers/catalog_controller.rb
spec/features/catalog_spec.rb

This allows people to search in read-only mode without getting errors
due to blacklight creating `Search` objects.
fixes #2875

Turn off search history when in read-only mode

---

Gemfile
Gemfile.lock
app/adapters/bagit/persister.rb
app/characterization_services/external_metadata_characterization_service.rb
app/characterization_services/gdal_characterization_service.rb
app/characterization_services/geo_characterization_service.rb
app/characterization_services/imagemagick_characterization_service.rb
app/characterization_services/mediainfo_characterization_service.rb
app/characterization_services/scanned_map_characterization_service.rb
app/characterization_services/tika_file_characterization_service.rb
app/resources/file_sets/file_set.rb
app/resources/file_sets/file_set_change_set.rb
app/resources/file_sets/file_sets_controller.rb
spec/models/file_set_spec.rb

This should prevent all race conditions overriding things like derivatives happening in background jobs. It could theoretically cause an error for users too, but we'll have to see if that happens in reality - it should be pretty hard to trigger, since the form doesn't include the lock token.
Tested and made sure this fixes the issue with #2657 and #2877.
Closes #2657 
Closes #2877

Enables optimistic locking for FileSets

---

app/resources/numismatic_people/numismatic_person_change_set.rb
app/resources/numismatic_people/numismatic_person_decorator.rb
spec/resources/numismatic_people/numismatic_person_decorator_spec.rb

Minor fixes for NumismaticPerson implementation.
- Add `replaces` property to change set. Corrects an initial mistake.
- Updates decorator to account for cases where born, died, years_active_start, and years_active_end are not all described.

Fixes for NumismaticPerson

---

.rubocop.yml
app/resources/coins/coin_decorator.rb
app/resources/coins/orangelight_coin_builder.rb
app/resources/numismatic_accessions/numismatic_accession_decorator.rb
app/resources/numismatic_issues/numismatic_issue.rb
app/resources/numismatic_issues/numismatic_issue_change_set.rb
app/resources/numismatic_issues/numismatic_issue_decorator.rb
app/resources/numismatic_subjects/numismatic_subject.rb
app/resources/numismatic_subjects/numismatic_subject_change_set.rb
app/resources/numismatic_subjects/numismatic_subject_decorator.rb
app/views/numismatic_issues/_numismatic_subject_fields.html.erb
app/views/numismatic_issues/edit_fields/_numismatic_subject.html.erb
config/locales/en.yml
spec/controllers/catalog_controller_spec.rb
spec/resources/coins/coin_decorator_spec.rb
spec/resources/coins/coin_feature_spec.rb
spec/resources/numismatic_accessions/numismatic_accession_decorator_spec.rb
spec/resources/numismatic_issues/numismatic_issue_change_set_spec.rb
spec/resources/numismatic_issues/numismatic_issue_decorator_spec.rb
spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb
spec/resources/numismatic_subjects/numismatic_subject_change_set_spec.rb
spec/resources/numismatic_subjects/numismatic_subject_decorator_spec.rb
spec/resources/numismatic_subjects/numismatic_subject_spec.rb
spec/services/orangelight_document_spec.rb

- Adds NumismaticSubject resource
- Use nested NumismaticSubject in NumismaticIssue
- Rename nested resources in numismatic decorators to be less confusing
- Reorganize / alphabetize NumismaticIssue, Coin, NumismaticAccession decorators
Closes #2899

 Adds NumismaticSubject resource

---

app/assets/stylesheets/components/select_box.scss

Small update in the drop down select. 
I noticed that changing into the same px number the max-height in open and inner class, some information (select options) might not be visible. Now I'm setting the open max-height > than the inner max-height to fix this.

small update in the drop down select box

---

app/jobs/update_fixity_job.rb

We don't want a barrage of updating events to slow down ingest.

Queue update fixity job as super low.

---

bin/ci_kakadu_install.sh

Pulls Kakadu from an AWS bucket until their website is back online.

Temp fix for kakadu download

---

app/jobs/ingest_archival_media_bag_job.rb
app/views/catalog/_media_html5_player_default.html.erb
spec/jobs/ingest_archival_media_bag_job_spec.rb

* Don't display the player unless there is a derivative file
* Cache filesets after saving to avoid duplicate filesets
Related to #1960

Archival audio fixes

---

app/controllers/reports_controller.rb
app/views/reports/pulfa_ark_report.html.erb
spec/controllers/reports_controller_spec.rb

- Guards against blank `since_date` on the controller.
- Makes `since_date` a required field.
- Adds date picker.
Closes #2999

Fix issue with blank pulfa report since_date

---

lib/tasks/lae.rake

This will give a more clear error in a case like the one we just saw,
where the directory had the wrong name.

Add another layer of messaging to the lae folder import task

---

app/controllers/concerns/resource_controller.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Ensures that when `Valkyrie::Persistence::StaleObjectErrors` are raised while attempting to update a resource, users are redirected to the edit view and alerted with a warning message.  Resolves #2970

Handles Valkyrie::Persistence::StaleObjectErrors during Resource updates

---

app/change_set_persisters/change_set_persister/cleanup_membership.rb
spec/change_set_persisters/change_set_persister_spec.rb

Ensures that thumbnail_id properties are emptied for a parent resource when deleting a member resource

---

app/services/reindexer.rb
lib/tasks/reindex.rake
spec/services/reindexer_spec.rb

* Add Rake task to reindex everything but FileSets
* Reduces batch size to 500 to avoid `Request Entity Too Large` errors
Fixes #3031

Add Rake task to reindex everything except FileSets

---

.rubocop.yml
app/services/manifest_builder.rb
spec/resources/numismatic_issues/numismatic_issues_controller_spec.rb
spec/services/manifest_builder_spec.rb

Prevents a sequence 0 error in the UV viewer by building the manifest with only the coins that have an image
Co-authored-by: Trey Pendragon <tpendragon@princeton.edu>

Display in the viewer only the coins that have an image

---

bin/ci_kakadu_install.sh

The Kakadu downloads should be restored:
```
% curl -I "http://kakadusoftware.com/wp-content/uploads/2014/06/KDU77_Demo_Apps_for_Linux-x86-64_150710.zip"
HTTP/1.1 200 OK
Date: Fri, 17 May 2019 15:09:29 GMT
...
```

Restores the Kakadu downloads (the website has been restored)

---

app/controllers/catalog_controller.rb
app/jobs/create_derivatives_job.rb
app/models/solr_document.rb
app/queries/find_deep_children_with_property.rb
app/resources/file_sets/file_set.rb
app/resources/scanned_resources/scanned_resource_wayfinder.rb
app/services/file_appender.rb
app/views/catalog/_in_process_notification_default.html.erb
config/initializers/valkyrie.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/models/file_set_spec.rb
spec/queries/find_deep_children_with_property_spec.rb
spec/views/catalog/_in_process_notification_default.html.erb_spec.rb
spec/wayfinders/wayfinder_spec.rb

After browse everything attached, but files not moved to repository:
Before derivatives done being created:
Wanted to add a note: I benchmarked this query for production. On a MVW with 1300 total filesets it takes ~ 70 ms to count them.
Closes #2447

Keep Track of and display status of FileSet derivative creation

---

app/views/numismatic_monograms/index.html.erb

Removes the manage monogram thumbnail link because it points to an invalid url:
https://figgy-staging.princeton.edu/concern/numismatic_monograms
Click "view" instead to view monogram object.

remove broken monogram thumbnail link

---

app/views/catalog/_attach_child_default.html.erb

With the action bar being sticky the dropdown fell off the screen.
fixes #3061

Change attach child button to drop-up

---

app/change_set_persisters/change_set_persister/extract_archival_collection_code.rb
app/jobs/extract_archival_collection_code_job.rb
app/models/remote_record.rb
app/services/bulk_ingest_service.rb
app/services/source_metadata_identifier_migrator.rb
app/validators/source_metadata_identifier_validator.rb
config/locales/simple_form.en.yml
db/migrate/20190521200107_update_source_metadata_identifier.rb
db/structure.sql
lib/tasks/migrate.rake
spec/change_set_persisters/change_set_persister/extract_archival_collection_code_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/models/remote_record_spec.rb
spec/resources/archival_media_collections/archival_media_collection_change_set_spec.rb
spec/resources/archival_media_collections/archival_media_collections_controller_spec.rb
spec/services/identifier_service_spec.rb
spec/services/manifest_builder/see_also_builder_spec.rb
spec/services/source_metadata_identifier_migrator_spec.rb

* Refactor PULFA id validation and parsing
* Require underscores to separate PULFA collection/component IDs (instead of allowing either slash or underscore)
* Add form hints on acceptable ID formats

Require underscores to separate PULFA collection/component IDs

---

app/derivative_services/audio_derivative_service.rb
app/derivative_services/default_derivative_service.rb
app/derivative_services/external_metadata_derivative_service.rb
app/derivative_services/scanned_map_derivative_service.rb
app/jobs/ingest_archival_media_bag_job.rb
app/resources/scanned_resources/recording_change_set.rb
app/resources/scanned_resources/scanned_resource.rb
app/services/manifest_builder.rb
app/validators/unique_archival_media_barcode_validator.rb
spec/derivative_services/audio_derivative_service_spec.rb
spec/jobs/ingest_archival_media_bag_job_spec.rb
spec/services/manifest_builder_spec.rb

I got a little ahead of myself. This PR does three things:
IngestArchivalMediaBagJob ingests Recordings instead.
Regenerating HLS derivatives works when there's an intermediate file.
Initial Manifest generation works
Closes #3079

Recordings instead of MediaResources

---

app/resources/scanned_resources/scanned_resource_decorator.rb
app/resources/scanned_resources/scanned_resource_wayfinder.rb
app/views/catalog/_admin_controls_recording.html.erb
app/views/catalog/_members_recording.html.erb
app/views/catalog/_members_simple_resource.html.erb
spec/jobs/ingest_archival_media_bag_job_spec.rb
spec/resources/scanned_resources/scanned_resource_decorator_spec.rb
spec/resources/scanned_resources/scanned_resource_feature_spec.rb
spec/views/catalog/_admin_controls_recording.html.erb_spec.rb
spec/views/catalog/_members_recording.html.erb_spec.rb
spec/wayfinders/wayfinder_spec.rb

1. This makes the change set human readable model take priority over the fact that it has ScannedResource children.
2. Hides "Create a Playlist" button for descriptive proxies
3. Displays the member list if it's a descriptive proxy.
Closes #3100

Descriptive Proxy Recordings display as Recordings

---

Gemfile
Gemfile.lock
bin/ci_kakadu_install.sh

Fixes issue with CI related to the unreliability of the http://kakadusoftware.com website.

Retrieve Kakadu binaries from Princeton google cloud storage

---

app/services/manifest_builder.rb
spec/services/manifest_builder_spec.rb

This is necessary to fully resolve #3070, as PDF renderings are offered in cases where a `Recording` has both image and audio `FileSets` as members.

Disables manifest sequence renderings for audio recording resources

---

app/change_set_persisters/change_set_persister/preserve_resource.rb
spec/features/fixity_dashboard_spec.rb

Updates were way too slow for preserved resources that were updating all
children.

Preserve in a background job, always.

---

spec/support/capybara_selenium.rb

Otherwise, Selenium opens a browser when these test suites are run.

Ensures that the Selenium feature tests are run headlessly

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/reorganize_collection.rb
app/jobs/ingest_archival_media_bag_job.rb
app/models/archival_media_bag_parser.rb
app/resources/collections/archival_media_collection_change_set.rb
app/views/records/edit_fields/_reorganize.html.erb
spec/change_set_persisters/change_set_persister_spec.rb
spec/resources/archival_media_collections/archival_media_collection_change_set_spec.rb

This provides a checkbox in the AMC edit form which, when the form is submitted, will parse the EAD and reorganize all of the AMC's existing barcodes based on where the EAD says they should be.
Closes #3021

Reorganize Barcodes within Archival Media Collection

---

app/change_sets/concerns/remote_metadata_property.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/resources/scanned_resources/scanned_resource_feature_spec.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Refresh remote metadata on change of SMID, no matter what

---

app/change_sets/change_set.rb
app/helpers/catalog_helper.rb
app/resources/collections/archival_media_collection_change_set.rb
app/services/manifest_builder.rb
app/services/manifest_builder/logo_builder.rb
app/views/catalog/_universal_viewer_default.html.erb
spec/services/manifest_builder_spec.rb

Resolves #3156 by addressing the following:
- Generating `Manifests` with `Recordings` for `ArchivalMediaCollections`
- Integrating Universal Viewer support for `ArchivalMediaCollections`
- Ensuring that `Manifest` `Range` labels are retrieved from `FileSets`
- Ensuring that `ArchivalMediaCollection` manifests exclude image `FileSets` from `Ranges`

Generating Manifests with Recordings for ArchivalMediaCollections

---

app/change_sets/dynamic_change_set.rb
app/controllers/concerns/resource_controller.rb
app/decorators/valkyrie/resource_decorator.rb
app/resources/scanned_resources/scanned_resources_controller.rb
spec/change_sets/dynamic_change_set_spec.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Resolves #2722 (previously this was only handled at the level of `ResourceController#new`, but this is invoked from other contexts; please see https://app.honeybadger.io/projects/53391/faults/46908296)

Ensures that ScannedResourcesController#change_set_class returns DynamicChangeSet when the change_set parameter is invalid

---

app/change_sets/change_set.rb
app/helpers/catalog_helper.rb
app/resources/collections/archival_media_collection_change_set.rb
app/views/catalog/_universal_viewer_default.html.erb

Resolves #3176 by reverting some of the changes introduced in https://github.com/pulibrary/figgy/commit/afdc8ac86474dd6af4fa73e22f6ebb236dfe3bf0

Removing the CatalogHelper#can_have_manifests? method due to performance issues introduced for non-ArchivalMediaCollection resources

---

app/resources/file_sets/file_set_decorator.rb
spec/resources/file_sets/file_set_decorator_spec.rb

For IDs which aren't in a PreservationObject it was returning all
events.

Fix file set cloud fixity display.

---

app/assets/javascripts/collection_bag_uploader.es6

Otherwise, https://github.com/pulibrary/figgy/pull/3145/files#diff-18b55a2cbdd21595a7dfdc75b12c3e8bR4 breaks this for resource (e. g. `ScannedResource`) file management

Ensures that the browse-everything bag uploader for ArchivalMediaCollections does not collide with the DOM binding for ScannedResource file uploader

---

app/views/numismatics/coins/_file_manager_extra_tools.html.erb
config/routes.rb

Fixes cases where attempting to add a `Coin` to a Numismatic `Issue` fails with an error:
There was also this namespacing issue when users attempt to upload files for `Coins`:

Fixes paths and routes for Numismatic Coins with improper namespaces

---

app/services/geo_discovery/document_builder/date_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

Fixes problem with dates that prevented `issue` property from being correctly added to GeoBlacklight documents.

Index issued property in geoblacklight documents

---

app/javascript/components/document_adder.vue

Also ensures that cases where Recordings without a title_ssim retrieved by the track
search form are handled properly.  Resolves #3035

Ensuring that when adding Recordings as Tracks for Playlists, the table does not have headers rendered when it is empty

---

Gemfile
Gemfile.lock
app/services/bulk_ingest_service.rb
spec/services/bulk_ingest_service_spec.rb

Resolves #3201 and #3194, but I should clarify here that I experienced significant difficulty reproducing these errors within a macOS environment.  `Dir` seems to attempt to avoid parsing for hidden file entries:
> Note, this will not match Unix-like hidden files (dotfiles). In order to include those in the match results, you must use the File::FNM_DOTMATCH flag or something like "{*,.*}".
(http://ruby-doc.org/core-2.6.3/Dir.html#method-c-glob)

Updating browse-everything and ensuring that the BulkIngestService excludes hidden files

---

RELEASE_NOTES.md
app/controllers/application_controller.rb
app/models/ability.rb
spec/models/ability_spec.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

* If a user can discover a resource, but can't read it, they'll get an
Unauthorized message which will prompt the viewer to let them log in.
* Users can Discover reading room resources if they're in the reading
room.
* Users can not discover private resources unless they're some sort of
administrator.

Use Discover permissions for Reading Room

---

.rubocop.yml
RELEASE_NOTES.md
app/jobs/ingest_ukrainian_ephemera_mods_job.rb
app/models/mets_document/mods_document.rb
app/queries/find_ephemera_term_by_label.rb
app/services/ingest_ephemera_mods.rb
lib/tasks/migrate.rake
spec/fixtures/files/ukrainian-001.mods
spec/jobs/ingest_ukrainian_ephemera_mods_job_spec.rb
spec/queries/find_ephemera_term_by_label_spec.rb
spec/services/ingest_ephemera_mods_spec.rb

Mostly targeting Ukrainian ephemera with a subclass that hard-codes some values.  But should be the vast majority of what's needed to ingest other ephemera with MODS metadata.

Add support for ingesting ephemera with MODS metadata

---

RELEASE_NOTES.md
app/derivative_services/image_derivative_service.rb
app/derivative_services/jp2_derivative_service.rb
app/derivative_services/raster_resource_derivative_service.rb
app/derivative_services/vector_resource_derivative_service.rb
spec/derivative_services/image_derivative_service_spec.rb
spec/derivative_services/jp2_derivative_service_spec.rb
spec/resources/raster_resources/raster_resource_derivative_service_spec.rb
spec/resources/scanned_maps/scanned_map_derivative_service_spec.rb
spec/resources/vector_resources/vector_resource_derivative_service_spec.rb

fixes #3235
Related issue created: https://github.com/pulibrary/figgy/issues/3265
Just an update; I commented in the issue that I wanted to do this in the regenerate derivatives job; that ended up being a bad place for 2 reasons:
1. When I did it there the jobs stepped on one another and there were stale object errors. 
2. It fits logically with the clean_derivatives code in the services themselves.

Clear error messages when clearing derivatives

---

RELEASE_NOTES.md
app/indexers/imported_metadata_indexer.rb
spec/indexers/imported_metadata_indexer_spec.rb

Index imported metadata values as plain strings without brackets, class names, etc.

---

RELEASE_NOTES.md
app/javascript/components/OrderManager.vue
app/javascript/components/OrderManagerControls.vue
app/javascript/store/resource/index.js
app/javascript/test/orderManagerControls.spec.js

Relates to #3233 by introducing a "fetching" property to the OrderManagerControls component in order to prevent users from submitting GraphQL update mutations between Resource updates

Introduces a "fetching" property to the OrderManagerControls component

---

RELEASE_NOTES.md
public/viewer.html

This has no empty space if there's no title meant to be displayed
(playlists only), and fixes the height if the title -is- displayed.
Closes #3249

Fix viewer empty space.

---

.rubocop.yml
RELEASE_NOTES.md
app/helpers/thumbnail_helper.rb
spec/helpers/thumbnail_helper_spec.rb

Ensures that the ThumbnailHelper#iiif_thumbnail_path handles cases where thumbnails can only be retrieved from member resources

---

app/services/migrations/add_preservation_object_ids_migrator.rb
lib/tasks/migrate.rake
spec/services/migrations/add_preservation_object_ids_migrator_spec.rb

This generates IDs for those PreservationObjects which don't have them in their FileMetadata nodes (a result of a bug which has since been fixed), and also deletes any events which try to associate with child_ids that don't exist.
Edit: A fair warning that since most of our events are from the pilot, a vast majority of our events are going to get deleted (all but 553 of them.) However, there's no reasonable way to determine which binary_node an Event was meant for, so it can't really be helped.

Add migration to fix PreservationObjects with no FileMetadata IDs

---

app/controllers/bulk_ingest_controller.rb
app/resources/scanned_resources/scanned_resource_change_set.rb
app/services/bulk_ingest_service.rb
spec/controllers/bulk_ingest_controller_spec.rb
spec/resources/scanned_resources/scanned_resource_change_set_spec.rb
spec/services/bulk_ingest_service_spec.rb

* Support the `replaces` attribute
* Move BibID-guessing to BulkIngestController, to allow command-line ingest of items without BibIDs

Bulk Ingest Updates

---

README.md

Remove outdated documentation from when we didn't use yarn.
closes #3307

Add documentation for running jest tests

---

app/javascript/components/OrderManagerControls.vue
app/javascript/store/resource/index.js
app/javascript/test/orderManagerControls.spec.js

Order manager fetch state is never returned to true.
The context of `this` in the `isDisabled` method:
https://github.com/pulibrary/figgy/blob/f4d6b17e6c0dc422c8e541a97727fb7a43376cf9/app/javascript/components/OrderManagerControls.vue#L100
is different from the context of `this` in the `SAVED_STATE` method:
https://github.com/pulibrary/figgy/blob/f4d6b17e6c0dc422c8e541a97727fb7a43376cf9/app/javascript/store/resource/index.js#L36
The result is that the fetching state is never returned to `false`. This PR uses a global variable to store this state. 
Closes #3399

Use global variable to store order manager fetching state

---

app/utils/data_seeder.rb
spec/utils/data_seeder_spec.rb

Running this was causing an error generating events because held_by
wasn't always being populated. This fixes that.
I was unable to get the data seeder to actually generate this error even
when running background jobs, so there must be some difference in running
in dev vs test.

Fix DataSeeder.

---

app/services/manifest_builder.rb

This was happening because it was checking to see if it was a recording.
We can just encode that it's not.
Closes #3430

Don't query all members of a collection to build manifest.

---

RELEASE_NOTES.md
app/jobs/export_collection_pdf_job.rb
app/mailers/pulfa_mailer.rb
app/services/export_service.rb
app/services/pulfa_exporter.rb
app/services/pulfa_exporter/svn_client.rb
app/views/pulfa_mailer/branch_notification.html.erb
config/config.yml
config/schedule.rb
config/svn.yml
lib/tasks/export.rake
spec/fixtures/files/pulfa/C0652.EAD.xml
spec/jobs/export_collection_pdf_job_spec.rb
spec/services/pulfa_exporter_spec.rb

Implements two related processes for linking finding aids (EADs) to Figgy:
1. Weekly cron job to add DAOs to EADs for recently-completed Figgy objects with PULFA imported metadata.
2. Rake task to export all objects in a collection as PDFs, and then update the EAD with DAOs that link to those local PDFs.
Closes #1236; Closes #3396

Add Figgy manifest links to EADs

---

RELEASE_NOTES.md
app/helpers/application_helper.rb
app/models/ability.rb
app/values/viewer_configuration.rb
public/viewer.html
spec/helpers/application_helper_spec.rb
spec/models/ability_spec.rb
spec/values/viewer_configuration_spec.rb
spec/views/catalog/_members_file_set.html.erb_spec.rb

- Configures UV to use the Figgy-generated config document. This config document changes depending on the downloadable status of the resource.
- Disables non-admin and non-staff download of files whose parent is not downloadable.
Closes #3443

Disable anonymous downloads for non-downloadable resources

---

app/exporters/hathi/submission_information_package.rb
spec/exporters/hathi/submission_information_package_spec.rb
spec/jobs/export_hathi_sip_job_spec.rb

The zip files were too big to handle, so this PR drops the zipping and just creates a directory in which to deposit the files in the SIP.

Changes target of Hathi SIP from a zip file to a directory.

---

Gemfile
Gemfile.lock

Figgy was previously using a prerelease version of `Webpacker`, and this triggered errors in certain development environments.

Updated the Gemfile to pin to Webpacker 4.0.z releases

---

app/controllers/base_resource_controller.rb
app/controllers/bulk_ingest_controller.rb
spec/controllers/bulk_ingest_controller_spec.rb

This was triggering failures for BrowseEverything uploads, as the file metadata was not actually being stored in the PendingUpload Resource.

Ensures that PendingUpload constructors receive Hashes with symbolized keys

---

app/services/pulfa_exporter.rb

It's usually run by cron via the rake task at this point.
This will give us more information when a filename comes through that
code down the line doesn't like.
fixes #3485

Default pulfa exporter to rails log so we can see it in datadog

---

RELEASE_NOTES.md
app/controllers/base_resource_controller.rb
app/controllers/bulk_ingest_controller.rb
spec/controllers/bulk_ingest_controller_spec.rb

Ensures that authorization headers are passed to the PendingUpload constructor for Google Drive resources

---

.rubocop.yml
app/services/marc_record_enhancer.rb
spec/services/marc_record_enhancer_spec.rb

Some of our earlier catalogued Cicognara items put the identifier in 024
rather than in 510. This does the appropriate crosswalk.
Progresses #2845

Enhances Cicognara MARC with 510 from 024

---

lib/tasks/bulk.rake

Adding ability to ingest arbitrary files on the command-line so Figgy could be used to preserve and allow downloads of misc. born-digital content that needs to be moved out of WebSpace by the end of the year.
The ability to handle any specified extension was already present in `IngestFolderJob`, but the rake tasks didn't support it (or support it correctly).

Add support for file filters to bulk ingest

---

RELEASE_NOTES.md
app/views/numismatics_dashboard/_issues_row.html.erb
spec/views/numismatics_dashboard/show.html.erb_spec.rb

Ensuring that the link to view Numismatic Issues within the Numismatic dashboard does not erroneously use "Numismatic Issue" as the facet value

---

.rubocop.yml
RELEASE_NOTES.md
app/assets/stylesheets/components/form.scss
app/javascript/components/issue_monogram.vue
app/javascript/components/issue_monograms.vue
app/javascript/packs/application.js
app/resources/numismatics/issues/numismatics/issues_controller.rb
app/views/records/edit_fields/_numismatic_monogram_ids.html.erb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Resolves #3063 by introducing an IssueMonograms Vue component in order to provide users with the ability to select monograms from a gallery display when creating or editing numismatic issues

Introduces an IssueMonograms Vue component for selecting numismatic Monograms for Issues

---

config/deploy/production.rb

This is needed in order to restore production deployments from the `master` branch

Removing lib-proc4 and lib-proc5 from the deployment hosts

---

Gemfile.lock
RELEASE_NOTES.md

Resolves #3562 by handling cases where Rails controllers strip the leading "/" characters from file paths passed in the request parameter (please see https://github.com/samvera/browse-everything/commit/7390981fb96c038a5713da1984026dd0f1ea36cb)

Updating the browse-everything branch for a bug fix for Rails controller request parameter parsing

---

RELEASE_NOTES.md
app/indexers/title_indexer.rb
spec/indexers/title_indexer_spec.rb

Index decorated titles in addition to titles in defined on the model. Needed for resources like Numismatics::Artist where components of the title are delegated to a wayfinder.
https://github.com/pulibrary/figgy/blob/master/app/resources/numismatics/artists/numismatics/artist_decorator.rb#L25
Closes #3565

Index decorated titles

---

lib/tasks/music_reserves.rake

The naming of the method was changed in a previous refactor, but it was missed in the rake task.
Previous refactor commit: https://github.com/pulibrary/figgy/pull/2414/commits/87412abe5ae0b72bd6e218a67c73808809f7aae0

Fix import recording rake task.

---

Gemfile
Gemfile.lock
app/values/browse_everything_file_paths.rb
spec/controllers/bulk_ingest_controller_spec.rb

Resolves #3587 by addressing the following:
- Updating browse-everything in order to ensure that selected directories are parsed from within Controllers are parsed from within Controllers including
BrowseEverything::Parameters
- Ensuring that BrowseEverythingFilePaths#parent_path returns the path of a selected directory (when only a single directory is chosen for upload)

Updating browse-everything in order to ensure that selected directories are parsed from within Controllers

---

app/controllers/base_resource_controller.rb
app/controllers/bulk_ingest_controller.rb
spec/controllers/bulk_ingest_controller_spec.rb

This was pushed upstream with https://github.com/jrgriffiniii/browse-everything/blob/figgy-issues-3587-jrgriffiniii/lib/browse_everything/driver/google_drive.rb#L182. Resolves #3593

Retrieves the auth_header without parsing it into JSON when constructing PendingUpload objects

---

bin/ci_mediainfo_install.sh

This fixes the CI build. The previous install was no longer authenticated.

Update mediainfo install.

---

app/services/music_import_service/recording_collector.rb

Closes #3568. Note that sometimes the "Complete Concert" playlists have higher selection ids than the pieces causing them to appear at the bottom, but we discard them. (It's probably sorted by jSelection time reverse)

orders the audio file query response by selection id

---

app/exporters/hathi/content_package.rb
app/exporters/hathi/submission_information_package.rb
spec/exporters/hathi/content_package_spec.rb

Creates original and derivative subclasses for Page class.
Removes pagedata method, because we don't use Hathi's controlled vocabulary for the labels.

Refactors pageclass

---

RELEASE_NOTES.md
app/assets/javascripts/figgy_boot.es6
app/assets/stylesheets/components/form.scss
app/resources/numismatics/issues/numismatics/issue_decorator.rb
app/resources/numismatics/issues/numismatics/issue_wayfinder.rb
app/views/layouts/application.html.erb
app/views/records/edit_fields/_color.html.erb
app/views/records/edit_fields/_denomination.html.erb
app/views/records/edit_fields/_edge.html.erb
app/views/records/edit_fields/_metal.html.erb
app/views/records/edit_fields/_object_type.html.erb
app/views/records/edit_fields/_shape.html.erb
spec/features/numismatic_issue_spec.rb
spec/resources/numismatics/issues/numismatics/issue_wayfinder_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Resolves #3618 by addressing the following:
- Integrating the select2 widget as a combobox for the Numismatic::Issue form
- Ensuring that the select2 can be used to select the fields "Object type", "Denomination", "Metal", "Shape", "Color", and "Edge"

Introduces a combobox for Numismatic::Issue form fields

---

RELEASE_NOTES.md
app/assets/javascripts/figgy_boot.es6
app/assets/stylesheets/components/form.scss

Users can clear select box values by clicking the "x" on the right of the dropdown element.
Closes #3662

Allow Numismatic edit form select box values to be cleared

---

app/controllers/downloads_controller.rb
app/models/ability.rb
spec/controllers/downloads_controller_spec.rb
spec/models/ability_spec.rb

There's no point in checking for the FileSet, as the permissions for
streaming differ from the permissions for downloading the original file.
Instead, derivatives are allowed if the FileSet is readable (it's
complete and accessible by the user), and original files are downloadable if the
FileSet is configured to be so.
An exception is made for Geo Thumbnails/Metadata, which are set to
always be downloadable as per existing functionality.
Closes #3652

Refactor download permissions to act on the FileMetadata

---

.circleci/config.yml

This is necessary after the Docker Image for PostgreSQL was updated for CircleCI builds: https://hub.docker.com/layers/postgres/library/postgres/9.6-alpine/images/sha256-07e2b0c89d90a2656c012fd06b9f167ce78b02e5631aae0f06123354d4d119eb?context=explore

Setting a password explicitly for the postgres Docker image for CircleCI

---

RELEASE_NOTES.md
app/resources/numismatics/coins/numismatics/coin_decorator.rb
app/resources/numismatics/coins/orangelight_coin_builder.rb
spec/services/orangelight_document_spec.rb

- Updates title and format to "Coin" instead of "Numismatics::Coin"
- Updates "Rare Books and Special Collections" to "Special Collections"
Closes #3687

Update properties in Orangelight coin document builder

---

RELEASE_NOTES.md
app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/resources/numismatics/issues/numismatics/issue_decorator.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/resources/numismatics/issues/numismatics/issue_change_set_spec.rb

I wrote up a detailed ticket describing why this PR might be desirable, but it didn't save for some reason and I don't feel up to recreating it in full. Long story short, I think that we should set Numismatic Issue states to "complete" by default and not propagate state changes to Coin members.
- Issues are like containers that hold metadata but no files. Users will add coins as they are acquired and cataloged.
- Focusing on getting the numismatics lab users to use workflow functionality for Coin resources seems much more important.

Make complete the default state on numismatic Issues

---

RELEASE_NOTES.md
app/views/numismatics/accessions/edit_fields/_firm_id.html.erb
app/views/numismatics/accessions/edit_fields/_person_id.html.erb
app/views/numismatics/issues/edit_fields/_master_id.html.erb
app/views/numismatics/issues/edit_fields/_ruler_id.html.erb
app/views/records/edit_fields/_person_id.html.erb
spec/resources/numismatics/accessions/numismatics/accession_feature_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

- Adds firm and person ajax drop downs to numismatics accessions.
- Adds buttons for new numismatic ruler and master.
Closes #3619

Add additional numismatics drop-downs

---

RELEASE_NOTES.md
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/views/numismatics/issues/edit_fields/_numismatic_place_id.html.erb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

* Update on the 'Numismatic Issue' form the label 'Numismatic Place' to 'Minting Location'.
* Move the 'Numismatic Place' field under the 'Ruler' field.
closes #3707

Numismatic Issue form: update the label Numismatic Place to Minting Location & Move the Numismatic Place field under the Ruler field.

---

app/views/numismatics/coins/edit_fields/_numismatic_citation_fields.html.erb
app/views/records/edit_fields/_numismatic_citation_fields.html.erb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Add button for new numismatic reference to citation form

---

RELEASE_NOTES.md
app/indexers/title_indexer.rb
app/resources/numismatics/references/numismatics/reference_decorator.rb
spec/indexers/title_indexer_spec.rb

- Allows unique values (different from the actual resource title) to be indexed into Solr.
- Creates an indexed title for NumismaticReference that is displayed in the ajax drop down.
Closes #3714

Index a unique numismatic reference title into Solr

---

app/jobs/delete_archival_collection_job.rb
lib/tasks/bulk.rake
spec/jobs/delete_archival_collection_job_spec.rb

identifier is now passed into IngestFolderJob, so that images can be associated with already-created ScannedResources from EADs.

Uses ENV["OBJID"] to associate identifier with existing resource

---

Gemfile
Gemfile.lock

Fixes a bunch of deprecation warnings regarding ID comparisons.

Update Valkyrie to 2.1.1

---

.circleci/config.yml
.tool-versions
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/components/issue_monogram.vue
app/javascript/test/__snapshots__/orderManagerFilesetsForm.spec.js.snap
app/javascript/test/orderManagerFilesetForm.spec.js
app/javascript/test/orderManagerFilesetsForm.spec.js
package.json
yarn.lock

Resolves #3726 by addressing the following:
- Rebuilds JavaScript package dependencies for Node 12.x releases
- Updates the Jest tests for LUX (this was necessary for supporting later releases of Vue)
- Pins the LUX dependency to release 2.0.3 (beyond this there were CSS updates which will need to be overridden, and I thought it best to postpone this for a future PR)
- Updates the CircleCI configuration to test using Erbium

Updates the JavaScript package dependencies for deployment with NodeJS 12.x LTS releases (Erbium)

---

app/resources/scanned_resources/scanned_resource_change_set.rb
lib/tasks/bulk.rake
spec/jobs/ingest_mets_job_spec.rb

Required so that identifier can be passed in to IngestFolderJob

Adds identifier property to ScannedResourceChangeSet

---

app/services/manifest_builder.rb
spec/services/manifest_builder/cantaloupe_helper_spec.rb

If the Pyramidal was in the array first it was pulling that instead,
resulting in broken links when set up to use Cantaloupe.

CantaloupeHelper should use the JP2

---

app/javascript/components/OrderManagerFilesetForm.vue
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/test/orderManagerFilesetsForm.spec.js
app/javascript/test/setup.js

Not updating on every input makes the interaction a lot less miserable.

Add debounce to Order Manager.

---

app/javascript/components/OrderManager.vue

Deep is deprecated in Firefox, and block is not the default display
type.

Fix Order Manager Sidebar display in Firefox.

---

RELEASE_NOTES.md
app/derivative_services/default_derivative_service.rb
app/derivative_services/jp2_derivative_service.rb
app/derivative_services/scanned_map_derivative_service.rb
app/derivative_services/thumbnail_derivative_service.rb
app/derivative_services/vips_derivative_service.rb
architecture-decisions/0008-jpeg2000-ingest.md
spec/derivative_services/default_derivative_service_spec.rb
spec/derivative_services/jp2_derivative_service_spec.rb
spec/derivative_services/scanned_map_derivative_service_spec.rb
spec/derivative_services/vips_derivative_service_spec.rb

- Removes functionality for generating derivatives from JPEG2000 images.
- Adds ADR explaining decision.
- Leaves the VIPS thumbnail derivative service intact.

Remove JPEG2000 derivative generation functionality

---

app/services/bulk_cloud_ingester.rb
spec/controllers/bulk_ingest_controller_spec.rb

This also makes source metadata identifier work for the bulk cloud
ingester.

Add SourceMetadataIdentifier Tests

---

app/services/pul_metadata_services/pulfa_record.rb
spec/fixtures/files/pulfa/WC064_c1630.xml
spec/services/pul_metadata_services/pulfa_record_spec.rb

For the creator of any pulfa record, the previous version always returned the collection_creators (as expressed in the `pulfa:context` element added to the EAD at pulfa ingest). Gabrielle Swift (#3839) asked that the creator of individual components be drawn from the component's `ead:origination` element, if it exists.

Implements component_creators

---

RELEASE_NOTES.md
app/providers/browse_everything/provider/fast_file_system.rb
spec/providers/browse_everything/provider/fast_file_system_spec.rb

* Orders files alphabetically
* No longer displays hidden files.
This should fix an issue where files are ingested in random order.

File Manager Improvements

---

app/change_set_persisters/change_set_persister/cache_parent_id.rb
app/models/schema/common.rb
app/models/schema/geo.rb
app/resources/ephemera_boxes/ephemera_box.rb
app/resources/ephemera_folders/ephemera_folder.rb
app/resources/file_sets/file_set.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/services/migrations/add_cached_parent_ids_migrator.rb
spec/models/scanned_resource_spec.rb
spec/services/migrations/add_cached_parent_ids_migrator_spec.rb

1. Enables cached_parent_id to be a nil value.
2. Makes the migration only migrate those objects which haven't been
migrated yet.
3. Only migrates top-level members. Ignore some known models that don't
have cached parents, as well as FileSets. All FileSets have parents, and
if we end up needing it later we can handle it then.

Continuable Cached Parent ID Migration

---

app/resources/scanned_resources/scanned_resources_controller.rb
app/resources/scanned_resources/simple_change_set.rb
spec/features/simple_resource_spec.rb

This lets simple resources be edited, but only allows a very minimal
amount of metadata to be changed - basically just those fields that
Figgy uses for curation such as collection ID, append_id, title, etc.

Allow simple resources to be edited.

---

app/models/concerns/linked_data/linked_imported_resource.rb
spec/models/linked_data/linked_ephemera_folder_spec.rb
spec/models/linked_data/linked_imported_resource_spec.rb

This was only showing up for finding aid resources. The nested values were interpreted by dpul's solr index as an attempt to index a nested document, which causes an error.
fixes pomegranate#793

Remove nested member_of_collections from jsonld

---

app/models/oai/figgy/oai_wrapper.rb
spec/controllers/oai_controller_spec.rb

Add language to oai_dc; use ISO-639-2

---

README.md

Also moved simple tiles install into dependencies list for consistency
@jrgriffiniii would you mind reviewing, as we took out some python info you had put in a while back. We weren't sure how it was related to simple tiles, which is a c library.

Add troubleshooting simple tiles problems to README

---

app/resources/cdl/charge_manager.rb
app/resources/cdl/charged_item.rb
app/resources/cdl/resource_charge_list.rb
app/resources/cdl/resource_charge_list_change_set.rb
app/wayfinders/base_wayfinder.rb
spec/factories/cdl/resource_charge_list.rb
spec/resources/cdl/charge_manager_spec.rb
spec/resources/cdl/charged_item_spec.rb
spec/resources/cdl/resource_charge_list_spec.rb

The `CDL::ChargeManager` is a business logic object which creates and
manages `CDL::ResourceChargeList` and its `CDL::ChargeItem`s.
The implementation currently stubs the EligibleItemService, but after
#4033 it will pull from bibdata.
Closes #4026

Add CDL::ChargeManager

---

app/assets/javascripts/viewer.js
app/controllers/viewer_controller.rb
app/views/layouts/viewer_layout.html.erb
app/views/viewer/auth.html.erb
app/views/viewer/index.html.erb
config/routes.rb
spec/controllers/viewer_controller_spec.rb

This should make it easier for us to handle things like CDL auth flows without a bunch of complex javascript branching or stashing data in manifest bodies.
Closes #4043

Don't use JS to handle viewer auth flow.

---

app/resources/cdl/charge_manager.rb
app/resources/cdl/hold.rb
app/resources/cdl/resource_charge_list.rb
app/resources/cdl/resource_charge_list_change_set.rb
app/resources/cdl/status.rb
app/views/viewer/cdl_checkout.html.erb
spec/resources/cdl/charge_manager_spec.rb
spec/resources/cdl/hold_spec.rb

Closes #4088
* Adds a CDL::Hold to store a hold.
* Adds a `hold_queue` to `CDL::ResourceChargeList`
* Adds `netid:` to `available_for_charge` so it can take into account existing active holds.
* Takes the `hold_queue` into account for `available_for_charge?`
* Clear out `hold_queue` when charging an item.

Adds ResourceChargeList#hold_queue

---

app/resources/cdl/bulk_hold_processor.rb
config/schedule.rb
lib/tasks/cdl.rake
spec/resources/cdl/bulk_hold_processor_spec.rb

This runs a cron which activates all possible holds every 10 minutes, sending the appropriate emails.
There's a possible alternate implementation which would use scheduled jobs, but it'd be significantly more complex (although likely require less processing power than this solution.)
Closes #4123

Activate holds based on a cron job

---

app/resources/scanned_resources/scanned_resource_change_set.rb
spec/resources/scanned_resources/scanned_resource_change_set_spec.rb

Adds the MARCRelator fields to the ScannedResourceChangeSet so that it can validate metadata fields requested by clients.

Adds MARCRelator attributes to ScannedResourceChangeSet

---

app/derivative_services/pdf_derivative_service.rb

This also refactors things a bit to use a known page count and makes it so the `IngestableFile`s are `copyable: true`, so that it's `mv`'d instead of copied, which results in a bunch of file handles being held open.
I can confirm that this branch results in both example PDFs ingesting.

Run GC between pages to keep file handle usage low.

---

spec/services/pulfa_exporter_spec.rb

Test for all xpaths instead of just the first one. This makes the test easier to
read and understand, and also tests the behavior of the code more fully.

Make pulfa exporter behavior more explicit in spec

---

config/deploy.rb

fixes #4195
excerpts from dry-run before:
```
00:00 git:create_release
01 mkdir -p /opt/figgy/releases/20200818124448
02 git archive master | /usr/bin/env tar -x -f - -C /opt/figgy/releases/202008181244…
```
```
00:00 deploy:log_revision
01 echo "Branch master (at ) deployed as release 20200818124448 by hackmastera" >> /opt…
```
dry-run after:
```
00:00 git:create_release
01 mkdir -p /opt/figgy/releases/20200818124526
02 git archive main | /usr/bin/env tar -x -f - -C /opt/figgy/releases/20200818124526
```
```
00:00 deploy:log_revision
01 echo "Branch main (at ) deployed as release 20200818124526 by hackmastera" >> /opt/f…
```

Deploy 'main' when we asked to deploy 'master'

---

app/derivative_services/pdf_derivative_service.rb
config/initializers/valkyrie.rb

The lazy array makes it extract groups of 200 files at a time, then adds
them to the parent (in a transaction), which moves the files off the tmp
location. This should take care of the issue where we run out of space,
but if the extraction fails we may end up with orphan files in
production.
Closes #4215

PDF Derivative Service should extract/move files in batches.

---

RELEASE_NOTES.md
app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/viewer/cdl_timer.js

This prevents attempting to parse a timer that doesn't exist as well as
displaying the return button on error.
Closes #4214

Don't process CDL Timer code if status check fails.

---

.lando.yml
README.md
config/database.yml
config/initializers/valkyrie.rb
db/structure.sql

This keeps us locked to the Postgres version we're running in
production, and keeps all the developers on the same version for this
project as well, resulting in a consistent schema file on rake
db:migrate.
Closes #4212

Use Lando for Postgres.

---

app/indexers/facet_indexer.rb
spec/indexers/facet_indexer_spec.rb

The tests for this class actually hit the class twice, once when the
record is created (and the metadata is pulled), and then again when
`described_class.to_solr` is called. The first time dates come through
as Time objects. The second time they come through as strings. There was
a bug in the code giving a nil value when the date was a Time object,
which the tests didn't catch because they were only checking values via
`described_class`. Adding a test that looks at the index directly gave a
failing test from which to resolve the bug.

Test FacetIndexer from Solr directly

---

app/services/reindexer.rb
spec/services/reindexer_spec.rb

There's millions, most of them point to FileSets, and we don't really
use their Solr records.

Don't reindex PreservationObjects.

---

RELEASE_NOTES.md
app/services/bulk_edit_service.rb
lib/tasks/bulk.rake
spec/services/bulk_edit_service_spec.rb

addresses #2586, #2862, and #4185 
- Extends bulk_edit_service to enable all items of a collection to be added to another collection.
- Provides a rake task to support this extension.
The GUI form is not addressed in this PR.

2586 bulk edit

---

app/resources/cdl/automatic_ingester.rb
config/schedule.rb
spec/resources/cdl/automatic_ingester_spec.rb

This will ingest any CDL file that hasn't been modified in the last
hour. Should decrease maximum time between copy and ingest to two hours.
An unfortunate side effect of this is they'll get emails a lot more often, probably, and throughout the day.

Run CDL a lot more often.

---

app/views/fixity_dashboard/_cloud_fixity_table.html.erb
spec/features/fixity_dashboard_spec.rb

Makes fixity dashboard display again.
Closes #3814

Fix display of fixity checks from deleted resources.

---

config/deploy.rb

Prevents the export:pulfa job from running in staging.
This is how Whenever's built in task works: https://github.com/javan/whenever/blob/master/lib/whenever/capistrano/v3/tasks/whenever.rake#L27-L28
I tried to use the built in task and couldn't get it to use the release_path correctly for some reason, so adjusting our custom task seemed easiest.
Closes #3462

Pass host roles to Whenever.

---

config/schedule.rb

The task is broken (see https://github.com/pulibrary/figgy/issues/4149), when it's fixed this will be too slow to run every night, we're about to switch to ASpace, and refreshing everything is breaking Figgy at night.

Disable Finding Aids Refresh

---

app/decorators/valkyrie/resource_decorator.rb
spec/services/manifest_builder_spec.rb

Location was removed from the IIIF manifest metadata hash in a broader cleanup guided by feedback from the Cicognara project (#2358). But there was no substantive discussion of that field in particular, and that project no longer uses the metadata hash for its displays.
The Grounds and Buildings collection has item-level location information for thousands of photographs, and displaying this field will allow researchers to request viewing the original photographs.

Restoring location to the IIIF manifest metadata hash

---

app/services/ingest_folder_locator.rb

Find.find passed to an Enumerator#find finds a directory in staging in
about 4 seconds, where the previous method took 23 seconds.

Speed up IngestFolderLocator

---

app/models/ability.rb
app/resources/ephemera_folders/ephemera_folder_decorator.rb
spec/models/ability_spec.rb

This also fixes up `ability.rb` so it uses the correct
`.create_for_repository`.
Closes #1367
Closes #4379

Staff can delete their own FileSets.

---

config/schedule.rb

We're migrating to ASpace, so modifying those SVN files is a bad idea.

Disable DAO synchronization.

---

app/services/manifest_builder.rb
app/services/manifest_builder/collection_manifest_service_locator.rb
spec/resources/collections/collections_controller_spec.rb
spec/services/manifest_builder/thumbnail_builder_spec.rb

We need MVWs to have them for sync to DPUL, but we don't need it for
collection manifests and it adds a ton of extra queries.
Work towards #1656

Don't build child thumbnails for collection manifests.

---

lib/tasks/bulk.rake

Useful when debugging bulk ingests.  Code was copied from demo.rake and modified.

Adds rake task to delete all members of a collection

---

.rubocop.yml
RELEASE_NOTES.md
app/controllers/reports_controller.rb
spec/controllers/reports_controller_spec.rb

* Adds support for all of the metadata fields in the ephemera forms
* Include boxless folders in the reports
Fixes #4431

Expand fields included in ephemera metadata export

---

app/resources/cdl/eligible_item_service.rb
spec/fixtures/files/bibdata/9965126093506421.json
spec/fixtures/files/bibdata/9968643943506421.json
spec/resources/cdl/eligible_item_service_spec.rb

I'm not sure why the item id was previous an int, or whether it will be a
problem for it to be a string here.
fixes pulibrary/bibdata#903

Look for the cdl field that bibdata-on-alma will return

---

app/models/oai/figgy/valkyrie_provider_model.rb
app/queries/paged_all_query.rb
spec/models/oai/figgy/valkyrie_provider_model_spec.rb

Fixes #4463 
This would suppress items from the OAI endpoint based on rights statement. For now, the list of rights statements to suppress is just the No Copyright/Contractual Restrictions which seems like a reasonably good fit for this scenario.

Filtering resources included in OAI endpoint based on rights statement

---

README.md

When I run the tests, about 30 feature tests fail because it can't find Chrome. Installing Chrome fixes this.

Adding explicit Chrome dependency

---

app/services/ingest_ephemera_mods.rb
spec/fixtures/files/GNIB/00223.mods

Fixes glitch where ocr_language was being set to "eng " or "spa " because there were trailing spaces in the source data.

strips leading/trailing spaces from mods:language elements

---

config/initializers/honeybadger.rb

See
https://docs.honeybadger.io/lib/ruby/support/v4-upgrade.html#removal-of-the-notice-accessor.
This might close #4539, and may be an issue for #4531

Update Honeybadger syntax for v4

---

app/models/ability.rb
app/wayfinders/base_wayfinder.rb
spec/models/ability_spec.rb

This fixes OARSC downloading of audio files. Audio resources are parent
resources that are a member of the collection with a child per
resource. Without this it wasn't finding that the child resource was a
member of a collection.
Closes #4562

Check restricted collection membership of parents if there is one.

---

app/services/dao_updater.rb
spec/services/dao_updater_spec.rb

Protects us from adding DAOs from private items when bulk updating DAOs
Closes #4568

Ensure we don't update DAOs for non-readable items.

---

app/controllers/viewer_controller.rb
app/models/ability.rb
app/resources/cdl/charge_manager.rb
spec/controllers/viewer_controller_spec.rb

Improves performance now that checking items in bibdata is so much
slower.
Closes #4596

Viewer#auth should not check eligibility twice.

---

app/services/bibid_updater.rb

Reduces the diff time between read/persist.
Closes #4597

Reload resource for Alma migration of resources.

---

app/models/resource.rb
lib/tasks/performance.rake
spec/jobs/update_fgdc_onlink_job_spec.rb
spec/services/add_ephemera_to_collection_spec.rb

Adds a rake task to benchmark/profile reindexing and adds a few easy fixes.
The next fix is to have the solr persister not convert from the solr document to a `Valkyrie::Resource`, which is much harder.

Reindexing Performance Optimizations

---

app/adapters/indexing_adapter.rb
app/services/reindexer.rb
spec/adapters/indexing_adapter_spec.rb

This doesn't actually improve reindexing speed or anything, but
preventing these from indexing makes our unit tests able to tell us if
we need to index PreservationObjects and Tombstones, and makes it so we don't accidentally end up with these in the index.
Closes #4601

Prevent indexing certain models

---

app/indexers/facet_indexer.rb
app/indexers/imported_metadata_indexer.rb
app/resources/scanned_resources/scanned_resource.rb
app/resources/scanned_resources/scanned_resource_decorator.rb
lib/tasks/performance.rake
spec/indexers/imported_metadata_indexer_spec.rb

Accessing this pre-built hash is about 5x faster than calling to_h (resulting in being able to convert 120 ScannedResource records/second vs 30 records/second).
Also, avoiding `primary_imported_metadata` repeatedly creating an `ImportedMetadata` object results in being able to convert 180 ScannedResource records/second.

Dramatically improve speed of indexing records with imported metadata.

---

app/utils/data_seeder.rb
lib/tasks/report.rake

advances #4639
- Update the data seeder to use the lae_subjects from production
- Add a task to report lae subjects to CSV
It would be better to put this in a service and test it, but since this is
urgently needed and doesn't update any data I thought I would inquire whether we
might just go ahead and merge it this way.

Add rake task to report LAE subjects to CSV

---

cloud_fixity/package.json
cloud_fixity/yarn.lock

Upgrades jest/core from `24.7.1` to `24.9.0`. This will hopefully keep things backward-compatible, but also get us some critical security patches.

Upgrade jest to fix longstanding security issue

---

config/boot.rb

as specified in the bootsnap README:
https://github.com/Shopify/bootsnap#usage
closes #4211

Require bootsnap/setup after bundler/setup

---

app/resources/numismatics/issues/numismatics/issue_change_set.rb
spec/resources/numismatics/issues/numismatics/issue_change_set_spec.rb

Closes #4668
The user request was to be able to leave the latest date blank, but this is much easier to implement, is something they automatically tried, and is less likely to negatively impact upstream indexers. I've told Alan about this compromise.

Issues should be valid if earliest/latest date are the same number.

---

app/services/geo_resource_reindexer.rb

Fixes bug where many copies of the first resource updated message is sent when reindexing Pulmap.

Remove memoization of GeoResourceIndexer event generator

---

config/deploy.rb

- Fixes issues that occurred as a result of namespacing rake tasks.
- Blocks deployment.

Properly namespace rake tasks in cap deploy

---

app/views/catalog/_member_resources_raster_resource.html.erb
app/views/catalog/_member_resources_scanned_map.html.erb
app/views/catalog/_member_resources_vector_resource.html.erb
app/views/catalog/_parent_resources_raster_resource.html.erb
app/views/catalog/_parent_resources_scanned_map.html.erb
app/views/catalog/_parent_resources_vector_resource.html.erb

Move geo member and parent labels into placeholder text to fix attach button alignment while preserving clarity.
Closes #4756

Move geo member and parent labels into placeholder text

---

.rubocop.yml
app/resources/numismatics/accessions/numismatics/accession.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/coins/numismatics/coin_change_set.rb
app/resources/numismatics/coins/numismatics/coin_decorator.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/services/migrations/cast_numismatics_integers_migrator.rb
app/types/types.rb
spec/controllers/catalog_controller_spec.rb
spec/resources/numismatics/accessions/numismatics/accession_spec.rb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb
spec/resources/numismatics/coins/numismatics/coin_spec.rb
spec/resources/numismatics/issues/numismatics/issue_spec.rb
spec/services/migrations/cast_numismatics_integers_migrator_spec.rb

Make them optional because in at least one case there was a nil value
that raised an error.
refs #4728

Coerce numismatics numbers to integers

---

app/derivative_services/raster_resource_derivative_service.rb
app/services/geoserver_message_generator.rb
config/config.yml
config/initializers/valkyrie.rb
spec/resources/raster_resources/raster_resource_derivative_service_spec.rb

This doesn't make it so you can hit "Download" in the list of files, but it does upload a second copy of the display_raster.tif to S3 in staging.
Closes #4769

Store Raster Derivatives in the Cloud

---

app/resources/scanned_resources/simple_change_set.rb

Previous PR added :series property to ScannedResource; this one adds it to SimpleResource as well (to cover the pudl0036 case)

adds :series property to SimpleResource

---

app/characterization_services/null_characterization_service.rb
spec/characterization_services/null_characterization_service_spec.rb

- Use real objects instead of mocks in null_characterization_service_spec
- Use primary_file in NullCharacterizationService
refs #4846 
note to reviewer: it may be helpful to look at the commits separately. The first refactors the specs and the second adds the new test / updates the code.

Use primary_file in NullCharacterizationService

---

app/controllers/application_controller.rb
app/controllers/catalog_controller.rb

So they don't proliferate.
Still get the message twice because the flash holds its message for one
request cycle. But we should not see the cookie overload anymore.
advances #4799

Move read only flash messages to catalog controller

---

public/uv/lib/AVComponent.js

Closes #4914 
Confirmed in staging this works. This will require a hard refresh from users to get this file out of their cache, unfortunately.

Prevent checking for range if a range hasn't started yet.

---

spec/values/tile_path_spec.rb

Closes #4968
Mosaics should only be displayed at the "Set" level. A scanned map with a raster child is not a "Set".

Update tile path service spec

---

app/resources/numismatics/issues/numismatics/issue_decorator.rb
spec/services/orangelight_document_spec.rb

When indexing coins via bibdata, we noticed that the reverse_description decorator refers to some obverse fields, when it should refer to their reverse field counterparts.

remove obverse fields from reverse_description decorator

---

app/services/json_ingester.rb
lib/tasks/import.rake
spec/fixtures/json_ingest.json
spec/services/json_ingester_spec.rb

Adds a task called **json** to _import.rake_; ingests resources from the Isilon server with metadata formatted as JSON.  This should be a general-purpose ingest task, but it has been created specifically for #5023

Json ingest task

---

config/locales/en.yml

This also removes the pdf_boilerplate key, which is not used.
Closes #5032

Update boilerplate statement.

---

app/services/geo_discovery/document_builder/wxs.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb

Closes #5043 
- Occasionally, blank strings are saved in geo resource `layer_name`,` wms_url`, and `wfs_url` properties which causes an issue with GeoBlacklight document references. Use a better test for blank values.

Fix generation of WMS and WFS references for geo resources

---

app/models/resource.rb
app/resources/ephemera_folders/ephemera_folder.rb
spec/characterization_services/imagemagick_characterization_service_spec.rb

This fixes #5049 but I'm not sure if it violates another existing use case.

An ephemera folder is an image resource

---

app/services/dao_updater.rb

It helps to know that it's an archival object not found when you look at the notice so you know what to say to the PO.
follow-up to #4981

Add more info to honeybadger notice

---

app/jobs/bulk_update_job.rb
spec/jobs/bulk_update_job_spec.rb

Raising means the job re-runs and sends another email.
closes #5116

Don't raise after a bulk update notification.

---

.rubocop.yml
config/initializers/simple_form_bootstrap.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/features/ephemera_box_spec.rb

This removes the is-valid classes because it was making select boxes
green on a new form.
Closes #5189
Closes #5184
Closes #5179

Use Bootstrap 4 configuration for Simple Form.

---

app/views/numismatics/accessions/_form.html.erb

Fixes AJAX select widgets on accessions edit form.
Adding `class=lux` for each div does not work - and I'm not sure why. The select widget is duplicated multiple times. The solution fI came up with for accessions is to add the `lux` class once by overriding the form partial.

Enable ajax selct on accessions edit form

---

app/views/base/_file_manager_thumbnail.html.erb

Use #document_presenter instead of #presenter.
Closes #5249

Fix document_presenter deprecation

---

.circleci/Dockerfile
.circleci/config.yml
README.md

Speed up CI build and run times by using custom Figgy docker image.

Use custom base docker image

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/inputs.scss
app/helpers/edit_field_helper.rb
app/inputs/multi_value_input.rb
app/javascript/figgy/field_manager.js
app/javascript/figgy/figgy_boot.js
app/views/layouts/blacklight/base.html.erb
app/views/records/edit_fields/_default.html.erb
spec/features/simple_resource_spec.rb

Remove Hydra Editor

---

config/deploy.rb

Closes #5284 
Mapnik is needed by workers and is installed via yarn/npm.

Run yarn install on production workers

---

app/javascript/helpers/setup_ajax_select.js
app/javascript/packs/application.js
app/views/base/_local_upload.html.erb
app/views/base/order_manager.html.erb
app/views/catalog/_members_playlist.html.erb
app/views/layouts/application.html.erb
app/views/layouts/blacklight/base.html.erb
app/views/numismatics/accessions/_form.html.erb
app/views/numismatics/accessions/edit_fields/_firm_id.html.erb
app/views/numismatics/accessions/edit_fields/_person_id.html.erb
app/views/numismatics/coins/_loan_fields.html.erb
app/views/numismatics/coins/_provenance_fields.html.erb
app/views/numismatics/coins/edit_fields/_append_id.html.erb
app/views/numismatics/coins/edit_fields/_find_place_id.html.erb
app/views/numismatics/coins/edit_fields/_numismatic_citation_fields.html.erb
app/views/numismatics/issues/_numismatic_artist_fields.html.erb
app/views/numismatics/issues/edit_fields/_master_id.html.erb
app/views/numismatics/issues/edit_fields/_numismatic_place_id.html.erb
app/views/numismatics/issues/edit_fields/_ruler_id.html.erb
app/views/records/edit_fields/_numismatic_accession_id.html.erb
app/views/records/edit_fields/_numismatic_citation_fields.html.erb
app/views/records/edit_fields/_numismatic_monogram_ids.html.erb
app/views/shared/_footer.html.erb

Removes all the lux tags, changes where we initialize the JS, and uses a single lux tag for the application.
The key here seems to be that you need to run non-vue JS -after- the vue is mounted, or it doesn't work. When I swapped everything to webpacker I made vue happen at the end on accident, which is what broke everything and necessitated controlled lux tags.
Previously we had two lux tags, one for the header and one for the body. It turned out that the numismatics code depended on that - the first lux tag would initialize vue, and add vue tags to the page in the HTML, and then the second would initialize vue and actually mount those components. To have one lux tag we have to add vue tags in beforeCreate instead so the mounting process will catch them, and then bind the cocoon helpers …

Fix Numismatics Forms

---

Gemfile
config/application.rb
config/initializers/valkyrie.rb

Initializers shouldn't call "require" and we have to avoid the mini
profiler patch problem causing an infinite loop.

Fix launching rails server.

---

app/decorators/ephemera_term_decorator.rb
spec/decorators/ephemera_term_decorator_spec.rb

This is okay because we strip spaces, which CGI.escape apparently
doesn't escape to spec.
closes #5272

Use CGI.escape instead of URI.escape

---

app/assets/stylesheets/components/show.scss
app/views/catalog/_auth_link_default.html.erb
app/views/catalog/_workflow_controls_default.html.erb

Also uses h2 for review and approval card title, improves card title
spacing
refs #5312
before:
after:

Use card instead of panel for authorized link content area

---

config/application.rb
config/environments/test.rb

Fixes CDL.
I'm finding these settings that changed during the upgrade by looking at https://api.rubyonrails.org/v6.1.6.1/classes/Rails/Application/Configuration.html#method-i-load_defaults and seeing what the new `load_defaults` line did.
Closes #5336

Configure same site protection to allow iFrames

---

app/graphql/mutations/update_resource.rb
app/queries/find_persisted_member_ids.rb
config/initializers/valkyrie.rb
spec/graphql/mutations/update_resource_spec.rb

Closes https://github.com/pulibrary/figgy/issues/5363
Things we did:
1. We wrote a test to make sure a non-existent member ID in a resource
doesn't cause an error in graphql.
2. We wrote a query that prevents that from happening by using the same
kind of join query the order manager uses, which will not return deleted
member_ids.
3. We used that query instead of using #member_ids on the resource.
Co-authored-by: Shaun Ellis <shaun@sdellis.com>
Co-authored-by: Eliot Jordan <eliot.jordan@gmail.com>

Make order manager handle resources w/ deleted members.

---

app/models/ingestable_file.rb
spec/models/ingestable_file_spec.rb

This conforms to the expected interface for `Valkyrie::StorageAdapter#upload`, and
fixes an issue with uploading to AWS for vector resources.
Closes #5377

Delegate IO methods to an opened file instance in IngestableFile

---

app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/layer_info_builder.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/services/geo_discovery/document_builder/layer_info_builder_spec.rb
spec/services/geo_discovery/document_builder_spec.rb

refs pulibrary/pulmap#1028
see also pulibrary/pulmap#1075 -- since that copies from the old single-value field to the new one we will also want to remove the old field as part of this PR.

Add a multi-value geom types field to gbl document

---

app/services/geoserver_publish_service.rb
spec/services/geoserver_publish_service_spec.rb

Fixes issue with publishing a raster derivative to GeoServer.
Closes #5416

Restore GeoServer raster publishing

---

app/change_sets/scanned_resource_change_set.rb
spec/change_sets/scanned_resource_change_set_spec.rb
spec/features/structure_manager_spec.rb

The new setter filters out structure nodes that try to proxy resources
that don't exist
closes #5407

Add a logical_order setter to scanned resource change set

---

app/decorators/scanned_resource_decorator.rb
app/models/schema/common.rb
app/models/schema/geo.rb
spec/models/linked_data/linked_imported_resource_spec.rb

We don't want these to display, and we don't want to add an exception to
every decorator.
Closes pulibrary/dpul#1395

Remove cached_parent_id from the common schema attribute list. 

---

app/models/ability.rb
spec/models/ability_spec.rb

Discover now means "someone could get the digital content for this potentially." For Reading Room material they could always participate in the OARSC program, so always mark reading room resources as discoverable. This will make the OARSC "yellow box" appear in Pulfalight.
Closes pulibrary/pulfalight#1096

Always return "unauthorized" for Reading Room resources.

---

docs/technical/aspace_identifiers.md

These are some things I think are true.
I realize this is cross-system documentation and may sit better in another location. I put it here because I think I would have looked here. Open to other locations! e.g. Should it go in https://github.com/pulibrary/pul-it-handbook/tree/main/services?

Document some things we know about archival ids

---

app/controllers/application_controller.rb
app/controllers/resources_controller.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb

Treat Blacklight::Exceptions::NotFoundError the same as
Valkyrie::Persistence::ObjectNotFoundError
closes #5442
I'm not really sure about this. The other option would be to accept the current behavior and ignore the error in honeybadger. The error does show up like a regular 404 to the browser. Which is a default rails page :(

Consistency in NotFoundErrors

---

Gemfile.lock

We are behind on Tika versions now.
Closes #5453

Use upstream ruby_tika_app gem and update

---

app/graphql/types/resource.rb
app/graphql/types/scanned_resource_type.rb
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
config/application.rb
config/environments/production.rb
spec/features/scanned_resource_spec.rb

This refactor will make it easier to create a click through populated from the graphql response.
Also it's less weird, and more consistent with the strategy we put in place for Pulfalight.

Refactor UV Manager to use GraphQL instead of Manifest HTTP Codes

---

app/graphql/types/resource.rb
app/graphql/types/scanned_resource_type.rb
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
config/application.rb
config/environments/production.rb
spec/features/scanned_resource_spec.rb

Reverts #5471 and #5472 due to #5474
- Revert "todo is done"
- Revert "Remove unneeded code, add comment to leaflet viewer."
- Revert "Clear all mocks before each test."
- Revert "Add js unit test for playlist title"
- Revert "Add a viewer integration test"
- Revert "Use processTitle for playlists."
- Revert "Update GraphQL to use the resource query."
- Revert "WIP refactor UV manager javascript"

Revert UV manager refactor

---

app/derivative_services/raster_resource_derivative_service.rb
app/services/migrations/remove_extra_derivatives.rb
lib/tasks/migrate.rake
spec/factories/file_metadata.rb
spec/models/raster_resource_derivative_service_spec.rb
spec/services/migrations/remove_extra_derivatives_spec.rb

Add migration to regenerate derivatives on filesets with too many

---

.tool-versions
app/services/mosaic_generator.rb
app/services/tile_metadata_service.rb
spec/services/tile_metadata_service_spec.rb

- Use temp file to pass raster paths to cogeo-mosaic
- Bump asdf java version up a minor version to allow M1 and non-M1 machines
Closes #5079

Use temp file to pass raster paths to cogeo-mosaic

---

architecture-decisions/0007-pyramidal-tiffs.md
config/config.yml
spec/services/manifest_builder_spec.rb
spec/services/manifest_builder_v3_spec.rb

Works towards #4837
(Not done yet, need to remove references in princeton_ansible as well)

Remove references to Cantaloupe

---

app/graphql/types/resource.rb
app/models/controlled_vocabulary.rb
config/authorities/notices.yml
config/locales/en.yml
spec/graphql/figgy_schema_spec.rb
spec/models/controlled_vocabulary_spec.rb

Closes #5492 
This includes a bunch of refactors @hackartisan and I had discussed before. Doing them made it easier to add a vocab that's not in ControlledVocabulary.all, but which has config for the visual display colocated with the ones which are.
There's also some refactors which utilizes polymorphism.

Add specific content warnings when they're available.

---

spec/features/bulk_edit_spec.rb
spec/models/linked_data/linked_ephemera_folder_spec.rb

Attempts to address a couple failing tests I'm seeing on my local dev instance:
1. BulkEditSpec - consistent error
- Need to wait for the page to redirect
- Most likely fixed.
2. linked_ephemera_folder_spec - almost impossible to consistently reproduce
- Simplifies the intermittently failing test
- Not sure it works, but it doesn't seem to hurt and will make further work easier
Work towards https://github.com/pulibrary/figgy/issues/5081

Attempt to address some flaky tests

---

app/change_set_persisters/change_set_persister/preserve_resource.rb
app/jobs/preserve_children_job.rb
app/jobs/preserve_resource_job.rb
spec/jobs/preserve_resource_job_spec.rb

Refs #3592 
- In PreserverResourceJob, adds logic to compare lock tokens passed as a param with current lock token values and exit early if they don't match.
- Works for FileSets and ResourceChangeLists. Will be enabled for all resources when this PR is merged: https://github.com/pulibrary/figgy/pull/5585

Add optimistic lock token checking to PreserveResourceJob

---

app/services/preserver/importer.rb
spec/services/preserver/importer_spec.rb

- Enable Preserver::Importer to set correct PCDM use on recovered files
- Refactor Preserver::Importer
Closes #5546

Enable Preserver::Importer to set correct PCDM use on recovered files

---

.circleci/config.yml
app/characterization_services/imagemagick_characterization_service.rb
app/characterization_services/mediainfo_characterization_service.rb
app/derivative_services/audio_derivative_service.rb
app/derivative_services/pdf_derivative_service.rb
app/models/ingestable_audio_file.rb
app/nested_resources/file_metadata.rb
app/views/catalog/_members_file_set.html.erb
spec/change_set_persisters/change_set_persister_spec.rb
spec/characterization_services/mediainfo_characterization_service_spec.rb
spec/characterization_services/null_characterization_service_spec.rb
spec/controllers/scanned_maps_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/derivative_services/pdf_derivative_service_spec.rb
spec/factories/file_set.rb
spec/jobs/ingest_archival_media_bag_job_spec.rb
spec/jobs/ingest_intermediate_file_job_spec.rb
spec/jobs/regenerate_derivatives_job_spec.rb
spec/models/file_set_spec.rb
spec/models/ingestable_audio_file_spec.rb
spec/nested_resources/file_metadata_spec.rb
spec/services/bulk_ingest_intermediate_service_spec.rb

- Allow either preservation use value (until we complete a migration)
- Use new PreservationFile over deprecated term.
- Use "global" instead of "master"
advances #5542

Use new PreservationFile use value

---

.circleci/config.yml

Works pretty reliably to use the date; might as well leave this in to establish the pattern.

Invalidate bundler cache to test new env var

---

spec/features/bulk_edit_spec.rb

The path check doesn't wait, so sometimes the tests would fail on a timing issue.
Closes #5571

Update spec to check for content before path.

---

app/services/migrations/event_current_migrator.rb
spec/services/migrations/event_current_migrator_spec.rb

Fixes issue with previous migration where `current: true` should have been `current:  [true]`

Add migration to fix current values migration

---

app/jobs/cloud_fixity_job.rb
spec/jobs/cloud_fixity_job_spec.rb

Exit CloudFixityJob silently when resource is not found

---

app/javascript/figgy/form/detect_duplicates.js
app/views/records/edit_fields/_barcode.html.erb

The query was only running the second half of the check, so would always say it was taken on the edit screen. I could only replicate by running it in proper selenium with some binding.prys.
Closes #5591

Fix duplicate detection query.

---

app/views/bulk_edit/resources_edit.html.erb
app/views/records/edit_fields/_downloadable.html.erb
app/views/records/edit_fields/_field_name.html.erb
app/views/records/edit_fields/_holding_location.html.erb
app/views/records/edit_fields/_notice_type.html.erb
app/views/records/edit_fields/_ocr_language.html.erb
app/views/records/edit_fields/_pdf_type.html.erb
app/views/records/edit_fields/_preservation_policy.html.erb
app/views/records/edit_fields/_service_targets.html.erb

Note to reviewer: We didn't see this class used anywhere else, and it was interfering with our local javascript. Is there somewhere we should check that we may have overlooked? A double-check would be appreciated.
It's used in the javascript that activates the rights statement note,
but it was present in a bunch of fields on the edit form. No evidence of
further use in other javascript or in styling. We also checked upstream.
fixes #5188

Remove rights-statement class from all over the place

---

Gemfile
Gemfile.lock
app/jobs/preserve_children_job.rb
app/queries/find_never_preserved_child_ids.rb
app/services/preserver.rb
config/initializers/valkyrie.rb
spec/queries/find_never_preserved_child_ids_spec.rb
spec/services/preserver_spec.rb

When preserving this now checks for children which don't have PreservationObjects and queues them up, rather than relying on it being the first time the parent was preserved.
This should fix any race conditions where that first attempt is missed, and will allow resources to preserve children on subsequent saves.
Closes #3463

Actively preserve un-preserved children.

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/append_to_parent.rb
spec/change_set_persisters/change_set_persister/append_to_parent_spec.rb
spec/change_set_persisters/change_set_persister_spec.rb

I wanted to add this logic into the existing `AppendToParent` class, but that's used as a post save hook and this needed to be pre-save. I'm not in love with the way this mirrors the logic in that class, and how the two may need to be changed together. Open to other ideas / approaches.
closes #5678

Remove resource from all collections when it's made a child

---

app/jobs/local_fixity_job.rb
spec/jobs/local_fixity_job_spec.rb

Update fixity job to add `current: true` to new events and set `current: false` for old events.
Closes #5686

Set current property on local fixity events

---

app/controllers/reports_controller.rb
app/values/csv_report.rb

Closes #5687 
Moved the `to_csv` and `hashes_to_csv` methods from the ReportsController to the CSVReport class (the CSVReport class didn't previously have a method that returns a CSV string directly), in order to put code converting objects to CSVs in the same place. The ReportsController now makes calls to the CSVReport class.

Refactor reports controller to use new CSVReport class

---

app/controllers/application_controller.rb
spec/requests/catalog_spec.rb

When an HTTP ACCEPT header is sent which is a wildcard, Rails picks the first response in a `respond_to` block. Blacklight runs first, which has HTML first, and then it'd hit our catch block and do JSON first, which would then error because Rails tries to respond with both HTML and JSON.
I couldn't get the spec to replicate this behavior (something's up with the testing harness), but I was able to
make sure that this method does the HTML behavior when given a wildcard header.
Closes #5350

Fix EZID type mismatch error.

---

spec/characterization_services/geo_characterization_service_spec.rb
spec/characterization_services/imagemagick_characterization_service_spec.rb
spec/characterization_services/mediainfo_characterization_service_spec.rb
spec/characterization_services/pdf_characterization_service_spec.rb
spec/characterization_services/tika_file_characterization_service_spec.rb
spec/controllers/deletion_markers_controller_spec.rb
spec/controllers/ephemera_boxes_controller_spec.rb
spec/controllers/ephemera_fields_controller_spec.rb
spec/controllers/ephemera_folders_controller_spec.rb
spec/controllers/ephemera_projects_controller_spec.rb
spec/controllers/ephemera_terms_controller_spec.rb
spec/controllers/ephemera_vocabularies_controller_spec.rb
spec/controllers/file_sets_controller_spec.rb
spec/controllers/playlists_controller_spec.rb
spec/controllers/raster_resources_controller_spec.rb
spec/controllers/scanned_maps_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/controllers/vector_resources_controller_spec.rb
spec/jobs/local_fixity_job_spec.rb
spec/rails_helper.rb
spec/support/fixture_file_with_use.rb

~~Controller tests don't like decorated `Rack::Test::UploadedFile` objects.~~
Updated to rename the spec support method causing the exception so we're not overriding.

Fix ocr upload_file test

---

Gemfile
Gemfile.lock

Closes #5746 , but we're not sure what it is about the retry logic they added in google-cloud-storage that broke this.

Downgrade Google Cloud Storage

---

.rubocop.yml
app/controllers/bulk_ingest_controller.rb
app/models/book_workflow.rb
app/models/draft_complete_workflow.rb
app/models/geo_workflow.rb
app/services/auto_completer.rb
architecture-decisions/0010-resource-autocomplete.md
config/locales/en.yml
config/schedule.rb
lib/tasks/auto_complete.rake
spec/controllers/bulk_ingest_controller_spec.rb
spec/models/book_workflow_spec.rb
spec/models/draft_complete_workflow_spec.rb
spec/models/workflow_registry_spec.rb
spec/services/auto_completer_spec.rb

This adds the "complete_when_processed" state which can't be advanced to, but can be selected in bulk ingest.
It also adds an auto-completer - every 30 minutes every resource which is marked `complete_when_processed` will be marked complete if it has members and all of its members, deep, are processed.
One downside of the auto-completer is that for bulk-ingested MVWs it marks all the volumes as "complete_when_processed", but when the MVW is marked complete it marks it for the children - so we get stale object errors for the volumes: https://app.honeybadger.io/projects/53391/faults/95377090. Maybe that's okay? Maybe we want to ignore stale object error exceptions and not notify?
Closes #5579, closes #5566

Add Complete When Processed to Bulk Ingest

---

app/graphql/types/resource.rb
spec/graphql/figgy_schema_spec.rb
spec/graphql/types/resource_spec.rb

This is much faster than getting members and then their ID.
Work in support of https://github.com/pulibrary/orangelight/pull/3527

Allow access to member_ids for resources in GraphQL.

---

app/services/preserver/importer.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/services/preserver/importer_spec.rb

Closes #5792 
Tested in staging. Can restore multiple times and the original filename is correct.

Restore original filename

---

Gemfile.lock
app/services/geoserver_publish_service.rb
spec/services/geoserver_publish_service_spec.rb

Closes #5808 
- Send keyword params as required in Ruby 3.
- Update geoserver-pusblish gem to fix issue with newer version of Faraday.

Send params to GeoServer::Publish as keywords

---

app/wayfinders/ephemera_project_wayfinder.rb
spec/views/catalog/_members_ephemera_project.html.erb_spec.rb

Both Templates and Deletion Markers use a property called parent_id as a foreign key. Templates weren't limited to Template models, so this was causing a conflict.
Closes #5772

Add model filter to templates wayfinder method.

---

app/controllers/collections_controller.rb
spec/controllers/collections_controller_spec.rb

Turns out we were just sending it to a bad path.
Closes #5797

Use catalog path for redirect after failing to delete collection

---

app/change_sets/recording_change_set.rb
spec/change_sets/recording_change_set_spec.rb

Closes #5787 
The ticket also calls for EphemeraFolders/EphemeraBoxes to only record when complete, but a couple things make me think we should leave it as is:
For EphemeraBox, there's a note that Boxes only have metadata so we may as well always preserve. That seems reasonable to me, and a decision we made in 2019: https://github.com/pulibrary/figgy/commit/b7ce523fcd259908b01cf5a8b6008ea64e246e86#diff-538bcb5518f90600d4fab5442eea649edbb2d6482067af948ec55c5c6abba714R49-R52
For EphemeraFolders, Draft is a "Public Readable State" because metadata is published the moment it's created. I think if we're displaying it to users we should preserve it.

Preserve Recordings only when complete

---

app/queries/deep_cloud_fixity_count.rb
app/queries/deep_local_fixity_count.rb
app/values/health_report/cloud_fixity_check.rb
app/values/health_report/local_fixity_check.rb
app/views/catalog/_health_status.html.erb
config/locales/en.yml
spec/features/file_set_spec.rb
spec/values/health_report_spec.rb
spec/wayfinders/wayfinder_spec.rb

Closes #5807 
This adds the file set health report back and makes sure the health report checks metadata events for nested members as well as itself.

Check self for cloud/local fixity tests

---

app/queries/find_deep_preservation_object_count.rb
app/wayfinders/base_wayfinder.rb
config/initializers/valkyrie.rb
spec/wayfinders/wayfinder_spec.rb

And prevent regression by adding a test
closes #5864

Restore assumption that a cloud preservation is a successful fixity check

---

app/services/pdf_service.rb
spec/requests/scanned_resource_spec.rb

due to an optimistic lock error
closes #5680

Serve generated PDF even if it couldn't save

---

app/javascript/viewer/uv_manager.js

The problem was a race condition where it could not evaluate the presence of the tabs reliably before resize. This fix puts the resize at the end of the `addViewerIcons` function and extend to wait time slightly to ensure the resize accounts for the tab height.

Fixes hidden UV footer when tabs are present

---

app/controllers/bulk_edit_controller.rb
spec/controllers/bulk_edit_controller_spec.rb

Allows Vector and Raster resources to be bulk edited. Because these resource types are not in Collections, the `load_removable_collections` method needs to be more tolerant of queries without a member_of_collection param.
Closes #5890

Fix bulk edit for vector and raster resources

---

app/views/fixity_dashboard/_fixity_table.html.erb
spec/views/fixity_dashboard/_fixity_table.html.erb_spec.rb

Notify with the event id when it has no resource_id

---

app/derivative_services/pdf_derivative_service.rb
app/models/ingestable_file.rb

This PR does a few things:
* Use the VIPS command line over the ruby interface for PDFs to avoid memory and file handle management issues of PDFs - spawning the process only long enough for it to die lets it clean up after itself.
* Close file handles for FileAppender on `#close` even if the file isn't there, but not if the instance variable hasn't been initialized - we were getting errors before without the file existence check, but it turns out that's because if the file's not there it can't instantiate, it's not that it can't close a file handle to a deleted file, and if we don't close the handle the system holds onto it.
* Remove all the GC management stuff from the PDF derivative service - by shelling out and managing file handles we don't need it.
* Reduce the number of pages it …

Fix PDF file handle overload

---

.circleci/Dockerfile
.circleci/config.yml
.lando.yml
Gemfile.lock
config/environments/test.rb
db/structure.sql

To make this work locally I had to upgrade lando and upgrade my local postgres (running via brew -- its pg_dump is used to create the schema file stored with the rails project)
advances #5903

Test and develop on postgres 15

---

config/environment.rb

See
https://github.com/DataDog/dd-trace-rb/issues/2012#issuecomment-1196877495

Removes the double injection of Datadog trace ID in Figgy logs.

---

app/decorators/file_set_decorator.rb
spec/decorators/file_set_decorator_spec.rb

Closes #5979 
- Display PreservationObject creation date as the cloud fixity date if file has no events
- Improve cloud and local fixity date formatting

Display PreservationObject creation date as the cloud fixity date if file has no events

---

app/derivative_services/geo_derivatives/processors/ogr.rb

When regenerating derivates for vector resources, we came across several errors in the gdal/ogr reprojection step.
```
Unable to execute command "env SHAPE_ENCODING= ogr2ogr -q -nln p-69ae9063-fa7f-45bf-8fe2-269b2b6c36b1 -f 'ESRI Shapefile' -t_srs EPSG:4326 -preserve_fid '/tmp/sufia20230929-7277-znakjp_1695996295528' '/tmp/sufia20230929-7277-znakjp_out'". 
Exit code: pid 26089 exit 1 Error message: ERROR 1: Failed to reproject feature 8979 (geometry probably out of source or destination SRS).
ERROR 1: Terminating translation prematurely after failed translation of layer world_mines (use -skipfailures to skip errors)
```
```
Unable to execute command "env SHAPE_ENCODING= ogr2ogr -q -nln p-c3497631-f7dc-4ada-89e3-c13886beac64 -f 'ESRI Shapefile' -t_srs EPSG:4326 -preserve_fid …
```

Make shapefile reprojection more fault tolerant

---

app/controllers/catalog_controller.rb
app/models/search_builder.rb
app/views/shared/_site_search.html.erb
spec/controllers/catalog_controller_spec.rb

Closes #6001
- Adds membership facet with two values: "no parent" and "has parent"
- Sets the default facet to "no parent" to replicate the current default search filter
- Removes the filter_parented search filter
- Allows for searching child resources

Allow search results for child records with parameter

---

app/queries/delete_duplicate_fixity_events.rb
config/initializers/valkyrie.rb
spec/queries/delete_duplicate_fixity_events_spec.rb

This will allow us to put in place the unique constraint in #5930
I think we'll need to rebase that PR on this one, and delete this query (more importantly its test, which will start to fail once that database migration exists).
refs #5938

Add a custom query to delete duplicate metadata nodes

---

app/services/repair_cloud_fixity.rb
spec/services/repair_cloud_fixity_spec.rb

Repairing metadata should requeue a fixity check.

---

app/assets/stylesheets/components/form.scss

There was a bug where the opacity would get set to 0 sometimes for some reason, making the options hidden.
Closes #6047

Force select2-dropdown opacity to be 1.

---

app/services/cloud_fixity.rb
spec/services/cloud_fixity_spec.rb

For some reason something's sending hundreds of thousands of these. It's too many, and too expensive, and a Repair's being sent for every one which is even more expensive. So turning this off for now while we investigate.
This is deployed to production.

Disable queueing for cloud fixity checks.

---

app/indexers/member_of_indexer.rb
app/services/geo_discovery/document_builder/relationship_builder.rb
spec/indexers/member_of_indexer_spec.rb
spec/services/geo_discovery/document_builder_spec.rb

Work towards #5858.
Fixes display and indexing issues in both Figgy and Pulmap. RasterResources will need to be re-indexed in both systems.
- Index RasterResources as member if parent is ScannedMap
- Generate correct geoblacklight documents for rasters with scanned map parents

Correctly index RasterResources with ScannedMap parents

---

app/services/cdl/eligible_item_service.rb
spec/services/cdl/eligible_item_service_spec.rb

This should speed up lookups for back-to-back CDL status in the catalog, but still be able to respond to taking CDL items off.
Work towards #6061

Cache eligible CDL item IDs for 5 minutes.

---

app/derivative_services/geo_derivatives/processors/gdal.rb

Closes #6088
Restores transparency to clipped raster derivatives.

Set explicit no-data value for raster derivatives

---

Gemfile
Gemfile.lock
app/services/migrations/reset_box_thumbnails.rb
lib/tasks/migrate.rake
spec/services/migrations/reset_box_thumbnails_spec.rb

- Add ruby debug as an alternative to pry/byebug
- I kept hitting this undefined constant error, see https://github.com/deivid-rodriguez/byebug/issues/564
- to use debug insert `binding.break`
- Add rake task and service  to fix orphan thumbnails
refs #6081

Add rake task to clear bad thumbnails in an ephemera box

---

app/services/bulk_ingest_service.rb
spec/controllers/bulk_ingest_controller_spec.rb
spec/services/bulk_ingest_service_spec.rb

It was handling a `collection` attribute, but it comes from the
controller as `member_of_collection_ids`
advances pulibrary/dpul#1420

Change BulkIngestService to handle attribute params it actually receives

---

app/services/preservation_status_reporter.rb
lib/tasks/preservation.rake
spec/services/preservation_status_reporter_spec.rb

And have the id check write to a different file
closes #6108

Refactor preservation audit over full repository vs list of ids

---

Gemfile
Gemfile.lock

We no longer need this since later versions of bundler first install
whatever bundler version the Gemfile.lock was generated with, then run
that to bundle. This will give us a little more flexibility on server
bundler versions.
refs pulibrary/princeton_ansible#3164

Back out requirement for specific bundler version

---

README.md
app/javascript/test/setup.js
package.json
yarn.lock

Remove babel and Jest because they are no longer used in our project. Resolves some javascript security issues.
Work towards #4482

Remove babel and Jest

---

README.md

ASDF's yarn doesn't work in Rosetta for whatever reason.

Fix mapnik M1 install instructions.

---

spec/derivative_services/external_metadata_derivative_service_spec.rb

Fixes issue with spec for ExternalMetadataDerivativeService that was causing issues when running the entire test suite.

Fix EventGenerator mocking in ExternalMetadataDerivativeService spec

---

app/jobs/characterization_job.rb
app/jobs/recharacterize_job.rb
spec/derivative_services/external_metadata_derivative_service_spec.rb
spec/jobs/characterization_job_spec.rb
spec/jobs/recharacterize_job_spec.rb

- Characterization failure messages were not being saved on the FileSet when run in production. The issue was the buffered persister which rolled back once the job errored.
- Also removes troublesome and unnecessary ExternalMetadataService test. 
Closes #6059 
Working in staging:

Don't use buffered persister in CharacterizationJob so error messages are saved

---

.circleci/config.yml

Fixes issues with chromedriver in CI. We don't need it.
CI builds started failing today.

Don't install chromedriver

---

app/controllers/downloads_controller.rb
app/services/manifest_builder.rb
app/values/hls_manifest.rb
app/values/hls_manifest/primary.rb
config/routes.rb
spec/controllers/downloads_controller_spec.rb
spec/controllers/playlists_controller_spec.rb
spec/services/manifest_builder_spec.rb

This adds a primary manifest in front of the AV manifests, as a place we
can put transcripts.
This also refactors where generating HLS manifests happens, so we can
add to that logic without changing DownloadsController all the time.
Work towards https://github.com/pulibrary/figgy/issues/6181

Use a primary HLS manifest

---

app/nested_resources/file_metadata.rb
app/values/hls_manifest.rb
app/values/hls_manifest/caption.rb
app/values/hls_manifest/primary.rb
spec/controllers/downloads_controller_spec.rb
spec/factories/scanned_resource.rb

This generates an HLS manifest for caption files (VTT) and associates them with the primary manifest.
Closes https://github.com/pulibrary/figgy/issues/6181

Attach caption HLS manifest to primary manifest. 

---

app/services/manifest_builder.rb
app/services/manifest_builder/manifest_service_locator_v3.rb
spec/services/manifest_builder_spec.rb

Closes #6245 
- Render V3 seeAlso property in av manifests
- Change method name to reflect both audio and video

Render V3 seeAlso property in av manifests

---

app/models/file_set.rb
app/queries/find_uncaptioned_members.rb
app/queries/find_video_members.rb
app/values/health_report.rb
app/values/health_report/video_caption_check.rb
config/initializers/valkyrie.rb
config/locales/en.yml
spec/factories/scanned_resource.rb
spec/queries/find_uncaptioned_members_spec.rb
spec/queries/find_video_members_spec.rb
spec/values/health_report_spec.rb

Closes #6192
I didn't add the links to attach a caption or the file manager because the links are right there, and frankly it was kinda hard. I would have had to have made the I18n accept an argument I think? And probably access path helpers from I18n?

Add a health check for Captions.

---

app/decorators/valkyrie/resource_decorator.rb
app/helpers/application_helper.rb
app/presenters/permission_badge.rb
config/locales/en.yml
spec/decorators/valkyrie/resource_decorator_spec.rb

Closes https://github.com/pulibrary/figgy/issues/6183
As an aside, this visibility logic wasn't very pleasant to work in, but I couldn't really think of how to clean it up.

Visibility warning for uncaptioned videos. 

---

app/javascript/viewer/uv_manager.js

Small fix after clover integration. A few `resize` methods need renaming to `resizeUV`.

Update resize method for UV

---

app/views/records/edit_fields/_ocr_language.html.erb
spec/shared_specs/controllers/base_resource_controller.rb
spec/views/records/edit_fields/_ocr_language.html.erb_spec.rb

Done on a whim, on a user request, and because it's been bothering me for a long time that our OCR generators all handle this but we can't put it in the form.

Make OCR language a multi-valued field.

---

app/derivative_services/av_derivative_service.rb
spec/controllers/downloads_controller_spec.rb

I very carefully crafted some subtitles for a demo video, uploaded them, and noticed subtitles were out of sync! According to https://stackoverflow.com/questions/61835223/ffmpeg-burnt-in-subtitles-out-of-sync-when-converting-to-hls ffmpeg adds a delay to AV when creating HLS - and sure enough, when I add this argument everything's in sync.

Add muxdelay 0 to ffmpeg HLS generation.

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/characterize.rb
app/jobs/generate_checksum_job.rb
spec/change_set_persisters/change_set_persister_spec.rb

This should handle future preservation targets as well.
I moved Characterize to after_save_commit so we'd have access to `post_save_resource` in its handlers - I couldn't find a reason for it to not be there.
Closes #6276

Generate Checksum for captions.

---

app/change_set_persisters/change_set_persister/generate_mosaic.rb
app/controllers/tile_metadata_controller.rb
app/derivative_services/raster_resource_derivative_service.rb
app/jobs/mosaic_job.rb
app/services/tile_metadata_service.rb
app/values/tile_path.rb
config/initializers/honeybadger.rb
spec/change_set_persisters/change_set_persister/generate_mosaic_spec.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/controllers/tile_metadata_controller_spec.rb
spec/decorators/raster_resource_decorator_spec.rb
spec/derivative_services/raster_resource_derivative_service_spec.rb
spec/jobs/mosaic_job_spec.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb
spec/services/geo_discovery/document_builder_spec.rb
spec/services/geoserver_publish_service_spec.rb
spec/services/manifest_builder_spec.rb
spec/services/manifest_builder_v3_spec.rb
spec/services/tile_metadata_service_spec.rb
spec/values/tile_path_spec.rb

Along with https://github.com/pulibrary/geoservices-aws/pull/2, this pull request:
1. Simplifies creation mosaic json documents
2. Decouples Figgy and the TiTiler lambda service to some degree; mostly when serving tiles, which improves performance.
3. Addresses potential race conditions when generating mosaic json documents by only allowing one MosaicJob for a resource to run at a time. 
4. Makes it possible to automatically invalidate the TiTiler / CloudFront cache when the mosaic data changes. Currently, the ID for a resource which you would use to invalidate is passed to TiTiler as a query param. While it is possible to cache using query params as keys in CloudFront, it is not possible to invalidate using query params. These PRs move the id from a param to the url path. See followup …

improve mosaics

---

config/initializers/health_monitor.rb
spec/requests/health_check_spec.rb

advances #6287
This monitor will fail if any job in the retry queue has 20 or more retries. There is not a way in the sidekiq api to check retry latency because it's not a queue; it's a set. We had determined that 5 days would probably be around 17 retries, but it's not configurable in the underlying gem.

Add sidekiq to health monitor

---

app/controllers/ephemera_folders_controller.rb
app/controllers/numismatics/coins_controller.rb
spec/controllers/ephemera_folders_controller_spec.rb
spec/controllers/numismatics/coins_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/shared_specs.rb
spec/shared_specs/controllers/base_resource_controller.rb
spec/shared_specs/controllers/concerns/pdfable.rb

- There were identical specs in ephemera folders controller, coins
controller, and scanned resources controller specs. This will make
them easier to change together
- The shared spec for ResourcesController had the pdf spec, but the
ResourcesController does not implement that code, it's directly in the
scanned resources controller itself, so it didn't make sense for the
spec to be there.
- Set us up to move the pdf controller code to a concern
refs #6278

Move pdf spec to its own shared spec.

---

.rubocop.yml
app/controllers/concerns/pdfable.rb
app/controllers/ephemera_folders_controller.rb
app/controllers/numismatics/coins_controller.rb
app/controllers/scanned_resources_controller.rb
app/jobs/generate_pdf_job.rb
app/services/export_service.rb
app/services/pdf_service.rb
config/initializers/inflections.rb
spec/jobs/generate_pdf_job_spec.rb
spec/requests/scanned_resource_spec.rb

There are also a couple of refactors in here; it may be helpful to view the commits separately.
- wrap pdf generation in a job, call it synchronously
- Remove change_set param from pdf and structure paths
- Generate pdf from the resource id
- Skip failing tests
- Move controller pdf method to a concern

Wrap pdf generation in a job, call it synchronously

---

app/derivative_services/raster_resource_derivative_service.rb
app/derivative_services/vector_resource_derivative_service.rb
config/config.yml
config/initializers/valkyrie.rb
spec/derivative_services/raster_resource_derivative_service_spec.rb
spec/derivative_services/vector_resource_derivative_service_spec.rb
spec/spec_helper.rb

- Use standard storage adapter for geo resource thumbnails
- Remove geo_derivative storage adapter
Works towards #6312

Use standard storage adapter for geo resource thumbnails

---

app/jobs/cdl/pdf_ingest_job.rb
app/services/file_appender.rb
spec/controllers/collections_controller_spec.rb
spec/controllers/reports_controller_spec.rb
spec/models/ability_spec.rb
spec/services/cdl/automatic_completer_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb
spec/services/manifest_builder_v3/by_resource_type/manifest_builder_v3_scanned_map_spec.rb
spec/services/preserver_spec.rb

This will keep pdf derivative generation from only generating a portion
of the files, and keep resources from being created if not all files
were successfully attached.
It's a bigger mess to have things half-ingested and have to clean up
after.
refs #5964

Let errors pass through if file appender fails on create_node

---

README.md
bin/setup
bin/setup_credentials

There's a rake task called setup_keys which does unrelated stuff. It's confusing to also have `bin/setup_keys`

Clarify sidekiq-pro credentials setup

---

Gemfile.lock
app/javascript/components/file_browser/directory_picker.vue
app/javascript/components/file_browser/file_browser.vue
app/javascript/entrypoints/application.js
app/javascript/test/file_browser/directory_picker.spec.js
app/javascript/test/file_browser/embedded_file_browser.spec.js
app/javascript/test/file_browser/file_browser.spec.js
app/javascript/test/file_browser/input_path_selector.spec.js
app/javascript/test/setup.js
package.json
yarn.lock

Closes #6372 
By managing `expanded` ourselves and rendering the tree based on that we can get rid of this dependency.

Stop using <details> for file browser, use <li>

---

spec/services/manifest_builder/by_resource_type/manifest_builder_audio_resource_spec.rb

Just moves the specs around / changes the nesting.
refs #5747

Refactor audio manifest builder spec for clarity

---

app/javascript/entrypoints/viewer.js
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/views/layouts/viewer_layout.html.erb

The download pane in Universal Viewer:
1. Doesn't fire any javascript events (so we can't bind to an event and send a custom event)
2. Doesn't count as an outbound link (https://plausible.io/docs/outbound-link-click-tracking doesn't work)
3. Doesn't count as a "File Download" (https://plausible.io/docs/file-downloads-tracking doesn't work)
4. DOES use `window.open` to open a link. (https://github.com/UniversalViewer/universalviewer/blob/main/src/content-handlers/iiif/extensions/uv-openseadragon-extension/DownloadDialogue.tsx#L431)
Thus we can fire a custom event by, if Universal Viewer is loaded, overriding `window.open` in the viewer. This also adds an "?embed_host" property that can be added to the iframe, and sends the environment it's sending as. This is done via the documentation at …

Track Downloads through Universal Viewer

---

Gemfile
Gemfile.lock

From comparing readmes, there appear to be breaking changes that weren't really enumerated in the 2.0 release notes.
refs #6403

Roll back filewatcher version

---

config/config.yml

Add the secure and general 10.* ranges
Update the GlobalProtect clientless VPN portal range
Oh, also removed one that was no longer in the OIT documentation.
closes #6409

Update campus vpn ranges

---

app/services/manifest_builder.rb

Trying to see if we have a manifest problem that's keeping audio from playing in UV and Ramp

Use Sound, not Audio

---

app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/services/embed.rb
spec/graphql/types/scanned_resource_type_spec.rb

We accidentally broke CDL in
https://github.com/pulibrary/figgy/blob/e4162d20d99111cd64e574fd306982246a75354e/app/javascript/viewer/uv_manager.js#L23. We used to check manifest statuses and redirect if it was unauthorized, but not if it was "forbidden."
This PR adds a forbidden status to the embed code, which should get us back to parity.
Tested locally and this fixes the screen for CDL.
Closes #6418

Update viewer logic to handle "unauthorized" redirects for CDL

---

app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/views/layouts/blacklight/base.html.erb

This may be a naive approach, but it listens for a click event on the #uv element, logs it (for testing), and dispatches a `uv-click` event to Plausible. I am unsure of how to test this in Plausible to make sure it was received.

Adds UV click event listener and sends custom event to Plausible

---

app/derivative_services/pdf_derivative_service.rb
spec/derivative_services/pdf_derivative_service_spec.rb

For PDF derivatives this does three things:
1. Ensure the whole resource rolls back appropriately if it fails to generate a derivative.
2. Retry if VIPS creates a zero byte file.
3. Uses the default DPI settings. 300 was resulting in 300 MB files PER PAGE for a PDF that was only 20 MB total.
Now it should only be able to make a zero byte file if the storage uploader somehow creates one when copying the file over.
Work towards #6436

PDF Resilience Attempts

---

app/javascript/components/StructManagerToolbar.vue
spec/features/struct_manager_spec.rb

There was no need to change the Ctrl-x hotkey since the hotkey collision issue on Windows was pasting text from the clipboard, not cutting or copying.

Updates the paste hotkey from Ctrl-v to Ctrl-.

---

app/services/manifest_builder/start_canvas_builder.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_maps_spec.rb

If a scanned map gets set as a start canvas, don't try to render it as one.
Closes #6456

ScannedMaps should not be start_canvases

---

README.md
bin/setup_keys

Several things were repeated, there was old content, and there was too
much detail in some places. Duplicate setup_keys script was removed. It
was probably moved to be called setup_credentials at some point to keep
it from being confusing given the setup_keys rake task.

Update readme for clarity and to reduce duplicate documentation

---

app/assets/stylesheets/components/form.scss
app/assets/stylesheets/components/show.scss
app/views/numismatics/coins/_form.html.erb
app/views/numismatics/issues/_form.html.erb

fixes the button spacing issue for numismatics

---

.circleci/Dockerfile
.circleci/config.yml
.github/workflows/build-ci-docker.yml
.github/workflows/prune-containers.yml
app/derivative_services/geo_derivatives/processors/gdal.rb
spec/derivative_services/geo_derivatives/processors/base_geo_processor_spec.rb

- Modifies geo derivative service to use built-in GDAL Cloud Optimized GeoTiff ouput format. Solves issue with improperly generated images.
- Updates CI docker image to latest base version to get the latest version of GDAL with the new format.
- Moves CI docker image from docker hub to GitHub packages to be more in line with other projects.
- Adds GitHub Actions task to build new docker images when the Dockerfile or dependency build scripts change.
Closes #6501 
Tried in figgy staging. Generates correctly formatted COG.

Update GDAL command to use built COG output format

---

config/locales/en.yml
spec/services/pdf_generator_spec.rb

We noticed this change because a redirect was dropped in the website migration. So we should update to the current URL for the page and not use the old URL which depends on the redirect.

Updating link for Special Collections citation guidelines

---

config/authorities/rights_statement.yml

We are hosting content from the British Library, and they have requested that we use this rights statement. It is very similar to CC0, but differs in that it asserts the item is already in the public domain, as opposed to saying we are putting it in the public domain.

Adding Creative Commons Public Domain Mark rights statement

---

config/environments/production.rb

We're seeing issues with Datadog related to SSL redirects. We do not need to set this in the application, as the load balancer does this for us.

Don't force ssl

---

config/deploy/staging.rb

We can't deploy to figgy-web-staging1, pending
https://github.com/pulibrary/figgy/issues/6593
Remove it for now

Remove figgy-web-staging1 as deploy target

---

config/initializers/health_monitor.rb
spec/requests/health_monitor_spec.rb

We weren't acting on this alert, and we have other process in place for
the retries queue.
Also make configuration for "default" queue more explicit
closes #6558

Remove retries check on sidekiq monitor

---

app/adapters/retrying_disk_adapter.rb
app/derivative_services/pdf_derivative_service.rb
app/services/preserver/preservation_checker.rb
app/utils/figgy_utils.rb
spec/services/preservation_status_reporter_spec.rb

Use with_rescue to retry SSLErrors during preservation audit

---

lib/tasks/preservation.rake

for better resilience between deploys
closes #6596

Use "current" path for preservation audit files

---

Gemfile.lock
app/change_sets/caption_change_set.rb
app/models/controlled_vocabulary.rb
app/nested_resources/file_metadata.rb
app/services/bulk_ingest_service/bulk_file_path_converter.rb
app/values/hls_manifest/primary.rb
app/views/records/edit_fields/_caption_language.html.erb
spec/controllers/downloads_controller_spec.rb
spec/controllers/file_metadata_controller_spec.rb
spec/factories/scanned_resource.rb
spec/features/file_set_spec.rb
spec/models/controlled_vocabulary/language_spec.rb
spec/services/bulk_ingest_service_spec.rb

- Make caption language multi-valued
- Use ISO 639.2 codes to supply language list (increases the number of available languages)
Tested in Chrome, Firefox, and Safari.

Add multi-language support to captions

---

app/services/preserver/preservation_checker.rb

So that these can be invoked separately when following up on the audit

Refactor `preserved?` methods to call helper methods

---

app/controllers/reports_controller.rb
app/models/ability.rb
app/services/mms_report_generator.rb
app/services/mms_report_generator/report_resource.rb
config/routes.rb
spec/controllers/reports_controller_spec.rb

Closes #6544
I made a couple changes to the specified format to support multiple resources per BibID and to provide some info about what the "visibility" value means to the devs using this. An example:
```json
{
"99125433518606421": [
{
"visibility": {
"value": "open",
"label": "open",
"definition": "Open to the world. Anyone can view."
},
"portion_note": null,
"iiif_manifest_url": "https://figgy-staging.princeton.edu/concern/raster_resources/9a3dd626-d169-49b4-b6eb-c21132d0bd32/manifest"
}
],
"9968666393506421": [
{
"visibility": {
"value": "open",
"label": "open",
"definition": "Open to the world. Anyone can view."
},
"portion_note": null,
"iiif_manifest_url": "https://figgy-staging.princeton.edu/concern/scanned_maps/4fbb471d-875f-486f-a867-12e70cf1501d/manifest"
},
{
"visibility": { …
```

MMS Report for Catalog Synchronization

---

app/queries/all_mms_resources_query.rb
app/services/mms_report_generator.rb
app/services/mms_report_generator/report_resource.rb
db/migrate/20250123183528_substring_mms_idx.rb
db/structure.sql
spec/controllers/reports_controller_spec.rb
spec/queries/all_mms_resources_query_spec.rb

Before this change, the MMS report developed for #6544 took about 20 minutes to generate.
By avoiding pulling all fields and not converting to resources, the report generates in ~ 15 minutes.
By using SUBSTRING, only checking for "99", and creating an index on that value the report generates in 7 minutes.
By doing both, the report generates in ~ 25 seconds.

Improve MMS Report Performance

---

app/services/manifest_builder.rb
spec/controllers/scanned_resources_controller_spec.rb

This pathway got bypassed when we separated the rendering logic for V2/V3 manifests, similar to how Playlists broke.
Closes #6547

ManifestBuilder should load a combined V3 manifest for MVW Recordings.

---

app/services/dao_updater.rb
spec/services/dao_updater_spec.rb

DAO Updater should only send a notice if the resource is a component.

---

app/characterization_services/imagemagick_characterization_service.rb
spec/characterization_services/imagemagick_characterization_service_spec.rb
spec/derivative_services/image_derivative_service_spec.rb
spec/derivative_services/jp2_creator_spec.rb
spec/derivative_services/thumbnail_derivative_service_spec.rb
spec/derivative_services/vips_derivative_service_spec.rb
spec/jobs/characterization_job_spec.rb
spec/jobs/recharacterize_job_spec.rb
spec/support/stub_tika.rb

ImageMagick 7 characterizes better than 6, but Debian's having a rough time getting IM 7 into their repo. Instead, let's just use VIPS!
Closes #6669

Replace characterization of tiffs with VIPS.

---

config/config.yml

This should be kept in draft until the illiad migration
closes #6412

Use ocr in and out path vars for new illiad installation

---

app/services/bulk_ingest_service.rb
spec/services/bulk_ingest_service_spec.rb

There's no reason to keep it, and it breaks manifests.

Don't include figgy_metadata.json in imported files.

---

app/jobs/refresh_remote_metadata_job.rb
config/deploy/production.rb

This should make the numbers for #6731 much better.

Prevent propagation when refreshing remote metadata.

---

app/jobs/server_upload_job.rb
spec/jobs/server_upload_job_spec.rb

You can't upload into non-existent objects, and we see this every week at honeybadger.

ServerUploadJob shouldn't raise an error when object not found.

---

app/views/layouts/blacklight/base.html.erb
app/views/layouts/viewer_layout.html.erb
app/views/shared/_analytics.html.erb
app/views/shared/_analytics_noscript.html.erb

This also adds local analytics for the viewer page - there's an
exception for the google tag in Google Tag Manager if it's on the viewer, so we maintain existing functionality.
Work towards pulibrary/dpul-collections#709

Use google tag manager for Figgy.

---

app/derivative_services/geo_derivatives/processors/base_geo_processor.rb
app/derivative_services/geo_derivatives/processors/raster/base.rb
app/derivative_services/geo_derivatives/processors/vector/base.rb
app/derivative_services/raster_resource_derivative_service.rb
app/derivative_services/vector_resource_derivative_service.rb
spec/derivative_services/raster_resource_derivative_service_spec.rb
spec/derivative_services/vector_resource_derivative_service_spec.rb

Closes #6780
Ensures that vector and raster derivative generation does not leave files on the worker.
- Creates a temp directory for all output and intermediate steps.
- Ensures that temp files and folders are removed when processing is done or an error is encountered.

Cleanup geo derivative working files
