pulibrary/figgy

app/adapters/indexing_adapter.rb, spec/adapters/indexing_adapter_spec.rb, spec/requests/scanned_resources_spec.rb
This is definitely bypassing some of Valkyrie's interface to get a feature it doesn't have yet, but I'd like to have it early on, before we can all figure out what the right interface is for transaction support in Valkyrie.
=> Rely on AR Transactions for safe indexing

Gemfile.lock, app/change_set_persisters/plum_change_set_persister.rb, app/change_sets/scanned_resource_change_set.rb, app/controllers/scanned_resources_controller.rb, app/decorators/valkyrie/resource_decorator.rb, app/jobs/browse_everything_ingest_job.rb, app/model/pending_upload.rb, app/models/plum_schema.rb, app/services/file_appender.rb, spec/controllers/scanned_resources_controller_spec.rb, valhalla/app/controllers/concerns/valhalla/resource_controller.rb, valhalla/app/views/valhalla/base/_pending_uploads.html.erb, valhalla/app/views/valhalla/base/_server_upload.html.erb
This also refactors how ChangeSets & `buffer_into_index` interacts.
=> Add PendingUploads

Gemfile.lock, app/change_sets/file_set_change_set.rb, app/derivative-services/jp2_derivative_service.rb, app/jobs/create_derivatives_job.rb, app/models/file_set.rb, app/services/file_appender.rb, bin/ci_kakadu_install.sh, circle.yml, config/config.yml, config/initializers/figgy.rb, config/initializers/valkyrie.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/derivative_services/jp2_derivative_service_spec.rb
=> Create JP2 Derivatives on Ingest

.rubocop.yml, Gemfile, Gemfile.lock, app/change_sets/scanned_resource_change_set.rb, app/services/manifest_builder.rb, spec/services/manifest_builder_spec.rb
This uses proper 2.1 ranges too.
=> Add range support to manifest.

.rubocop.yml, Gemfile, Gemfile.lock, app/change_sets/scanned_resource_change_set.rb, app/helpers/state_helper.rb, app/models/book_workflow.rb, app/models/scanned_resource.rb, app/validators/state_validator.rb, app/views/records/edit_fields/_state.html.erb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/models/book_workflow_spec.rb, spec/validators/state_validator_spec.rb
=> AASM state-machine workflow for ScannedResources

Gemfile.lock, app/change_set_persisters/plum_change_set_persister.rb, app/decorators/scanned_resource_decorator.rb, app/models/imported_metadata.rb, app/models/plum_schema.rb, app/models/scanned_resource.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/models/scanned_resource_spec.rb, spec/views/catalog/show.html.erb_spec.rb
=> Store imported attributes in a nested record.

app/change_sets/scanned_resource_change_set.rb, spec/change_sets/scanned_resource_change_set_spec.rb
=> Add a default structure label.

app/change_set_persisters/plum_change_set_persister.rb, app/change_sets/scanned_resource_change_set.rb, app/decorators/scanned_resource_decorator.rb, app/decorators/valkyrie/resource_decorator.rb, app/services/manifest_builder.rb, app/views/catalog/_admin_controls.html.erb, app/views/records/edit_fields/_append_id.html.erb, config/routes.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/routing/scanned_resource_routes_spec.rb, spec/services/manifest_builder_spec.rb, valhalla/app/controllers/concerns/valhalla/resource_controller.rb, valhalla/app/services/valhalla/contextual_path.rb
=> Adds Append Scanned Resource Functionality

app/change_set_persisters/plum_change_set_persister.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Set thumbnail ID on appending.

app/change_set_persisters/plum_change_set_persister.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Clean up membership associations on delete.

app/change_set_persisters/plum_change_set_persister.rb, app/indexers/member_of_indexer.rb, app/models/search_builder.rb, app/services/file_appender.rb, config/initializers/valkyrie.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/indexers/member_of_indexer_spec.rb
=> Index member_of and restrict discovery.

app/assets/stylesheets/components/show.scss, app/decorators/valkyrie/resource_decorator.rb
=> Add visibility badge to show page.

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/bootstrap_select_dropdown.js, app/assets/javascripts/figgy_boot.es6, app/assets/javascripts/rights_note.js, app/assets/stylesheets/application.scss, app/views/records/edit_fields/_member_of_collection_ids.html.erb, spec/controllers/scanned_resources_controller_spec.rb
=> Convert selects to bootstrap-select.

app/models/search_builder.rb, spec/controllers/catalog_controller_spec.rb, spec/factories/scanned_resource.rb
=> Add workflow gated search.

spec/change_set_persisters/plum_change_set_persister_spec.rb
Looks like CI didn't catch the broken specs for some reason? This fixes
it.
=> Specs broke and CI didn't catch it

app/controllers/catalog_controller.rb, app/services/identifier_service.rb, config/routes.rb, spec/controllers/catalog_controller_spec.rb, spec/services/identifier_service_spec.rb
=> Looking up manifests by ARK

app/assets/stylesheets/components/form.scss, app/change_sets/scanned_resource_change_set.rb, app/change_sets/workflow_note_change_set.rb, app/controllers/catalog_controller.rb, app/decorators/workflow_note_decorator.rb, app/helpers/state_helper.rb, app/models/controlled_vocabulary.rb, app/models/scanned_resource.rb, app/models/workflow_note.rb, app/views/catalog/_workflow_controls_default.html.erb, app/views/records/edit_fields/_state.html.erb, config/locales/en.yml, spec/controllers/catalog_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Add state transition widget to show pages.

app/decorators/upload_decorator.rb, app/services/file_appender.rb, app/views/catalog/_admin_controls.html.erb, config/routes.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/valhalla/downloads_controller_spec.rb, valhalla/app/controllers/valhalla/downloads_controller.rb, valhalla/config/routes.rb
=> Downloading and updating file content

valhalla/app/assets/javascripts/valhalla/file_manager.es6
=> Re-enable File Manager Affix

app/controllers/catalog_controller.rb, app/decorators/scanned_resource_decorator.rb, app/views/catalog/_members_default.html.erb, spec/views/catalog/show.html.erb_spec.rb
=> Displaying members

app/change_sets/file_set_change_set.rb, app/models/file_set.rb, config/locales/simple_form.en.yml, spec/views/scanned_resources/file_manager.html.erb_spec.rb, valhalla/app/assets/javascripts/valhalla/plum_file_manager.es6, valhalla/app/views/valhalla/base/_file_manager_attributes.html.erb
=> Add File Set viewing hint to file manager.

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/figgy_boot.es6, app/assets/stylesheets/application.scss, app/views/records/edit_fields/_nav_date.html.erb, spec/controllers/scanned_resources_controller_spec.rb
=> Add timepicker to Navigation Date.

Gemfile.lock
Brings test suite down from > 30 to < 28s.
=> Add speedup commits from Valkyrie.

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/browse_everything.scss
This doesn't add the loading text changes, because they always look a
little strange.
Closes #59
=> Add Browse Everything CSS

Gemfile.lock, app/controllers/collections_controller.rb, app/models/index_collection.rb, app/services/manifest_builder.rb, app/services/manifest_builder/manifest_service_locator.rb, config/routes.rb, spec/controllers/collections_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Collection manifests

app/models/concerns/linked_data.rb, app/models/remote_record.rb, app/models/solr_document.rb, app/services/manifest_builder.rb, app/services/manifest_builder/see_also_builder.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/factories/scanned_resource.rb, spec/fixtures/files/bibdata/context.json, spec/services/manifest_builder/see_also_builder_spec.rb, spec/support/stub_bibdata.rb
=> Export records as RDF

Gemfile.lock, app/characterization_services/tika_file_characterization_service.rb, app/decorators/file_set_decorator.rb, app/models/file_metadata.rb, app/models/file_set.rb, config/locales/en.yml, spec/views/catalog/show.html.erb_spec.rb
=> Display original_file's tech metadata on FileSet show page

app/views/catalog/_members_default.html.erb, spec/views/catalog/show.html.erb_spec.rb
=> Member thumbnail should link to member in parent context

config/deploy.rb
=> Tagging releases with revision hash and timestamp

Gemfile.lock, app/helpers/osd_modal_helper.rb, app/services/manifest_builder.rb, app/services/manifest_builder/faster_iiif_manifest.rb, app/services/manifest_builder/manifest_service_locator.rb, config/deploy.rb, spec/services/manifest_builder/cantaloupe_helper_spec.rb, spec/services/manifest_builder_spec.rb, valhalla/app/views/valhalla/base/_file_manager_thumbnail.html.erb, valhalla/app/views/valhalla/base/_structure_node.html.erb
This brings a 1140 page manifest from 11 seconds to 2.6 seconds to
generate.
=> Speed up IIIF Manifest Generation

app/assets/javascripts/figgy_boot.es6, app/assets/javascripts/universal_viewer.es6
=> Fix fullscreen for UV.

.solr_wrapper, lib/tasks/dev.rake
Should fix issues with @shaune's tmp directory as well as issues with
the solr mirror.
=> Fix Solr Wrapper.

valhalla/app/assets/javascripts/valhalla/file_manager/member.es6, valhalla/app/views/valhalla/base/_file_manager_derivatives.html.erb
A form tag wasn't closed.
Closes #181
=> Fix file manager.

.rubocop.yml, app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb, app/change_sets/ephemera_folder_change_set.rb, app/change_sets/scanned_resource_change_set.rb, app/decorators/ephemera_folder_decorator.rb, app/models/controlled_vocabulary.rb, app/models/ephemera_folder.rb, app/models/folder_workflow.rb, app/views/catalog/_parent_breadcrumb_ephemera_folder.html.erb, spec/controllers/catalog_controller_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/factories/ephemera_folder.rb, spec/models/folder_workflow_spec.rb, spec/support/shared/workflow_specs.rb, valhalla/app/change_sets/valhalla/change_set.rb, valhalla/app/change_sets/valhalla/change_set_workflow.rb
Also DRYs this up a bit to make it easier to add another workflow later.
=> Add Ephemera Folder Workflow

app/change_sets/ephemera_project_change_set.rb, app/decorators/ephemera_project_decorator.rb, app/models/ephemera_project.rb, app/views/ephemera_projects/index.html.erb, spec/controllers/catalog_controller_spec.rb, spec/controllers/ephemera_projects_controller_spec.rb, spec/factories/ephemera_project.rb, spec/models/ephemera_project_spec.rb
=> Rename project `name` to `title`

app/change_set_persisters/plum_change_set_persister/propagate_visibility_and_state.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Don't persist state/visibility to FileSets

app/change_set_persisters/plum_change_set_persister/propagate_visibility_and_state.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Only propagate valid states.

app/views/records/edit_fields/_shipped_date.html.erb
=> Add shipped date to boxes.

spec/views/catalog/_members_ephemera_box.html.erb_spec.rb, spec/views/catalog/_members_ephemera_project.html.erb_spec.rb, spec/views/catalog/_members_scanned_resource.html.erb_spec.rb, spec/views/catalog/_resource_attributes_default.html.erb_spec.rb
It was running a ton of lookups for templates and was really really
slow. This shaves off ~17 seconds from specs.
=> Avoid show.html.erb spec.

app/controllers/ephemera_folders_controller.rb, spec/controllers/ephemera_folders_controller_spec.rb
=> Redirect to Box on Folder Delete.

app/views/records/edit_fields/_member_of_vocabulary_id.html.erb
=> Remove add vocabulary button.

app/controllers/catalog_controller.rb, app/decorators/valkyrie/resource_decorator.rb, app/document_presenters/valkyrie_show_presenter.rb, spec/helpers/blacklight_helper_spec.rb, spec/support/view_verify_doubles.rb
Closes #240, closes #238, closes #239
=> Uses decorator for Blacklight headers.

app/controllers/ephemera_boxes_controller.rb, spec/controllers/ephemera_boxes_controller_spec.rb
=> Redirect to Project on Box delete.

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/delete_referenced.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Delete controlled fields w/ Vocabulary.

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
=> Fix search by source_metadata_identifier

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/characterize.rb, app/change_set_persisters/plum_change_set_persister/publish_message.rb, spec/jobs/ingest_mets_job_spec.rb
=> Generate derivatives for METS Ingest.

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
=> Search by title & ARK

app/decorators/application_decorator.rb, app/decorators/ephemera_folder_decorator.rb, app/decorators/scanned_map_decorator.rb, app/decorators/scanned_resource_decorator.rb
=> Don't clobber magic 'attributes' method

app/views/records/edit_fields/_description.html.erb
=> Description as a text box.

spec/controllers/catalog_controller_spec.rb
=> Ensure diacritic/bracketed searching works.

app/decorators/ephemera_vocabulary_decorator.rb, spec/decorators/ephemera_vocabulary_decorator_spec.rb
=> Sort Vocabulary Terms in Menus.

app/controllers/templates_controller.rb, spec/controllers/templates_controller_spec.rb
=> Load controlled vocabs for Templates.

app/jobs/ingest_ephemera_job.rb, lib/tasks/lae.rake, spec/services/ingest_ephemera_service_spec.rb
=> Add rake task & background job for LAE ingest.

solr/conf/solrconfig.xml, solr/config/solrconfig.xml
We don't use "did you mean" functionality from Blacklight, and building
up the suggest component was taking a long time every soft commit.
Closes #298
=> Remove suggest component.

app/change_sets/date_range_change_set.rb, app/change_sets/ephemera_folder_change_set.rb, app/decorators/date_range_decorator.rb, app/decorators/ephemera_folder_decorator.rb, app/models/date_range.rb, app/models/ephemera_folder.rb, app/validators/year_validator.rb, app/views/records/edit_fields/_date_range_form.html.erb, config/initializers/simple_form_bootstrap.rb, config/locales/en.yml, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/models/ephemera_folder_spec.rb, spec/views/catalog/_resource_attributes_default.html.erb_spec.rb, valhalla/app/assets/stylesheets/valhalla/form.scss
Closes #280.
This is a little more complicated than needs be, but it creates a nested object for date ranges so we could potentially add multiple pairs later on. It's a need we've recognized before when talking about Visuals stuff, so I thought it'd be a good idea to see what it looks like to implement.
=> Add start & end dates to form.

app/controllers/catalog_controller.rb, app/decorators/ephemera_box_decorator.rb, app/indexers/project_indexer.rb, config/initializers/valkyrie.rb, spec/controllers/ephemera_boxes_controller_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/indexers/project_indexer_spec.rb
=> Index Ephemera Project

app/services/plum_importer.rb, spec/fixtures/files/plum/ps7529f137.json, spec/services/plum_importer_spec.rb
=> Import Arks.

app/controllers/catalog_controller.rb, app/decorators/scanned_resource_decorator.rb, app/indexers/human_readable_type_indexer.rb, config/initializers/valkyrie.rb, spec/indexers/human_readable_type_indexer_spec.rb
=> Implementing a HumanReadableTypeIndexer for indexing Multi-Volume Works

valhalla/app/controllers/valhalla/downloads_controller.rb
=> Don't set a blank Last-modified header

Gemfile, Gemfile.lock, README.md, app/adapters/indexing_adapter.rb, app/services/file_appender.rb, app/utils/data_seeder.rb, app/utils/user_utils.rb, config/config.yml, db/seeds.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/services/plum_importer_spec.rb, spec/utils/data_seeder_spec.rb, spec/utils/user_utils_spec.rb
resolves #307 as much as is gonna happen for now
=> Add DataSeeder and UserUtils, use for wiping/seeding dev db

app/decorators/ephemera_box_decorator.rb, app/indexers/ephemera_box_indexer.rb, config/initializers/valkyrie.rb, spec/decorators/ephemera_box_decorator_spec.rb, spec/indexers/ephemera_box_indexer_spec.rb
=> Displaying and indexing EphemeraBox titles

app/change_sets/ephemera_box_change_set.rb, app/models/ephemera_box.rb, app/services/ingest_ephemera_service.rb, app/views/records/edit_fields/_received_date.html.erb, app/vocabs/pul_store.rb, spec/services/ingest_ephemera_service_spec.rb
=> Migrate additional box properties

app/indexers/collection_indexer.rb, spec/indexers/collection_indexer_spec.rb
=> Index ephemera boxes' collection for ephemera folders

app/change_sets/ephemera_folder_change_set.rb, app/decorators/ephemera_folder_decorator.rb, app/models/ephemera_folder.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/factories/ephemera_folder.rb, spec/models/ephemera_folder_spec.rb
=> Add provenance attribute to ephemera folders, refs #374

app/services/plum_importer.rb, spec/fixtures/files/plum/ps7529f137.json, spec/services/plum_importer_spec.rb
=> Import viewing hint/direction

app/decorators/ephemera_field_decorator.rb, app/models/controlled_vocabulary.rb, app/models/ephemera_field.rb
=> Adding code documentation for ControlledVocabulary and EphemeraField

app/models/file_metadata.rb, app/services/file_appender.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Managing file timestamps

app/helpers/catalog_helper.rb, app/views/catalog/_resource_attributes_default.html.erb, spec/helpers/blacklight_helper_spec.rb
=> Handling RTL titles in header

spec/support/reset_auth.rb
=> Stubs the response to the external CAS endpoint

circle.yml
This has been triggering build failures on multiple pull requests.
=> Updates the Circle CI build environment to use Ruby release 2.3.4

app/services/manifest_builder.rb, spec/services/manifest_builder_spec.rb
=> Ensures that Collections properly generate IIIF Manifests

app/change_sets/boxless_ephemera_folder_change_set.rb, app/change_sets/ephemera_folder_change_set.rb, app/controllers/ephemera_folders_controller.rb, app/decorators/ephemera_folder_decorator.rb, app/decorators/ephemera_project_decorator.rb, app/decorators/valkyrie/resource_decorator.rb, app/views/catalog/_members_ephemera_box.html.erb, app/views/catalog/_members_ephemera_project.html.erb, app/views/catalog/_parent_breadcrumb_ephemera_folder.html.erb, config/routes.rb, spec/change_sets/boxless_ephemera_folder_change_set_spec.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/decorators/ephemera_project_decorator_spec.rb, spec/routing/ephemera_folder_routes_spec.rb, spec/support/shared/ephemera_folder_change_set_specs.rb, spec/views/catalog/_members_ephemera_box.html.erb_spec.rb, spec/views/catalog/_members_ephemera_project.html.erb_spec.rb
=> Allow adding folders directly to projects

app/indexers/facet_indexer.rb, spec/indexers/facet_indexer_spec.rb
=> Add non-imported subjects and languages to facet index

app/decorators/ephemera_folder_decorator.rb, app/indexers/facet_indexer.rb, spec/indexers/facet_indexer_spec.rb
Improves upon #416 by ensuring categories are indexed, and that larger
vocabularies are not.
=> Index subject categories in the subject facet

app/controllers/catalog_controller.rb, app/indexers/sorting_indexer.rb, config/initializers/valkyrie.rb, spec/controllers/catalog_controller_spec.rb
=> Adding basic sort options

app/models/concerns/linked_data/linked_node.rb, app/queries/find_project_folders.rb, app/services/manifest_builder.rb, config/initializers/valkyrie.rb, spec/controllers/ephemera_projects_controller_spec.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb, spec/services/manifest_builder_spec.rb
=> Project Manifests should show Folders as members.

app/services/ingest_ephemera_service.rb, spec/services/ingest_ephemera_service_spec.rb
=> Map states for ephemera migration

app/decorators/ephemera_folder_decorator.rb
This was functionality introduced in #424 that regressed in #412
=> Restore rendered_subject to eph folder decorator

app/decorators/collection_decorator.rb, spec/services/manifest_builder_spec.rb
=> Ensures that slugs are also exposed for Collections

app/decorators/ephemera_box_decorator.rb, app/views/catalog/_members_ephemera_project.html.erb, spec/decorators/ephemera_box_decorator_spec.rb, spec/views/catalog/_members_ephemera_project.html.erb_spec.rb
=> Displaying more info about boxes on the ephemera project show page

app/views/ephemera_vocabularies/new.html.erb, spec/controllers/ephemera_vocabularies_controller_spec.rb, spec/features/ephemera_vocabularies_spec.rb
=> Displaying 'New Category' header when adding a sub-vocab

app/services/plum_derivative_mover.rb, config/initializers/valkyrie.rb, spec/services/plum_derivative_mover_spec.rb
=> Link derivatives intead of copying them

.rubocop.yml, app/models/concerns/linked_data/linked_date_range.rb, app/models/concerns/linked_data/linked_ephemera_folder.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb
=> Expose date ranges in JSON-LD.

.rubocop.yml, app/models/concerns/linked_data/linked_collection.rb, app/models/concerns/linked_data/linked_date_range.rb, app/models/concerns/linked_data/linked_ephemera_folder.rb, app/models/concerns/linked_data/linked_ephemera_term.rb, app/models/concerns/linked_data/linked_ephemera_vocabulary.rb, app/models/concerns/linked_data/linked_imported_resource.rb, app/models/concerns/linked_data/linked_resource.rb, app/models/concerns/linked_data/linked_resource_factory.rb, app/models/concerns/linked_data/linked_vocabulary_base.rb, spec/controllers/catalog_controller_spec.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb, spec/models/linked_data/linked_ephemera_term_spec.rb, spec/models/linked_data/linked_ephemera_vocabulary_spec.rb, spec/rails_helper.rb, spec/shared_specs.rb, spec/shared_specs/linked_data.rb
=> Refactors and implements shared specs for LinkedData::Resources

app/utils/data_seeder.rb
Thought I'd already submitted this but it was sitting around in my working directory
=> Seed subject and language for ephemera folder

db/migrate/20171025174720_create_path_gin_index.valkyrie_engine.rb, db/schema.rb
Forgot to run this when we updated Valkyrie. Creates a new index which
significantly speeds up queries.
=> Add missing migration.

app/controllers/reports_controller.rb, app/models/report.rb, app/queries/find_identifiers_to_reconcile.rb, app/views/catalog/_home_text.html.erb, app/views/catalog/_report_home.html.erb, app/views/reports/identifiers_to_reconcile.html.erb, config/initializers/valkyrie.rb, config/routes.rb, spec/controllers/reports_controller_spec.rb, spec/models/report_spec.rb, spec/queries/find_identifiers_to_reconcile_spec.rb
=> Report for records with ARKs not present in Voyager metadata

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/delete_members.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Implements a `DeleteMembers` handler for removing Multi-Volume Works in the `PlumChangeSetPersister`

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
=> Enables the indexing the barcode property for EphemeraBoxes and EphemeraFolders

.rubocop.yml, app/services/bulk_ingest_service.rb, spec/jobs/ingest_lae_folder_job_spec.rb
=> LAE Hard Drive Import names FileSets.

app/change_sets/ephemera_folder_change_set.rb
* Displaying rights statement last on ephemera folder new/edit form
* Changing default rights statement to Copyright Not Evaluated
Fixes #491
=> Rights statement form improvements for ephemera

app/controllers/ephemera_folders_controller.rb, app/views/catalog/_admin_controls_ephemera_folder.html.erb, spec/views/catalog/_admin_controls_ephemera_folder.html.erb_spec.rb
* Add flash notice when using "Save and Create Another"
* Add button to create another folder from folder show page
Fixes #492
=> Folder creation improvements

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/delete_members.rb, app/change_set_persisters/plum_change_set_persister/delete_referenced.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Deletes member resources for Collections, FileSets and general Resources

app/views/catalog/_members_ephemera_box.html.erb, app/views/catalog/_members_ephemera_project.html.erb, spec/views/catalog/_members_ephemera_box.html.erb_spec.rb
=> Ensures that the "Delete" buttons are not rendered within Ephemera Project show templates

app/controllers/ephemera_folders_controller.rb, spec/controllers/ephemera_folders_controller_spec.rb, valhalla/app/controllers/concerns/valhalla/resource_controller.rb
=> Fixing 'Save and Create Another' after update

spec/features/ephemera_folder_spec.rb, spec/support/capybara_selenium.rb
=> Extending the EphemeraFolder feature tests for saving and creating subsequent folders

app/change_sets/ephemera_project_change_set.rb, app/controllers/ephemera_folders_controller.rb, app/controllers/templates_controller.rb, app/decorators/ephemera_project_decorator.rb, app/helpers/edit_field_helper.rb, app/models/ephemera_project.rb, app/views/catalog/_members_ephemera_project.html.erb, app/views/records/edit_fields/_genre.html.erb, app/views/records/edit_fields/_geo_subject.html.erb, app/views/records/edit_fields/_geographic_origin.html.erb, app/views/records/edit_fields/_language.html.erb, app/views/records/edit_fields/_subject.html.erb, app/views/records/edit_fields/_top_language.html.erb, spec/change_sets/ephemera_project_change_set_spec.rb, spec/controllers/ephemera_projects_controller_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/decorators/ephemera_project_decorator_spec.rb, spec/helpers/edit_field_helper_spec.rb, spec/models/ephemera_project_spec.rb
=> Add top_language property to ephemera projects

app/controllers/ephemera_folders_controller.rb, spec/features/ephemera_vocabularies_spec.rb
=> Fixing controlled vocabularies for boxless folders

app/jobs/recharacterize_job.rb, lib/tasks/import.rake, spec/jobs/recharacterize_job_spec.rb
=> Add rake task and background job to re-run characterization

db/migrate/20171107160259_email_not_unique.rb, db/schema.rb, spec/controllers/catalog_controller_spec.rb
=> Removing unique constraint on user email field

app/assets/javascripts/figgy_boot.es6, app/assets/javascripts/form/detect_duplicates.es6, app/views/records/edit_fields/_barcode.html.erb, app/views/records/edit_fields/_source_metadata_identifier.html.erb, spec/features/ephemera_box_spec.rb, spec/features/ephemera_folder_spec.rb, spec/features/scanned_resource_spec.rb
=> Introduces JavaScript form functionality for warning users of duplicate source_metadata_identifiers and barcodes

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/characterize.rb, app/jobs/characterization_job.rb, app/jobs/ingest_ephemera_job.rb, app/jobs/ingest_folder_job.rb, app/jobs/ingest_folders_job.rb, app/jobs/ingest_lae_folder_job.rb, app/jobs/ingest_map_folder_job.rb, app/jobs/ingest_mets_job.rb, app/jobs/plum_importer_job.rb, lib/tasks/bulk.rake, lib/tasks/import.rake, lib/tasks/lae.rake, spec/change_set_persisters/plum_change_set_persister_spec.rb
=> Bulk jobs use low-priority queue

.gitignore, config/blacklight.yml, config/config.yml
also updates .gitignore - no need to check in packs and node modules
=> fixes failing tests when not using solr wrapper... 

app/characterization_services/imagemagick_characterization_service.rb, app/characterization_services/plum_characterization_service.rb, spec/characterization_services/imagemagick_characterization_service_spec.rb, spec/support/stub_tika.rb
=> Use ImageMagick to characterize.

app/services/manifest_builder/thumbnail_builder.rb, spec/services/manifest_builder_spec.rb
=> Manifest works even with bad thumbnail_id

app/models/ability.rb, spec/models/ability_spec.rb
=> Let image editors edit ephemera folders.

app/change_sets/ephemera_folder_change_set.rb, app/change_sets/scanned_resource_change_set.rb, app/change_sets/vector_work_change_set.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/controllers/vector_works_controller_spec.rb, valhalla/app/controllers/concerns/valhalla/resource_controller.rb
=> Setting depositor when a user uploads a work

app/models/ingestable_file.rb
=> Add comments to IngestableFile.

app/jobs/clean_dead_queues_job.rb, app/jobs/clean_guest_users_job.rb, app/jobs/clean_searches_job.rb, lib/tasks/clean.rake, spec/jobs/clean_dead_queues_job_spec.rb, spec/jobs/clean_guest_users_job_spec.rb, spec/jobs/clean_searches_job_spec.rb
Resolves #576 by introducing jobs for cleaning dead Sidekiq Queues, old guest user accounts, and old Blacklight searches
=> Implements Sidekiq jobs for cleaning dead queues, deleting old guest users, and old searches

spec/features/ephemera_folder_spec.rb
=> Attempts to circumvent the race condition within Ephemera Folders Feature test suite

app/controllers/catalog_controller.rb, app/decorators/valkyrie/resource_decorator.rb, app/document_presenters/figgy_index_presenter.rb, app/document_presenters/valkyrie_show_presenter.rb, app/helpers/catalog_helper.rb, app/models/concerns/linked_data/linked_ephemera_folder.rb, app/views/catalog/_members_multi_volume_work.html.erb, app/views/catalog/_members_scanned_map.html.erb, app/views/catalog/_members_vector_work.html.erb, app/views/catalog/_parent_breadcrumb_default.html.erb, app/views/catalog/_parent_breadcrumb_ephemera_box.html.erb, app/views/catalog/_parent_breadcrumb_ephemera_folder.html.erb, app/views/catalog/_parent_breadcrumb_ephemera_term.html.erb, app/views/catalog/_parent_breadcrumb_ephemera_vocabulary.html.erb, app/views/scanned_maps/file_manager.html.erb, app/views/vector_works/file_manager.html.erb, spec/decorators/valkyrie/resource_decorator_spec.rb, spec/document_presenters/figgy_index_presenter_spec.rb, spec/helpers/blacklight_helper_spec.rb, spec/services/manifest_builder_spec.rb, valhalla/app/views/valhalla/base/file_manager.html.erb
=> Don't join multi-val titles with 'and'; don't show breadcrumb when no parents

Gemfile.lock, db/migrate/20171204142457_create_internal_resource_index.valkyrie_engine.rb, db/schema.rb
=> Update Valkyrie for orm_resources index.

app/queries/find_by_local_identifier.rb
=> Use find_by_string_property for speed in find_by_local_identifier.

app/change_set_persisters/plum_change_set_persister.rb, app/services/plum_importer.rb, spec/services/plum_importer_spec.rb, spec/support/with_queue_adapter.rb
=> Queue jobs for PlumImporter after transaction.

app/controllers/ephemera_folders_controller.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/features/ephemera_folder_spec.rb, valhalla/app/views/valhalla/base/_form_progress.html.erb
=> Fix Save and Duplicate Metadata Button

app/change_sets/concerns/visibility_property.rb, app/change_sets/ephemera_folder_change_set.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/controllers/scanned_maps_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/controllers/vector_works_controller_spec.rb
=> Visibility Open by default.

app/change_sets/ephemera_folder_change_set.rb, app/decorators/ephemera_folder_decorator.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/factories/ephemera_folder.rb, spec/features/ephemera_folder_spec.rb, spec/support/shared/ephemera_folder_change_set_specs.rb
=> Require a subject heading for Folders.

app/assets/javascripts/figgy_boot.es6, app/controllers/catalog_controller.rb
=> Fix facet more link.

app/decorators/scanned_resource_decorator.rb, spec/decorators/scanned_resource_decorator_spec.rb
=> Do not display raw imported metadata

app/views/records/edit_fields/_holding_location.html.erb, app/views/records/edit_fields/_member_of_collection_ids.html.erb
=> Sorting collections and holding locations by title

app/change_sets/ephemera_folder_change_set.rb, app/controllers/ephemera_folders_controller.rb, spec/controllers/ephemera_folders_controller_spec.rb
=> Fix saving Ephemera Folders.

config/environments/test.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/file_sets_controller_spec.rb, spec/controllers/scanned_maps_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/derivative_services/scanned_map_derivative_service_spec.rb, spec/jobs/ingest_mets_job_spec.rb, spec/services/geo_metadata_extractor_spec.rb, spec/services/manifest_builder/cantaloupe_helper_spec.rb, spec/services/manifest_builder_spec.rb, spec/services/pdf_generator_spec.rb, spec/services/plum_importer_spec.rb, spec/services/riiif_resolver_spec.rb, spec/views/catalog/_resource_attributes_default.html.erb_spec.rb
Speeds up the test suite a bit.
=> Only run jobs if necessary.

app/change_set_persisters/plum_change_set_persister.rb, app/change_set_persisters/plum_change_set_persister/reindex_children_on_state.rb, app/indexers/ephemera_folder_indexer.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/controllers/catalog_controller_spec.rb
=> Change LAE Visibility Algorithm

app/services/manifest_builder/manifest_service_locator.rb, app/services/manifest_builder/sequence_builder.rb, spec/services/manifest_builder_spec.rb
=> Add viewing hint to Sequence.

Gemfile, Gemfile.lock
See https://github.com/samvera-labs/valkyrie/pull/346
=> Updating Gemfile to avoid incompatibility with pg 1.0.0

app/controllers/application_controller.rb, app/controllers/base_resource_controller.rb, app/controllers/ephemera_fields_controller.rb, app/controllers/ephemera_terms_controller.rb, app/controllers/ephemera_vocabularies_controller.rb, spec/controllers/catalog_controller_spec.rb
Fixes https://github.com/pulibrary/figgy/issues/740
=> Rescue from all access-denied errors to avoid generic 'something went wrong' errors for users

app/assets/stylesheets/components/browse_everything.scss, valhalla/app/javascript/components/Thumbnails.vue, valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js, valhalla/app/javascript/test/unit/specs/__snapshots__/Thumbnails.spec.js.snap
I think I just need to style this "pending uploads" dropdown a little better, but would like some feedback/objections.
=> Ready for merge - Issue 580

app/controllers/scanned_resources_controller.rb, config/routes.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/routing/scanned_resource_routes_spec.rb
=> Add redirects for old manifest URLs

app/services/manifest_builder.rb, app/services/manifest_builder/canvas_builder.rb, app/services/manifest_builder/manifest_service_locator.rb, spec/services/manifest_builder_spec.rb
=> Add old FileSet IDs to Canvases

app/utils/data_seeder.rb
=> Check for the derivative path before deleting it to avoid error

.rubocop.yml, app/models/concerns/linked_data/linked_ephemera_folder.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb
=> Ensures that the "series" attribute for EphemeraFolder Objects is exposed as linked data

app/characterization_services/tika_file_characterization_service.rb, app/decorators/file_set_decorator.rb, app/models/file_metadata.rb, app/models/file_set.rb, spec/characterization_services/tika_file_characterization_service_spec.rb
=> Add more tika file characterization attributes

app/decorators/valkyrie/resource_decorator.rb, spec/services/manifest_builder_spec.rb
=> Extends `ResourceDecorator::MetadataObject` in order to build IIIF Manifests using linked data terms

app/services/plum_importer.rb, spec/services/plum_importer_spec.rb
=> Ensures that failures to extract the thumbnail ID from the imported Plum Solr Document are logged and handled

.rubocop.yml, app/change_sets/scanned_map_change_set.rb, app/decorators/scanned_map_decorator.rb, app/models/scanned_map.rb, spec/decorators/scanned_map_decorator_spec.rb
=> Add relation and references properties to scanned maps

app/services/bulk_ingest_service.rb, spec/services/bulk_ingest_service_spec.rb
=> Ordering bulk-ingested child directories

lib/tasks/bulk.rake, spec/jobs/ingest_folder_job_spec.rb
* Works around problem passing objects instead of strings
Fixes #769
=> Passing collection membership using member_of_collection_ids

public/uv_config.json
=> Ensures that the "Index" tab is expanded within the UniversalViewer

app/controllers/scanned_resources_controller.rb, app/services/bulk_ingest_service.rb, app/services/ingest_folder_locator.rb, config/browse_everything_providers.yml, spec/controllers/scanned_resources_controller_spec.rb, spec/services/bulk_ingest_service_spec.rb
=> Ensures that `BulkIngestService#attach_dir` can only parse directory content using an absolute path

app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/fixtures/files/bibdata/6866386.jsonld
=> Don't apply remote identifier property to geo resources

app/controllers/reports_controller.rb, app/views/reports/identifiers_to_reconcile.html.erb, spec/controllers/reports_controller_spec.rb
=> Adding title to identifiers-to-reconcile report

README.md, config/blacklight.yml, config/config.yml, lib/tasks/dev.rake, solr/config/solrconfig.xml, spec/support/clean_solr.rb
=> Gives unique names to figgy solr cores

app/jobs/characterization_job.rb, app/jobs/create_derivatives_job.rb
Right now there's a race condition which we can't fix without optimistic
locking or by doing this.
=> Run Fixity after derivatives.

spec/services/cicognara_csv_spec.rb
Brings test coverage to a pleasing 💯 percent.
Closes #848
=> Test date method rescue value in cicognara_csv service

config/locales/en.yml
=> Change title at top to say Figgy

valhalla/app/javascript/components/ResourceForm.vue, valhalla/app/javascript/components/SidePanel.vue, valhalla/app/javascript/test/unit/specs/ResourceForm.spec.js, valhalla/app/javascript/test/unit/specs/__snapshots__/ResourceForm.spec.js.snap
=> Displays filecount in Filemanager

public/robots.txt
=> Updating robots.txt to ban all robot traffic

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/lograge.rb
Improves DataDog log collection.
=> Production Logging as JSON

app/helpers/fixity_dashboard_helper.rb, app/views/fixity_dashboard/_fixity_table.html.erb, spec/helpers/fixity_dashboard_helper_spec.rb
=> Handle nil value for fixity_last_success_date in fixity dashboard

app/helpers/fixity_dashboard_helper.rb, app/views/fixity_dashboard/_fixity_table.html.erb, spec/helpers/fixity_dashboard_helper_spec.rb
=> Add formatting for fixity success valule

Gemfile.lock, README.md, package-lock.json, package.json
Tested the file manager on staging a bit and it seems fine
fixes #881
Add a note to README about yarn vs. npm
Update webpacker from 3.2.0 to 3.3.1
Resolve ajv peer dependency by upgrading from 5.3.0 to 6.2.1
=> Update some npm packages

app/decorators/scanned_resource_decorator.rb, spec/views/scanned_resources/file_manager.html.erb_spec.rb, valhalla/app/views/valhalla/base/file_manager.html.erb
=> Add breadcrumb to MVWs.

app/derivative-services/raster_resource_derivative_service.rb, app/derivative-services/vector_work_derivative_service.rb, config/config.yml, config/initializers/valkyrie.rb, spec/derivative_services/raster_resource_derivative_service_spec.rb, spec/derivative_services/vector_work_derivative_service_spec.rb, spec/spec_helper.rb
=> Store vector and raster derivatives using geo_derivatives storage adapter

valhalla/app/javascript/app.vue, valhalla/app/javascript/components/ResourceForm.vue, valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js, valhalla/app/javascript/store/vuex/mutations.js, valhalla/app/javascript/store/vuex/state.js, valhalla/app/javascript/test/fixtures/manifest.js, valhalla/app/javascript/test/unit/specs/ResourceForm.spec.js, valhalla/app/javascript/test/unit/specs/__snapshots__/ResourceForm.spec.js.snap, valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
=> Adds BibId to Filemanager

app/helpers/osd_modal_helper.rb, app/helpers/thumbnail_helper.rb, spec/helpers/osd_modal_helper_spec.rb, spec/helpers/thumbnail_helper_spec.rb
=> Use path to thumbnail derivative for vector and raster work thumbnail display

app/change_sets/raster_resource_change_set.rb, app/change_sets/scanned_map_change_set.rb, app/change_sets/vector_work_change_set.rb, app/decorators/raster_resource_decorator.rb, app/decorators/scanned_map_decorator.rb, app/decorators/vector_work_decorator.rb, spec/decorators/raster_resource_decorator_spec.rb, spec/decorators/scanned_map_decorator_spec.rb, spec/decorators/vector_work_decorator_spec.rb
=> Add holding location to geo resources

.rubocop.yml, BROWSE_EVERYTHING.md, Gemfile, Gemfile.lock, README.md, app/controllers/base_resource_controller.rb, app/jobs/browse_everything_ingest_job.rb, app/models/pending_upload.rb, bin/ci_simple_tiles_install.sh, circle.yml, config/browse_everything_providers.yml
=> Integrates Google Drive support as a `browse-everything` provider

app/services/ingest_folder_locator.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Fix Save and Ingest.

valhalla/app/javascript/components/Controls.vue, valhalla/app/javascript/store/vuex/mutations.js, valhalla/app/javascript/test/unit/specs/__snapshots__/Controls.spec.js.snap
=> Fixes problem with Apply Changes (save) button in Vue Filemanager

Gemfile, Gemfile.lock
=> Update geo_work-derivatives for compatibility with GDAL version 2

app/services/manifest_builder/manifest_service_locator.rb, spec/services/manifest_builder_spec.rb
=> Adds thumbnails to manifest children of a MVW

app/change_sets/ephemera_folder_change_set.rb, spec/change_sets/ephemera_folder_change_set_spec.rb
=> Make series multi-valued for ephemera folders

.rubocop.yml, app/controllers/catalog_controller.rb, app/models/ephemera_folder.rb, spec/controllers/catalog_controller_spec.rb, spec/models/ephemera_folder_spec.rb
=> Extends the `EphemeraFolder` using the attribute `transliterated_title`

app/utils/data_seeder.rb, db/seeds.rb, spec/utils/data_seeder_spec.rb, test-compress.sh
=> Separate sammelband and mvw in data seeder

app/controllers/catalog_controller.rb, spec/features/bookmarks_spec.rb
=> Ensures that users can manage resources which they have bookmarked within search results

valhalla/app/javascript/components/Thumbnails.vue, valhalla/app/javascript/store/vuex/actions.js, valhalla/app/javascript/store/vuex/mutations.js, valhalla/app/javascript/store/vuex/state.js, valhalla/app/javascript/test/unit/specs/Thumbnails.spec.js, valhalla/app/javascript/test/unit/specs/__snapshots__/Thumbnails.spec.js.snap
=> Allows for simple cut and paste in Vue Filemanager

valhalla/app/javascript/components/Controls.vue, valhalla/app/javascript/components/FilesetForm.vue, valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js, valhalla/app/javascript/test/fixtures/mvw.js, valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
=> Allows user to set thumbnail for MVW

app/services/manifest_builder.rb, spec/services/manifest_builder_spec.rb
=> Fixes seeAlso links in manifests.

app/services/pdf_generator.rb, app/services/pdf_generator/canvas_downloader.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/requests/scanned_resource_spec.rb, spec/services/pdf_generator_spec.rb
=> Ensures that the aspect ratio for images in PDF documents is preserved

package-lock.json, package.json, valhalla/app/javascript/components/Controls.vue, valhalla/app/javascript/components/SidePanel.vue, valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js, valhalla/app/javascript/test/fixtures/image-collection.js, valhalla/app/javascript/test/unit/specs/Controls.spec.js, valhalla/app/javascript/test/unit/specs/__snapshots__/Controls.spec.js.snap, valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
=> Allows for enlarged/zoomable image viewing in Vue Filemanager

app/decorators/valkyrie/resource_decorator.rb, app/services/pdf_generator/canvas_downloader.rb, spec/decorators/valkyrie/resource_decorator_spec.rb
Discovered while attempting to resolve https://github.com/pulibrary/pomegranate/issues/336
=> Ensures that only Collection titles are featured within the IIIF Manifest metadata

Gemfile, Gemfile.lock
=> Updating `browse-everything` upstream

app/assets/stylesheets/components/catalog.scss, app/helpers/thumbnail_helper.rb, spec/helpers/thumbnail_helper_spec.rb
- Rescue exception where thumbnail file set is missing
- Set max width for document thumbnail so default thumbnail displays properly
Closes #987
=> Refactor geo thumbnail helper

app/models/user.rb, spec/models/user_spec.rb
=> Ensures user ID uniqueness

app/helpers/thumbnail_helper.rb
=> Fixes issue with nil geo thumnail id value

app/services/geo_discovery/document_builder/layer_info_builder.rb, spec/services/geo_discovery/document_builder/layer_info_builder_spec.rb
=> Clean geometry values for geoblacklight document

.rubocop.yml, app/change_sets/simple_resource_change_set.rb, app/helpers/application_helper.rb, app/models/controlled_vocabulary.rb, app/views/catalog/_home_text.html.erb, spec/change_sets/simple_resource_change_set_spec.rb, spec/features/root_spec.rb
Required adding the workflow, which fixes #1031
=> Add SimpleResource to the home page (no icon yet)

valhalla/app/javascript/mixins/manifesto-filemanager-mixins.js, valhalla/app/javascript/test/fixtures/manifest.js, valhalla/app/javascript/test/unit/specs/manifesto-filemanager-mixins.spec.js
=> Fixes Vue Filemanager bug when dealing with blank labels

spec/indexers/ephemera_folder_indexer_spec.rb
Adds a test for use in future refactoring
=> Add test for ephemera folder indexer

app/models/workflow_registry.rb, config/initializers/workflows.rb, spec/models/workflow_registry_spec.rb
=> Add new class for workflow registry (not yet in use)

app/jobs/ingest_mets_job.rb, app/models/mets_document.rb, app/models/mets_document/factory.rb, spec/jobs/ingest_mets_job_spec.rb, spec/models/mets_document_spec.rb
=> Adding objects imported from METS to collections referenced in IsPartOf relation

app/decorators/simple_resource_decorator.rb, app/services/manifest_builder/logo_builder.rb, app/views/catalog/_members_simple_resource.html.erb, config/routes.rb
=> Fixes `SimpleResource` membership admin. controls and PUL logo links in Manifests

app/services/manifest_builder/thumbnail_builder.rb, spec/services/manifest_builder_spec.rb
=> Don't generate thumbnail without derivative.

app/helpers/application_helper.rb, config/routes.rb, spec/routing/simple_resource_routes_spec.rb
=> Ensures that the FileManager interface is offered for `SimpleResources`

app/models/search_builder.rb, spec/controllers/catalog_controller_spec.rb
Resolves #1040; a new indexer was not required
=> Add SimpleResource to discoverable classes in search_builder

app/change_sets/archival_media_collection_change_set.rb, app/controllers/archival_media_collections_controller.rb, app/views/catalog/_home_text.html.erb, app/views/shared/_add_content.html.erb, config/routes.rb, spec/controllers/archival_media_collections_controller_spec.rb, spec/features/root_spec.rb
resolves #1087
Currently linked to a form that renders Collection objects; that should
be addressed as part of #1006
=> Add controller, link to create Archival Media Collection

app/services/manifest_builder.rb, spec/services/manifest_builder_spec.rb
=> Filter raster children from scanned map manifests

app/utils/data_seeder.rb, spec/utils/data_seeder_spec.rb
- Adds additional geo resources to data seeder
- Re-organizes data seeder class for easier navigation of the code.
Closes #1110
=> Seed additional geo resources

valhalla/app/javascript/components/Controls.vue, valhalla/app/javascript/components/FilesetForm.vue, valhalla/app/javascript/test/unit/specs/__snapshots__/Controls.spec.js.snap
=> OpenSeadragon no longer breaks after Apply Changes

app/change_sets/raster_resource_change_set.rb, app/change_sets/scanned_map_change_set.rb, app/change_sets/vector_resource_change_set.rb, app/decorators/raster_resource_decorator.rb, app/decorators/scanned_map_decorator.rb, app/decorators/vector_resource_decorator.rb, spec/decorators/raster_resource_decorator_spec.rb, spec/decorators/scanned_map_decorator_spec.rb, spec/decorators/vector_resource_decorator_spec.rb, spec/features/scanned_map_spec.rb
=>  Add portion note to geo resources

app/decorators/geoblacklight_metadata_decorator.rb, spec/services/geo_discovery/document_builder_spec.rb
=> Don't merge imported identifier in geoblacklight metadata decorator

app/decorators/scanned_map_decorator.rb, spec/decorators/scanned_map_decorator_spec.rb
=> Add collections method to scanned map decorator

config/initializers/workflows.rb, spec/change_sets/media_resource_change_set_spec.rb
=> MediaResource uses draft publish workflow

app/decorators/archival_media_collection_decorator.rb, app/models/archival_media_collection.rb, spec/decorators/archival_media_collection_decorator_spec.rb
=> Display imported metadata on ArchivalMediaCollection

app/derivative-services/raster_resource_derivative_service.rb, app/derivative-services/vector_resource_derivative_service.rb
=> Correct geo derivative srid directive for vector and raster files

app/assets/javascripts/bounding_box_selector.js
- Makes bounding box easier to see.
Closes #1190
=> Change bounding box color from white to blue

app/models/controlled_vocabulary.rb, app/models/geo_workflow.rb, config/initializers/workflows.rb, spec/change_sets/raster_resource_change_set_spec.rb, spec/change_sets/scanned_map_change_set_spec.rb, spec/change_sets/vector_resource_change_set_spec.rb, spec/models/geo_workflow_spec.rb
Workflow just for geo.
Closes #1191
=> Add workflow for geo resources

app/decorators/raster_resource_decorator.rb, app/decorators/scanned_map_decorator.rb, app/decorators/vector_resource_decorator.rb, spec/decorators/raster_resource_decorator_spec.rb, spec/decorators/scanned_map_decorator_spec.rb, spec/decorators/vector_resource_decorator_spec.rb, spec/features/scanned_map_spec.rb
=> Display identifier as ark for geo resources

app/change_sets/ephemera_folder_change_set_base.rb, app/decorators/ephemera_folder_decorator.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb
=> Ensures that the property transliterated_title is exposed on forms for `EphemeraFolders`

app/services/geo_discovery/geoblacklight_document.rb, spec/services/geo_discovery/document_builder_spec.rb
Closes #1210 
Closes https://github.com/pulibrary/pulmap/issues/521
Closes https://github.com/pulibrary/pulmap/issues/522
=> Remove download and iiif refs from restricted scanned maps

app/change_sets/ephemera_folder_change_set_base.rb, app/decorators/ephemera_folder_decorator.rb, app/models/ephemera_folder.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/derivative_services/hocr_derivative_service_spec.rb
=> Extends the EphemeraFolder Model, Decorator, and ChangeSet for generating OCR from member Files

app/change_set_persisters/plum_change_set_persister/apply_remote_metadata.rb, spec/change_set_persisters/plum_change_set_persister_spec.rb, spec/services/identifier_service_spec.rb
Fixes #1180 
Alternative to #1206
=> Copy imported identifiers to the resource to prevent minting duplicate ARKs

app/views/catalog/_members_archival_media_collection.html.erb
=> Display members on archival media collection show page

config/deploy/production.rb
Fixes https://github.com/pulibrary/figgy/issues/1223
=> Removing worker role from production webservers

.rubocop.yml, app/change_sets/ephemera_folder_change_set_base.rb, app/controllers/ephemera_folders_controller.rb, app/views/ephemera_folders/edit_fields/_append_id.html.erb, spec/controllers/ephemera_folders_controller_spec.rb, spec/features/ephemera_folder_spec.rb
=> Add 'Ephemera box' field to folder edit form, fixes #1143

app/jobs/characterization_job.rb, app/jobs/check_fixity_recursive_job.rb, app/jobs/create_derivatives_job.rb, spec/controllers/archival_media_collections_controller_spec.rb, spec/jobs/check_fixity_recursive_job_spec.rb, spec/jobs/create_derivatives_job_spec.rb
=> Refactoring around enqueued jobs in specs

app/services/manifest_builder/canvas_rendering_builder.rb, spec/services/manifest_builder_spec.rb
=> Extending the `ManifestBuilder::CanvasRenderingBuilder` in order to insert links to original files for download

app/services/manifest_builder/canvas_rendering_builder.rb, spec/services/manifest_builder_spec.rb
Fix build broken when a PR from before the rule change was merged
=> Change quotes to doubles

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/check_fixity.rb, app/change_set_persisters/change_set_persister/update_ocr.rb
=> Removing the unnecessary post_save_resource param from `ChangeSetPersister#after_update_commit`

spec/features/order_manager_spec.rb, valhalla/app/javascript/components/Thumbnails.vue, valhalla/app/javascript/test/unit/specs/__snapshots__/Thumbnails.spec.js.snap, valhalla/app/views/valhalla/base/order_manager.html.erb
=> Removes awkward File Upload feature from Order Manager

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/sync_resource.rb, app/controllers/base_resource_controller.rb, app/controllers/file_sets_controller.rb, app/controllers/scanned_resources_controller.rb, app/controllers/simple_resources_controller.rb, app/derivative-services/hocr_derivative_service.rb, app/jobs/ingest_archival_media_bag_job.rb, app/jobs/ingest_geoportal_record_job.rb, app/jobs/ingest_mets_job.rb, app/services/bulk_ingest_service.rb, app/services/folder_json_importer.rb, app/services/ingest_ephemera_service.rb, app/services/update_state.rb, app/utils/data_seeder.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/controllers/archival_media_collections_controller_spec.rb, spec/controllers/reports_controller_spec.rb, spec/features/ephemera_box_spec.rb, spec/features/scanned_map_spec.rb, spec/features/scanned_resource_spec.rb, spec/features/simple_resource_spec.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb, spec/queries/find_identifiers_to_reconcile_spec.rb, spec/services/geo_discovery/document_builder_spec.rb, spec/services/identifier_service_spec.rb, spec/services/manifest_builder_spec.rb
=> Sync change set with model before saving

app/models/ability.rb, app/models/scanned_resource.rb, app/models/user.rb, lib/tasks/migrate.rake, spec/controllers/auth_tokens_controller_spec.rb, spec/controllers/templates_controller_spec.rb, spec/factories/user.rb, spec/features/scanned_resource_spec.rb, spec/fixtures/files/plum/p3b593k91p.json, spec/fixtures/files/plum/ppc28d195m.json, spec/fixtures/files/plum/ps7529f137-broken.json, spec/fixtures/files/plum/ps7529f137.json, spec/fixtures/files/plum/pz029rp965.json, spec/models/ability_spec.rb, spec/models/user_spec.rb, spec/views/catalog/_home_text.html.erb_spec.rb
=> Simplify ability/permissions by replacing a bunch of roles with 'staff'

app/models/file_metadata.rb, app/models/file_set.rb, app/views/catalog/_admin_controls_file_set.html.erb
=> Add intermediate and preservation files to file_set list view

app/models/concerns/linked_data/linked_ephemera_folder.rb, app/wayfinders/ephemera_folder_wayfinder.rb
I'm not sure why this spec fails sometimes without this - it seems
almost like it's a race condition happening inside rspec, which makes no
sense to me.
=> Fix intermittently failing spec.

app/controllers/archival_media_collections_controller.rb, spec/controllers/archival_media_collections_controller_spec.rb
=> Add access controls to ark_report

app/validators/source_metadata_identifier_validator.rb, spec/change_sets/archival_media_collection_change_set_spec.rb
=> Add validation that source_metadata_identifier was an actual ID

Gemfile.lock
=> Update pul_metadata_services to get more fields on pulfa collection

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/bulk_ingest.scss, app/controllers/bulk_ingest_controller.rb, app/jobs/ingest_folder_job.rb, app/jobs/ingest_folders_job.rb, app/services/file_appender.rb, app/values/browse_everything_file_paths.rb, app/views/bulk_ingest/_mvw.html.erb, app/views/bulk_ingest/_visibility.html.erb, app/views/bulk_ingest/_workflow_state.html.erb, app/views/bulk_ingest/show.html.erb, app/views/catalog/_home_text.html.erb, app/views/catalog/_work_types.html.erb, config/routes.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/controllers/bulk_ingest_controller_spec.rb, spec/jobs/ingest_folder_job_spec.rb, spec/values/browse_everything_file_paths_spec.rb, spec/views/catalog/_home_text.html.erb_spec.rb
- Adds bulk ingest controller and views
- Modifies file appender so attached external metadata XML files don't get set as thumbnail
Closes #1273
=> Bulk ingest

app/controllers/base_resource_controller.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Fix error from empty files from Browse Everything

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb, app/change_sets/change_set.rb, app/change_sets/ephemera_box_change_set.rb, app/models/base_workflow.rb, app/models/book_workflow.rb, app/models/box_workflow.rb, app/models/draft_publish_workflow.rb, app/models/folder_workflow.rb, app/models/geo_workflow.rb, spec/change_set_persisters/change_set_persister/propagate_visibility_and_state_spec.rb, spec/change_sets/ephemera_box_change_set_spec.rb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/models/base_workflow_spec.rb
=> Integrating support for propagating state to member resources within `ChangeSetPersister::PropagateVisibilityAndState`

spec/change_set_persisters/change_set_persister_spec.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Stubs the Logger in order to suppress Bagit errors while executing tests

app/change_sets/raster_resource_change_set.rb, app/change_sets/vector_resource_change_set.rb, app/controllers/raster_resources_controller.rb, app/controllers/vector_resources_controller.rb, app/decorators/raster_resource_decorator.rb, app/decorators/scanned_map_decorator.rb, app/decorators/vector_resource_decorator.rb, app/views/catalog/_admin_controls_raster_resource.html.erb, app/views/catalog/_admin_controls_vector_resource.html.erb, app/views/records/edit_fields/_thumbnail_id.html.erb, spec/controllers/raster_resources_controller_spec.rb, spec/controllers/vector_resources_controller_spec.rb, spec/decorators/raster_resource_decorator_spec.rb, spec/decorators/scanned_map_decorator_spec.rb, spec/decorators/vector_resource_decorator_spec.rb
=>  Allow users to choose vector and raster resource thumbnails

app/adapters/instrumented_adapter.rb, config/initializers/valkyrie.rb
=> Documenting the storage adapter integration from Valkyrie

app/views/catalog/_members_archival_media_collection.html.erb, app/views/catalog/_members_collection.html.erb, spec/features/archival_media_collection_spec.rb, spec/features/collections_spec.rb
=> Updates active sort fields in a collection based on the current document

app/controllers/ephemera_folders_controller.rb, spec/controllers/ephemera_folders_controller_spec.rb
=> Redirect to parent instead of box after ephemera folder completion

app/decorators/ephemera_folder_decorator.rb, spec/decorators/ephemera_folder_decorator_spec.rb
=> Ensures that EphemeraFolderDecorator#rendered_ocr_language handles invalid language codes

README.md, app/views/base/_form_metadata.html.erb, spec/features/scanned_resource_spec.rb
=> Removing file uploads for resource edit forms

app/controllers/bulk_ingest_controller.rb, app/views/bulk_ingest/_collections.html.erb, app/views/bulk_ingest/_mvw.html.erb, app/views/bulk_ingest/_visibility.html.erb, app/views/bulk_ingest/_workflow_state.html.erb, app/views/bulk_ingest/show.html.erb, spec/controllers/bulk_ingest_controller_spec.rb
=> Allow users to select collections when during bulk ingest

app/models/file_set.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Update FileSet#mime_type to check preservation_file if there's no original_file

.rubocop.yml, app/services/pdf_generator.rb, app/services/pdf_generator/canvas_downloader.rb, spec/services/pdf_generator_spec.rb
=> Handling and logging errors encountered when attempting to download PDFs in `PDFGenerator#render`

.rubocop.yml, Gemfile, Gemfile.lock, app/characterization_services/imagemagick_characterization_service.rb, app/services/file_appender.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Restructuring FileAppender in order to raise exceptions when a file cannot be created or updated

app/characterization_services/default_characterization_service.rb, app/characterization_services/imagemagick_characterization_service.rb, app/characterization_services/tika_file_characterization_service.rb, app/models/raster_resource.rb, app/models/resource.rb, app/models/scanned_map.rb, app/models/scanned_resource.rb, app/models/simple_resource.rb, app/models/vector_resource.rb, config/config.yml, config/initializers/valkyrie.rb, spec/characterization_services/default_characterization_service_spec.rb, spec/characterization_services/tika_file_characterization_service_spec.rb
Resolves #1379 but is blocked by the merging of #1368
=> Uses TikaFileCharacterizationService as the default for characterization

app/jobs/ingest_archival_media_bag_job.rb, app/models/archival_media_bag_parser.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb, spec/models/archival_media_bag_parser_spec.rb
=> Implementing IngestArchivalMediaBagJob#add_thumbnail and IngestArchivalMediaBagJob#create_image_file_set for ingesting JPEGs in AV bags

.rubocop.yml, app/services/geo_resource_reindexer.rb, spec/services/geo_resource_reindexer_spec.rb
Service for reindexing GeoBlacklight, GeoServer, and OpenGeoMetadata.
Closes #1385
=> Add reindexing service for geo resources

package-lock.json, package.json
=> Pins to earlier manifesto version so thumbs now show in Order Manager

app/change_sets/archival_media_collection_change_set.rb, app/jobs/ingest_archival_media_bag_job.rb, app/validators/unique_archival_media_barcode_validator.rb, spec/change_sets/archival_media_collection_change_set_spec.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Set visibility on archival media collection, propagate to members during ingest

app/services/geo_discovery/document_builder/basic_metadata_builder.rb, spec/services/geo_discovery/document_builder_spec.rb
=> Filter out non ISO 19115 topic categories in Vector and Raster GeoBlacklight documents

app/models/schema/common.rb, app/models/schema/geo.rb
Work towards pulibrary/pomegranate#360
Adds text_language, provenance, binding_note, and source_acquisiton.
=> Add additional metadata to schema.

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Propagate visibility, not just read_groups

app/jobs/ingest_archival_media_bag_job.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Fix visibility to read_group translation logic

app/decorators/media_resource_decorator.rb, app/wayfinders/media_resource_wayfinder.rb
=> Add collections to metadata display for media resource

app/services/geo_discovery/abstract_document.rb, app/services/geo_discovery/document_builder/basic_metadata_builder.rb, app/services/geo_discovery/geoblacklight_document.rb, spec/services/geo_discovery/document_builder_spec.rb
For display in Pulmap.
Closes #1443
=>  Add call number to GeoBlacklight document

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb, app/change_sets/file_set_change_set.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Propagate read_groups access to FileSets in change set persister

app/change_set_persisters/change_set_persister/append_to_parent.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb
=> Change append_id to remove from old parent if there was one

app/controllers/ephemera_folders_controller.rb, app/views/ephemera_folders/edit_fields/_append_id.html.erb, spec/controllers/ephemera_folders_controller_spec.rb
=> Add parent box to ephemera folder edit form

app/assets/javascripts/save_and_ingest_handler.es6
=> Encode periods when sending to the save and ingest handler

app/controllers/catalog_controller.rb, app/indexers/imported_metadata_indexer.rb, spec/controllers/catalog_controller_spec.rb, spec/indexers/imported_metadata_indexer_spec.rb
=> Add call number to index, search fields

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Ensure change set to propagate has :read_groups before calling

app/models/scanned_map.rb, config/routes.rb, spec/requests/scanned_map_spec.rb
=> Add pdf download route to scanned maps

app/decorators/valkyrie/resource_decorator.rb, app/mailers/application_mailer.rb, app/mailers/collections_mailer.rb, app/models/collection.rb, app/utils/data_seeder.rb, app/views/collections_mailer/owner_report.html.erb, config/environments/production.rb, config/environments/staging.rb, db/seeds.rb, lib/tasks/figgy.rake, spec/mailers/collections_mailer_spec.rb, spec/mailers/previews/collections_mailer_preview.rb, spec/utils/data_seeder_spec.rb
refs #1331; see the issue for the remaining steps necessary to close.
=> Add collections owner report mailer

config/schedule.rb
10am on Mondays
resolves #1331
tested on staging by adjusting and running the actual cron
=> Add send_collection_reports to crontab via whenever

Gemfile, Gemfile.lock, app/assets/javascripts/bounding_box_selector.es6, app/change_sets/scanned_map_change_set.rb, spec/features/scanned_map_spec.rb, vendor/assets/javascripts/leaflet-boundingbox.js
=> Improve bbox widget and re-add coverage to scanned map edit page

app/derivative-services/jp2_derivative_service.rb, spec/derivative_services/jp2_derivative_service_spec.rb
=> Generate tiff from jpeg, then build JP2

app/services/reindexer.rb, lib/tasks/reindex.rake, spec/services/reindexer_spec.rb
=> Adds a rake task to reindex without wiping.

app/javascript/mixins/manifesto-filemanager-mixins.js, app/javascript/test/fixtures/manifest.js
=> Fix accessing non-double ID in OM

app/change_sets/scanned_resource_change_set.rb
Done in response to a request from the Imaging Studio staff.
Resolves #1543
=> Move up collection select for Scanned Resources

app/change_sets/scanned_resource_change_set.rb, app/change_sets/simple_resource_change_set.rb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/shared_specs/change_sets/change_set.rb
=> Default PDF should be color.

lib/tasks/demo.rake
Useful for a/v demos
fixes #1406
=> Add rake task to delete collection and its members

app/services/event_generator/manifest_event_generator.rb, spec/services/event_generator/manifest_event_generator_spec.rb
=> Allow Geo resources to be synced to DPUL

public/uv.html, public/uv_config.json
* Fixes location of UV config file
* Addes `branchNodesSelectable` option for when UniversalViewer/universalviewer#606  is resolved
Fixes  #1470 
Refs #859
=> Update UV config

app/assets/javascripts/form/detect_duplicates.es6, app/assets/javascripts/save_and_ingest_handler.es6, config/routes.rb
=> Default to json and allow all characters to save_and_ingest

app/controllers/base_resource_controller.rb
=> Ensures that BaseResourceController#load_collections loads an empty Array if no Collections are found

app/jobs/ingest_mets_job.rb, spec/jobs/ingest_mets_job_spec.rb
=> Create collection in ingest mets job if it didn't exist yet

app/graphql/mutations/update_resource.rb, app/graphql/types/file_set_type.rb, app/graphql/types/resource.rb, app/graphql/types/scanned_resource_type.rb, app/graphql/types/thumbnail.rb, app/graphql/types/viewing_direction_enum.rb, spec/graphql/mutations/update_resource_spec.rb, spec/graphql/types/file_set_type_spec.rb, spec/graphql/types/resource_spec.rb, spec/graphql/types/scanned_resource_type_spec.rb, spec/graphql/types/thumbnail_spec.rb, spec/graphql/types/viewing_direction_enum_spec.rb
=> Add Viewing Direction/Thumbnails to GraphQL

lib/tasks/bulk.rake, spec/jobs/ingest_folder_job_spec.rb, spec/jobs/ingest_folders_job_spec.rb, spec/services/bulk_ingest_service_spec.rb
=> Providing the MODEL parameter for the bulk:ingest and bulk:attach_each_dir Rake tasks

app/services/geo_discovery/document_builder/basic_metadata_builder.rb, spec/controllers/scanned_maps_controller_spec.rb
=> Fix GeoBlacklight titles for imported scanned maps

app/models/ingestable_file.rb
=> Improve `copyable` documentation in IngestableFile

app/views/catalog/_admin_controls_simple_resource.html.erb, app/views/catalog/_members_simple_resource.html.erb, config/routes.rb, spec/controllers/simple_resources_controller_spec.rb, spec/shared_specs/controllers/base_resource_controller.rb
=> Remove "edit" functionality from SimpleResource

spec/features/archival_media_collection_spec.rb, spec/features/bookmarks_spec.rb, spec/features/collections_spec.rb, spec/features/ephemera_box_spec.rb, spec/features/ephemera_folder_spec.rb, spec/features/ephemera_terms_spec.rb, spec/features/ephemera_vocabularies_spec.rb, spec/features/file_manager_spec.rb, spec/features/file_set_spec.rb, spec/features/manage_users_spec.rb, spec/features/raster_resource_spec.rb, spec/features/root_spec.rb, spec/features/scanned_map_spec.rb, spec/features/scanned_resource_spec.rb, spec/features/simple_resource_spec.rb, spec/features/vector_resource_spec.rb, spec/support/capybara_selenium.rb
Locally this shaves off ~ 50 seconds from the test suite.
=> Move feature specs to JS-free when possible.

app/change_set_persisters/change_set_persister/mint_identifier.rb, app/jobs/ingest_geoportal_record_job.rb, spec/change_set_persisters/change_set_persister/mint_identifier_spec.rb
=> Only update Ezid when metadata has changed

app/characterization_services/null_characterization_service.rb, app/jobs/ingest_mets_job.rb, app/services/manifest_builder.rb, config/initializers/valkyrie.rb, package-lock.json, package.json, spec/characterization_services/null_characterization_service_spec.rb, spec/jobs/ingest_mets_job_spec.rb, spec/services/manifest_builder_spec.rb
=> Ingest mets file itself during mets ingest

app/services/identifier_service.rb, spec/services/identifier_service_spec.rb, spec/support/stub_ezid.rb
=> Throw an error if you try to overwrite a pulfa ARK

app/jobs/ingest_mets_job.rb, spec/fixtures/mets/pudl0001-4612596.mets, spec/jobs/ingest_mets_job_spec.rb, spec/models/mets_document_spec.rb
=> Assign ARK from METS on ingest.

lib/tasks/import.rake
capitalize only does the first letter
=> Use casecmp to match against "TRUE"

app/models/grouping.rb, spec/models/grouping_spec.rb
=> Add a Grouping Valkyrie::Resource with "elements" attribute

app/graphql/types/resource.rb, app/graphql/types/scanned_map_type.rb, spec/graphql/types/scanned_map_type_spec.rb
=> Add graphql ScannedMapType

app/decorators/scanned_map_decorator.rb, spec/decorators/scanned_map_decorator_spec.rb, spec/services/event_generator/manifest_event_generator_spec.rb
=> Add #collection_slugs to ScannedMapDecorator

app/services/manifest_builder.rb, app/utils/data_seeder.rb, spec/services/manifest_builder_spec.rb, spec/utils/data_seeder_spec.rb
=> Multi-volume map sets

app/controllers/scanned_resources_controller.rb, spec/features/simple_resource_spec.rb
=> Disable edit for SimpleResource.

.rubocop.yml, app/models/ark_with_title.rb, app/models/mets_document.rb, app/models/mets_document/mods_document.rb, spec/fixtures/mets/pudl0036-135-01.mets, spec/models/mets_document/mods_document_spec.rb
=> Extract MODS metadata for PUDL0036

app/models/mets_document.rb, app/models/mets_document/mods_document.rb, spec/fixtures/mets/pudl0017-wc064.mets, spec/models/mets_document/mods_document_spec.rb
Work towards #1702 
I think this adds the missing photographer field needed for #1588 too.
=> Add missing metadata for WA-WC064

app/change_sets/simple_resource_change_set.rb
Allows MODS import of photographers.
=> Add photographer to SimpleResourceChangeSet

app/models/mets_document/mods_document.rb, spec/fixtures/mets/pudl0017-wc064-s-s2687.mets, spec/models/mets_document_spec.rb
=> Fix PUDL0017 when there's no extra series info

app/change_sets/simple_resource_change_set.rb, app/characterization_services/mediainfo_characterization_service.rb, app/models/schema/common.rb, app/values/coverage_point.rb, spec/values/coverage_point_spec.rb
=> Add CoveragePoint resource in app/values

spec/change_set_persisters/change_set_persister_spec.rb
=> Small cleanups to change_set_persister_spec

app/models/mets_document.rb, app/models/mets_document/mods_document.rb, spec/fixtures/mets/pudl0038-mp090-0894.mets, spec/models/mets_document/mods_document_spec.rb, spec/models/mets_document_spec.rb
=> Mods subtitle, coverage_point to allow ingest of pudl0017

app/models/mets_document.rb, spec/fixtures/mets/pudl0100-lc-egx_0003-nolocation.mets, spec/models/mets_document_spec.rb
Fixes a bug which is preventing ingest of PUDL0100.
References #1612
=> Allow for blank holding location

app/graphql/types/query_type.rb, app/graphql/types/resource.rb, app/graphql/types/scanned_map_type.rb, app/graphql/types/scanned_resource_type.rb, spec/graphql/types/query_type_spec.rb, spec/graphql/types/scanned_map_type_spec.rb, spec/graphql/types/scanned_resource_type_spec.rb
=> Add GraphQL query for searching by BibID

app/models/ability.rb, spec/controllers/graphql_controller_spec.rb, spec/models/ability_spec.rb
=> Open up GraphQL to public

app/decorators/scanned_resource_decorator.rb, spec/decorators/scanned_resource_decorator_spec.rb
=> Validate that PDFs exist in decorator

.rubocop.yml, app/models/concerns/linked_data/linked_resource_factory.rb, app/models/concerns/linked_data/linked_simple_resource.rb, spec/controllers/catalog_controller_spec.rb
=> Display JSON-LD for simple resources.

app/models/concerns/linked_data/linked_simple_resource.rb, spec/controllers/catalog_controller_spec.rb
Necessary for DPUL syncing of Ivy Lee.
=> Support ArkWithTitle in PartOf

app/controllers/downloads_controller.rb, spec/controllers/downloads_controller_spec.rb
Allows downloading files with an auth token
=> Adding support for auth tokens to downloads controller

spec/mailers/collections_mailer_spec.rb
=> Split mailer test into smaller fixtures to reduce vulnerability to order

app/queries/memory_efficient_all_query.rb, app/services/reindexer.rb, spec/queries/memory_efficient_all_query_spec.rb, spec/services/reindexer_spec.rb
=> Don't reindex ProcessedEvent

app/models/search_builder.rb, spec/controllers/catalog_controller_spec.rb
=> Add Template to search builder blacklist

app/indexers/title_indexer.rb, app/models/grouping.rb, config/initializers/valkyrie.rb, spec/indexers/title_indexer_spec.rb, spec/models/grouping_spec.rb
Step 1 of 2 towards #1837
replaces #1843
=> Add figgy_title values to index

app/models/book_workflow.rb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/models/book_workflow_spec.rb, spec/validators/state_validator_spec.rb
=> Allow transition straight to complete in book workflow

app/change_sets/boxless_ephemera_folder_change_set.rb, app/change_sets/ephemera_box_change_set.rb, app/change_sets/ephemera_folder_change_set.rb, app/change_sets/ephemera_folder_change_set_base.rb, app/change_sets/media_resource_change_set.rb, app/change_sets/raster_resource_change_set.rb, app/change_sets/scanned_resource_change_set.rb, app/change_sets/simple_resource_change_set.rb, app/change_sets/vector_resource_change_set.rb, app/validators/rights_statement_validator.rb, spec/change_sets/boxless_ephemera_folder_change_set_spec.rb, spec/change_sets/ephemera_box_change_set_spec.rb, spec/change_sets/ephemera_folder_change_set_spec.rb, spec/change_sets/media_resource_change_set_spec.rb, spec/change_sets/raster_resource_change_set_spec.rb, spec/change_sets/scanned_resource_change_set_spec.rb, spec/change_sets/simple_resource_change_set_spec.rb, spec/change_sets/vector_resource_change_set_spec.rb, spec/controllers/ephemera_boxes_controller_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/controllers/raster_resources_controller_spec.rb, spec/controllers/scanned_maps_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/controllers/vector_resources_controller_spec.rb, spec/shared_specs/change_sets/change_set.rb, spec/shared_specs/controllers/base_resource_controller.rb, spec/validators/rights_statement_validator_spec.rb
=> Add rights statement validator and use in all relevant change sets

app/views/fixity_dashboard/_fixity_table.html.erb, spec/views/fixity_dashboard/_fixity_table.html.erb_spec.rb
=> Allow for orphaned file sets in fixity dashboard

app/controllers/catalog_controller.rb
Index ran successfully on prod on Friday.
This pr has been deployed to staging and searching / display tested briefly.
resolves #1837
=> Change catalog controller to use new figgy_title fields

app/decorators/archival_media_collection_decorator.rb, app/decorators/scanned_resource_decorator.rb, spec/decorators/archival_media_collection_decorator_spec.rb, spec/decorators/scanned_resource_decorator_spec.rb
=> Remove spaces in #created date range for consistency with vals in #date_created

.rubocop.yml, app/change_sets/media_resource_change_set.rb, app/decorators/media_resource_decorator.rb, app/jobs/ingest_archival_media_bag_job.rb, app/models/media_resource.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb, spec/models/media_resource_spec.rb
=> Add upload_set_id to MediaResource, use it during archival media ingest

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/reindex_collection_members.rb, app/indexers/collection_indexer.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Reindex resources when collection/project they belong to changes title

app/indexers/collection_indexer.rb, spec/indexers/collection_indexer_spec.rb
=> Index a resource's collection titles as text for better searching

Gemfile, Gemfile.lock, app/controllers/ephemera_boxes_controller.rb, app/controllers/ephemera_projects_controller.rb, app/decorators/ephemera_box_decorator.rb, app/decorators/ephemera_folder_decorator.rb, app/decorators/ephemera_project_decorator.rb, app/models/ephemera_folder.rb, app/models/folder_data_source.rb, app/models/resource.rb, app/queries/find_members_with_relationship.rb, app/wayfinders/ephemera_box_wayfinder.rb, app/wayfinders/ephemera_project_wayfinder.rb, config/environments/development.rb, config/initializers/valkyrie.rb, spec/controllers/ephemera_projects_controller_spec.rb, spec/queries/find_members_with_relationship_spec.rb
First attempt at solving N+1 queries in Figgy. Closes #1658.
Edit: It's still spending a bunch of time in Ruby code (maybe just the cost of converting to Valkyrie Resources?), not sure if it's worth merging.
=> Find folders with genres pre-loaded

app/jobs/update_fgdc_onlink_job.rb, app/services/fgdc_update_service.rb, spec/jobs/update_fgdc_onlink_job_spec.rb
=> Update file checksum in FgdcUpdateService

Gemfile, Gemfile.lock, app/adapters/indexing_adapter.rb, app/queries/count_members.rb, app/queries/file_sets_sorted_by_updated.rb, app/queries/find_by_string_property.rb, app/queries/find_ephemera_term_by_label.rb, app/queries/find_ephemera_vocabulary_by_label.rb, app/queries/find_fixity_failures.rb, app/queries/find_identifiers_to_reconcile.rb, app/queries/find_saved_ids.rb, app/queries/memory_efficient_all_query.rb, config/initializers/valkyrie.rb, spec/services/valkyrie1_migrator_spec.rb, spec/support/database_cleaner.rb
Mostly a proof of concept. This should roughly half access and conversion times for many of our objects.
=> Use Valkyrie-Sequel

app/views/catalog/_universal_viewer_default.html.erb, app/views/ephemera_folders/_form.html.erb, app/views/ephemera_folders/edit.html.erb, spec/controllers/ephemera_folders_controller_spec.rb
Closes #1935
I sent the screenshot and a tabbed option to our PO's for Ephemera to see which they prefer. This PR will change if they don't pick this one.
=> Render viewer on edit screen for Folders

Gemfile, Gemfile.lock
=> Update valkyrie to 1.2.1 from 1.2.0

app/decorators/ephemera_folder_decorator.rb, app/models/concerns/linked_data/linked_ephemera_folder.rb, spec/features/ephemera_folder_spec.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb, spec/services/manifest_builder_spec.rb
=> Provenance and series are displayed for ephemera folders and included in JSON-LD

app/assets/stylesheets/components/form.scss, app/views/base/_form.html.erb, app/views/templates/new.html.erb
=> Make resource save box sticky

app/controllers/scanned_resources_controller.rb, app/services/manifest_builder.rb, spec/controllers/scanned_resources_controller_spec.rb
=> Avoid querying for every thumbnail in Structure

app/assets/javascripts/figgy_boot.es6, app/change_sets/ephemera_field_change_set.rb, app/controllers/ephemera_folders_controller.rb, app/decorators/ephemera_field_decorator.rb, app/models/ephemera_field.rb, app/views/records/edit_fields/_favorite_term_ids.html.erb, app/wayfinders/ephemera_field_wayfinder.rb, config/locales/simple_form.en.yml, spec/controllers/ephemera_fields_controller_spec.rb, spec/controllers/ephemera_folders_controller_spec.rb, spec/wayfinders/wayfinder_spec.rb
=> Add Favorite Term support to EphemeraFields.

app/controllers/ephemera_folders_controller.rb, spec/features/ephemera_folder_spec.rb
=> Allow boxed folders to move between boxes.

app/assets/stylesheets/components/show.scss, app/helpers/application_helper.rb, app/views/catalog/_resource_attributes_default.html.erb, spec/helpers/application_helper_spec.rb
=> Add whitespace:pre-wrap CSS property to description list element

app/change_sets/ephemera_box_change_set.rb, app/models/ephemera_box.rb, spec/change_sets/ephemera_box_change_set_spec.rb, spec/controllers/collections_controller_spec.rb, spec/indexers/collection_indexer_spec.rb
=> Remove member_of_collection_ids from ephemerabox

app/services/geo_discovery/document_builder/iiif_builder.rb, spec/services/geo_discovery/document_builder/iiif_builder_spec.rb
=> Return a nil GBL document IIIF url when ObjectNotFoundError is raised

.rubocop.yml, Gemfile, Gemfile.lock, app/models/index_collection.rb, app/services/manifest_builder.rb, app/services/manifest_builder/canvas_builder_v3.rb, app/services/manifest_builder/manifest_service_locator.rb, app/services/manifest_builder/manifest_service_locator_v3.rb, app/services/manifest_builder/record_property_builder_v3.rb, spec/services/manifest_builder_spec.rb
=> Use iiif v3 for audio resources

app/controllers/catalog_controller.rb, solr/config/schema.xml, spec/features/catalog_spec.rb
=> Adds a solr.TextField for case insensitive text searches

.rubocop.yml, app/change_set_persisters/change_set_persister/mint_identifier.rb, app/change_sets/coin_change_set.rb, app/change_sets/numismatic_issue_change_set.rb, app/controllers/coins_controller.rb, app/controllers/numismatic_issues_controller.rb, app/decorators/coin_decorator.rb, app/decorators/numismatic_issue_decorator.rb, app/models/coin.rb, app/models/numismatic_issue.rb, app/wayfinders/coin_wayfinder.rb, app/wayfinders/numismatic_issue_wayfinder.rb, app/wayfinders/wayfinder.rb, config/routes.rb, spec/change_sets/coin_change_set_spec.rb, spec/change_sets/numismatic_issue_change_set_spec.rb, spec/controllers/coins_controller_spec.rb, spec/controllers/numismatic_issues_controller_spec.rb, spec/decorators/coin_decorator_spec.rb, spec/decorators/numismatic_issue_decorator_spec.rb, spec/factories/coin.rb, spec/factories/numismatic_issue.rb, spec/models/coin_spec.rb, spec/models/numismatic_issue_spec.rb
=> Adding models/change_sets/decorators for NumismaticIssue and Coin

app/change_sets/coin_change_set.rb, app/change_sets/numismatic_issue_change_set.rb, app/controllers/coins_controller.rb, app/controllers/numismatic_issues_controller.rb, app/decorators/numismatic_issue_decorator.rb, app/graphql/types/coin_type.rb, app/graphql/types/numismatic_issue_type.rb, app/graphql/types/resource.rb, app/indexers/member_of_indexer.rb, app/models/coin.rb, app/models/numismatic_issue.rb, app/views/catalog/_members_numismatic_issue.html.erb, app/wayfinders/coin_wayfinder.rb, app/wayfinders/numismatic_issue_wayfinder.rb, config/routes.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/coins_controller_spec.rb, spec/controllers/numismatic_issues_controller_spec.rb, spec/decorators/numismatic_issue_decorator_spec.rb, spec/factories/coin.rb, spec/factories/numismatic_issue.rb, spec/features/coins_spec.rb, spec/features/numismatic_issues_spec.rb, spec/graphql/types/coin_type_spec.rb, spec/graphql/types/numismatic_issue_type_spec.rb, spec/models/coin_spec.rb, spec/models/numismatic_issue_spec.rb, spec/wayfinders/wayfinder_spec.rb
=>  Adds basic forms for numismatic issues and coins

app/models/ability.rb, spec/models/ability_spec.rb
=> Don't lookup nil tokens

app/helpers/application_helper.rb, app/views/catalog/_home_text.html.erb
=> Adding Numismatics to home page and + menu, tweaking labels

spec/controllers/catalog_controller_spec.rb
=> Numismatic discovery

app/views/catalog/_members_numismatic_issue.html.erb, spec/features/numismatic_issues_spec.rb, spec/views/catalog/_members_numismatic_issue.html.erb_spec.rb
=> Allow coins to be attached and removed from numismatic issues

app/wayfinders/numismatic_issue_wayfinder.rb
=> Add parent relationship to numismatic issue wayfinder

app/change_sets/media_reserve_change_set.rb, spec/change_sets/media_reserve_change_set_spec.rb
Co-authored-by: Trey Pendragon <tpendragon@princeton.edu>
=> Adds media_reserve_change_set

app/assets/javascripts/relationships/related_resources_table.es6
Resolves reference error for Firefox. 
closes #2073
=> Resolves firefox referencerror

.rubocop.yml, app/change_sets/dynamic_change_set.rb, app/controllers/scanned_resources_controller.rb, config/routes.rb, spec/change_sets/dynamic_change_set_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/routing/media_reserve_resource_spec.rb
=> Enables ScannedResource form to use MediaReserves

app/change_sets/playlist_change_set.rb, app/decorators/playlist_decorator.rb, app/models/playlist.rb, spec/change_sets/playlist_change_set_spec.rb, spec/decorators/playlist_decorator_spec.rb, spec/factories/playlist.rb, spec/models/playlist_spec.rb
=> Add Playlist model, change set, decorator

.rubocop.yml, app/services/manifest_builder.rb, app/services/manifest_builder/canvas_builder_v3.rb, app/services/manifest_builder/manifest_service_locator_v3.rb, app/services/manifest_builder/record_property_builder_v3.rb, app/services/manifest_builder/structure_builder_v3.rb, spec/services/manifest_builder_spec.rb
Audio ranges should play and show labels for each track in the "Index"
portion.
=> Fix ranges for Audio

app/change_sets/proxy_file_change_set.rb, app/decorators/proxy_file_decorator.rb, app/models/proxy_file.rb, spec/change_sets/proxy_file_change_set_spec.rb, spec/decorators/proxy_file_decorator_spec.rb, spec/models/proxy_file_spec.rb
=> Add ProxyFile resource, change set, decorator

app/controllers/playlists_controller.rb, config/routes.rb, spec/controllers/playlists_controller_spec.rb
=> Add playlists controller

app/change_sets/media_reserve_change_set.rb
=> set visibility to private

app/decorators/playlist_decorator.rb, app/decorators/valkyrie/resource_decorator.rb, app/views/catalog/_admin_controls_default.html.erb, spec/decorators/coin_decorator_spec.rb, spec/decorators/ephemera_box_decorator_spec.rb, spec/decorators/ephemera_field_decorator_spec.rb, spec/decorators/ephemera_folder_decorator_spec.rb, spec/decorators/ephemera_project_decorator_spec.rb, spec/decorators/ephemera_term_decorator_spec.rb, spec/decorators/ephemera_vocabulary_decorator_spec.rb, spec/decorators/file_set_decorator_spec.rb, spec/decorators/playlist_decorator_spec.rb, spec/decorators/proxy_file_decorator_spec.rb
=> Split out `orderable_files?`

app/models/playlist.rb, spec/models/playlist_spec.rb
=> Use playlist label as its title for indexing purposes

app/views/shared/_add_works.html.erb, app/views/shared/_title_bar.html.erb, spec/features/root_spec.rb
=> 2045 button to create new media reserve (administrators)

app/change_sets/coin_change_set.rb, app/change_sets/numismatic_issue_change_set.rb, app/models/coin.rb, app/models/numismatic_issue.rb, app/queries/find_highest_value.rb, app/validators/auto_increment_validator.rb, config/initializers/valkyrie.rb, spec/change_sets/coin_change_set_spec.rb, spec/features/numismatic_issues_spec.rb, spec/graphql/types/coin_type_spec.rb, spec/graphql/types/numismatic_issue_type_spec.rb, spec/queries/find_highest_value_spec.rb
=> Adding coin/issue number management

app/views/catalog/_home_text.html.erb, app/views/catalog/_work_types_media_reserves.html.erb, spec/views/catalog/_home_text.html.erb_spec.rb
=> Adds a media reserve panel in the home page

app/queries/memory_efficient_all_query.rb, spec/queries/memory_efficient_all_query_spec.rb
This should resolve a hang in reindexing on prod which has been blocking reindex in service of #1782
=> Lazy map resources in MemoryEfficientAllQuery

app/change_sets/media_reserve_change_set.rb, app/javascript/components/document_adder.vue, app/javascript/packs/application.js, app/models/search_builder.rb, app/views/catalog/_admin_controls_playlist.html.erb, config/webpack/environment.js, package.json, spec/views/catalog/_admin_controls_playlist.html.erb_spec.rb
=> Add widget for adding Recordings to Playlists

app/change_sets/dynamic_change_set.rb, app/change_sets/recording_change_set.rb, app/controllers/playlists_controller.rb, app/controllers/scanned_resources_controller.rb, app/javascript/components/document_adder.vue, app/views/catalog/_admin_controls_recording.html.erb, app/views/catalog/_admin_controls_scanned_resource.html.erb, app/views/catalog/_work_types_media_reserves.html.erb, app/views/shared/_add_works.html.erb, config/routes.rb, spec/change_sets/dynamic_change_set_spec.rb, spec/change_sets/recording_change_set_spec.rb, spec/controllers/playlists_controller_spec.rb, spec/controllers/scanned_resources_controller_spec.rb, spec/factories/scanned_resource.rb, spec/features/root_spec.rb, spec/features/scanned_resource_spec.rb, spec/routing/media_reserve_resource_spec.rb, spec/routing/recording_resource_spec.rb, spec/services/manifest_builder_spec.rb, spec/views/catalog/_admin_controls_recording.html.erb_spec.rb, spec/views/catalog/_home_text.html.erb_spec.rb
=> Rename MediaReserve to Recording

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/create_proxy_file_sets.rb, app/change_sets/proxy_file_set_change_set.rb, app/decorators/proxy_file_set_decorator.rb, app/models/proxy_file_set.rb, app/models/search_builder.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/change_sets/proxy_file_set_change_set_spec.rb, spec/controllers/playlists_controller_spec.rb, spec/decorators/proxy_file_set_decorator_spec.rb, spec/models/proxy_file_set_spec.rb, spec/services/manifest_builder_spec.rb, spec/wayfinders/playlist_wayfinder_spec.rb
=> Rename ProxyFile to ProxyFileSet

app/graphql/types/playlist_type.rb, app/graphql/types/proxy_file_set_type.rb, app/graphql/types/resource.rb, app/wayfinders/playlist_wayfinder.rb, spec/factories/proxy_file_set.rb, spec/graphql/types/playlist_type_spec.rb, spec/graphql/types/proxy_file_set_type_spec.rb
=> Add GraphQL support for Playlists.

app/services/manifest_builder.rb, app/wayfinders/playlist_wayfinder.rb, spec/services/manifest_builder_spec.rb, spec/wayfinders/playlist_wayfinder_spec.rb
=> Playlists use ProxyFileSet labels for Canvases

app/controllers/downloads_controller.rb, spec/controllers/downloads_controller_spec.rb
=> Notify honeybadger and return 404 in downloadscontroller

public/viewer.html
This viewer will update the URL with settings for canvas and shouldn't
change locations even if the UV install method changes.
Closes #2037
=> Add non-embedded Viewer page.

.rubocop.yml, app/services/manifest_builder/record_property_builder_v3.rb, spec/services/manifest_builder_spec.rb
Co-authored-by:: Trey Pendragon <tpendragon@princeton.edu>
=> Disable download button in the v3 viewer

app/change_sets/playlist_change_set.rb, app/controllers/playlists_controller.rb, app/decorators/playlist_decorator.rb, app/graphql/types/playlist_type.rb, app/models/playlist.rb, app/services/manifest_builder.rb, spec/change_sets/playlist_change_set_spec.rb, spec/controllers/playlists_controller_spec.rb, spec/decorators/playlist_decorator_spec.rb, spec/factories/playlist.rb, spec/graphql/types/playlist_type_spec.rb, spec/models/playlist_spec.rb, spec/services/manifest_builder_spec.rb
=> Replaces labels with titles for Playlists

app/wayfinders/playlist_wayfinder.rb
=> Orders ProxyFileSets in the ManifestBuilder test suite to pass

app/indexers/member_of_indexer.rb, app/indexers/parent_issue_indexer.rb, config/initializers/valkyrie.rb, spec/controllers/catalog_controller_spec.rb
=> Indexing Coins' parent issue metadata, but not membership to make them discoverable

app/indexers/parent_issue_indexer.rb
=> Prefixing parent_issue_indexer fields

Gemfile.lock
=> Update Valkyrie-Sequel to fix Single Values

app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/numismatic_accessions/numismatic_accession.rb, app/resources/numismatic_accessions/numismatic_accession_change_set.rb, app/resources/numismatic_accessions/numismatic_accession_decorator.rb, app/resources/numismatic_accessions/numismatic_accessions_controller.rb, app/views/numismatic_accessions/index.html.erb, app/views/shared/_add_content.html.erb, config/routes.rb, spec/change_sets/numismatic_accession_change_set_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/controllers/numismatic_accessions_controller_spec.rb, spec/decorators/numismatic_accession_decorator_spec.rb, spec/factories/numismatic_accession.rb, spec/features/coins_spec.rb, spec/models/numismatic_accession_spec.rb
Fixes #2126
* Alternative to #2164 that doesn't depend on #2131
* Reorganizes files in new resources layout
=> Adding Numismatic Accessions

app/change_set_persisters/change_set_persister.rb, app/derivative-services/default_derivative_service.rb, spec/derivative_services/default_derivative_service_spec.rb
=> One transaction for DefaultDerivativeService

app/graphql/types/playlist_type.rb, spec/graphql/types/playlist_type_spec.rb
=> Add missing label to Playlist type.

app/resources/numismatic_finds/numismatic_find.rb, app/resources/numismatic_finds/numismatic_find_change_set.rb, app/resources/numismatic_finds/numismatic_find_decorator.rb, app/resources/numismatic_finds/numismatic_finds_controller.rb, app/views/numismatic_finds/index.html.erb, config/routes.rb, spec/factories/numismatic_find.rb, spec/resources/numismatic_find/numismatic_find_change_set_spec.rb, spec/resources/numismatic_find/numismatic_find_decorator_spec.rb, spec/resources/numismatic_find/numismatic_find_spec.rb, spec/resources/numismatic_find/numismatic_finds_controller_spec.rb
=> Adds numismatic_finds

app/resources/numismatic_accessions/numismatic_accession.rb
=> Remove member_ids from accessions

app/views/catalog/_admin_controls_default.html.erb, app/views/catalog/_admin_controls_ephemera_folder.html.erb, app/views/catalog/_attach_child_default.html.erb, app/views/catalog/_members_multi_volume_work.html.erb, app/views/catalog/_members_numismatic_issue.html.erb, app/views/catalog/_members_numismatic_reference.html.erb, spec/controllers/catalog_controller_spec.rb, spec/views/catalog/_admin_controls_default.html.erb_spec.rb
* Also, DRY up forms a bit
Fixes #2218
=> Don't show an 'Attach Child' menu unless there are multiple choices

app/controllers/base_resource_controller.rb, app/resources/scanned_resources/scanned_resource_decorator.rb, app/views/base/file_manager.html.erb, app/views/base/order_manager.html.erb, spec/resources/scanned_resource/scanned_resource_decorator_spec.rb
=> Updating File Manager to link to parents like Order Manager does

app/change_set_persisters/change_set_persister/create_proxy_file_sets.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> De-dup ProxyFileSets.

app/resources/numismatic_accessions/numismatic_accession.rb, app/resources/numismatic_accessions/numismatic_accession_change_set.rb, app/resources/numismatic_accessions/numismatic_accession_decorator.rb, app/resources/numismatic_accessions/numismatic_accession_wayfinder.rb, app/views/catalog/_members_coin.html.erb, app/views/catalog/_members_numismatic_accession.html.erb, app/views/catalog/_members_numismatic_issue.html.erb, app/wayfinders/wayfinder.rb, config/routes.rb, spec/resources/numismatic_accession/numismatic_accession_decorator_spec.rb, spec/resources/numismatic_citation/numismatic_citations_controller_spec.rb
=> Adding Citations to NumismaticAccessions

app/assets/javascripts/auto_ingest_handler.es6
- Fixes bug where coin discovery get request is made on every Figgy page load.
- Minor UI improvement: hides auto ingest button if no images are found.
Closes #2235
=> Only trigger coin auto ingest ajax call in coin file manager

app/javascript/components/playlist_members.vue, spec/features/playlist_spec.rb
This also introduces a feature test for this.  Resolves #2199
=> Changes Recordings for Tracks in the PlaylistMembers component header

app/resources/numismatic_accessions/numismatic_accession_change_set.rb
=> Remove number_in_accession from the accession change_set

app/helpers/application_helper.rb
Closes #2248
Looks like this was just the result of a rebase gone awry.
=> Fix coverage.

config/deploy/production.rb
probably best to not merge until we have confirmation that these boxes are off.
resolves #2270
=> Remove lib-proc2 and 3 as workers

lib/tasks/music_reserves.rake
=> Update rake music:report:bibids to accept a dbname env var

app/services/music_import_service/recording_collector.rb, spec/services/music_import_service_spec.rb
=> Extract cache to a class.

app/services/music_import_service.rb, spec/services/music_import_service_spec.rb
also remove related unused line in spec
=> Fix cache default in music import service initializer

.rubocop.yml, app/services/music_import_service/recording_collector.rb, spec/fixtures/music_import_service/recordings-extra-bibs-2018-12-06.csv, spec/fixtures/music_import_service/recordings-zero-bibs-2018-12-06.csv, spec/services/music_import_service/recording_collector_spec.rb
=> Lookup recording bibs on user-provided csv

app/services/bulk_ingest_service.rb, spec/services/bulk_ingest_service_spec.rb
=> Ignore Thumbs.db files during bulk ingest

app/characterization_services/mediainfo_characterization_service.rb, spec/characterization_services/mediainfo_characterization_service_spec.rb
=> Only set fileset title from embedded metadata; not file metadata label

app/models/ability.rb, app/resources/file_sets/file_set_decorator.rb, app/resources/playlists/playlists_controller.rb, app/services/manifest_builder.rb, spec/controllers/downloads_controller_spec.rb, spec/controllers/playlists_controller_spec.rb, spec/models/ability_spec.rb, spec/resources/file_set/file_set_decorator_spec.rb, spec/services/manifest_builder_spec.rb
=> Ensures that the authorization tokens are passed to the ManifestBuilder and inserted into FileSet URLs

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
=> Make authorized link point to viewer.

app/assets/javascripts/save_and_ingest_handler.es6
=> Pass change_set with javascript call to save_and_ingest

app/views/records/edit_fields/_owners.html.erb, spec/resources/collections/collections_feature_spec.rb
=> Allow selecting multiple collection owners, and sort them

app/helpers/bounding_box_helper.rb, spec/helpers/bounding_box_helper_spec.rb
=> Fix bounding box display on geo resource edit page

app/models/ability.rb, spec/models/ability_spec.rb
=> Ensuring that nil AuthTokens are handled properly (i. e. without triggering errors)

app/resources/scanned_resources/scanned_resource_decorator.rb, config/locales/en.yml, spec/indexers/human_readable_type_indexer_spec.rb
=> Add recording and simple resource to human_readable_type

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/extract_archival_collection_code.rb, app/resources/scanned_resources/scanned_resource.rb, lib/tasks/migrate.rake, spec/change_set_persisters/change_set_persister/extract_archival_collection_code_spec.rb, spec/change_set_persisters/change_set_persister_spec.rb
populate it from source_metadata_identifier
fixes #2339
=> Add archival_collection_code to scanned resource

.rubocop.yml, app/controllers/bulk_ingest_controller.rb, spec/controllers/bulk_ingest_controller_spec.rb
=> Extending BulkIngestController in order to handle the bulk creation of resources using files downloaded from a cloud storage provider

app/services/identifier_service.rb, spec/services/identifier_service_spec.rb
=> Link geo resource ARKs to Pulmap

app/queries/find_highest_value.rb, db/migrate/20190102173711_auto_increment_validator_index.rb, db/structure.sql
Should significantly improve performance of numismatics ingest in
Production.
=> Add indexes for HighestValue query.

app/javascript/components/OrderManagerFilesetForm.vue, app/javascript/test/resource.spec.js
=> [WIP] Ensures that the OrderManager handles thumbnails erroneously set to null values

spec/services/bulk_ingest_service_spec.rb
=> Update comment to reflect use case

app/decorators/valkyrie/resource_decorator.rb, app/services/manifest_builder.rb, spec/decorators/valkyrie/resource_decorator_spec.rb, spec/services/manifest_builder_spec.rb, spec/shared_specs/valkyrie/decorators/resource_decorator.rb
=> Removing unwanted metadata from IIIF manifest metadata hash

app/views/catalog/_admin_controls_file_set.html.erb, spec/views/catalog/_admin_controls_file_set.html.erb_spec.rb
=> Remove "update" form from file set page file listing

app/graphql/types/ephemera_folder_type.rb, app/graphql/types/resource.rb, app/resources/ephemera_folders/ephemera_folder_wayfinder.rb, app/views/catalog/_admin_controls_ephemera_folder.html.erb, spec/graphql/types/ephemera_folder_type_spec.rb, spec/views/catalog/_admin_controls_ephemera_folder.html.erb_spec.rb
=> Adding order manager support to Ephemera Folders

.circleci/config.yml, .eslintrc.js, app/javascript/components/OrderManager.vue, app/javascript/components/OrderManagerControls.vue, app/javascript/components/OrderManagerFilesetForm.vue, app/javascript/components/OrderManagerFilesetsForm.vue, app/javascript/components/OrderManagerResourceForm.vue, app/javascript/components/OrderManagerToolbar.vue, app/javascript/components/document_adder.vue, app/javascript/components/playlist_member.vue, app/javascript/components/playlist_members.vue, app/javascript/test/__snapshots__/orderManager.spec.js.snap, app/javascript/test/__snapshots__/orderManagerControls.spec.js.snap, app/javascript/test/__snapshots__/orderManagerFilesetForm.spec.js.snap, app/javascript/test/__snapshots__/orderManagerFilesetsForm.spec.js.snap, app/javascript/test/__snapshots__/orderManagerResourceForm.spec.js.snap, app/javascript/test/__snapshots__/orderManagerToolbar.spec.js.snap, app/javascript/test/orderManagerResourceForm.spec.js, app/javascript/test/setup.js, app/views/catalog/_admin_controls_playlist.html.erb, app/views/catalog/_members_playlist.html.erb, config/webpack/environment.js, package.json, spec/features/playlist_spec.rb, yarn.lock
This currently ignores our basic JS/ES6 files, but take care of all the Vue stuff which is actually hooked to webpacker.
Closes #2332
=> Add & Apply ESLint to Vue.js Files

app/resources/collections/collection_change_set.rb, app/resources/ephemera_projects/ephemera_project_change_set.rb, app/validators/unique_slug_validator.rb, spec/resources/collections/collection_change_set_spec.rb
=> Extract slug validation from EphemeraProjects and use for Collections

Gemfile, Gemfile.lock, app/characterization_services/imagemagick_characterization_service.rb, app/characterization_services/tika_file_characterization_service.rb, app/derivative_services/image_derivative_service.rb, app/indexers/parent_issue_indexer.rb, app/models/pending_upload.rb, app/resources/coins/coin.rb, app/resources/nested_resources/file_metadata.rb, app/resources/numismatic_accessions/numismatic_accession.rb, app/resources/numismatic_finds/numismatic_find.rb, app/resources/templates/template_change_set.rb
This is based on a branch, but this fixes all the deprecation notices for things which will be changed in 2.0.
=> Update to Valkyrie 1.3.0

app/helpers/application_helper.rb, spec/views/catalog/_resource_attributes_default.html.erb_spec.rb
=> Add link to Catalog for Source Identifier.

app/resources/scanned_maps/scanned_map_wayfinder.rb, app/resources/scanned_maps/scanned_maps_controller.rb, app/resources/scanned_resources/scanned_resources_controller.rb, spec/resources/scanned_map/scanned_maps_controller_spec.rb
=> Fix logical structure for scanned maps

.rubocop.yml, app/jobs/finding_aids_update_job.rb, app/services/finding_aids_updater.rb, config/schedule.rb, config/svn.yml, lib/tasks/figgy.rake, spec/services/finding_aids_updater_spec.rb
pending ansible requirements
fixes #2324
=> Add finding aids updater with rake tasks, cron and queuing

config/locales/simple_form.en.yml
=> Change label for template title to "Template Name"

app/controllers/application_controller.rb
=> Redirect the user back to the page they were on after logging in

.rubocop.yml, app/helpers/file_proxy_helper.rb, app/javascript/components/playlist_member.vue, app/views/catalog/_members_playlist.html.erb, config/webpacker.yml, spec/features/playlist_spec.rb, spec/helpers/file_proxy_helper_spec.rb
=> Add link back to recording on playlist members

app/resources/scanned_resources/scanned_resource_decorator.rb, config/locales/en.yml, spec/views/catalog/_resource_attributes_default.html.erb_spec.rb
=> Replace holding location with rendered holding location on scanned resource show page

app/models/mets_document.rb, app/models/mets_document/mods_document.rb, app/resources/scanned_resources/scanned_resource_decorator.rb, app/resources/scanned_resources/simple_resource_change_set.rb, spec/jobs/ingest_mets_job_spec.rb, spec/jobs/reprocess_mets_job_spec.rb, spec/models/mets_document/mods_document_spec.rb, spec/models/mets_document_spec.rb
refs #1978 
but doesn't close the issue because once this is merged the mods needs to be re-imported to add the new value.
=> Add archival_collection_code during mods import

app/helpers/file_proxy_helper.rb, spec/helpers/file_proxy_helper_spec.rb
=> Ensure RDF::Literals are converted to strings before being passed to vue

Gemfile.lock, config/initializers/valkyrie.rb
=> Check connection validity every time.

app/jobs/voyager_update_job.rb, spec/jobs/voyager_update_job_spec.rb
=> VoyagerUpdateJob should use Figgy IDs

app/resources/scanned_resources/scanned_resources_controller.rb, config/config.yml, spec/resources/scanned_resource/scanned_resources_controller_spec.rb, spec/services/ingest_folder_locator_spec.rb
=> Change default IngestFolder location to "studio_new/DPUL"

app/views/catalog/_auth_link_default.html.erb
=> Add confirm box to regenerate auth token for playlists

app/resources/scanned_resources/scanned_resources_controller.rb, app/services/bulk_ingest_service.rb, spec/resources/scanned_resource/scanned_resources_controller_spec.rb
=> BulkIngestService now preserves file names for WAV

app/javascript/components/OrderManagerFilesetsForm.vue
=> Set default foliation options

.rubocop.yml, app/helpers/application_helper.rb, app/services/manifest_builder.rb, spec/services/manifest_builder_spec.rb
Allows for a navigable table of contents, which updates the title of the
viewer.
Closes #2467
=> Generate a default structure for AV materials.

app/assets/stylesheets/components/form.scss
=> Increase space between save and delete buttons

app/javascript/components/document_adder.vue
We learned a lot about javascript today.
Closes #2316
=> Support adding one track.

config/schedule.rb
=> Remove cron to refresh finding aid data

app/change_sets/concerns/date_range_property.rb, app/models/concerns/linked_data/linked_date_range.rb, app/models/concerns/linked_data/linked_simple_resource.rb, app/resources/date_ranges/date_range.rb, app/resources/date_ranges/date_range_change_set.rb, app/resources/date_ranges/date_range_decorator.rb, app/resources/ephemera_folders/ephemera_folder_change_set_base.rb, app/resources/numismatic_issues/numismatic_issue_change_set.rb, app/resources/scanned_resources/scanned_resource.rb, app/resources/scanned_resources/scanned_resource_decorator.rb, app/resources/scanned_resources/simple_resource_change_set.rb, app/views/records/edit_fields/_date_range_form.html.erb, config/locales/simple_form.en.yml, spec/change_sets/concerns/date_range_property_spec.rb, spec/change_sets/simple_resource_change_set_spec.rb, spec/models/concerns/linked_data/linked_date_range_spec.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb, spec/models/linked_data/linked_simple_resource_spec.rb, spec/resources/date_ranges/date_range_decorator_spec.rb, spec/resources/numismatic_issue/numismatic_issue_change_set_spec.rb, spec/resources/numismatic_issue/numismatic_issues_feature_spec.rb, spec/resources/scanned_resource/scanned_resource_decorator_spec.rb, spec/shared_specs.rb, spec/shared_specs/models/linked_data/resource/with_date_range.rb, spec/support/shared/ephemera_folder_change_set_specs.rb
=> Add 'approximate' flag to date range, date range to simple resource

config/locales/simple_form.en.yml, spec/resources/scanned_resource/scanned_resources_controller_spec.rb
=> Adding hint that title is only required if not entering Source Metadata ID

public/uv/lib/AVComponent.js
=> Increase HLS timeouts.

app/decorators/valkyrie/resource_decorator.rb, app/views/catalog/_member_resources_raster_resource.html.erb, app/views/catalog/_member_resources_scanned_map.html.erb, app/views/catalog/_member_resources_vector_resource.html.erb, app/views/catalog/_members_multi_volume_work.html.erb, app/views/catalog/_members_numismatic_issue.html.erb, app/views/catalog/_parent_resources_raster_resource.html.erb, app/views/catalog/_parent_resources_scanned_map.html.erb, app/views/catalog/_parent_resources_vector_resource.html.erb, spec/decorators/valkyrie/resource_decorator_spec.rb
=> Adding visibility badge without verbose note, using in tabular member lists

app/resources/scanned_resources/recording_change_set.rb
=> Add part_of to recording change set

app/controllers/catalog_controller.rb
=> Add part_of facet

app/javascript/components/playlist_member.vue
=> Add spinning loader (from lux!) to track detach button

app/javascript/packs/application.js, app/javascript/packs/auth_link_clipboard.js, app/views/catalog/_auth_link_default.html.erb
=> Don't use javascript_pack_tag; import js modules to application.js

config/deploy/production.rb
=> Add lib-proc7/8

yarn.lock
=> Upgrade Lux to fix thumbnails in Order Manager

app/views/layouts/application.html.erb
Recommendation of Google PageSpeed.
=> Defer javascript rendering to end of page.

app/graphql/types/resource.rb, spec/graphql/types/scanned_resource_type_spec.rb
=> Handle thumbnail returning nil in GraphQL

.rubocop.yml, app/indexers/ephemera_folder_indexer.rb, app/indexers/imported_metadata_indexer.rb, spec/controllers/catalog_controller_spec.rb
* Index all imported metadata attributes: Fixes #383 
* Index Box/Folder labels for ephemera: Fixes #2444
=> Index box/folder labels for ephemera and all imported metadata

public/viewer.html
The viewer's being embedded via an iFrame in Blackboard.
=> Mark viewer as embedded.

app/javascript/packs/auth_link_clipboard.js
=> Ensure div exists before filling it with moar html

Gemfile, Gemfile.lock, app/indexers/parent_issue_indexer.rb, app/indexers/sorting_indexer.rb, spec/indexers/parent_issue_indexer_spec.rb, spec/indexers/sorting_indexer_spec.rb
This will be a problem in future Solr versions, and wasn't intended in
the first place.
=> Don't index nested objects

.circleci/config.yml, Gemfile, Gemfile.lock, scripts/combine_coverage.rb, spec/rails_helper.rb
CircleCI has access to the simplecov HTML report, and will now error if
it drops below 100%.
=> Remove Coveralls

app/jobs/voyager_update_job.rb, spec/jobs/voyager_update_job_spec.rb
=> Set refresh_remote_metadata to correct value to fix VoyagerUpdateJob

app/graphql/types/file_set_type.rb, app/graphql/types/resource.rb, spec/graphql/types/file_set_type_spec.rb, spec/graphql/types/scanned_resource_type_spec.rb
Will allow DPUL to pull all the OCR at once.
=> Allow GraphQL to query for OCR Content.

app/services/geo_discovery/geoblacklight_document.rb, spec/services/geo_discovery/document_builder_spec.rb
=> Use dc_source_sm in generated GeoBlacklight documents

Gemfile, Gemfile.lock, app/controllers/catalog_controller.rb, app/models/ability.rb, app/models/blacklight_iiif_search/iiif_search.rb, app/models/concerns/blacklight_iiif_search/annotation_behavior.rb, app/models/iiif_search_builder.rb, app/services/manifest_builder.rb, app/services/manifest_builder/iiif_search_builder.rb, app/services/manifest_builder/manifest_service_locator.rb, config/routes.rb, spec/controllers/catalog_controller_spec.rb, spec/services/manifest_builder_spec.rb
=> Implement IIIF search-within.

app/services/event_generator/geoblacklight_event_generator.rb, spec/services/event_generator/geoblacklight_event_generator_spec.rb
=> Add bulk flag to geoblacklight messages

app/controllers/bulk_ingest_controller.rb, app/values/browse_everything_file_paths.rb, spec/controllers/bulk_ingest_controller_spec.rb, spec/values/browse_everything_file_paths_spec.rb
=> Handles cases where clients do not select files to be ingested for the `BulkIngestController`

app/change_set_persisters/change_set_persister/mint_identifier.rb, app/controllers/concerns/resource_controller.rb, app/services/identifier_service.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb, spec/services/identifier_service_spec.rb
=> Ensures that when PULFA ARKs are encountered they are not updated

app/graphql/types/query_type.rb, spec/graphql/types/query_type_spec.rb
=> In bibid queries don't return resources without a graphql type

app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/cleanup_terms.rb, app/queries/find_id_usage_by_model.rb, config/initializers/valkyrie.rb, spec/resources/ephemera_terms/ephemera_terms_controller_spec.rb
=> Cleanup EphemeraTerm references on delete.

spec/rails_helper.rb
=> Prevent leaking view contexts between tests

app/jobs/clean_deleted_subject_job.rb, spec/jobs/clean_deleted_subject_job_spec.rb
I will probably just run this job from the console for now, but I wanted some tested code
refs #2604
=> Add a job to delete a subject from all ephemera folders

app/views/catalog/_admin_controls_recording.html.erb
=> Remove link to structure manager from recording

app/controllers/reports_controller.rb, app/models/report.rb, app/queries/updated_archival_resources.rb, app/views/reports/pulfa_ark_report.html.erb, config/initializers/valkyrie.rb, config/routes.rb, spec/controllers/reports_controller_spec.rb, spec/models/report_spec.rb
=> Adding time-based ARK reports for PULFA resources

app/queries/updated_archival_resources.rb, spec/controllers/reports_controller_spec.rb
=> Limit updated resource query to resources with identifiers

app/change_set_persisters/change_set_persister/extract_archival_collection_code.rb, spec/change_set_persisters/change_set_persister/extract_archival_collection_code_spec.rb
=> A collection code may be the full source metadata id

app/graphql/types/raster_resource_type.rb, app/graphql/types/resource.rb, app/graphql/types/vector_resource_type.rb, spec/graphql/types/query_type_spec.rb, spec/graphql/types/raster_resource_type_spec.rb, spec/graphql/types/vector_resource_type_spec.rb
=> Add raster and vector resource types to graphql

app/resources/coins/orangelight_coin_builder.rb, spec/services/orangelight_document_spec.rb
=> Rename numismatic orangelight document technique property

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/pagination.scss, spec/features/numismatic_reference_spec.rb
=> Update pagination z-index to be less than the add-content button z-index

app/services/manifest_builder/iiif_search_builder.rb, spec/services/manifest_builder_spec.rb
=> Don't put search service inside an array

app/resources/numismatic_monograms/numismatic_monogram_wayfinder.rb, spec/wayfinders/wayfinder_spec.rb
=> Attach monogram file in a numismatic monogram

app/controllers/catalog_controller.rb, spec/resources/coins/coin_feature_spec.rb
=> Show issue in breadcrumb when parent_id is not in the path

app/models/iiif_search_builder.rb, spec/controllers/catalog_controller_spec.rb
=> Ensure fq makes it all the way to solr in iiif search

app/graphql/types/coin_type.rb, app/graphql/types/resource.rb, spec/graphql/types/coin_type_spec.rb, spec/graphql/types/resource_spec.rb, spec/graphql/types/scanned_resource_type_spec.rb
=> adds orangelightId property to graphql response

.rubocop.yml, app/change_set_persisters/change_set_persister.rb, app/change_set_persisters/change_set_persister/append_artist_to_parent.rb, app/models/search_builder.rb, app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coin_wayfinder.rb, app/resources/numismatic_artists/numismatic_artist.rb, app/resources/numismatic_artists/numismatic_artist_change_set.rb, app/resources/numismatic_artists/numismatic_artist_decorator.rb, app/resources/numismatic_artists/numismatic_artist_wayfinder.rb, app/resources/numismatic_artists/numismatic_artists_controller.rb, app/views/catalog/_members_coin.html.erb, app/views/records/edit_fields/_artist_parent_id.html.erb, app/views/records/edit_fields/_citation_parent_id.html.erb, app/wayfinders/wayfinder.rb, config/routes.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/factories/numismatic_artist.rb, spec/resources/coins/coin_change_set_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_feature_spec.rb, spec/resources/numismatic_artists/numismatic_artist_change_set_spec.rb, spec/resources/numismatic_artists/numismatic_artist_decorator_spec.rb, spec/resources/numismatic_artists/numismatic_artist_spec.rb, spec/resources/numismatic_artists/numismatic_artists_controller_spec.rb, spec/views/catalog/_members_coin.html.erb_spec.rb
=> Include artist table in coin

.rubocop.yml, app/graphql/types/coin_type.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/orangelight_coin_builder.rb, app/services/event_generator.rb, app/services/event_generator/orangelight_event_generator.rb, app/services/orangelight_messaging_client.rb, config/config.yml, config/initializers/figgy.rb, spec/services/event_generator/orangelight_event_generator_spec.rb, spec/services/orangelight_document_spec.rb, spec/services/orangelight_messaging_client_spec.rb
For syncing coins to Orangelight with RabbitMQ.
Closes #2678
=>  Add orangelight event generator

spec/resources/archival_media_collections/archival_media_collections_controller_spec.rb
=> Refactor ArchivalMediaCollectionsController spec to prevent intermittent failure

app/resources/playlists/playlist_change_set.rb, spec/resources/playlists/playlist_change_set_spec.rb
=> Add part_of to Playlists.

app/resources/playlists/playlists_controller.rb, spec/resources/playlists/playlists_controller_spec.rb
=> Migrate recording part_of to created Playlist

app/resources/numismatic_artists/numismatic_artist_wayfinder.rb, app/resources/numismatic_artists/numismatic_artists_controller.rb, app/resources/numismatic_citations/numismatic_citation_wayfinder.rb, app/resources/numismatic_citations/numismatic_citations_controller.rb, spec/resources/numismatic_artists/numismatic_artist_wayfinder_spec.rb, spec/resources/numismatic_artists/numismatic_artists_controller_spec.rb, spec/resources/numismatic_citations/numismatic_citation_wayfinder_spec.rb, spec/resources/numismatic_citations/numismatic_citations_controller_spec.rb
=> Redirect to parent coin when deleting citation/artist

app/resources/playlists/playlist.rb, app/resources/playlists/playlist_change_set.rb, app/resources/playlists/playlist_decorator.rb, app/resources/playlists/playlists_controller.rb, app/resources/proxy_file_sets/proxy_file_set.rb, app/services/manifest_builder.rb, app/services/manifest_builder/structure_builder_v3.rb, config/routes.rb, spec/resources/playlists/playlist_decorator_spec.rb, spec/resources/playlists/playlists_controller_spec.rb, spec/services/manifest_builder_spec.rb
This also fixes manifest generation of playlists with deeply nested
hierarchy.
Closes #2653
=> Add Structure Editor to playlist.

app/javascript/components/OrderManagerFilesetsForm.vue, app/javascript/test/orderManagerFilesetsForm.spec.js
=> Foliation not happen when in paginate mode

app/decorators/valkyrie/resource_decorator.rb, app/resources/numismatic_monograms/numismatic_monogram_decorator.rb, app/views/catalog/_admin_controls_default.html.erb, app/views/catalog/_display_order_manager_button.html.erb, spec/resources/numismatic_monograms/numismatic_monogram_decorator_spec.rb, spec/resources/numismatic_monograms/numismatic_monogram_feature_spec.rb
=> Remove order manager button from monogram show page

app/jobs/update_cico_ids_job.rb, lib/tasks/migrate.rake, spec/jobs/update_cico_ids_job_spec.rb
=> Add rake task to update local ids from `cico:` to `dcl:`

app/services/event_generator/orangelight_event_generator.rb, app/services/orangelight_document.rb, spec/services/event_generator/orangelight_event_generator_spec.rb
=> Return orangelight document as a hash instead of a JSON string

app/jobs/bulk_update_job.rb, spec/jobs/bulk_update_job_spec.rb
=> Don't bulk update takedown states.

app/helpers/metadata_form_helper.rb, spec/helpers/metadata_form_helper_spec.rb
=> Update form_title based on the change_set value

app/services/bulk_ingest_service.rb
=> Ensure mime_type is not nil before calling content_type

app/resources/numismatic_issues/numismatic_issue.rb, app/resources/numismatic_issues/numismatic_issue_change_set.rb, app/resources/numismatic_issues/numismatic_issue_decorator.rb, spec/controllers/catalog_controller_spec.rb, spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb, spec/services/orangelight_document_spec.rb
=> Remove artist attribute from the numismatic issue

app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coin_wayfinder.rb, app/views/catalog/_members_coin.html.erb, spec/change_set_persisters/change_set_persister_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_feature_spec.rb, spec/resources/numismatic_artists/numismatic_artist_wayfinder_spec.rb, spec/resources/numismatic_artists/numismatic_artists_controller_spec.rb, spec/views/catalog/_members_coin.html.erb_spec.rb
=> Remove artist from coin

app/assets/javascripts/save_and_ingest_handler.es6
=> Don't pass change_set if it's edit

app/controllers/catalog_controller.rb, spec/controllers/catalog_controller_spec.rb
=> Set default index per_page to 20.

app/resources/coins/orangelight_coin_builder.rb, spec/services/orangelight_document_spec.rb
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
=> Add issue sort fields for orangelight advanced search

app/resources/coins/orangelight_coin_builder.rb, spec/services/orangelight_document_spec.rb
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
closes #2747
=> add facet fields for orangelight coin search

app/assets/stylesheets/components/thumbnail.scss, app/controllers/catalog_controller.rb, app/views/catalog/_document_list.html.erb, app/views/catalog/_index_header_list_default.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/catalog/_thumbnail_list_default.html.erb
Closes #131
New View:
Old View:
=> Move around Catalog Index View display to put thumbnails on left.

Gemfile.lock, app/jobs/regenerate_derivatives_job.rb, spec/derivative_services/audio_derivative_service_spec.rb, spec/derivative_services/default_derivative_service_spec.rb, spec/derivative_services/external_metadata_derivative_service_spec.rb, spec/derivative_services/hocr_derivative_service_spec.rb, spec/derivative_services/image_derivative_service_spec.rb, spec/derivative_services/jp2_derivative_service_spec.rb, spec/jobs/regenerate_derivatives_job_spec.rb, spec/resources/raster_resources/raster_resource_derivative_service_spec.rb, spec/resources/scanned_maps/scanned_map_derivative_service_spec.rb, spec/resources/vector_resources/vector_resource_derivative_service_spec.rb
=> Use Valkyrie::Derivatives version with new id interface

app/assets/stylesheets/components/show.scss, app/javascript/components/playlist_member.vue, app/javascript/components/playlist_members.vue
=> Allow detaching multiple Playlist Items at once.

app/controllers/catalog_controller.rb
=> Add call number to index view.

app/controllers/concerns/resource_controller.rb, app/validators/source_metadata_identifier_validator.rb, spec/resources/archival_media_collections/archival_media_collection_change_set_spec.rb, spec/shared_specs/controllers/base_resource_controller.rb
=> Handles cases where invalid source metadata IDs are provided for new resources

.rubocop.yml, app/resources/coins/coin_decorator.rb, app/resources/coins/orangelight_coin_builder.rb, spec/services/orangelight_document_spec.rb
Closes pulibrary/orangelight#1605.
=> adds holdings for coin objects

config/deploy.rb, lib/tasks/reindex.rake
=> Implements Rake and Capistrano tasks for reindexing geospatial resources

.rubocop.yml, app/change_set_persisters/change_set_persister/cleanup_pdfs.rb, app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coins_controller.rb, app/services/pdf_generator/cover_page_generator.rb, config/routes.rb, spec/factories/coin.rb, spec/resources/coins/coin_change_set_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_spec.rb, spec/resources/coins/coins_controller_spec.rb
=> add coin pdf support

app/resources/coins/coin_decorator.rb, spec/resources/coins/coin_decorator_spec.rb
trap nil numismatic issue for pub_created_display when a coin is not attached to a numismatic issue
closes #2788
=> trap nil numismatic issue for pub_created_display

app/views/layouts/application.html.erb, app/views/shared/_matomo.html.erb
Should help us track how users are using the home page.
=> Add Matomo to layout.

app/controllers/catalog_controller.rb, app/helpers/catalog_helper.rb, app/indexers/facet_indexer.rb, config/initializers/valkyrie.rb, spec/indexers/facet_indexer_spec.rb
* Adds Yes/No facet for whether an item has logical structure
* Alphabetizes indexer in initializer for readability
Fixes #2775
=> Add 'Has Structure' facet

lib/tasks/reindex.rake
=> Fix reindex task

app/services/reindexer.rb, config/initializers/valkyrie.rb, lib/tasks/reindex.rake
Provide the core URL via CLEAN_REINDEX_SOLR_URL
=> Add support for reindexing to another Solr Core.

.rubocop.yml, app/services/reindexer.rb, spec/services/reindexer_spec.rb
=> Update reindexer to retry records one at a time

app/services/reindexer.rb
saying when records start being indexed individually
=> Add a log msg to reindexer

app/controllers/concerns/resource_controller.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb
=> Strip spaces from incoming form data

spec/services/reindexer_spec.rb
=> Try to fix intermittent spec by forcing `let` to cache

app/services/reindexer.rb, spec/services/reindexer_spec.rb
=> Send more data with solr error on reindex

spec/services/reindexer_spec.rb
Hopefully fixes intermittently failing reindexer spec. 🤞 Working locally with a consistently failing rspec seed.
Addresses #2838
=> Use change matcher in failing reindexer spec

Gemfile, Gemfile.lock
This also ensures that directory file entries are sorted by file name, and as such, advances #2836
=> Resolves issues related to the selection of multiple file entries in the BrowseEverything selection dialogue

app/resources/file_sets/file_set_change_set.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Don't preserve unless parent is preserved.

app/controllers/base_resource_controller.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb
should be the last piece in order to close #2836
=> Deduplicate files before creating PendingUploads

app/helpers/application_helper.rb, app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coin_wayfinder.rb, app/resources/coins/coins_controller.rb, app/views/records/edit_fields/_numismatic_accession_id.html.erb, config/locales/en.yml, spec/controllers/catalog_controller_spec.rb, spec/helpers/application_helper_spec.rb, spec/resources/coins/coin_change_set_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_feature_spec.rb
=> Link NumismaticAccessions by reference

architecture-decisions/0003-preservation.md
=> Architecture Decision #3: Preservation

app/resources/coins/orangelight_coin_builder.rb, app/services/event_generator/orangelight_event_generator.rb, spec/services/event_generator/orangelight_event_generator_spec.rb, spec/services/orangelight_document_spec.rb
=> Don't sync a coin to Ol or build an Ol document  if there is no parent numismatic issue. 

app/models/search_builder.rb, app/resources/numismatic_issues/numismatic_issue.rb, app/resources/numismatic_places/numismatic_place_decorator.rb
=> Small numismatic updates

app/controllers/application_controller.rb, app/models/ability.rb, spec/features/root_spec.rb, spec/models/ability_spec.rb
=> Add READ_ONLY_MODE to Ability

app/controllers/application_controller.rb, app/models/ability.rb, config/application.rb, config/database.yml, config/deploy.rb, config/read_only_mode.rb, spec/features/root_spec.rb, spec/models/ability_spec.rb
requires provisioning of pulibrary/princeton_ansible#479
fully resolves #2830
=> Add capistrano switch to read only mode

app/services/event_generator/orangelight_event_generator.rb, spec/services/event_generator/orangelight_event_generator_spec.rb
=> when coin is in a draft state event generator publishes a delete message

lib/tasks/bulk.rake, spec/services/bulk_edit_service_spec.rb
=> Add support for preservation_policy to bulk:update_attrs

app/services/preserver.rb, spec/change_set_persisters/change_set_persister_spec.rb
=> Don't queue empty CleanupFilesJobs.

app/jobs/preserve_resource_job.rb
This will likely result in slower preservation, but will have better and
less expensive retrying should something bad happen.
Closes #2883
=> Preserve resources one at a time in a background job.

spec/services/reindexer_spec.rb
=> Remove intermittently failing spec

spec/services/reindexer_spec.rb
Another attempt to fix the intermittent spec failure
=> Remove arguments from `multi_index_persist` stub

app/resources/coins/orangelight_coin_builder.rb, app/resources/numismatic_issues/numismatic_issue.rb, app/resources/numismatic_issues/numismatic_issue_change_set.rb, app/resources/numismatic_issues/numismatic_issue_decorator.rb, app/resources/numismatic_issues/numismatic_issue_wayfinder.rb, app/views/records/edit_fields/_master_id.html.erb, spec/controllers/catalog_controller_spec.rb, spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb, spec/services/orangelight_document_spec.rb
=> Link master property to NumismaticPerson

app/resources/coins/orangelight_coin_builder.rb, app/resources/numismatic_issues/numismatic_issue.rb, app/resources/numismatic_issues/numismatic_issue_change_set.rb, app/resources/numismatic_issues/numismatic_issue_decorator.rb, spec/change_sets/concerns/date_range_property_spec.rb, spec/controllers/catalog_controller_spec.rb, spec/resources/numismatic_issues/numismatic_issue_change_set_spec.rb, spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb, spec/services/orangelight_document_spec.rb
=> Replace date_range with ce1 and ce2

app/resources/numismatic_artists/numismatic_artist.rb, app/resources/numismatic_artists/numismatic_artist_change_set.rb, app/resources/numismatic_artists/numismatic_artist_decorator.rb, app/resources/numismatic_artists/numismatic_artist_wayfinder.rb, app/views/numismatic_issues/_numismatic_artist_fields.html.erb, app/wayfinders/wayfinder.rb, spec/resources/numismatic_artists/numismatic_artist_change_set_spec.rb, spec/resources/numismatic_artists/numismatic_artist_decorator_spec.rb, spec/resources/numismatic_artists/numismatic_artist_spec.rb, spec/resources/numismatic_issues/numismatic_issue_decorator_spec.rb, spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb, spec/services/orangelight_document_spec.rb
=> Link NumismaticPerson resources to NumismaticArtist by ID

app/resources/numismatic_issues/numismatic_issue.rb, app/resources/numismatic_issues/numismatic_issue_change_set.rb, app/resources/numismatic_issues/numismatic_issue_decorator.rb, app/resources/numismatic_notes/numismatic_note.rb, app/resources/numismatic_notes/numismatic_note_change_set.rb, app/resources/numismatic_notes/numismatic_note_decorator.rb, app/views/numismatic_issues/_numismatic_note_fields.html.erb, app/views/numismatic_issues/edit_fields/_numismatic_note.html.erb, spec/controllers/catalog_controller_spec.rb, spec/resources/numismatic_issues/numismatic_issue_change_set_spec.rb, spec/resources/numismatic_issues/numismatic_issue_decorator_spec.rb, spec/resources/numismatic_issues/numismatic_issues_feature_spec.rb, spec/resources/numismatic_notes/numismatic_note_change_set_spec.rb, spec/resources/numismatic_notes/numismatic_note_decorator_spec.rb, spec/resources/numismatic_notes/numismatic_note_spec.rb
=> Add a NumismaticNote resource and use it in NumismaticIssue

app/jobs/update_fixity_job.rb, app/resources/events/event.rb, app/services/reindexer.rb, cloud_fixity/index.js, cloud_fixity/test/index.test.js, spec/jobs/update_fixity_job_spec.rb, spec/resources/events/event_change_set_spec.rb, spec/resources/events/event_spec.rb, spec/services/cloud_fixity_spec.rb, spec/support/clean_solr.rb
=> Create events in response to Cloud Fixity

app/queries/find_random_resources_by_model.rb, app/services/cloud_fixity.rb, config/config.yml, config/deploy.rb, config/initializers/valkyrie.rb, lib/tasks/fixity_worker.rake, spec/queries/find_random_resources_by_model_spec.rb, spec/services/cloud_fixity_spec.rb
=> Request % of Preserved Resources be Fixity Checked

app/resources/numismatic_references/numismatic_reference.rb, app/resources/numismatic_references/numismatic_reference_change_set.rb, app/resources/numismatic_references/numismatic_reference_decorator.rb, app/resources/numismatic_references/numismatic_reference_wayfinder.rb, app/resources/numismatic_references/numismatic_references_controller.rb, app/views/numismatic_references/edit_fields/_author_id.html.erb, spec/resources/numismatic_references/numismatic_reference_change_set_spec.rb, spec/resources/numismatic_references/numismatic_reference_decorator_spec.rb
=> Updates to NumismaticReferences

app/resources/numismatic_references/numismatic_reference_change_set.rb, app/resources/numismatic_references/numismatic_reference_decorator.rb, app/resources/numismatic_references/numismatic_reference_wayfinder.rb, spec/resources/numismatic_references/numismatic_reference_decorator_spec.rb
=> Make author_id multivalued

spec/services/voyager_updater/event_stream_spec.rb
=> Ensuring that the test suite for VoyagerUpdater::EventStream#events does not fail for Events generated by other tests

app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coin_wayfinder.rb, app/resources/coins/coins_controller.rb, app/resources/coins/orangelight_coin_builder.rb, app/views/coins/edit_fields/_find_place_id.html.erb, spec/controllers/catalog_controller_spec.rb, spec/resources/coins/coin_feature_spec.rb, spec/services/orangelight_document_spec.rb
=> Link Coin find_place property to NumismaticPlace by ID

Gemfile, Gemfile.lock, spec/spec_helper.rb, spec/support/chromedriver_helper.rb
=> Use webdrivers instead of chromedriver-helper

app/models/search_builder.rb, app/resources/numismatic_firm/numismatic_firm.rb, app/resources/numismatic_firm/numismatic_firm_change_set.rb, app/resources/numismatic_firm/numismatic_firm_decorator.rb, app/resources/numismatic_firm/numismatic_firms_controller.rb, app/views/numismatic_firms/index.html.erb, app/views/shared/_add_content.html.erb, config/routes.rb, spec/factories/numismatic_firm.rb, spec/resources/numismatic_firms/numismatic_firm_change_set_spec.rb, spec/resources/numismatic_firms/numismatic_firm_decorator_spec.rb, spec/resources/numismatic_firms/numismatic_firm_feature_spec.rb, spec/resources/numismatic_firms/numismatic_firm_spec.rb, spec/resources/numismatic_firms/numismatic_firms_controller_spec.rb
=> Add NumismaticFirm

app/resources/numismatic_accessions/numismatic_accessions_controller.rb, app/resources/numismatic_firm/numismatic_firms_controller.rb, app/resources/numismatic_monograms/numismatic_monograms_controller.rb, app/resources/numismatic_people/numismatic_people_controller.rb, app/resources/numismatic_places/numismatic_places_controller.rb, app/resources/numismatic_references/numismatic_references_controller.rb, spec/resources/numismatic_accessions/numismatic_accessions_controller_spec.rb, spec/resources/numismatic_firms/numismatic_firms_controller_spec.rb, spec/resources/numismatic_monograms/numismatic_monograms_controller_spec.rb, spec/resources/numismatic_people/numismatic_people_controller_spec.rb, spec/resources/numismatic_places/numismatic_places_controller_spec.rb, spec/resources/numismatic_references/numismatic_references_controller_spec.rb
=> Manage Numismatic Resources: on update or create redirect to the index view

spec/services/cloud_fixity_spec.rb
=> Extends the acceptance test for the CloudFixity service

app/models/search_builder.rb, app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/coins/coins_controller.rb, app/resources/numismatic_provenances/numismatic_provenance.rb, app/resources/numismatic_provenances/numismatic_provenance_change_set.rb, app/resources/numismatic_provenances/numismatic_provenance_decorator.rb, app/resources/numismatic_provenances/numismatic_provenance_wayfinder.rb, app/views/coins/_provenance_fields.html.erb, app/views/coins/edit_fields/_provenance.html.erb, app/wayfinders/wayfinder.rb, spec/controllers/catalog_controller_spec.rb, spec/resources/coins/coin_change_set_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_feature_spec.rb, spec/resources/numismatic_provenances/numismatic_provenance_change_set_spec.rb, spec/resources/numismatic_provenances/numismatic_provenance_decorator_spec.rb, spec/resources/numismatic_provenances/numismatic_provenance_spec.rb
=>  Add NumismaticProvenance resource

app/resources/numismatic_accessions/numismatic_accession.rb, app/resources/numismatic_accessions/numismatic_accession_change_set.rb, app/resources/numismatic_accessions/numismatic_accession_decorator.rb, app/resources/numismatic_accessions/numismatic_accession_wayfinder.rb, app/resources/numismatic_accessions/numismatic_accessions_controller.rb, app/views/records/edit_fields/_firm_id.html.erb, spec/factories/numismatic_firm.rb, spec/resources/numismatic_accessions/numismatic_accession_change_set_spec.rb, spec/resources/numismatic_accessions/numismatic_accession_decorator_spec.rb, spec/resources/numismatic_firms/numismatic_firm_decorator_spec.rb
=> Add linked NumismaticFirm to NumismaticAccession

spec/resources/numismatic_provenances/numismatic_provenance_decorator_spec.rb
Fixing the unstable test suite for NumismaticProvenanceDecorator (ports a solution from @eliotjordan offered  in #2965)
=> Fixes the unstable test suite for `NumismaticProvenanceDecorator`

app/models/search_builder.rb, app/resources/coins/coin.rb, app/resources/coins/coin_change_set.rb, app/resources/coins/coin_decorator.rb, app/resources/numismatic_loans/numismatic_loan.rb, app/resources/numismatic_loans/numismatic_loan_change_set.rb, app/resources/numismatic_loans/numismatic_loan_decorator.rb, app/resources/numismatic_loans/numismatic_loan_wayfinder.rb, app/views/coins/_loan_fields.html.erb, app/views/coins/edit_fields/_loan.html.erb, app/wayfinders/wayfinder.rb, spec/controllers/catalog_controller_spec.rb, spec/resources/coins/coin_change_set_spec.rb, spec/resources/coins/coin_decorator_spec.rb, spec/resources/coins/coin_feature_spec.rb, spec/resources/numismatic_loans/numismatic_loan_change_set_spec.rb, spec/resources/numismatic_loans/numismatic_loan_decorator_spec.rb, spec/resources/numismatic_loans/numismatic_loan_spec.rb, spec/resources/numismatic_provenances/numismatic_provenance_decorator_spec.rb
=>  Add NumismaticLoan resource

.rubocop.yml, app/resources/coins/coins_controller.rb, spec/resources/coins/coins_controller_spec.rb
=> when deleting a coin redirect to the parent issue

app/graphql/types/numismatic_monogram_type.rb, app/graphql/types/query_type.rb, app/graphql/types/resource.rb, app/models/ability.rb, app/resources/coins/orangelight_coin_builder.rb, spec/graphql/types/query_type_spec.rb, spec/models/ability_spec.rb, spec/services/orangelight_document_spec.rb
Advances pulibrary/orangelight#1616.
Co-authored-by: Christina Chortaria <actspatial@gmail.com>
=> Add monogram properties to coin orangelight document

app/jobs/export_files_job.rb, app/services/export_service.rb, config/config.yml, lib/tasks/export.rake, spec/jobs/export_files_job_spec.rb, spec/services/export_service_spec.rb
=> Adding export service and rake task

app/controllers/application_controller.rb
* Stores user locations on appropriate GET requests
* Uses stored location to redirect back after login
Fixes #2395
=> Using Devise::Controllers::StoreLocation

app/models/ability.rb, spec/models/ability_spec.rb
=> Allow users with CAS login to download campus-only geo files

app/helpers/application_helper.rb, app/views/catalog/_home_text.html.erb, spec/features/root_spec.rb
=> Remove UI functionality to create MediaResources

public/uv/lib/uv-av-extension-dependencies.js, public/uv/uv.html, public/viewer.html
=> Include local HLS.js

app/javascript/components/OrderManagerFilesetsForm.vue, app/javascript/test/orderManagerFilesetsForm.spec.js
=> Update order manager `f. ` for folio, `p. ` for pagination

app/controllers/fixity_dashboard_controller.rb, app/queries/find_cloud_fixity_failures.rb, config/initializers/valkyrie.rb, spec/queries/find_cloud_fixity_failures_spec.rb
=> Implements the FindCloudFixityFailures custom query for finding Events for fixity failures (which didn't later succeed)

README.md, architecture-decisions/0004-preservation-fixity.md, preservation_documentation.md
=> First pass at Fixity ADR.

app/javascript/components/OrderManagerResourceForm.vue, app/javascript/test/__snapshots__/orderManagerResourceForm.spec.js.snap
=> Add a warning for cases where no FileSet members are found for resources on the OrderManager

app/services/manifest_builder.rb, app/services/manifest_builder/structure_builder_v3.rb, spec/services/manifest_builder_spec.rb
=> Fix structure for Audio Files

app/models/controlled_vocabulary.rb, app/resources/ephemera_folders/ephemera_folder_decorator.rb, spec/resources/ephemera_folders/ephemera_folder_decorator_spec.rb
=> Handles multiple URLs for holding location values

app/resources/numismatic_accessions/numismatic_accession.rb
=> remove thumbnail_id from accessions

app/jobs/export_pdf_job.rb, app/resources/coins/coins_controller.rb, app/resources/ephemera_folders/ephemera_folders_controller.rb, app/resources/scanned_resources/scanned_resources_controller.rb, app/services/export_service.rb, app/services/pdf_service.rb, lib/tasks/export.rake, spec/jobs/export_pdf_job_spec.rb, spec/resources/coins/coins_controller_spec.rb, spec/resources/ephemera_folders/ephemera_folders_controller_spec.rb, spec/services/export_service_spec.rb
* Provides a rake task and background job for exporting PDFs
* Refactors PDF generation to reduce duplication between export and controllers
Advances #2968; Closes #2462
=> PDF export

.rubocop.yml, app/jobs/numismatic_import_job.rb, app/jobs/numismatic_issue_import_job.rb, app/services/numismatics_import_service.rb, spec/jobs/numismatic_import_job_spec.rb
Co-authored-by: Nikitas Tampakis <nikitas.tampakis@gmail.com>
=> Adds issues & coins to a collection during import

app/resources/file_sets/file_set_wayfinder.rb, app/resources/file_sets/file_sets_controller.rb, spec/resources/file_sets/file_sets_controller_spec.rb
=> after deleting a fileset redirect to the parent

.rubocop.yml, app/queries/find_ids_with_property_not_empty.rb, app/services/bulk_update_remote_metadata_service.rb, config/initializers/valkyrie.rb, lib/tasks/bulk.rake, spec/queries/find_ids_with_property_not_empty_spec.rb, spec/services/bulk_update_remote_metadata_service_spec.rb
=> Rake task to refresh remote metadata on all resources

app/resources/numismatic_issues/numismatic_issue_decorator.rb, app/views/catalog/_admin_controls_numismatic_issue.html.erb, config/routes.rb, spec/resources/numismatic_issues/numismatic_issue_decorator_spec.rb
=> Remove File manager from numismatic issue

app/views/catalog/show.html.erb
=> Hide show page sidebar (action buttons) unless logged in

app/models/ability.rb, app/resources/numismatic_accessions/numismatic_accession.rb, app/resources/numismatic_accessions/numismatic_accession_change_set.rb, app/resources/numismatic_firm/numismatic_firm.rb, app/resources/numismatic_firm/numismatic_firm_change_set.rb, app/resources/numismatic_monograms/numismatic_monogram.rb, app/resources/numismatic_monograms/numismatic_monogram_change_set.rb, app/resources/numismatic_people/numismatic_person.rb, app/resources/numismatic_people/numismatic_person_change_set.rb, app/resources/numismatic_places/numismatic_place.rb, app/resources/numismatic_places/numismatic_place_change_set.rb, app/resources/numismatic_references/numismatic_reference.rb, app/resources/numismatic_references/numismatic_reference_change_set.rb, app/views/numismatic_accessions/index.html.erb, app/views/numismatic_firms/index.html.erb, app/views/numismatic_monograms/index.html.erb, app/views/numismatic_people/index.html.erb, app/views/numismatic_places/index.html.erb, app/views/numismatic_references/index.html.erb, spec/resources/numismatic_accessions/numismatic_accessions_controller_spec.rb, spec/resources/numismatic_firms/numismatic_firms_controller_spec.rb, spec/resources/numismatic_monograms/numismatic_monograms_controller_spec.rb, spec/resources/numismatic_people/numismatic_people_controller_spec.rb, spec/resources/numismatic_places/numismatic_places_controller_spec.rb, spec/resources/numismatic_references/numismatic_references_controller_spec.rb
=> Update ability with numismatic classes- updates classes with depositor

app/assets/stylesheets/components/header.scss
=> Adjust header styles to fix z-index of add-content menu

spec/resources/numismatic_places/numismatic_places_controller_spec.rb
=> updates numismatic_controllers_place test depositor

app/services/recording_downloadable_migrator.rb, lib/tasks/migrate.rake, spec/services/recording_downloadable_migrator_spec.rb
=> Add rake task to migrate recordings to be undownloadable

app/resources/scanned_resources/recording_change_set.rb, spec/change_sets/recording_change_set_spec.rb
=> Change default `downloadable` for Recordings to `none`

app/services/manifest_builder/record_property_builder_v3.rb, spec/services/manifest_builder_spec.rb
This doesn't provide the download options we want really, but we can
look into that as part of #3070
Closes #3071
=> Recordings should respect downloadability

.rubocop.yml, app/utils/data_seeder.rb, spec/utils/data_seeder_spec.rb
=> Add generator for an archival recording

app/derivative_services/audio_derivative_service.rb, spec/derivative_services/audio_derivative_service_spec.rb
=> Generate HLS from intermediate WAV file.

app/change_set_persisters/change_set_persister/create_file.rb, app/characterization_services/null_characterization_service.rb, app/characterization_services/tika_file_characterization_service.rb, app/jobs/ingest_archival_media_bag_job.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Generate derivatives for attached Audio Files

app/jobs/ingest_archival_media_bag_job.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> IngestArchivalMediaBagJob should make Recordings downloadable

app/queries/find_deep_children_with_property.rb
This runs about 4x faster on staging.
=> Significantly speed up deep children query.

app/services/manifest_builder.rb, app/services/manifest_builder/canvas_builder_v3.rb, app/services/manifest_builder/canvas_rendering_builder.rb, spec/services/manifest_builder_spec.rb
=> Add mp3 rendering to canvases

app/change_sets/concerns/geo_change_set_properties.rb, app/models/schema/geo.rb, app/resources/raster_resources/raster_resource_change_set.rb, app/resources/scanned_maps/scanned_map_change_set.rb, app/resources/vector_resources/vector_resource_change_set.rb, app/services/geo_discovery/abstract_document.rb, app/services/geo_discovery/document_builder/basic_metadata_builder.rb, app/services/geo_discovery/document_builder/slug_builder.rb, app/services/geo_discovery/geoblacklight_document.rb, spec/resources/raster_resources/raster_resource_feature_spec.rb, spec/resources/raster_resources/raster_resources_controller_spec.rb, spec/resources/scanned_maps/scanned_map_feature_spec.rb, spec/resources/scanned_maps/scanned_maps_controller_spec.rb, spec/resources/vector_resources/vector_resource_feature_spec.rb, spec/resources/vector_resources/vector_resources_controller_spec.rb, spec/services/geo_discovery/document_builder_spec.rb
=> GeoBlacklight document slugs

app/assets/javascripts/form/mutex.js, app/resources/collections/collection.rb, app/resources/collections/collection_change_set.rb, app/views/records/edit_fields/_title.html.erb, spec/resources/collections/collection_change_set_spec.rb, spec/resources/collections/collections_controller_spec.rb
=> Add imported metadata to collections

Gemfile, Gemfile.lock, app/resources/file_sets/file_set.rb, app/services/manifest_builder.rb, app/services/manifest_builder/record_property_builder_v3.rb, spec/services/manifest_builder_spec.rb
=> Generates the `posterCanvas` property for IIIFv3 Manifests where Recordings have image FileSets

.rubocop.yml, app/services/preserver/importer.rb, spec/services/preserver/importer_spec.rb
=> Implements a Preserver::Importer Class for importing resources from file identifiers

app/services/manifest_builder/manifest_service_locator.rb, app/services/manifest_builder/media_sequence_builder.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/fixtures/files/sample.pdf, spec/services/manifest_builder_spec.rb
=> Add PDF support for IIIF manifests

app/resources/collections/collections_controller.rb, app/services/manifest_builder.rb, app/services/manifest_builder/record_property_builder.rb, spec/resources/collections/collections_controller_spec.rb, spec/services/manifest_builder_spec.rb
Fixes display for IIIF Universe
=> Don't display inaccessible manifests in Collection manifest.

app/characterization_services/mediainfo_characterization_service.rb, app/resources/media_resources/media_resource_change_set.rb, app/resources/media_resources/media_resource_wayfinder.rb, spec/change_set_persisters/change_set_persister_spec.rb, spec/resources/media_resources/media_resource_change_set_spec.rb
=> Introduces preservation support for MediaResources

app/jobs/ingest_folder_job.rb, spec/jobs/ingest_folder_job_spec.rb
Allow ingesting PDF files with bulk ingest Rake task
=> PDF bulk ingest

app/views/catalog/_members_file_set.html.erb, spec/views/catalog/_members_file_set.html.erb_spec.rb
=> Render a summary for derivative partials instead of each partial.

app/jobs/ingest_archival_media_bag_job.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
=> Fix file set order for AV ingest

.rubocop.yml, app/controllers/bulk_edit_controller.rb, app/jobs/bulk_update_job.rb, app/views/bulk_edit/resources_edit.html.erb, app/views/catalog/_members_collection.html.erb, spec/jobs/bulk_update_job_spec.rb
=> Add Rights Statement and OCR Language to Bulk Edit

config/locales/simple_form.en.yml
=> Add hint for slug.

spec/adapters/indexing_adapter_spec.rb
=> Clarify IndexingAdapter Spec

bin/ci_free_tds_install.sh, bin/ci_kakadu_install.sh, bin/ci_simple_tiles_install.sh
=> Use tmp instead of creating a downloads dir

.rubocop.yml, app/jobs/browse_everything_ingest_job.rb, spec/jobs/browse_everything_ingest_job_spec.rb
=> BrowseEverythingIngestJob rescues from not-found IDs

app/change_sets/change_set.rb, app/controllers/concerns/resource_controller.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb
=> Fix saving logical structure.

app/helpers/fixity_dashboard_helper.rb, app/resources/events/event.rb, app/resources/file_sets/file_set_decorator.rb, app/resources/nested_resources/file_metadata.rb, app/resources/preservation_objects/preservation_object.rb, app/views/catalog/_file_detail.html.erb, app/views/catalog/_members_file_set.html.erb, spec/helpers/fixity_dashboard_helper_spec.rb, spec/resources/file_sets/file_set_decorator_spec.rb
=> Display cloud fixity status on FileSets

app/change_set_persisters/change_set_persister/apply_remote_metadata.rb, app/models/archival_media_bag_parser.rb, app/models/remote_record.rb, app/services/pul_metadata_services/pulfa_record.rb
Will later allow us to delete MediaResource
=> Use an instance instead of a class for RemoteRecord

app/decorators/valkyrie/resource_decorator.rb, app/queries/find_deep_failed_cloud_fixity_count.rb, app/queries/find_deep_preservation_object_count.rb, app/views/catalog/_resource_attributes_default.html.erb, app/wayfinders/base_wayfinder.rb, config/initializers/valkyrie.rb, spec/resources/scanned_resources/scanned_resource_decorator_spec.rb, spec/wayfinders/wayfinder_spec.rb
=> Resource Cloud Fixity Summary

app/views/base/_form_visibility_component.html.erb, app/views/bulk_ingest/_visibility.html.erb
we're not quite ready to deploy this feature.
=> Remove reading room visibility from form ui

app/services/numismatics_import_service.rb, spec/services/numismatics_import_service_spec.rb
=> Ensures that the NumismaticsImportService imports Coins using ChangeSets (and generates derivatives for appended files)

.rubocop.yml, app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/helpers/application_helper.rb, app/views/catalog/_universal_viewer_default.html.erb, public/viewer.html, spec/features/login_spec.rb, spec/helpers/application_helper_spec.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb
This allows the viewer embed to provide a login button if it's possible for someone to login and see the content.
=> UV Pre-Authentication Javascript

app/graphql/types/query_type.rb, app/graphql/types/resource.rb, app/models/ability.rb, spec/graphql/types/ephemera_folder_type_spec.rb, spec/graphql/types/file_set_type_spec.rb, spec/graphql/types/numismatics/coin_type_spec.rb, spec/graphql/types/numismatics/issue_type_spec.rb, spec/graphql/types/query_type_spec.rb, spec/graphql/types/scanned_map_type_spec.rb, spec/graphql/types/scanned_resource_type_spec.rb, spec/models/ability_spec.rb
=> Open Items in GraphQL Response

app/controllers/catalog_controller.rb
=> Add depositor facet.

.circleci/config.yml, Gemfile, Gemfile.lock, app/assets/stylesheets/base/typography.scss, app/assets/stylesheets/components/header.scss, app/views/extra_extra/release_notes/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_add_content.html.erb, app/views/shared/_add_works.html.erb, app/views/shared/_brand_bar.html.erb, config/initializers/extra_extra.rb, config/routes.rb, release_notes.md
=> Add Release Notes to Figgy

RELEASE_NOTES.md, app/models/user.rb, lib/tasks/migrate.rake, spec/models/user_spec.rb
=> Don't add @princeton.edu to UIDs when they are email addresses already

app/models/user.rb, lib/tasks/migrate.rake, spec/models/user_spec.rb
Testing lack of release notes update.
=> External email without release notes

RELEASE_NOTES.md, app/assets/stylesheets/components/header.scss, app/views/shared/_title_bar.html.erb
=> Remove site-title in favor of lux header

RELEASE_NOTES.md, app/services/music_import_service.rb, spec/services/music_import_service_spec.rb
=> Update course part_of when skipping pre-ingested Recordings

app/controllers/base_resource_controller.rb, spec/resources/scanned_resources/scanned_resources_controller_spec.rb
=> Ensuring that BaseResourceController#new_pending_uploads filters for hidden files

RELEASE_NOTES.md, app/services/identifier_service.rb, app/services/pdf_generator/cover_page_generator.rb, spec/services/pdf_generator_spec.rb
=> Ensures that ARK links, catalog links, or finding aid links are used within PDF cover pages

app/services/ingest_ephemera_mods.rb, spec/services/ingest_ephemera_mods_spec.rb
=> Sort ingested files by filename so they are ingested in the correct order

RELEASE_NOTES.md, app/presenters/permission_badge.rb, config/locales/en.yml, spec/decorators/valkyrie/resource_decorator_spec.rb, spec/factories/scanned_resource.rb
=> Update visibility badge notices with new rules

app/views/base/_form_visibility_component.html.erb, app/views/bulk_ingest/_visibility.html.erb
Whenever we're ready to add these to the UI. We may want to wait until all the front-end apps are set up.
=> Visibility radios

app/queries/find_deep_failed_cloud_fixity_count.rb, spec/wayfinders/wayfinder_spec.rb
=> Fixity count should take into account child_property

app/services/preserver.rb, spec/services/preserver_spec.rb
Makes identifying resources in Preservation Storage easier.
=> Upload some basic metadata for preservation.

RELEASE_NOTES.md, app/change_set_persisters/change_set_persister/update_ocr.rb
=> Don't change queue for RunOCRJob

.circleci/config.yml
=> Fix coverage check

.circleci/config.yml, bin/ci_check_release_notes.sh
to prevent false positives on this check
fixes #3267
=> Check that change in release notes adds a new message

RELEASE_NOTES.md, app/jobs/ingest_archival_media_bag_job.rb, spec/jobs/ingest_archival_media_bag_job_spec.rb
Both descriptive proxies and recordings
fixes #3281
=> Use Copyright Not Evaluated for archival media resources

app/services/preserver.rb, spec/services/preserver_spec.rb
We'll likely get a bib-id if someone accidentally deletes a book.
=> Send Source Metadata Identifier to GCS as Metadata

RELEASE_NOTES.md, app/inputs/dpul_url_input.rb, app/views/records/edit_fields/_slug.html.erb, config/locales/simple_form.en.yml
=> Change "Slug" label to "DPUL URL" on collection form

app/models/ability.rb
fixes #3270
no release notes needed
=> Refactor to create a private? method in the Ability class

cloud_fixity/test/index.test.js, package.json, yarn.lock
as part of `yarn test` and also in ci
=> Configure yarn/jest to run cloud_fixity tests

cloud_fixity/index.js, cloud_fixity/test/index.test.js
=> Retry Cloud Fixity on Download Error

RELEASE_NOTES.md, app/controllers/catalog_controller.rb, app/helpers/catalog_helper.rb, spec/controllers/catalog_controller_spec.rb, spec/helpers/catalog_helper_spec.rb
=> Adding visibility facet and creator display to search results

app/jobs/update_fixity_job.rb, app/resources/nested_resources/file_metadata.rb, spec/jobs/update_fixity_job_spec.rb, spec/models/file_set_spec.rb
=> Honeybadger notifications on fixity failures

Gemfile, Gemfile.lock, app/services/preserver/blind_importer.rb, app/services/preserver/blind_importer/file_metadata_adapter.rb, app/services/preserver/blind_importer/file_metadata_adapter/query_service.rb, app/services/preserver/blind_importer/file_metadata_adapter/query_service/blind_importer_metadata_wayfinder.rb, app/services/preserver/blind_importer/file_metadata_adapter/query_service/file_metadata_resource.rb, app/wayfinders/wayfinder.rb, spec/factories/scanned_resource.rb, spec/services/preserver/blind_importer_spec.rb
Closes #3297 
Confirmed that this can import A/V materials as well as ScannedResources.
=> Support import from GCS structure

app/services/preserver/blind_importer/file_metadata_adapter/query_service/blind_importer_metadata_wayfinder.rb, app/services/preserver/blind_importer/file_metadata_adapter/query_service/file_metadata_resource.rb, app/services/preserver/nested_storage_path.rb, config/initializers/valkyrie.rb, spec/services/preserver/nested_storage_path_spec.rb
=> Move NestedStoragePath to preserver namespace.

RELEASE_NOTES.md, app/services/pdf_generator/cover_page_generator.rb, spec/services/pdf_generator_spec.rb
=> Fix identifier handling for ephemera

RELEASE_NOTES.md, app/resources/scanned_resources/scanned_resource_wayfinder.rb, app/resources/tombstones/tombstone.rb, app/views/base/file_manager.html.erb, spec/factories/tombstone.rb, spec/features/file_manager_spec.rb, spec/views/scanned_resources/file_manager.html.erb_spec.rb, spec/wayfinders/wayfinder_spec.rb
=> Add UI for reinstating a tombstone

app/models/search_builder.rb
=> Exclude Tombstones from search results.

app/helpers/catalog_helper.rb, app/presenters/permission_badge.rb, spec/helpers/catalog_helper_spec.rb
Hopefully will help us diagnose #3370
=> Pass on bad visibility values to facet, notify in Honeybadger

RELEASE_NOTES.md, config/schedule.rb
=> Updating imported metadata from PULFA nightly

RELEASE_NOTES.md, app/resources/scanned_maps/scanned_map_change_set.rb, app/resources/scanned_maps/scanned_map_decorator.rb, app/resources/scanned_maps/scanned_maps_controller.rb, spec/resources/scanned_maps/scanned_maps_controller_spec.rb
=> Add dropdown to choose scanned map thumbnails

RELEASE_NOTES.md, app/values/viewer_configuration.rb, public/uv/uv_config.json, public/uv/uv_config_downloads_disabled.json
=> Set UV OpenSeadragon module option immediateRender to true

app/models/concerns/linked_data/linked_ephemera_folder.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb
Closes pulibrary/pomegranate#620
=> Add transliterated title to Ephemera Folder JSON-LD

RELEASE_NOTES.md, app/queries/find_random_resources_by_model.rb, app/services/cloud_fixity.rb, config/schedule.rb, lib/tasks/fixity_worker.rake, spec/queries/find_random_resources_by_model_spec.rb, spec/services/cloud_fixity_spec.rb
=> Schedule daily cloud fixity checks

app/controllers/catalog_controller.rb, app/models/concerns/linked_data.rb, app/models/concerns/linked_data/linked_resource.rb, app/models/concerns/linked_data/linked_resource_factory.rb, app/models/concerns/linked_data/linked_vocabulary_base.rb, app/models/solr_document.rb, spec/models/linked_data/linked_resource_factory_spec.rb
=> Add system_created_at/system_updated_at to JSON-LD

config/deploy.rb
=> RabbitMQ Capistrano Tunnel Command.

RELEASE_NOTES.md, app/services/cloud_fixity.rb, lib/tasks/fixity_worker.rake, spec/services/cloud_fixity_spec.rb
=> Add task to run a cloud fixity check on a single resource

config/deploy.rb
No more ssh -L for opening Solr console.
=> Add cap [staging/production] solr:console

RELEASE_NOTES.md, app/assets/javascripts/bounding_box_selector.es6
=> Set correct initial bounds in bbox widget

RELEASE_NOTES.md, app/services/geo_discovery/document_builder/date_builder.rb, spec/services/geo_discovery/document_builder_spec.rb
=> Use imported date value to generate solr year value in geoblacklight documents

RELEASE_NOTES.md, app/controllers/concerns/resource_controller.rb, app/models/controlled_vocabulary.rb, app/resources/ephemera_boxes/ephemera_box.rb, app/resources/ephemera_folders/ephemera_folder.rb, app/resources/ephemera_projects/ephemera_project.rb, app/resources/ephemera_projects/ephemera_project_change_set.rb, app/views/catalog/_admin_controls_ephemera_box.html.erb, app/views/catalog/_ephemera_box_home.html.erb, app/views/catalog/_members_ephemera_project.html.erb, app/views/records/edit_fields/_contributor_uids.html.erb, config/locales/simple_form.en.yml, spec/models/ability_spec.rb, spec/resources/ephemera_folders/ephemera_folders_controller_spec.rb, spec/resources/ephemera_projects/ephemera_project_change_set_spec.rb, spec/resources/ephemera_projects/ephemera_project_spec.rb, spec/views/catalog/_admin_controls_ephemera_box.html.erb_spec.rb, spec/views/records/edit_fields/_contributor_uids.html.erb_spec.rb
=> Add External Contributors to Ephemera Projects.

app/models/concerns/linked_data/linked_ephemera_folder.rb, app/services/manifest_builder.rb, spec/models/linked_data/linked_ephemera_folder_spec.rb, spec/models/linked_data/linked_resource_factory_spec.rb, spec/services/manifest_builder_spec.rb
fixes pulibrary/pomegranate#644
=> Add transliterated title to jsonld title for ephemera folders
