RELEASE_NOTES.md
app/derivative_services/raster_resource_derivative_service.rb
app/derivative_services/vector_resource_derivative_service.rb
spec/resources/scanned_maps/scanned_map_derivative_service_spec.rb

Fix stale object error for vector and raster derivatives

---

app/graphql/types/resource.rb

Fix GraphQL Resource Comment

---

README.md

Add FFMpeg install directions to README

---

app/resources/scanned_resources/scanned_resource_wayfinder.rb
app/wayfinders/base_wayfinder.rb
spec/services/preserver_spec.rb

Define a preservation_objects relationship for all wayfinders

---

app/change_sets/change_set.rb
app/resources/ephemera_boxes/ephemera_box_change_set.rb
app/resources/ephemera_folders/ephemera_folder_change_set_base.rb
app/resources/ephemera_projects/ephemera_project_change_set.rb
app/services/preserver.rb
spec/resources/ephemera_folders/ephemera_folder_change_set_spec.rb
spec/services/preserver_spec.rb

Preserve Ephemera

---

app/resources/numismatics/coins/numismatics/coin.rb
app/services/manifest_builder.rb
spec/graphql/types/numismatics/coin_type_spec.rb
spec/resources/numismatics/coins/numismatics/coin_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb
spec/services/manifest_builder_spec.rb

Fix coin manifest ids and title display

---

app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/coins/numismatics/coin_decorator.rb
spec/resources/numismatics/coins/numismatics/coin_decorator_spec.rb
spec/resources/numismatics/coins/numismatics/coin_spec.rb

Mint ARK identifiers for Coin resources

---

app/helpers/application_helper.rb
public/viewer.html
spec/helpers/application_helper_spec.rb

Viewer uses dynamic config instead of requiring each embedding app to set it themselves

---

public/viewer.html

Fixing broken viewer config URL

Fixing viewer config URL

---

RELEASE_NOTES.md
app/models/ability.rb
app/resources/playlists/playlist_decorator.rb
spec/factories/playlist.rb
spec/factories/scanned_resource.rb
spec/models/ability_spec.rb

Allows anonymous download of files in a playlist with a token.
Closes #3475

Allows anonymous download of files in a playlist with a token

---

RELEASE_NOTES.md
app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/references_builder.rb
app/services/geo_discovery/document_builder/wxs.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/services/geo_discovery/document_builder_spec.rb

Remove WFS endpoints from raster geoblacklight docs and add WCS endpoints

---

RELEASE_NOTES.md
app/services/geo_discovery/document_builder/relationship_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

Ensure child scanned maps are suppressed in GeoBlacklight

---

RELEASE_NOTES.md
app/services/pulfa_exporter.rb
spec/services/pulfa_exporter_spec.rb

Fixes https://github.com/pulibrary/figgy/issues/3499

Gracefully handle the situation when an EAD can't be found.

---

app/services/manifest_builder/thumbnail_builder.rb

Thanks to @aaron-collier for reporting these!

Fixing typos in profile URLs

---

RELEASE_NOTES.md
app/assets/stylesheets/components/flash.scss

Fix z-index of the flash message bar.

---

.rubocop.yml
Gemfile
Gemfile.lock
RELEASE_NOTES.md
app/controllers/oai_controller.rb
app/models/oai_provider.rb
app/models/oai_provider/marc21.rb
app/models/oai_provider/oai_wrapper.rb
app/models/oai_provider/valkyrie_provider_model.rb
app/queries/paged_all_query.rb
config/initializers/valkyrie.rb
config/routes.rb
spec/controllers/oai_controller_spec.rb
spec/models/oai_provider/valkyrie_provider_model_spec.rb

Implement OAI-PMH for MARC21

---

Gemfile
Gemfile.lock
RELEASE_NOTES.md

Ensures that BrowseEverything grants users access to shared Google Drive items

---

app/services/music_import_service.rb
app/services/music_import_service/recording_collector.rb
lib/tasks/music_reserves.rake

Improve music import logging

---

RELEASE_NOTES.md
app/resources/numismatics/issues/numismatics/issue.rb
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/resources/numismatics/places/numismatics/place_change_set.rb
app/views/numismatics/issues/_numismatic_place_fields.html.erb
app/views/numismatics/issues/edit_fields/_numismatic_place.html.erb
spec/resources/numismatics/issues/numismatics/issue_change_set_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb
spec/resources/numismatics/places/numismatics/place_change_set_spec.rb

Introduced nest Numismatic Places into the forms for Numismatic Issues

---

RELEASE_NOTES.md
app/controllers/base_resource_controller.rb
app/helpers/metadata_form_helper.rb
app/resources/ephemera_folders/ephemera_folder_change_set_base.rb
app/resources/templates/templates_controller.rb
app/views/records/edit_fields/_member_of_collection_ids.html.erb
spec/support/shared/ephemera_folder_change_set_specs.rb

Ephemera collections

---

RELEASE_NOTES.md

Fixing the formatting for the release notes

---

db/migrate/20200106182149_add_preservation_object_indexes.rb
db/structure.sql
spec/services/cloud_fixity_spec.rb

This index speeds up the query from 11s to 20ms.

Fix slow query on Catalog Show Page.

---

app/exporters/hathi/content_package.rb
spec/exporters/hathi/content_package_spec.rb

Tests for ocr? and hocr? were broken because not dealing with empty string.

Deposit files error

---

app/resources/numismatics/accessions/numismatics/accession.rb
app/resources/numismatics/accessions/numismatics/accession_decorator.rb
spec/resources/numismatics/accessions/numismatics/accession_decorator_spec.rb
spec/resources/numismatics/accessions/numismatics/accession_spec.rb

Enhance indexed numismatic accession title

---

app/resources/numismatics/issues/numismatics/issues_controller.rb

Correctly load numismatic issue member monogram ids

---

RELEASE_NOTES.md
app/change_sets/change_set.rb
app/resources/scanned_resources/recording_change_set.rb
app/views/catalog/_admin_controls_recording.html.erb
spec/resources/scanned_resources/recording_change_set_spec.rb
spec/views/catalog/_admin_controls_default.html.erb_spec.rb
spec/views/catalog/_admin_controls_recording.html.erb_spec.rb

Add structure editor to Recordings.

---

RELEASE_NOTES.md
app/assets/stylesheets/application.scss
app/javascript/components/ajax-select.vue
app/javascript/helpers/setup_ajax_select.js
app/javascript/packs/application.js
app/models/search_builder.rb
app/resources/numismatics/coins/numismatics/coins_controller.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/resources/numismatics/issues/numismatics/issues_controller.rb
app/views/numismatics/coins/_loan_fields.html.erb
app/views/numismatics/coins/_provenance_fields.html.erb
app/views/numismatics/coins/edit_fields/_append_id.html.erb
app/views/numismatics/coins/edit_fields/_find_place_id.html.erb
app/views/numismatics/issues/_numismatic_artist_fields.html.erb
app/views/numismatics/issues/edit_fields/_numismatic_place_id.html.erb
app/views/records/edit_fields/_numismatic_accession_id.html.erb
app/views/records/edit_fields/_numismatic_citation_fields.html.erb
package.json
spec/resources/numismatics/accessions/numismatics/accession_feature_spec.rb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb
spec/resources/numismatics/coins/numismatics/coins_controller_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb
yarn.lock

Co-authored-by: James Griffin <jrgriffiniii@gmail.com>
Closes #2715

Add ajax-powered select elements for numismatic issues and coins

---

RELEASE_NOTES.md
app/resources/ephemera_folders/ephemera_folder_decorator.rb
spec/change_set_persisters/change_set_persister_spec.rb

Output collection slugs in Ephemera Folder events.

---

app/models/concerns/linked_data/linked_ephemera_folder.rb
spec/models/linked_data/linked_ephemera_folder_spec.rb

Add Project Title to "memberOf" for JSON-LD DPUL Sync.

---

RELEASE_NOTES.md
app/services/music_import_service.rb
spec/services/music_import_service_spec.rb

Combine two PUO recordings with the same bib-id into one Recording

---

RELEASE_NOTES.md
app/services/music_import_service.rb
spec/services/music_import_service_spec.rb

Add selection title in PUO logical structure.

---

RELEASE_NOTES.md
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/views/numismatics/issues/edit_fields/_master_id.html.erb
app/views/numismatics/issues/edit_fields/_ruler_id.html.erb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Add Person dropdown functionality for Master/Ruler

---

RELEASE_NOTES.md
app/models/search_builder.rb
spec/controllers/catalog_controller_spec.rb

allows staff users to use vue select in numismatics issue form

---

RELEASE_NOTES.md
app/queries/find_facet_values.rb
app/resources/numismatics/issues/numismatics/issue_decorator.rb
app/resources/numismatics/issues/numismatics/issue_wayfinder.rb
app/resources/numismatics/issues/numismatics/issues_controller.rb
app/values/facet_item.rb
app/views/records/edit_fields/_color.html.erb
app/views/records/edit_fields/_denomination.html.erb
app/views/records/edit_fields/_edge.html.erb
app/views/records/edit_fields/_metal.html.erb
app/views/records/edit_fields/_object_type.html.erb
app/views/records/edit_fields/_shape.html.erb
config/initializers/valkyrie.rb
spec/features/numismatic_issue_spec.rb
spec/resources/numismatics/issues/numismatics/issue_wayfinder_spec.rb
spec/resources/numismatics/issues/numismatics/issues_controller_spec.rb

Use solr queries to populate  numismatic issue select boxes

---

RELEASE_NOTES.md
app/resources/numismatics/issues/numismatics/issue_wayfinder.rb
app/views/catalog/_universal_viewer_issue.html.erb
spec/resources/numismatics/issues/numismatics/issue_wayfinder_spec.rb
spec/views/catalog/_universal_viewer_issue.html.erb_spec.rb

Ensuring that the Universal Viewer is not rendered for Issues where Coins do not have FileSets

---

.circleci/config.yml

This was recommended to me by @carolyncole based upon their work in https://github.com/pulibrary/approvals/pull/589/files

Uses the POSTGRES_HOST_AUTH_METHOD as opposed to POSTGRES_PASSWORD in the CircleCI configuration

---

.rubocop.yml
RELEASE_NOTES.md
app/javascript/helpers/setup_ajax_select.js
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

I am still testing this, but given that this seems to be a higher priority issue, I thought that I should offer this in order to expedite requesting input.
Resolves #3666

Ensuring that Vue ajax-select Components are mounted when added in multiple select fields for Numismatic Issues

---

.rubocop.yml
RELEASE_NOTES.md
app/helpers/application_helper.rb
app/models/resource.rb
app/resources/ephemera_folders/ephemera_folder.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/coins/numismatics/coins_controller.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/resources/numismatics/issues/numismatics/issues_controller.rb
app/views/base/_form_progress.html.erb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Integrates the "Save and Duplicate Metadata" feature for Numismatic Issues and Coins

---

RELEASE_NOTES.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/form.scss
app/assets/stylesheets/components/vue_select.scss
app/javascript/components/ajax-select.vue
app/views/numismatics/coins/edit_fields/_append_id.html.erb
app/views/numismatics/coins/edit_fields/_find_place_id.html.erb
app/views/numismatics/issues/edit_fields/_master_id.html.erb
app/views/numismatics/issues/edit_fields/_numismatic_place_id.html.erb
app/views/numismatics/issues/edit_fields/_ruler_id.html.erb
app/views/records/edit_fields/_numismatic_accession_id.html.erb

- Fixes bug with searching using unicode characters
- Improves select box layout
- Adds an additional wildcard (*) character to make search more flexible
Closes #3694 
Closes #3688

Improvements to numismatics AJAX select widget

---

RELEASE_NOTES.md
app/controllers/application_controller.rb
config/application.rb
spec/requests/sessions_spec.rb

Log user out of CAS when logging out of Figgy

---

RELEASE_NOTES.md
app/models/ability.rb
spec/controllers/downloads_controller_spec.rb

Fix HLS authorized token download permissions.

---

RELEASE_NOTES.md
app/assets/stylesheets/components/form.scss
app/views/numismatics/coins/_form.html.erb
app/views/numismatics/issues/_form.html.erb

[WIP] Update the numismatics form to have smaller padding and margin

---

spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Update issue_feature_spec monogram panel

---

RELEASE_NOTES.md
app/helpers/application_helper.rb
app/views/collections/_bulk_edit_button.html.erb
spec/features/bulk_edit_spec.rb

Allow Coins, Scanned Maps, Vector and Raster Resources to be bulk edited

---

RELEASE_NOTES.md
app/assets/javascripts/figgy_boot.es6
app/views/catalog/_members_issue.html.erb

Set default sort order for coin members data table

---

RELEASE_NOTES.md
app/resources/numismatics/citations/numismatics/citation.rb
app/resources/numismatics/citations/numismatics/citation_change_set.rb
app/views/numismatics/coins/edit_fields/_numismatic_citation.html.erb
app/views/numismatics/coins/edit_fields/_numismatic_citation_fields.html.erb
app/views/records/edit_fields/_numismatic_citation_fields.html.erb
spec/resources/numismatics/citations/numismatics/citation_change_set_spec.rb
spec/resources/numismatics/citations/numismatics/citation_spec.rb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb

- Adds citation type to nested citation resource.
- Reorganizes citation form.
Closes #3702 
Closes #3708

Add citation type to nested citation resource

---

RELEASE_NOTES.md
app/resources/numismatics/coins/numismatics/coin_change_set.rb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb

Hide PDF Type field on coin edit form

---

app/resources/numismatics/coins/numismatics/coin_change_set.rb
spec/resources/numismatics/coins/numismatics/coin_change_set_spec.rb

Change name of Coin Loans panel to Loans and Exhibits

---

RELEASE_NOTES.md
app/javascript/components/ajax-select.vue
app/queries/find_facet_values.rb

- Sorts values alphabetically for both types of numismatics drop downs.
Closes #3704

Sort numismatics drop down values alphabetically

---

RELEASE_NOTES.md
app/resources/numismatics/references/numismatics/reference_decorator.rb
spec/indexers/title_indexer_spec.rb
spec/resources/numismatics/references/numismatics/reference_decorator_spec.rb

Refine indexed numismatic reference title

---

RELEASE_NOTES.md
app/resources/numismatics/coins/numismatics/coin_change_set.rb

- Adds thumbnail_id property to coin change set
Closes #3745

Allows coin thumbnail to be set in the order manager

---

RELEASE_NOTES.md
app/services/file_appender.rb
spec/change_set_persisters/change_set_persister_spec.rb

Title coin FileSets based on original file name

---

.circleci/config.yml
RELEASE_NOTES.md
app/derivative_services/jp2_derivative_service.rb
spec/services/geo_discovery/document_builder/layer_info_builder_spec.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb
spec/services/geo_discovery/document_builder_spec.rb
spec/support/stub_fixity.rb

Our Kakadu license is running out and we believe this will work for us.
Closes #2989
Requires https://github.com/pulibrary/princeton_ansible/pull/1359

Generate JP2s with OpenJPEG

---

RELEASE_NOTES.md
public/uv/lib/pdfobject.js

Looks like this was just missed when we updated UV.
Closes #3506

Add missing UV PDFObject.js library.

---

spec/services/orangelight_reindexer_spec.rb

Unset ENV["BULK"] after spec of orangelight reindexer is run

---

app/services/manifest_builder.rb
config/config.yml
spec/services/manifest_builder_spec.rb

We have to disable pyramidals until we get our lambda limit increased.
This will make it easy to do that.

Add an environment variable switch for Pyramidals.

---

Gemfile
Gemfile.lock

This should reduce our data transfer costs to only those which are
absolutely necessary.

Use delayed valkyrie-shrine reads.

---

RELEASE_NOTES.md
app/services/pdf_generator/cover_page_generator.rb
spec/services/pdf_generator_spec.rb

Fix pdf generation for coin resources

---

app/resources/nested_resources/file_metadata.rb
app/services/manifest_builder/thumbnail_builder.rb
spec/services/manifest_builder/thumbnail_builder_spec.rb

Don't create manifest thumbnail entries for Audio files.

---

RELEASE_NOTES.md
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/coins/numismatics/coin_change_set.rb
spec/decorators/valkyrie/resource_decorator_spec.rb
spec/resources/numismatics/coins/numismatics/coin_change_set_spec.rb
spec/resources/numismatics/coins/numismatics/coin_spec.rb

Allow download of coin images from viewer

---

app/services/event_generator/geoserver_event_generator.rb
spec/services/event_generator/geoserver_event_generator_spec.rb

Ensure scanned maps don't trigger a GeoServer event

---

.lando.yml
Procfile
README.md
config/application.rb
config/blacklight.yml
config/lando_env.rb
spec/support/clean_solr.rb

Just playing with Lando as an option for dev dependencies.

use Lando for solr

---

config/config.yml

Add pyramidals_bucket config

---

app/derivative_services/vips_derivative_service.rb
app/models/pending_upload.rb
app/services/file_appender.rb
spec/derivative_services/vips_derivative_service_spec.rb

This allows our lambda image server to work.

Upload height/width to S3 Metadata with VIPS.

---

app/resources/ephemera_folders/ephemera_folder_change_set.rb
spec/resources/ephemera_folders/ephemera_folder_change_set_spec.rb

Remove width/height requirement from Ephemera Folders

---

RELEASE_NOTES.md
app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/clear_remote_metadata.rb
spec/change_set_persisters/change_set_persister_spec.rb

Clear imported metadata when removing source metadata identifier.

---

RELEASE_NOTES.md
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/test/__snapshots__/orderManagerFilesetsForm.spec.js.snap
package.json
yarn.lock

Add two-up support to order manager.

---

RELEASE_NOTES.md
app/javascript/components/OrderManager.vue
app/javascript/components/OrderManagerControls.vue
app/javascript/store/resource/index.js
app/javascript/store/vuex/actions.js
app/javascript/test/__snapshots__/orderManager.spec.js.snap
app/javascript/test/orderManagerControls.spec.js

This also locks up the "Apply Changes" button while it's trying to save.
Closes #3824

Provide a loading bar while the order manager is saving.

---

RELEASE_NOTES.md
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/test/orderManagerFilesetsForm.spec.js

Allow unnumbered labels in order manager

---

RELEASE_NOTES.md
app/services/geo_discovery/document_builder/spatial_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

 Use first valid coverage value when generating GeoBlacklight document

---

RELEASE_NOTES.md
app/change_sets/change_set.rb
app/controllers/catalog_controller.rb
app/models/schema/common.rb
app/models/schema/geo.rb
app/resources/ephemera_folders/ephemera_folder.rb
app/resources/ephemera_folders/ephemera_folder_change_set_base.rb
app/resources/media_resources/media_resource_change_set.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/coins/numismatics/coin_change_set.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/resources/raster_resources/raster_resource_change_set.rb
app/resources/scanned_maps/scanned_map_change_set.rb
app/resources/scanned_resources/letter_change_set.rb
app/resources/scanned_resources/recording_change_set.rb
app/resources/scanned_resources/scanned_resource_change_set.rb
app/resources/scanned_resources/simple_change_set.rb
app/resources/vector_resources/vector_resource_change_set.rb
app/views/catalog/_show_header_default.html.erb
spec/controllers/catalog_controller_spec.rb
spec/resources/scanned_resources/scanned_resource_change_set_spec.rb
spec/views/catalog/_show_header_default.html.erb_spec.rb

Add the ability to "Claim" a resource.

---

RELEASE_NOTES.md
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/test/__snapshots__/orderManagerFilesetsForm.spec.js.snap
app/javascript/test/orderManagerFilesetsForm.spec.js

Add support for bracketing of even and odd numbered pages

---

RELEASE_NOTES.md
app/helpers/application_helper.rb
spec/models/remote_record_spec.rb
spec/views/catalog/_resource_attributes_default.html.erb_spec.rb

Add link to pulfa when source metadata id is a component id

---

app/controllers/bulk_ingest_controller.rb
app/jobs/bulk_browse_everything_cloud_ingest_job.rb
app/services/bulk_cloud_ingester.rb
spec/controllers/bulk_ingest_controller_spec.rb

Perform bulk cloud ingest in background.

---

app/controllers/bulk_ingest_controller.rb
app/jobs/bulk_browse_everything_cloud_ingest_job.rb
app/services/bulk_cloud_ingester.rb

It's not required if we require that MVWs have a parent directory.
Work towards #3724

Remove the mvw option.

---

Gemfile
Gemfile.lock
package.json
yarn.lock

Fixes google picker in staging.

Use authResponse fix in browse everything redux react.

---

app/models/remote_record.rb
spec/models/remote_record_spec.rb

Handle nil in RemoteRecord.record_url

---

app/views/catalog/_members_issue.html.erb
spec/views/catalog/_members_issue.html.erb_spec.rb

Update issue show page "no coins" message

---

.rubocop.yml
lib/tasks/numismatics.rake

refs #3848
Tried it in staging and ran fine.

Add rake task to report on unlabeled coin images

---

lib/tasks/numismatics.rake

refs #3848
tested in staging 👍

Don't include coins without filesets in "to label" report

---

Gemfile
Gemfile.lock

Remove rb-readline from dev / test

---

RELEASE_NOTES.md
app/views/numismatics/issues/edit_fields/_shape.html.erb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Fix selected shape on numismatic issue form

---

RELEASE_NOTES.md
app/resources/numismatics/coins/orangelight_coin_builder.rb
spec/services/orangelight_document_spec.rb

Capitalize a subset of issue / coin fields at index time
refs #3869; reindex required to close.

3869 field capitalization

---

RELEASE_NOTES.md
app/views/numismatics/issues/edit_fields/_color.html.erb
app/views/numismatics/issues/edit_fields/_denomination.html.erb
app/views/numismatics/issues/edit_fields/_edge.html.erb
app/views/numismatics/issues/edit_fields/_metal.html.erb
app/views/numismatics/issues/edit_fields/_object_type.html.erb
app/views/numismatics/issues/edit_fields/_shape.html.erb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Ensure numismatic issue autocomplete forms default to blank

---

app/adapters/bagit/bag_exporter.rb
app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/cache_parent_id.rb
app/models/schema/common.rb
app/models/schema/geo.rb
app/resources/ephemera_boxes/ephemera_box.rb
app/resources/ephemera_folders/ephemera_folder.rb
app/resources/file_sets/file_set.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/services/migrations/add_cached_parent_ids_migrator.rb
lib/tasks/migrate.rake
spec/change_set_persisters/change_set_persister_spec.rb
spec/services/migrations/add_cached_parent_ids_migrator_spec.rb

This will allow for fast queries of everything that has a parent, which
is necessary for things like OAI.
Work towards #3917

Add CachedParentID to all children.

---

.rubocop.yml
app/models/oai_provider/valkyrie_provider_model.rb
app/queries/paged_all_query.rb
spec/controllers/oai_controller_spec.rb
spec/factories/scanned_resource.rb
spec/models/oai_provider/valkyrie_provider_model_spec.rb

Should fix our Getty export.
Closes #3904

Hide Volumes/Incomplete/Non-Public resources from OAI

---

RELEASE_NOTES.md
app/assets/javascripts/figgy_boot.es6
app/assets/javascripts/relationships/parent_resources_table.es6
app/assets/javascripts/relationships/related_resources_table.es6
app/assets/stylesheets/components/show.scss
app/views/catalog/_member_resources_raster_resource.html.erb
app/views/catalog/_member_resources_scanned_map.html.erb
app/views/catalog/_member_resources_scanned_resource.html.erb
app/views/catalog/_member_resources_vector_resource.html.erb
app/views/catalog/_members_multi_volume_work.html.erb
app/views/catalog/_members_scanned_resource.html.erb
app/views/catalog/_parent_resources_raster_resource.html.erb
app/views/catalog/_parent_resources_scanned_map.html.erb
app/views/catalog/_parent_resources_vector_resource.html.erb
spec/views/catalog/_members_multi_volume_work.html.erb_spec.rb
spec/views/catalog/_members_scanned_resource.html.erb_spec.rb

Allow users to attach existing volumes to scanned resources

---

package.json
yarn.lock

Had to update babel/preset-env package. Should fix CI.

Fix CI / Add support for NodeJS 12.17 and 12.18

---

.circleci/config.yml
app/derivative_services/vips_derivative_service.rb
bin/ci_vips_install.sh

Convert color space to SRGB through VIPS

---

app/services/pdf_generator.rb
app/services/pdf_generator/canvas.rb
app/services/pdf_generator/canvas_downloader.rb
spec/services/pdf_generator_spec.rb

PDFs embed OCR as searchable text.

---

app/models/concerns/linked_data/linked_imported_resource.rb
app/resources/scanned_resources/scanned_resource_decorator.rb
spec/models/linked_data/linked_imported_resource_spec.rb
spec/services/manifest_builder_spec.rb

Add Finding Aid Metadata to JSON-LD.

---

app/change_set_persisters/change_set_persister/propagate_visibility_and_state.rb
spec/change_set_persisters/change_set_persister_spec.rb

Disabling collection state/visibility propagation

---

config/deploy/staging.rb

Deploy to figgy-staging2.

---

config/deploy.rb

Tested in staging and works.
Closes #3359

Add missing environment variable for Fixity function.

---

app/models/oai/figgy/provider.rb
spec/controllers/oai_controller_spec.rb

Add admin email to oai response

---

app/models/oai/figgy/provider.rb
spec/controllers/oai_controller_spec.rb

Provide a sample uuid in oai information response

---

RELEASE_NOTES.md
app/services/pul_metadata_services/pulfa_record.rb
spec/services/pul_metadata_services/pulfa_record_spec.rb

Add physical dimensions to extent from finding aids

---

app/models/oai/figgy/valkyrie_provider_model.rb
app/queries/pluck_earliest_updated_at.rb
config/initializers/valkyrie.rb
spec/controllers/oai_controller_spec.rb
spec/queries/pluck_earliest_updated_at_spec.rb

Add Earliest time to OAI-PMH.

---

config/schedule.rb

Removed system user reference

---

.rubocop.yml
app/models/oai/figgy/oai_wrapper.rb
app/wayfinders/base_wayfinder.rb
spec/controllers/oai_controller_spec.rb
spec/wayfinders/wayfinder_spec.rb

Add format to oai_dc response

---

spec/controllers/oai_controller_spec.rb

Fix format test

---

app/models/oai/figgy/oai_wrapper.rb
spec/controllers/oai_controller_spec.rb

Add source to oai_dc response

---

app/models/remote_record.rb
app/models/schema/common.rb
spec/models/scanned_resource_spec.rb

Pull format from bibdata json

---

app/models/oai/figgy/oai_wrapper.rb
spec/controllers/oai_controller_spec.rb

depends on #4011 and will need to be rebased once that's merged.

Add type to oai_dc response

---

app/models/oai/figgy/oai_wrapper.rb
spec/controllers/oai_controller_spec.rb

Add description, contributor, and subject fields to oai_dc

---

RELEASE_NOTES.md

Add release note for oai_dc completion

---

app/resources/numismatics/coins/orangelight_coin_builder.rb
spec/services/orangelight_document_spec.rb

Remove Issue Number from orangelight numismatics document

---

app/jobs/create_ocr_request_job.rb
app/jobs/pdf_ocr_job.rb

Closes #4013 
Depends on https://github.com/pulibrary/princeton_ansible/pull/1605

Queue PDF OCR request jobs as 'high'

---

bin/pdf_watcher

Ensure that PDFs staged for OCR match ILLiad naming scheme

---

app/resources/cdl/charge_manager.rb
app/resources/cdl/charged_item.rb
spec/factories/cdl/charged_item.rb
spec/resources/cdl/charge_manager_spec.rb

Seeking feedback on refactors or adjustments
fixes #4039

Clean up expired charges when ChargeManager is initialized

---

config/initializers/analyze_job.rb
spec/jobs/active_storage/analyze_job_spec.rb

Rescue ActiveJob::DeserializationError

---

.rubocop.yml
app/decorators/valkyrie/resource_decorator.rb
app/models/ability.rb
app/resources/cdl/charge_manager.rb
app/resources/cdl/eligible_item_service.rb
app/resources/vector_resources/vector_resource_decorator.rb
spec/models/ability_spec.rb
spec/resources/cdl/charge_manager_spec.rb
spec/resources/cdl/eligible_item_service_spec.rb

CDL Manifest Permissions

---

app/controllers/viewer_controller.rb
app/views/viewer/auth.html.erb
spec/controllers/viewer_controller_spec.rb

Add login button for CDL items.

---

app/resources/cdl/cdl_controller.rb
app/resources/cdl/charge_manager.rb
app/resources/cdl/status.rb
config/routes.rb
spec/resources/cdl/cdl_controller_spec.rb

Add CDL Charge Status API

---

app/resources/cdl/cdl_controller.rb
app/resources/cdl/status.rb
config/routes.rb
spec/resources/cdl/cdl_controller_spec.rb

Add charge action for CDL

---

app/assets/stylesheets/viewer.scss
app/controllers/viewer_controller.rb
app/resources/cdl/charge_manager.rb
app/views/viewer/cdl_checkout.html.erb
spec/controllers/viewer_controller_spec.rb
spec/resources/cdl/charge_manager_spec.rb

Add CDL Checkout Page

---

.eslintrc.js
app/assets/stylesheets/viewer.scss
app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/viewer/cdl_timer.js
app/javascript/viewer/uv_manager.js
app/models/ability.rb
package.json
spec/models/ability_spec.rb
yarn.lock

This PR also includes a fix to `Ability` which wasn't blocking expired charges from seeing the item.
Closes #4032

Add Expiration Timer to UV for CDL

---

app/jobs/bulk_update_job.rb
app/models/search_builder.rb
app/services/bulk_ingest_service.rb
app/services/manifest_builder.rb
app/services/reindexer.rb

Reviewer note: please do ensure I chose appropriate names; there were a variety
of contexts.
fixes #4054

Remove all remaining uses of "blacklist"

---

spec/services/bulk_ingest_service_spec.rb

Really remove the last use of "blacklist" for real this time

---

app/controllers/concerns/resource_controller.rb
app/javascript/components/file-uploader.vue
app/models/search_builder.rb
app/views/base/_file_manager_extra_tools.html.erb
app/views/base/_local_upload.html.erb
app/views/ocr_requests/index.html.erb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

This uses the Vue Dropzone component we use for PDF OCR Upload.
Closes #4071, closes #4072

Add local file upload to File Manager.

---

app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js

Add a test for viewer auth redirect.

---

app/views/viewer/cdl_checkout.html.erb
spec/controllers/viewer_controller_spec.rb

Update button caption to be: Check Out for 3 Hours

---

app/javascript/components/file-uploader.vue

Set dropzone timeout to 5 minutes.

---

app/resources/cdl/charge_manager.rb
app/resources/cdl/hold.rb
spec/resources/cdl/charge_manager_spec.rb

Add ChargeManager#create_hold

---

app/values/viewer_configuration.rb
spec/requests/viewer_config_spec.rb
spec/values/viewer_configuration_spec.rb

Enable share widget.

---

app/resources/cdl/eligible_item_service.rb
spec/fixtures/files/bibdata/1377084.json
spec/fixtures/files/bibdata/7214786.json
spec/resources/cdl/eligible_item_service_spec.rb

Update the EligibleItemService to look for patron_group_charged: "CDL"

---

app/resources/cdl/cdl_controller.rb
app/resources/cdl/charge_manager.rb
app/views/viewer/cdl_checkout.html.erb
config/routes.rb
spec/controllers/viewer_controller_spec.rb
spec/resources/cdl/cdl_controller_spec.rb
spec/resources/cdl/charge_manager_spec.rb

Add a CDL Hold Frontend

---

app/resources/cdl/charge_manager.rb
app/resources/cdl/hold.rb
app/resources/cdl/hold_mailer.rb
app/resources/cdl/resource_charge_list.rb
app/views/cdl/hold_mailer/hold_activated.html.erb
app/views/cdl/hold_mailer/hold_expired.html.erb
app/views/viewer/cdl_checkout.html.erb
config/application.rb
spec/factories/cdl/resource_charge_list.rb
spec/resources/cdl/charge_manager_spec.rb

Closes #4090 
This also includes some refactors to move around responsibilities a bit.
The emails aren't pretty, but there's another ticket to look at that: #4117

Activate/Expire Holds & Notify Users

---

app/resources/cdl/resource_charge_list.rb
app/resources/cdl/resource_charge_list_change_set.rb
spec/resources/cdl/resource_charge_list_spec.rb

Enable and test optimistic locking for ResourceChargeList.

---

.rubocop.yml
app/resources/cdl/charge_manager.rb
app/resources/cdl/event_logging.rb
spec/resources/cdl/bulk_hold_processor_spec.rb
spec/resources/cdl/cdl_controller_spec.rb
spec/resources/cdl/charge_manager_spec.rb
spec/resources/cdl/event_logging_spec.rb

Track events in google analytics for the CDL Hold Queue

---

app/change_sets/change_set.rb
app/resources/cdl/resource_change_set.rb
config/locales/en.yml
config/routes.rb
spec/resources/cdl/resource_change_set_spec.rb
spec/routing/cdl_resource_spec.rb

Add CDL::ResourceChangeSet

---

config/deploy/production.rb
config/schedule.rb

Please resolve the HB error on merge / deploy
fixes #3462
Co-authored-by: Kate Lynch <katelynch@princeton.edu>

Only run export:pulfa on production db

---

Gemfile
Gemfile.lock
app/resources/cdl/automatic_ingester.rb
app/resources/cdl/pdf_ingest_job.rb
app/resources/cdl/resource_change_set.rb
config/config.yml
config/schedule.rb
lib/tasks/cdl.rake
spec/resources/cdl/automatic_ingester_spec.rb
spec/resources/cdl/pdf_ingest_job_spec.rb

Work towards #4133 
Ansible PR: https://github.com/pulibrary/princeton_ansible/pull/1663

Add Automatic CDL Ingester

---

app/resources/scanned_maps/scanned_map_decorator.rb
app/resources/scanned_resources/scanned_resource_decorator.rb
spec/resources/scanned_maps/scanned_map_decorator_spec.rb
spec/resources/scanned_resources/scanned_resource_decorator_spec.rb

Added handling for Voyager downtime in IIIF manifests and test coverage

---

app/resources/cdl/eligible_item_service.rb
spec/fixtures/files/bibdata/922720.json
spec/resources/cdl/eligible_item_service_spec.rb

Fix CDL Eligibility for items with multiple holdings/locations

---

app/services/event_generator/geoblacklight_event_generator.rb
spec/services/event_generator/geoblacklight_event_generator_spec.rb

Don't send messages to RabbitMQ for records that generate invalid GeoBlacklight documents

---

app/derivative_services/pdf_derivative_service.rb
spec/derivative_services/pdf_derivative_service_spec.rb

Improve derivatives of PDF intermediate files.

---

.rubocop.yml
app/assets/stylesheets/viewer.scss
app/controllers/viewer_controller.rb
app/models/ability.rb
app/resources/collections/collection.rb
app/resources/collections/collection_change_set.rb
app/resources/collections/collection_decorator.rb
app/views/viewer/auth.html.erb
spec/controllers/viewer_controller_spec.rb
spec/models/ability_spec.rb
spec/resources/collections/collection_change_set_spec.rb
spec/resources/collections/collection_spec.rb

Collection Restricted Viewers

---

app/services/ingest_ephemera_mods.rb
spec/fixtures/files/GNIB/00223.mods
spec/services/ingest_ephemera_mods_spec.rb

MInimal implementation for #4180

Implements Ingester for GNIB MODS

---

.rubocop.yml
app/resources/cdl/pdf_ingest_job.rb
spec/resources/cdl/pdf_ingest_job_spec.rb

Raise an error if an auto PDF ingest doesn't attach a file.

---

.circleci/config.yml
bin/ci_check_release_notes.sh

Restore nightly build and fix release notes check

---

app/resources/cdl/cdl_controller.rb
app/resources/cdl/charge_manager.rb
app/resources/cdl/resource_charge_list.rb
config/routes.rb
spec/resources/cdl/cdl_controller_spec.rb
spec/resources/cdl/charge_manager_spec.rb

Add return action to CDL controller

---

app/resources/cdl/automatic_completer.rb
spec/factories/scanned_resource.rb
spec/resources/cdl/automatic_completer_spec.rb

CDL AutomaticCompleter should check for Draft instead of Pending

---

RELEASE_NOTES.md
app/assets/stylesheets/viewer.scss
app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/viewer/cdl_timer.js
app/views/viewer/index.html.erb

Add a button to return a CDL item early

---

app/jobs/ingest_gnib_mods_job.rb
app/services/ingest_ephemera_mods.rb
lib/tasks/migrate.rake
spec/jobs/ingest_gnib_mods_job_spec.rb
spec/services/ingest_ephemera_mods_spec.rb

Copied almost verbatim from IngestUkrainianEphemera code.

Jobs and Tasks for ingesting GNIB records

---

app/characterization_services/pdf_characterization_service.rb
app/resources/cdl/automatic_completer.rb
app/resources/nested_resources/file_metadata.rb
config/initializers/valkyrie.rb
spec/characterization_services/pdf_characterization_service_spec.rb

PDF Characterization Service

---

app/resources/cdl/complete_mailer.rb
spec/resources/cdl/automatic_completer_spec.rb

Also email reserves for completion email.

---

app/controllers/application_controller.rb
app/javascript/viewer/uv_manager.js
app/values/viewer_configuration.rb
spec/controllers/application_controller_spec.rb
spec/values/viewer_configuration_spec.rb

Disable share/download for CDL enabled items.

---

app/resources/cdl/eligible_item_service.rb
spec/resources/cdl/eligible_item_service_spec.rb

Handle JSON::ParserError in EligibleItemService

---

app/models/oai/figgy/oai_wrapper.rb
spec/controllers/oai_controller_spec.rb

Add another identifier entry to oai_dc with full ark uri

---

lib/tasks/bulk.rake

Supports ingest of pudl0009 and similar legacy collections

Adds rake task to ingest directory of Stroop-style METS

---

architecture-decisions/0009-unlinked-files.md

Add ADR about unlinked files.

---

app/services/file_appender.rb
spec/derivative_services/pdf_derivative_service_spec.rb

Set thumbnail for PDF derivatives.

---

.rubocop.yml
app/services/pulfa_exporter.rb
spec/services/pulfa_exporter_spec.rb

Add download links to DAO for zip files.

---

app/resources/cdl/hold_mailer.rb
app/resources/cdl/resource_charge_list.rb
app/views/cdl/hold_mailer/_header.html.erb
app/views/cdl/hold_mailer/hold_activated.html.erb
app/views/cdl/hold_mailer/hold_expired.html.erb
app/views/layouts/holds/mailer.html.erb

Style Hold Expired/Activated Emails

---

app/resources/ephemera_folders/ephemera_folder_decorator.rb
spec/resources/ephemera_folders/ephemera_folder_feature_spec.rb

Ephemera Folders should show collections they're a member of.

---

lib/tasks/bulk.rake

to support ingest of Derrida resources.

Adds title and note as options to pass into bulk ingest task

---

app/indexers/facet_indexer.rb
spec/fixtures/files/bibdata/10001790.jsonld
spec/fixtures/files/bibdata/10001791.jsonld
spec/fixtures/files/bibdata/10001792.jsonld
spec/indexers/facet_indexer_spec.rb

Add index field pub_date_start_itsi

---

app/resources/cdl/charge_manager.rb
spec/resources/cdl/bulk_hold_processor_spec.rb

Try using deliver_now for hold_activated emails

---

app/resources/cdl/complete_mailer.rb
spec/resources/cdl/automatic_completer_spec.rb

Fixed reserve email

---

lib/tasks/bulk.rake

Bulk append coll

---

app/controllers/catalog_controller.rb

Add Date to Index View.

---

app/derivative_services/hocr_derivative_service.rb
spec/change_set_persisters/change_set_persister_spec.rb

Support OCR for intermediate files if no original file.

---

.circleci/config.yml

CI: Move mediainfo install after apt-get update

---

config/authorities/rights_statement.yml

Adding CC-BY and CC-Zero statements

---

app/javascript/components/file-uploader.vue
app/resources/ephemera_folders/ephemera_folder_change_set_base.rb
spec/support/shared/ephemera_folder_change_set_specs.rb

Skip validation for Ephemera Folder Drag/Drop

---

app/javascript/store/resource/index.js
app/javascript/store/vuex/actions.js

This will reduce javascript errors.
See follow up issue https://github.com/pulibrary/figgy/issues/4293

Fix order manager javascript errors

---

app/jobs/ingest_ephemera_job.rb
app/jobs/ingest_lae_folder_job.rb
config/initializers/valkyrie.rb
lib/tasks/vocab.rake
spec/services/ingest_ephemera_service_spec.rb
spec/services/ingest_vocab_service_spec.rb

Disk via copy instead of lae_storage

---

RELEASE_NOTES.md
app/resources/numismatics/accessions/numismatics/accession_decorator.rb
app/resources/numismatics/coins/orangelight_coin_builder.rb
app/resources/numismatics/issues/numismatics/issue_decorator.rb
spec/resources/numismatics/accessions/numismatics/accession_decorator_spec.rb
spec/resources/numismatics/issues/numismatics/issue_decorator_spec.rb
spec/services/orangelight_document_spec.rb

Added new fields to the orangelight coin document

---

app/resources/numismatics/coins/numismatics/coin_decorator.rb
app/resources/numismatics/coins/orangelight_coin_builder.rb
app/resources/numismatics/issues/numismatics/issue_decorator.rb
spec/resources/numismatics/issues/numismatics/issue_decorator_spec.rb
spec/services/orangelight_document_spec.rb

Numismatic builder fix 4324

---

app/resources/numismatics/accessions/numismatics/accession_decorator.rb
spec/services/orangelight_document_spec.rb

Improve numismatic accession formatted date generation

---

app/controllers/downloads_controller.rb
spec/controllers/downloads_controller_spec.rb

Don't error if there's no file updated_at.

---

app/jobs/preserve_children_job.rb
spec/jobs/preserve_children_job_spec.rb

PreserveChildrenJob should not error when object not found.

---

config/config.yml

The Global Protect client IPs look like these local ranges to our
servers.

Add local VPN IPs to Figgy's campus IPs

---

app/resources/cdl/eligible_item_service.rb
spec/resources/cdl/eligible_item_service_spec.rb

Don't error in CDL if Voyager is down.

---

RELEASE_NOTES.md
app/models/geo_workflow.rb
spec/models/geo_workflow_spec.rb
spec/resources/raster_resources/raster_resource_change_set_spec.rb
spec/resources/vector_resources/vector_resource_change_set_spec.rb

Allow geo workflow to go from pending to complete

---

app/models/ability.rb
spec/models/ability_spec.rb

Staff should not be able to manage roles.

---

RELEASE_NOTES.md
app/values/geo_coverage.rb
spec/values/geo_coverage_spec.rb

Ensure small floating point geo coverage values are formatted correctly

---

app/assets/javascripts/save_and_ingest_handler.es6
app/resources/scanned_resources/scanned_resources_controller.rb
app/views/base/_form_progress.html.erb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Don't search for save and ingest path twice.

---

Gemfile
Gemfile.lock
README.md
RELEASE_NOTES.md
Rakefile
lib/tasks/dev.rake

- Creates rake tasks for starting and stopping lando
- Removes solr_wrapper.
Closes #4371

 Create rake tasks for starting and stopping lando

---

app/services/ingest_folder_locator.rb

This was only not working in Production. Adding this fixes it.

Add Find to IngestFolderLocator

---

app/resources/scanned_resources/scanned_resource_decorator.rb
spec/resources/scanned_resources/scanned_resource_decorator_spec.rb

Handle created dates not in ISO8601

---

app/models/ability.rb
spec/models/ability_spec.rb

Pass parent object for CDL readability check for MVW child works

---

app/views/viewer/auth.html.erb
spec/controllers/viewer_controller_spec.rb

fixes pulibrary/orangelight#2356

Update wording of cdl link

---

app/services/geo_discovery/document_builder/basic_metadata_builder.rb
spec/services/geo_discovery/document_builder_spec.rb

- Fix for an urgent data request.
- Added a new figgy ticket for a more permanent solution (https://github.com/pulibrary/figgy/issues/4411)

Do not filter VectorResource subjects

---

app/controllers/downloads_controller.rb

Don't notify Honeybadger about download 404s.

---

app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/basic_metadata_builder.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/services/geo_discovery/document_builder_spec.rb

Closes #4411 
Example from figgy-staging
```
"dc_subject_sm": [
"Society"
],
"all_subject_sm": [
"religion",
"religions",
"religious",
"site", 
"sites",
"Buddhism",
"Taoism",
"Islam",
"Christianity",
"worship",
"temple",
"temples",
"mosque",
"mosques",
"church",
"churches",
"Society"
],
```

 Add unfiltered subjects field to geoblacklight document

---

app/resources/collections/collection_decorator.rb
config/locales/en.yml
spec/resources/collections/collection_decorator_spec.rb

Display collection attributes so you don't have to go into the edit form to see all values (or build the DPUL/IIIF URLs yourself)

Improving collection display

---

RELEASE_NOTES.md
app/change_sets/concerns/geo_change_set_properties.rb
app/models/schema/geo.rb
app/resources/raster_resources/raster_resource_change_set.rb
app/resources/vector_resources/vector_resource_change_set.rb
app/services/geo_discovery/document_builder/wxs.rb
spec/resources/raster_resources/raster_resource_feature_spec.rb
spec/resources/vector_resources/vector_resource_feature_spec.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb

Add ogc web service override properties to raster and vector resources

---

RELEASE_NOTES.md
app/change_sets/concerns/geo_change_set_properties.rb
app/models/schema/geo.rb
app/resources/raster_resources/raster_resource_change_set.rb
app/resources/vector_resources/vector_resource_change_set.rb
app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/references_builder.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/resources/raster_resources/raster_resource_feature_spec.rb
spec/resources/vector_resources/vector_resource_feature_spec.rb
spec/services/geo_discovery/document_builder_spec.rb

Add tile_layer_url property to raster and vector resources

---

app/controllers/reports_controller.rb
app/resources/ephemera_folders/ephemera_folder_decorator.rb
spec/controllers/reports_controller_spec.rb

adds additional fields to report

---

app/controllers/reports_controller.rb
app/resources/ephemera_folders/ephemera_folder_decorator.rb
spec/controllers/reports_controller_spec.rb
spec/resources/ephemera_folders/ephemera_folder_decorator_spec.rb

addendum to #4445 
addresses #4440

Includes titles of collections in report

---

app/controllers/catalog_controller.rb
app/helpers/application_helper.rb
app/wayfinders/base_wayfinder.rb
config/routes.rb
spec/controllers/catalog_controller_spec.rb
spec/helpers/application_helper_spec.rb

Adding '/pdf' action to redirect to best PDF version of a resource

---

app/models/ability.rb

Check cdl permissions last to reduce Alma API hits

---

package.json
yarn.lock

This will allow us to upgrade date-and-time, which will address GHSA-r92x-f52r-x54g
See https://github.com/advisories/GHSA-r92x-f52r-x54g for more details
Connected to #4482

Upgrade @google-cloud/storage

---

config/deploy/production.rb

Use figgy3 instead of figgy2.

---

.rubocop.yml
app/services/geo_metadata_extractor/iso19139.rb
spec/fixtures/files/geo_metadata/iso.xml
spec/fixtures/files/geo_metadata/princeton_iso.xml
spec/services/geo_discovery/document_builder_spec.rb
spec/services/geo_metadata_extractor_spec.rb

Extract more metadata from ISO19139 documents

---

app/decorators/upload_decorator.rb
app/resources/file_sets/file_sets_controller.rb
app/services/file_appender.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/resources/file_sets/file_sets_controller_spec.rb

Remove update_files and associated methods.

---

app/resources/ephemera_terms/ephemera_term_decorator.rb
spec/resources/ephemera_terms/ephemera_term_decorator_spec.rb

Encode utf-8 in ephemera terms for uri generation

---

app/resources/numismatics/coins/orangelight_coin_builder.rb
spec/services/orangelight_document_spec.rb

Closes https://github.com/pulibrary/figgy/issues/4551
Closes https://github.com/pulibrary/bibdata/issues/1426
Closes https://github.com/pulibrary/orangelight/issues/2518

Update numismatic orangelight document location

---

Gemfile
Gemfile.lock
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb

Note this has already been fixed in other projects: https://github.com/pulibrary/abid/pull/26
Fixes #4557

Run against released version of archivesspace-client

---

app/services/dao_updater.rb
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb

Fix ASpace Sync

---

app/resources/cdl/eligible_item_service.rb
spec/resources/cdl/eligible_item_service_spec.rb

Refs https://github.com/pulibrary/orangelight/issues/2552

Fix CDL for requesting a non-alma ID

---

app/resources/numismatics/citations/numismatics/citation.rb
app/resources/numismatics/citations/numismatics/citation_change_set.rb
app/resources/numismatics/citations/numismatics/citation_decorator.rb
app/views/numismatics/coins/edit_fields/_numismatic_citation_fields.html.erb
app/views/records/edit_fields/_numismatic_citation_fields.html.erb
spec/resources/numismatics/citations/numismatics/citation_change_set_spec.rb
spec/resources/numismatics/citations/numismatics/citation_spec.rb
spec/resources/numismatics/coins/numismatics/coin_feature_spec.rb
spec/resources/numismatics/issues/numismatics/issues_feature_spec.rb

Create uri property for nested numismatics citations

---

app/services/geo_discovery/document_builder/layer_info_builder.rb
spec/services/geo_discovery/document_builder/layer_info_builder_spec.rb

Allow shapefiles with Measured Line String geometry

---

app/resources/ephemera_terms/ephemera_term_decorator.rb
spec/resources/ephemera_terms/ephemera_term_decorator_spec.rb

Handle dashes and apostrophes in EphemeraTerm labels.

---

app/resources/numismatics/coins/numismatics/coins_controller.rb
app/resources/numismatics/issues/numismatics/issue_change_set.rb
app/resources/numismatics/issues/numismatics/issues_controller.rb
spec/resources/numismatics/issues/numismatics/issue_change_set_spec.rb

Validate numismatic issue earliest and latest date

---

app/resources/scanned_resources/scanned_resources_controller.rb
spec/resources/scanned_resources/scanned_resources_controller_spec.rb

Make Save and Ingest not ingest if you hit the "Save" button.

---

Gemfile
Gemfile.lock
README.md
bin/setup_keys
config/initializers/sidekiq.rb
config/routes.rb

Install Sidekiq Pro.

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/append_to_collection.rb
app/change_sets/change_set.rb
app/controllers/bulk_edit_controller.rb
app/jobs/bulk_update_job.rb
app/resources/scanned_resources/scanned_resource_change_set.rb
app/views/bulk_edit/resources_edit.html.erb
spec/change_set_persisters/change_set_persister/append_to_collection_spec.rb
spec/features/bulk_edit_spec.rb
spec/jobs/bulk_update_job_spec.rb

Add support for bulk adding collections to bulk edit form.

---

app/services/bibid_updater.rb
spec/services/bibid_updater_spec.rb

Reduce calls to bibdata API

---

app/services/ingest_folder_locator.rb

Fix IngestFolderLocator finding partial matches.

---

README.md

Added versions and lastpass for set up to README

Added versions and lastpass set up to README

---

README.md

Added clarity to commands with bundle exec and rake task for admin access

README clarity for bundle exec and rake tasks

---

app/resources/cdl/charge_manager.rb
spec/resources/cdl/cdl_controller_spec.rb

Cache item_ids in charge_manager

---

app/services/bibid_updater.rb

I found that the cursor used in the find_by_property query forces a
transaction, meaning any changes weren't reflected in the edit forms of
the UI, and resulted in Solr being in a different state than postgres.
There's plenty of memory to load it in, and it only takes a minute or
so.

BibID Updater Fixes

---

app/change_set_persisters/change_set_persister.rb
app/jobs/delete_archival_collection_job.rb
app/jobs/preserve_children_job.rb
app/jobs/preserve_resource_job.rb
app/models/oai/figgy/oai_wrapper.rb
app/resources/cdl/automatic_completer.rb
app/resources/cdl/pdf_ingest_job.rb
app/resources/scanned_resources/scanned_resources_controller.rb
app/services/bibid_updater.rb
app/services/migrations/add_preservation_object_ids_migrator.rb
spec/change_set_persisters/change_set_persister/append_to_collection_spec.rb
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb
spec/characterization_services/pdf_characterization_service_spec.rb
spec/controllers/downloads_controller_spec.rb
spec/resources/cdl/automatic_completer_spec.rb
spec/resources/cdl/charge_manager_spec.rb
spec/resources/cdl/pdf_ingest_job_spec.rb
spec/resources/cdl/resource_charge_list_spec.rb
spec/services/migrations/add_preservation_object_ids_migrator_spec.rb
spec/services/preserver/blind_importer_spec.rb
spec/services/preserver/importer_spec.rb
spec/wayfinders/wayfinder_spec.rb

Add default method to ChangeSetPersister

---

app/models/remote_record.rb
app/services/pul_metadata_services/client.rb
config/config.yml

Remove hardcoded urls

---

app/jobs/preserve_resource_job.rb
spec/jobs/preserve_resource_job_spec.rb

PreserveResourceJob rescues ObjectNotFound exceptions

---

app/indexers/project_indexer.rb
spec/indexers/project_indexer_spec.rb

Added tokenized indexing for ephemera project title

---

app/services/persistence_adapter.rb
lib/tasks/report.rake
spec/services/ingest_vocab_service_spec.rb

Fix ephemera terms report and vocab ingest service.

---

app/services/voyager_updater/dump.rb

Do not error when relevant_ids is empty

---

README.md
bin/setup

I just set up Figgy on a fresh MacOS box with asdf, so I thought
scripting the commands together would make it easier.

Update directions for a fresh install.

---

README.md
lib/tasks/dev.rake

Renamed figgy:server:start rake task to team convention servers:start

---

db/structure.sql

Update Structure.sql to use lando generated info.

---

app/queries/find_by_source_metadata_identifier.rb
spec/queries/find_by_source_metadata_identifier_spec.rb

Maintain constant order in find_by_source_metadata_identifiers

---

app/assets/stylesheets/variables/typography.scss
app/assets/stylesheets/viewer.scss

remove "Arial Unicode MS" from font faces

---

app/jobs/create_derivatives_job.rb
spec/jobs/create_derivatives_job_spec.rb

rescue FileNotFound in CreateDerivatesJob

---

app/models/ability.rb
spec/models/ability_spec.rb

Allow users to download VRR Zip Files if authorized.

---

README.md
app/adapters/read_only_adapter.rb
app/controllers/application_controller.rb
app/models/ability.rb
config/config.yml
config/initializers/figgy.rb
config/initializers/valkyrie.rb
spec/adapters/read_only_adapter_spec.rb
spec/features/root_spec.rb
spec/figgy_config_spec.rb
spec/models/ability_spec.rb

Add index read only switch

---

README.md
config/schedule.rb
lib/tasks/bulk.rake
lib/tasks/bundler_audit.rake
lib/tasks/cache.rake
lib/tasks/cdl.rake
lib/tasks/clean.rake
lib/tasks/csv.rake
lib/tasks/dev.rake
lib/tasks/export.rake
lib/tasks/fixity_worker.rake
lib/tasks/geniza.rake
lib/tasks/import.rake
lib/tasks/keys.rake
lib/tasks/lae.rake
lib/tasks/migrate.rake
lib/tasks/music_reserves.rake
lib/tasks/numismatics.rake
lib/tasks/performance.rake
lib/tasks/reindex.rake
lib/tasks/report.rake
lib/tasks/vocab.rake

Add figgy namespace to rake tasks

---

.rubocop.yml
app/controllers/manifests_controller.rb
app/resources/scanned_maps/scanned_maps_controller.rb
app/services/manifest_builder_v3.rb
app/services/manifest_builder_v3/canvas_builder.rb
app/services/manifest_builder_v3/canvas_rendering_builder.rb
app/services/manifest_builder_v3/iiif_search_builder.rb
app/services/manifest_builder_v3/manifest_service_locator.rb
app/services/manifest_builder_v3/nav_place_builder.rb
app/services/manifest_builder_v3/record_property_builder.rb
app/services/manifest_builder_v3/rendering_builder.rb
app/services/manifest_builder_v3/rights_builder.rb
app/services/manifest_builder_v3/see_also_builder.rb
app/services/manifest_builder_v3/structure_builder.rb
app/services/manifest_builder_v3/thumbnail_builder.rb
app/values/geo_coverage.rb
config/initializers/monkeypatches/iiif_language_map_patch.rb
config/routes.rb
spec/controllers/manifests_controller_spec.rb
spec/requests/playlist_spec.rb
spec/resources/playlists/playlists_controller_spec.rb
spec/resources/scanned_maps/scanned_maps_controller_spec.rb
spec/services/manifest_builder/canvas_builder_v3_spec.rb
spec/services/manifest_builder_spec.rb
spec/services/manifest_builder_v3/nav_place_builder_spec.rb
spec/services/manifest_builder_v3_spec.rb

Add navPlace to ScannedMaps

---

app/jobs/update_dao_job.rb
app/services/aspace/client.rb
spec/jobs/update_dao_job_spec.rb
spec/services/dao_updater_spec.rb
spec/support/stub_aspace.rb

Handle archival object not being found

---

app/resources/ephemera_fields/ephemera_field.rb
app/resources/ephemera_fields/ephemera_field_change_set.rb
app/resources/ephemera_fields/ephemera_field_decorator.rb
app/resources/ephemera_fields/ephemera_field_wayfinder.rb
app/resources/ephemera_folders/ephemera_folders_controller.rb
app/views/records/edit_fields/_rarely_used_term_ids.html.erb
spec/resources/ephemera_fields/ephemera_fields_controller_spec.rb
spec/resources/ephemera_folders/ephemera_folders_controller_spec.rb
spec/wayfinders/wayfinder_spec.rb

Add "Rarely Used Terms" feature to Ephemera Fields

---

app/models/concerns/linked_data/linked_simple_resource.rb
spec/models/linked_data/linked_simple_resource_spec.rb

Don't add start_canvas to SimpleResource JSON-LD.

---

app/models/concerns/linked_data/linked_resource.rb
app/models/concerns/linked_data/literal.rb
app/models/resource.rb
app/resources/ephemera_folders/ephemera_folder.rb
app/resources/ephemera_terms/ephemera_term.rb
app/resources/ephemera_vocabularies/ephemera_vocabulary.rb
app/resources/raster_resources/raster_resource.rb
app/resources/scanned_maps/scanned_map.rb
app/resources/scanned_resources/scanned_resource.rb
app/resources/vector_resources/vector_resource.rb
spec/models/linked_data/linked_resource_spec.rb
spec/shared_specs/models/linked_data/linked_resource.rb

- Refactor fall through and add test for scanned resource
- Remove case statement from LinkedResource.for
- LinkedResource.for only accepts a Resource
refs #4712

Refactor linked data resource factory method

---

app/models/search_builder.rb
spec/controllers/catalog_controller_spec.rb

Fix discovery for admin/staff when in index read-only mode.

---

app/jobs/check_fixity_job.rb
spec/jobs/check_fixity_job_spec.rb

4521 orphan fileset

---

app/models/concerns/linked_data/linked_resource.rb
app/resources/scanned_resources/scanned_resource.rb

And add a class-level comment explaining different types of scanned
resources!
refs #4712

Handle LinkedSimpleResource from ScannedResource

---

app/resources/cdl/cdl_controller.rb
spec/resources/cdl/cdl_controller_spec.rb

Work towards #4755 
It doesn't hurt to retry.

Retry CDL if stale object error.

---

.rubocop.yml
app/resources/cdl/charge_manager.rb
app/resources/cdl/resource_charge_list.rb
spec/resources/cdl/charge_manager_spec.rb

Don't create two charge entries for the same person.

---

app/change_set_persisters/change_set_persister/apply_remote_metadata.rb
app/values/ark.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/fixtures/files/bibdata/9919685413506421.jsonld

If it's been used on another resource we'll want to mint a new one
closes #4765

Only set an identifier on a resource if it is unique

---

app/services/geoserver_message_generator.rb

Fix path checking for staging geoserver.

---

.lando.yml
config/redis.yml

Run redis via lando

---

app/resources/scanned_resources/scanned_resource_change_set.rb
spec/resources/scanned_resources/scanned_resource_change_set_spec.rb

Adds :series property to ScannedResourceChangeSet

fixes #4821

---

app/derivative_services/audio_derivative_service.rb
app/derivative_services/hocr_derivative_service.rb

Fix stale object error for audio and hocr derivative services

---

bin/ci_mediainfo_install.sh
spec/services/manifest_builder_spec.rb

Update mediainfo and update recording duration spec

---

app/controllers/concerns/orangelight_document_controller.rb
app/resources/numismatics/coins/orangelight_coin_builder.rb
spec/resources/numismatics/coins/numismatics/coins_controller_spec.rb
spec/services/orangelight_document_spec.rb

Return orangelight coin document error with status code 500

---

app/views/viewer/auth.html.erb
spec/controllers/viewer_controller_spec.rb

Sara Logue asked me to update this language.

Updating language for OARSC login/access prompt

---

app/resources/raster_resources/raster_resource_decorator.rb
app/resources/raster_resources/raster_resource_wayfinder.rb
app/views/catalog/_admin_controls_raster_set.html.erb
app/views/catalog/_members_raster_set.html.erb
app/views/catalog/_parent_resources_raster_set.html.erb
spec/indexers/human_readable_type_indexer_spec.rb

Index rasters with children as Raster Sets.

---

app/decorators/valkyrie/resource_decorator.rb
app/models/concerns/linked_data.rb
app/models/concerns/linked_data/linked_resource.rb
spec/models/linked_data/linked_simple_resource_spec.rb
spec/services/manifest_builder_spec.rb
spec/shared_specs/models/linked_data/linked_resource.rb
spec/shared_specs/models/linked_data/resource/with_date_range.rb

[Refactorama] Remove LinkedResource factory in favor of resource.linked_resource

---

app/derivative_services/raster_resource_derivative_service.rb
app/resources/file_sets/file_set.rb
app/resources/nested_resources/file_metadata.rb
app/views/catalog/_members_file_set.html.erb
spec/resources/raster_resources/raster_resource_derivative_service_spec.rb
spec/views/catalog/_members_file_set.html.erb_spec.rb

Add a CloudDerivative PCMD use for raster derivatives

---

app/queries/mosaic_fingerprint_query.rb
config/initializers/valkyrie.rb
spec/factories/file_set.rb
spec/queries/mosaic_fingerprint_query_spec.rb

Add mosaic fingerprint query.

---

lib/tasks/keys.rake

so you can generate cloud derivatives in dev

Add staging AWS keys in .env

---

.circleci/config.yml
.tool-versions
README.md
app/resources/nested_resources/file_metadata.rb
app/resources/raster_resources/raster_resource_decorator.rb
app/resources/raster_resources/raster_resources_controller.rb
app/services/mosaic_generator.rb
app/services/mosaic_service.rb
app/storage_adapters/instrumented_storage_adapter.rb
bin/setup
config/routes.rb
spec/factories/raster_resource.rb
spec/resources/nested_resources/file_metadata_spec.rb
spec/resources/raster_resources/raster_resources_controller_spec.rb
spec/services/mosaic_generator_spec.rb
spec/services/mosaic_service_spec.rb

This PR creates files called mosaic.json, does not yet have the fingerprint checking functionality
advances #4770

Add mosaic endpoint for raster sets

---

app/resources/nested_resources/file_metadata.rb
config/config.yml
spec/resources/nested_resources/file_metadata_spec.rb

Generate proper cloud URIs for mosaic generation.

---

app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/references_builder.rb
app/services/geo_discovery/document_builder/wxs.rb
app/services/geo_discovery/geoblacklight_document.rb
config/config.yml
spec/services/geo_discovery/document_builder_spec.rb

Add a wmts reference to GeoBlacklightDocument

---

docs/use_cases.md

Document bound-withs in use_cases.md

---

app/derivative_services/raster_resource_derivative_service.rb
app/jobs/mosaic_job.rb
app/services/mosaic_service.rb
spec/factories/raster_resource.rb
spec/jobs/mosaic_job_spec.rb
spec/resources/raster_resources/raster_resource_derivative_service_spec.rb
spec/resources/raster_resources/raster_resources_controller_spec.rb
spec/services/mosaic_service_spec.rb

- Creates fingerprinted mosaic.json files
- Runs mosaic generation job after creation or cleanup of raster file set derivatives.
Closes #4859 
Closes #4873

Fingerprint mosaic.json files

---

app/indexers/member_of_indexer.rb
spec/indexers/member_of_indexer_spec.rb

Exclude raster set members from search results

---

app/resources/raster_resources/raster_resources_controller.rb

Caches the mosaic endpoint for 10 minutes.

Cache the mosaic endpoint

---

config/deploy/production.rb

Adds our two new VMs to the production system.

4868 figgy2

---

app/change_sets/concerns/geo_change_set_properties.rb
app/models/schema/geo.rb
app/resources/raster_resources/raster_resource_change_set.rb
app/resources/vector_resources/vector_resource_change_set.rb
app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/references_builder.rb
app/services/geo_discovery/document_builder/wxs.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/resources/raster_resources/raster_resource_feature_spec.rb
spec/resources/vector_resources/vector_resource_feature_spec.rb
spec/services/geo_discovery/document_builder_spec.rb

Closes #4885 
Closed https://github.com/pulibrary/figgy/issues/4897

Add XYZ reference to Pulmap Solr document

---

app/services/dao_updater.rb
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb
spec/support/stub_aspace.rb

Support digital object existing already when updating DAO.

---

app/resources/numismatics/accessions/numismatics/accession.rb
app/resources/numismatics/coins/numismatics/coin.rb
app/resources/numismatics/issues/numismatics/issue.rb
app/resources/numismatics/issues/numismatics/issue_decorator.rb
app/services/migrations/cast_numismatics_integers_migrator.rb
spec/resources/numismatics/accessions/numismatics/accession_spec.rb
spec/resources/numismatics/coins/numismatics/coin_spec.rb
spec/resources/numismatics/issues/numismatics/issue_decorator_spec.rb
spec/resources/numismatics/issues/numismatics/issue_spec.rb
spec/services/migrations/cast_numismatics_integers_migrator_spec.rb

- Coerce numismatics numbers to integers
- Add CastNumismaticsIntegersMigrator
closes #4728 
alternative to #4759

Coerce numismatics numbers to integers

---

docs/mosaic.md
docs/use_cases.md

Add documentation about mosaics and maps

---

app/resources/numismatics/accessions/numismatics/accession_decorator.rb
spec/resources/numismatics/accessions/numismatics/accession_decorator_spec.rb

Accept an accession date in unexpected format

---

app/controllers/catalog_controller.rb

Removes duplicate flash messages in read-only mode

---

app/queries/mosaic_fingerprint_query.rb
spec/queries/mosaic_fingerprint_query_spec.rb

Closes #4889
In staging this is about 5ms slower than the old query on the Cuba resource.

Update mosaic fingerprint query to work arbitrarily deep.

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Allow playlist page to load

---

app/queries/mosaic_file_set_query.rb
app/services/mosaic_service.rb
config/initializers/valkyrie.rb
spec/factories/file_set.rb
spec/factories/raster_resource.rb
spec/services/mosaic_service_spec.rb

Add support for generating mosaics from all levels of hierarchy

---

app/queries/mosaic_file_set_query.rb
app/queries/mosaic_fingerprint_query.rb
spec/queries/mosaic_fingerprint_query_spec.rb

 Update mosaic fingerprint query to only count mosaic service_targets.  fe3d174

---

.github/ISSUE_TEMPLATE/kel-issue-template.md

adding clone of KEL issue template being used in DPUL to Figgy Repo for testing  out.

Update issue templates

---

app/controllers/tile_metadata_controller.rb
spec/controllers/tile_metadata_controller_spec.rb
spec/factories/scanned_map.rb
spec/queries/mosaic_fingerprint_query_spec.rb

Generate tile metadata for MapSets with raster children

---

app/resources/file_sets/file_set_change_set.rb
app/resources/file_sets/file_set_decorator.rb
app/views/records/edit_fields/_service_targets.html.erb
spec/resources/file_sets/file_set_change_set_spec.rb

Make FileSet service_targets property editable

---

app/models/ingestable_file.rb

Hold on to Tempfile reference in IngestableFile.

---

app/services/bulk_ingest_service.rb
spec/services/bulk_ingest_service_spec.rb

Bulk ingest title or source identifier, not both.

---

app/queries/mosaic_file_set_query.rb
app/queries/mosaic_fingerprint_query.rb
app/resources/raster_resources/raster_resource_wayfinder.rb
app/resources/scanned_maps/scanned_map_wayfinder.rb
app/services/bulk_ingest_service.rb
docs/mosaic.md
spec/factories/file_set.rb
spec/factories/raster_resource.rb
spec/factories/scanned_map.rb
spec/queries/mosaic_fingerprint_query_spec.rb
spec/services/bulk_ingest_service_spec.rb
spec/services/geo_discovery/document_builder_spec.rb
spec/services/tile_metadata_service_spec.rb

Change mosaic to tiles for service_targets

---

spec/services/geo_discovery/document_builder_spec.rb

Add test for wmts service in geo document_builder

---

app/views/records/edit_fields/_service_targets.html.erb
spec/services/geo_discovery/document_builder_spec.rb
spec/views/records/edit_fields/_service_targets.html.erb_spec.rb

Replace mosaic FileSet service target value with tiles

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/generate_mosaic.rb
spec/change_set_persisters/change_set_persister/generate_mosaic_spec.rb

Add persister to generate mosaic on complete

---

app/change_set_persisters/change_set_persister/create_file.rb
app/services/file_appender.rb
spec/change_set_persisters/change_set_persister_spec.rb

closes #4946 
review: commits are split into refactors, work.

Notify on file appender error

---

app/jobs/update_dao_job.rb
app/services/aspace/client.rb
app/services/dao_updater.rb
spec/jobs/update_dao_job_spec.rb
spec/services/dao_updater_spec.rb
spec/support/stub_aspace.rb

Closes #4902
Also removes error handling in UpdateDaoJob that never would have been hit.

Notify Honeybadger when an archival object not found

---

.circleci/config.yml

Try installing specific version of morecantil

---

config/authorities/rights_statement.yml

This license was requested by Ellen Ambrosone.

Adding CC-BY-NC-NoDerivatives license

---

lib/tasks/cache.rake
lib/tasks/lae.rake
lib/tasks/performance.rake
lib/tasks/reindex.rake
lib/tasks/vocab.rake

Ensure all rake tasks have descriptions

---

app/services/json_ingester.rb
lib/tasks/import.rake
spec/fixtures/json_ingest.json
spec/services/json_ingester_spec.rb

* Extracts rake task to JsonIngester.
* Adds a test.
* Does a little refactoring thanks to the test.
* Ingests as SimpleResources, since there's local creator metadata.

Add tests to JSON Ingest.

---

docs/use_cases.md

The technical implementation is up for discussion in this PR - the only things set in stone are the folder structure and file naming convention. What's presented here is a solution which means we can ingest these in a tight timeline with no development work.

Add multispectral use case.

---

app/services/event_generator/geoblacklight_event_generator.rb

Fixes issue with syncing MapSets. Verified on staging.
Closes #5011

Remove memoization of document generator

---

app/jobs/mosaic_job.rb
app/resources/raster_resources/raster_resource_decorator.rb
spec/jobs/mosaic_job_spec.rb

Remove raster_set check from MosaicJob

---

app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder.rb
app/services/geo_discovery/document_builder/rights_builder.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/services/geo_discovery/document_builder_spec.rb

Work towards pulibrary/pulmap#1060

Index rights statements into Geoblacklight document.

---

app/jobs/geoserver_publish_job.rb
app/services/geo_discovery/document_builder/wxs.rb

Closes #5065 
- Run GeoserverPublishJob with priority
- Simplify overly complex file_set method to assist with debugging

Queue GeoserverPublishJob as high

---

app/services/migrations/add_service_target_migrator.rb
lib/tasks/migrate.rake
spec/services/migrations/add_service_target_migrator_spec.rb

Refs #4960 -- don't close that issue until the migration has been run on prod.

Create rake task for migrating rasters

---

spec/resources/collections/collections_controller_spec.rb

refactor done while analyzing #5042

Reorganize and relabel tests

---

Gemfile.lock
app/services/migrations/map_copyright_migrator.rb
lib/tasks/maps_add_copyright.rake
spec/services/migrations/map_copyright_migrator_spec.rb

... for maps with no known copyright and campus-only access
refs #5056

Adds migration rake task for updating rights statements ... 

---

config/application.rb

Allow credentials to graphql endpoint

---

app/graphql/types/embed_type.rb
app/graphql/types/resource.rb
app/graphql/types/scanned_resource_type.rb
app/services/dao_updater.rb
app/services/embed.rb
spec/graphql/figgy_schema_spec.rb
spec/graphql/types/scanned_resource_type_spec.rb

Refs pulibrary/pulfalight#985
Refs pulibrary/figgy#5035

Add GraphQL field for embed

---

.rubocop.yml
app/services/dao_updater.rb

Add even more info to Honeybadger notification

---

Gemfile.lock
app/services/embed.rb
spec/graphql/types/scanned_resource_type_spec.rb

Add type to graphql embed

---

app/services/dao_updater.rb
app/services/embed.rb
spec/graphql/types/scanned_resource_type_spec.rb

Refactor link_label into Embed

---

app/services/pul_metadata_services/client.rb
config/config.yml
config/initializers/figgy.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/support/stub_bibdata.rb

Refs https://github.com/pulibrary/pulfalight/pull/1032

Use an auth token to access Pulfalight metadata.

---

app/services/dao_updater.rb
app/services/embed.rb
app/services/migrations/dao_migrator.rb
lib/tasks/migrate.rake
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb
spec/services/migrations/dao_migrator_spec.rb

Closes #5092 
Closes https://github.com/pulibrary/pulfalight/issues/1002
- Updates DAO title for resources with zip files
- Adds task to update all DAOs

Update DAO title for resources with zip files

---

app/services/migrations/map_copyright_migrator.rb
spec/services/migrations/map_copyright_migrator_spec.rb

Set private geo resources to in-copyright

---

app/controllers/bulk_ingest_controller.rb
app/services/bulk_ingest_service.rb
app/views/bulk_ingest/show.html.erb
spec/controllers/bulk_ingest_controller_spec.rb
spec/services/bulk_ingest_service_spec.rb

Add bulk ingest option to preserve file names.

---

app/controllers/resources_controller.rb

Don't check CSRF token for resources controller.

---

spec/controllers/resources_controller_spec.rb

Fix resources controller spec

---

app/controllers/bulk_edit_controller.rb
app/jobs/bulk_update_job.rb
app/mailers/bulk_update_mailer.rb
app/views/bulk_update_mailer/update_status.html.erb
spec/controllers/bulk_edit_controller_spec.rb
spec/jobs/bulk_update_job_spec.rb
spec/mailers/bulk_update_mailer_spec.rb

Provide useful error message when bulk update finishes

---

app/controllers/resources_controller.rb
app/models/ability.rb
spec/controllers/resources_controller_spec.rb
spec/models/ability_spec.rb

Closes #5108 
Tested on staging.

Restrict refresh_remote_metadata route

---

app/assets/stylesheets/components/form.scss
app/assets/stylesheets/components/positioning.scss
app/assets/stylesheets/variables/bootstrap.scss
app/views/base/_form_metadata.html.erb
app/views/base/_form_metadata_inner.html.erb
app/views/base/_form_progress.html.erb
app/views/numismatics/_form_metadata_inner.html.erb
app/views/numismatics/_form_metadata_inner_two_fields_one_line.html.erb
app/views/records/edit_fields/_source_metadata_identifier.html.erb
app/views/shared/_brand_bar.html.erb
app/views/shared/_footer.html.erb
config/authorities/visibility.yml
config/initializers/simple_form_bootstrap.rb
config/locales/simple_form.en.yml
spec/models/numismatics/issues_feature_spec.rb

Rails 6 edit page

---

Gemfile.lock
app/views/base/file_manager.html.erb

Upgrade filemanager to Bootstrap 4

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/badge.scss
app/assets/stylesheets/components/show.scss
app/controllers/catalog_controller.rb
app/helpers/bounding_box_helper.rb
app/javascript/figgy/relationships/member_resources_table.js
app/javascript/figgy/relationships/parent_resources_table.js
app/models/controlled_vocabulary.rb
app/views/catalog/_member_resources.html.erb
app/views/catalog/_members_media_resource.html.erb
app/views/catalog/_parent_resources_raster_resource.html.erb
app/views/catalog/_parent_resources_scanned_map.html.erb
app/views/catalog/_parent_resources_vector_resource.html.erb
app/views/catalog/_workflow_controls_default.html.erb
spec/decorators/ephemera_box_decorator_spec.rb
spec/features/simple_resource_spec.rb
spec/models/scanned_resource_feature_spec.rb
spec/views/catalog/_members_ephemera_project.html.erb_spec.rb
spec/views/catalog/_members_multi_volume_work.html.erb_spec.rb

Fixes most show page formatting issue related to Bootstrap upgrade.
Closes #5128

Fix show page and show page title

---

Gemfile.lock
app/assets/stylesheets/components/form.scss
app/helpers/application_helper.rb
app/javascript/components/OrderManagerFilesetForm.vue
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/components/OrderManagerResourceForm.vue
app/javascript/test/__snapshots__/orderManagerFilesetForm.spec.js.snap
app/javascript/test/__snapshots__/orderManagerFilesetsForm.spec.js.snap
app/javascript/test/__snapshots__/orderManagerResourceForm.spec.js.snap
app/views/base/order_manager.html.erb
app/views/layouts/application.html.erb
app/views/layouts/blacklight/base.html.erb

Upgrades ordermanager to Bootstrap 4

---

Gemfile.lock
app/views/catalog/_parent_breadcrumb_default.html.erb
app/views/catalog/_parent_breadcrumb_ephemera_folder.html.erb
app/views/catalog/_parent_breadcrumb_ephemera_term.html.erb
app/views/catalog/_parent_breadcrumb_ephemera_vocabulary.html.erb
app/views/reports/ephemera_data.html.erb
app/views/reports/pulfa_ark_report.html.erb
spec/models/numismatics/coin_feature_spec.rb

Updates Breadcrumbs to Bootstrap 4

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
spec/features/ephemera_box_spec.rb

Removes unused layout type helper methods.

Remove layout type helper methods

---

app/helpers/structure_helper.rb

Fixes Bootstrap breadcrumbs in Structure Manager 

---

app/views/catalog/_show_header_default.html.erb

Fixes "Unclaim" button styling

---

app/javascript/components/issue_monogram.vue
app/models/folder_data_source.rb
app/views/_members_collection_archival_media_collection.html.erb
app/views/base/structure.html.erb
app/views/bulk_ingest/show.html.erb
app/views/catalog/_folder_actions.html.erb
app/views/catalog/_member_resources.html.erb
app/views/catalog/_members_collection.html.erb
app/views/catalog/_members_ephemera_project.html.erb
app/views/catalog/_members_issue.html.erb
app/views/catalog/_members_recording.html.erb
app/views/catalog/_members_reference.html.erb
app/views/catalog/_parent_resources_raster_resource.html.erb
app/views/catalog/_parent_resources_scanned_map.html.erb
app/views/catalog/_parent_resources_vector_resource.html.erb
app/views/ephemera_boxes/attach_drive.html.erb
app/views/numismatics/_form_buttons.html.erb
app/views/numismatics/accessions/index.html.erb
app/views/numismatics/finds/index.html.erb
app/views/numismatics/firms/index.html.erb
app/views/numismatics/monograms/index.html.erb
app/views/numismatics/people/index.html.erb
app/views/numismatics/places/index.html.erb
app/views/numismatics/references/index.html.erb
app/views/ocr_requests/index.html.erb
app/views/roles/edit.html.erb

Replace btn-default with btn-secondary.

---

spec/services/migrations/dao_migrator_spec.rb

Clear out enqueued jobs to prevent flapping DAO spec.

---

app/assets/stylesheets/components/viewer.scss
app/controllers/catalog_controller.rb
app/views/base/_file_manager_member.html.erb
app/views/base/_file_manager_thumbnail.html.erb
app/views/base/_local_upload.html.erb
app/views/base/_server_upload.html.erb
app/views/layouts/blacklight/base.html.erb

Closes #5172 
Closes #5173 
- Fixes FileSet cards
- Fixes thumbnails and openseadragon modal
- Fixes drag-and-drop
- Fixes button styling

FileManger Updates

---

app/assets/stylesheets/components/form.scss
app/javascript/components/issue_monogram.vue
app/javascript/components/issue_monograms.vue
app/views/numismatics/issues/_form.html.erb
app/views/records/edit_fields/_numismatic_monogram_ids.html.erb
spec/models/numismatics/issues_feature_spec.rb

Fix monogram selector

---

app/assets/stylesheets/components/structure_editor.scss
app/javascript/figgy/structure_manager.js
app/views/base/_structure_node.html.erb

Fix structure editor

---

app/views/catalog/_members_file_set.html.erb

Update fileset show page labels to badges

---

app/javascript/packs/application.js
config/initializers/simple_form_bootstrap.rb

Fixes for numismatics edit forms

---

app/views/catalog/_members_playlist.html.erb

Adds Track listing back to Playlist show page

---

app/assets/stylesheets/components/show.scss
app/views/catalog/_show_header_default.html.erb

Adds bottom margin to claim/unclaim buttons

---

app/views/catalog/_workflow_controls_default.html.erb
config/initializers/simple_form_bootstrap.rb

Review and Approval styling

---

app/helpers/fixity_dashboard_helper.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/views/catalog/_members_multi_volume_work.html.erb_spec.rb
spec/views/catalog/_resource_attributes_default.html.erb_spec.rb

Update fixity count badges

---

app/views/records/edit_fields/_member_of_collection_ids.html.erb

Sort by title string

---

config/environments/test.rb

Closes #5237 
Test now passes.
```
rspec spec/views/catalog/_universal_viewer_issue.html.erb_spec.rb --seed 32680
```

Set cache_template_loading to true during testing

---

Gemfile
Gemfile.lock

Upgrade to latest Blacklight.
Closes #5218

Upgrade blacklight to 7.28.0

---

app/helpers/catalog_helper.rb
app/types/types.rb
app/views/catalog/_thumbnail_list_default.html.erb
app/views/catalog/show.html.erb
app/views/shared/_site_search.html.erb

refs #5236
This was everything I could resolve in our own code that came up when running the catalog controller spec.
Made an issue for one:
https://github.com/pulibrary/figgy/issues/5243
A bunch of blacklight deprecations are coming from inside blacklight itself.

Silence some deprecations

---

app/views/numismatics/monograms/index.html.erb

Fixes deprecation.
Closes #5247

Use #presenter.thumbnail.thumbnail tag method

---

app/helpers/application_helper.rb

Fixes deprecation.
Closes #5250

Use blacklight_config.default_per_page

---

app/document_presenters/figgy_index_presenter.rb

Fixes deprecation.
Closes #5248

Use #field_value

---

app/controllers/catalog_controller.rb

Fix Blacklight 8 deprecation.
Refs #5236

Add extra permitted params

---

app/views/base/_structure_node.html.erb

fixes deprecation
closes #5247

Use #document_presenter.thumbnail.thumbnail tag method

---

.circleci/config.yml

Install only chrome and chromedriver

---

app/controllers/catalog_controller.rb

Add all our params to be allowed in search state

---

Gemfile
Gemfile.lock

silences search_field deprecation warnings
closes #5236 
draft until released.

Use updated blacklight

---

app/jobs/create_ocr_request_job.rb
app/jobs/pdf_ocr_job.rb

Remove ActiveStorage::Downloading

---

app/services/voyager_updater/event_stream.rb

Call URI.open directly.

---

spec/controllers/downloads_controller_spec.rb
spec/controllers/file_sets_controller_spec.rb

Replace content_type with media_type

---

app/helpers/osd_modal_helper.rb
app/views/base/_file_manager_thumbnail.html.erb
spec/helpers/osd_modal_helper_spec.rb
spec/views/scanned_resources/file_manager.html.erb_spec.rb

Improve file manager thumbnail display for non-image file sets

---

app/change_set_persisters/change_set_persister/create_file.rb
app/change_set_persisters/change_set_persister/create_file/factory.rb
app/controllers/cdl/cdl_controller.rb
app/controllers/ocr_requests_controller.rb
app/jobs/create_ocr_request_job.rb
app/models/ocr_request.rb
app/overrides/browse_everything/upload_override.rb
app/services/manifest_builder/iiif_search_builder.rb
app/services/manifest_builder/manifest_service_locator.rb
app/services/manifest_builder_v3/iiif_search_builder.rb
app/services/manifest_builder_v3/manifest_service_locator.rb
config/application.rb
config/initializers/inflections.rb
db/migrate/20200608160046_create_ocr_requests.rb
db/structure.sql
spec/controllers/cdl/cdl_controller_spec.rb
spec/controllers/ocr_requests_controller_spec.rb
spec/factories/ocr_requests.rb
spec/requests/viewer_config_spec.rb
spec/requests/viewer_exhibit_config_spec.rb

Lots of changes to support the Rails 6.0 default config, which enables zeitwerk and sets a few things which will make the 6.1 transition easier.
Closes #5268

Get Zeitwerk and standard Rails 6.0 config working.

---

.gitignore
app/assets/stylesheets/components/header.scss
app/views/shared/_site_actions.html.erb

The new height isn't a perfect match but it is closer.
closes #5280

+ button styles

---

config/application.rb

Fix BrowseEverything.

---

app/assets/stylesheets/components/bulk_edit.scss
app/views/bulk_edit/resources_edit.html.erb

Update and style bulk edit form

---

app/javascript/components/document_adder.vue

Update document-adder to use the new blacklight search API

---

app/assets/stylesheets/components/show.scss
app/javascript/components/playlist_members.vue

Fix playlist tracks list styles

---

app/views/base/_custom_file_manager_actions.html.erb

Remove unused file

---

spec/features/playlist_spec.rb

Add feature tests for adding / removing tracks from a playlist

---

app/helpers/osd_modal_helper.rb
app/helpers/thumbnail_helper.rb
app/models/proxy_file_set.rb
app/views/base/_structure_node.html.erb
spec/controllers/playlists_controller_spec.rb
spec/helpers/osd_modal_helper_spec.rb

OSDModalHelper wasn't wrapping the thumbnail, just putting a clickable spot next to
it.
Closes #5323

Fix Structure Editor Zoom

---

app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/viewer/cdl_timer.js
app/views/layouts/viewer_layout.html.erb

Use meta CSRF token for CDL Return

---

docs/qa.md

Add a QA doc

---

app/services/geo_discovery/geoblacklight_document.rb
app/services/migrations/add_service_target_migrator.rb
spec/services/ingest_ephemera_csv_sae_spec.rb
spec/services/ingest_ephemera_csv_validate_spec.rb
spec/services/migrations/add_service_target_migrator_spec.rb
spec/services/pdf_generator_spec.rb

- Update service target migrator to handle multiple file sets
- Update Metrics/LineLength cop name
Works towards #4960

Update service target migrator to handle multiple file sets

---

app/assets/stylesheets/viewer.scss

Fix leaflet viewer in Firefox

---

app/validators/member_validator.rb
spec/validators/member_validator_spec.rb

If there's bad data in there that's our system's fault, we shouldn't
make the user contact us to fix it.
Closes #5364

Only validate newly added members.

---

.rubocop.yml
app/adapters/bagit/bag_exporter.rb
app/adapters/bagit/bag_importer.rb
app/services/file_appender.rb
app/services/preserver.rb
app/services/preserver/blind_importer.rb
spec/controllers/downloads_controller_spec.rb

Close file handles after StorageAdapter uses them.

---

app/controllers/catalog_controller.rb

Enable raw json endpoint

---

app/decorators/scanned_resource_decorator.rb
spec/decorators/scanned_resource_decorator_spec.rb

Closes #5358 
Resolve [honeybadger notification](https://app.honeybadger.io/projects/53391/faults/87113909) once merged.

Rescue invalid date ranges

---

app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js

Only use dynamic UV config if it's a Figgy manifest.

---

app/decorators/valkyrie/resource_decorator.rb
app/helpers/application_helper.rb
app/models/ability.rb
app/presenters/permission_badge.rb
config/locales/en.yml
spec/decorators/valkyrie/resource_decorator_spec.rb

Closes #5406 
- Adds visibility label for embargoed resources
- Adds an embargo service

Add visibility label for embargoed resources

---

app/decorators/valkyrie/resource_decorator.rb
spec/models/ability_spec.rb

Inherit embargo status down to individual volumes.

---

config/application.rb

Only require dotenv in development / test

---

config/routes.rb
spec/routing_spec.rb

- Refactor concerns in route
- Deduplicate routes entries
- Serve the opensearch route correctly
closes #5346

5346 opensearch route

---

app/controllers/ocr_requests_controller.rb
spec/controllers/ocr_requests_controller_spec.rb

Filter OcrRequests that are three months or older

---

docs/ux/use_cases.md

Add Supplemental content PDFs use case

---

app/views/roles/edit.html.erb
spec/views/roles/edit.html.erb_spec.rb

Remove "update/delete" role form

---

app/jobs/run_ocr_job.rb
spec/jobs/run_ocr_job_spec.rb

Rescue file not found error and test it

---

app/change_sets/raster_resource_change_set.rb
app/change_sets/recording_change_set.rb
app/change_sets/scanned_resource_change_set.rb
app/change_sets/simple_change_set.rb
app/change_sets/vector_resource_change_set.rb
app/decorators/valkyrie/resource_decorator.rb
app/models/controlled_vocabulary.rb
app/models/schema/common.rb
app/views/records/edit_fields/_notice_type.html.erb
spec/change_sets/raster_resource_change_set_spec.rb
spec/change_sets/recording_change_set_spec.rb
spec/change_sets/scanned_map_change_set_spec.rb
spec/change_sets/scanned_resource_change_set_spec.rb
spec/change_sets/simple_change_set_spec.rb
spec/change_sets/vector_resource_change_set_spec.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/features/scanned_resource_spec.rb
spec/models/controlled_vocabulary_spec.rb
spec/shared_specs/valkyrie/decorators/resource_decorator.rb

Add notice_type to all primary resources

---

app/jobs/bulk_update_job.rb
app/views/bulk_edit/resources_edit.html.erb
spec/services/bulk_edit_service_spec.rb

Adding remote metadata refresh to bulk edit screen

---

app/jobs/bulk_update_job.rb
app/views/bulk_edit/resources_edit.html.erb
spec/jobs/bulk_update_job_spec.rb
spec/services/bulk_edit_service_spec.rb

Add holding location to bulk edit form

---

app/services/export_service.rb
spec/services/export_service_spec.rb

Support titles with extra characters for export.

---

app/views/layouts/blacklight/base.html.erb

We had the code but we weren't actually putting it in the layout, no page hits data since early August

Use analytics tracking

---

app/controllers/graphql_controller.rb
app/graphql/types/resource.rb
app/graphql/types/scanned_resource_type.rb
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
config/application.rb
config/environments/production.rb
spec/controllers/graphql_controller_spec.rb
spec/features/scanned_resource_spec.rb

Refactor Viewer JS to use GraphQL

---

app/assets/stylesheets/viewer.scss
app/graphql/types/notice_type.rb
app/graphql/types/resource.rb
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/models/controlled_vocabulary.rb
app/views/viewer/index.html.erb
config/authorities/notices.yml
spec/graphql/figgy_schema_spec.rb
spec/models/controlled_vocabulary_spec.rb

This doesn't implement the 1 hour cookie, but this popup is so minimally intrusive that I'm checking to see if that's actually necessary.

Add popup for Senior Thesis notices to the viewer

---

app/graphql/types/notice_type.rb
app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/models/controlled_vocabulary.rb
app/views/viewer/index.html.erb
config/authorities/notices.yml
spec/graphql/figgy_schema_spec.rb
spec/models/controlled_vocabulary_spec.rb

This also adds the harmful/explicit content messages.
Closes #5447

Add configurable accept button label.

---

app/controllers/bulk_ingest_controller.rb
app/views/bulk_ingest/_holding_location.html.erb
app/views/bulk_ingest/show.html.erb
spec/controllers/bulk_ingest_controller_spec.rb

Add holding location to bulk ingest form

---

app/services/embed.rb
spec/graphql/types/scanned_resource_type_spec.rb

Make on-campus resources you don't have access to be unauthorized

---

app/change_sets/ephemera_folder_change_set_base.rb
app/models/ephemera_folder.rb
spec/change_sets/ephemera_folder_change_set_spec.rb

Add notice type to Ephemera Folders.

---

app/javascript/test/viewer/uv_manager.spec.js
app/views/viewer/index.html.erb

Renames UV tab from "Default" to "Sheets"

---

app/services/geo_discovery/document_builder/wxs.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb

Build layer identifier correctly

---

app/models/ability.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/factories/scanned_resource.rb

refs pulibrary/dpul#1367
refs #5510

Check ip_readable in test_read

---

app/services/tile_metadata_service.rb
app/values/tile_path.rb
spec/controllers/tile_metadata_controller_spec.rb
spec/factories/raster_resource.rb
spec/factories/scanned_map.rb
spec/services/tile_metadata_service_spec.rb
spec/values/tile_path_spec.rb

Allow tile metadata service to generate tilejson for scanned map with single raster

---

app/jobs/box_boxless_folders_job.rb
lib/tasks/lae.rake
spec/jobs/box_boxless_folders_job_spec.rb

Add a rake task and job to box all boxless ephemera folders

---

docs/ux/use_cases.md

Add CollectorSystems use case and requirements.

---

spec/jobs/box_boxless_folders_job_spec.rb

Add test to ensure other boxes aren't removed from projects

---

app/change_set_persisters/change_set_persister/generate_mosaic.rb
app/change_set_persisters/change_set_persister/geoserver_publish.rb
app/change_set_persisters/change_set_persister/publish_message.rb
app/characterization_services/imagemagick_characterization_service.rb
app/jobs/geoserver_publish_job.rb
app/services/geo_resource_reindexer.rb
app/services/manifest_builder.rb
app/services/manifest_builder_v3.rb
app/wayfinders/base_wayfinder.rb
app/wayfinders/scanned_map_wayfinder.rb

Use wayfinders instead of decorators where possible

---

app/change_set_persisters/change_set_persister/update_aspace_dao.rb
spec/change_set_persisters/change_set_persister/update_aspace_dao_spec.rb

refs https://github.com/pulibrary/pulfalight/issues/1203

Queue the UpdateDaoJob any time the resource is complete

---

app/jobs/check_fixity_job.rb
app/services/preserver.rb
app/services/preserver/blind_importer.rb
app/services/preserver/blind_importer/file_metadata_adapter.rb
app/services/preserver/blind_importer/file_metadata_adapter/query_service.rb
app/services/preserver/importer.rb

just the comments from #5530 -- we want to merge this stuff.

Add comments and small changes to preservation code

---

app/jobs/prune_preservation_objects_job.rb
spec/jobs/prune_preservation_objects_job_spec.rb

Add job to prune multiple preservation objects

---

.circleci/config.yml
cloud_fixity/yarn.lock

Run cloud fixity tests in CI

---

app/change_set_persisters/change_set_persister/preserve_resource.rb
app/jobs/preserve_resource_job.rb

Add more documentation about PreservationObject race condition & lock tokens

---

app/change_sets/recording_change_set.rb
spec/change_sets/recording_change_set_spec.rb

Preserve Recordings

---

config/authorities/rights_statement.yml

Adding custom rights statement for items digitized by MFA Boston

---

app/change_sets/change_set.rb
app/change_sets/event_change_set.rb
app/change_sets/file_set_change_set.rb
app/change_sets/tombstone_change_set.rb
app/indexers/parent_issue_indexer.rb
app/models/event.rb
app/models/file_set.rb
app/models/resource.rb
app/models/tombstone.rb
app/services/pdf_service.rb
app/utils/data_seeder.rb
spec/adapters/indexing_adapter_spec.rb
spec/change_set_persisters/change_set_persister/apply_remote_metadata_spec.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/jobs/missing_thumbnail_job_spec.rb
spec/models/numismatics/issues_feature_spec.rb
spec/services/cdl/automatic_completer_spec.rb
spec/services/geo_discovery/document_builder_spec.rb
spec/services/manifest_builder_spec.rb
spec/services/manifest_builder_v3_spec.rb
spec/services/preserver/importer_spec.rb
spec/wayfinders/wayfinder_spec.rb

Enable optimistic locking for all resources

---

app/derivative_services/audio_derivative_service.rb
docs/ux/use_cases.md

Document Original/Preservation/IntermediateFile.

---

app/services/migrations/preservation_file_migrator.rb
spec/services/migrations/preservation_file_migrator_spec.rb

There were 9127 of these in prod.
refs #5542

Add a migration to convert deprecated use value to PreservationFile

---

app/characterization_services/mediainfo_characterization_service.rb
app/jobs/check_fixity_job.rb
app/jobs/export_collection_pdf_job.rb
app/services/add_ephemera_to_collection.rb
app/services/bulk_edit_service.rb
app/services/cicognara_csv.rb
app/services/manifest_builder.rb
app/services/manifest_builder_v3.rb

Use wayfinders instead of decorators where possible (cont.)

---

app/change_sets/event_change_set.rb
app/jobs/update_fixity_job.rb
app/models/event.rb
app/models/preservation_object.rb
app/services/migrations/event_current_migrator.rb
spec/factories/event.rb
spec/jobs/update_fixity_job_spec.rb
spec/models/event_spec.rb
spec/services/migrations/event_current_migrator_spec.rb

- Add `current` attribute to Event
- Mark the previous cloud_fixity Event current:false
refs #5589

Add a `current` attribute to Event

---

app/decorators/raster_resource_decorator.rb
app/decorators/scanned_map_decorator.rb
app/decorators/vector_resource_decorator.rb
spec/decorators/raster_resource_decorator_spec.rb
spec/decorators/scanned_map_decorator_spec.rb
spec/decorators/vector_resource_decorator_spec.rb

Add file_sets method to geo resource decorators

---

db/migrate/20230119155402_add_unique_current_event_index.rb
db/structure.sql
spec/models/event_spec.rb

Add unique current event index

---

spec/features/ephemera_box_spec.rb

Add some more setup to barcode test.

---

app/queries/find_cloud_fixity_failures.rb
spec/decorators/event_decorator_spec.rb
spec/decorators/file_set_decorator_spec.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/features/fixity_dashboard_spec.rb
spec/queries/find_cloud_fixity_failures_spec.rb
spec/queries/find_cloud_fixity_spec.rb
spec/wayfinders/wayfinder_spec.rb

Use current: true in cloud fixity failures query

---

app/queries/find_deep_failed_cloud_fixity_count.rb

Update find deep failed cloud fixity count query to use current: true

---

app/change_sets/ephemera_folder_change_set_base.rb
app/models/controlled_vocabulary.rb
app/models/ephemera_folder.rb
app/models/resource.rb
app/views/records/edit_fields/_content_warning.html.erb
spec/controllers/ephemera_folders_controller_spec.rb
spec/graphql/figgy_schema_spec.rb

Add specific harmful content warnings to Ephemera Folders

---

app/jobs/preserve_resource_job.rb
app/services/preserver.rb
spec/jobs/preserve_resource_job_spec.rb
spec/services/preserver_spec.rb

Add force_preservation parameter to Preserver and PreserveResourceJob

---

app/controllers/bulk_edit_controller.rb
spec/controllers/bulk_edit_controller_spec.rb

Add authorization to BulkEdit controller.

---

app/views/records/edit_fields/_source_metadata_identifier.html.erb

Update wording "Refresh metadata from PULFA/Voyager" to reflect new ILS

---

app/jobs/update_dao_job.rb
spec/jobs/update_dao_job_spec.rb

Rescue ObjectNotFoundError in UpdateDaoJob for deleted objects

---

app/derivative_services/audio_derivative_service.rb
app/derivative_services/pdf_derivative_service.rb
app/derivative_services/raster_resource_derivative_service.rb
app/jobs/ingest_mets_job.rb
app/models/ingestable_file.rb
app/models/mets_document.rb
app/services/bulk_ingest_service/bulk_file_path_converter/bulk_ingest_file.rb
app/services/folder_json_importer.rb
app/services/ingest_ephemera_csv.rb
app/services/ingest_ephemera_mods.rb
spec/jobs/ingest_mets_job_spec.rb
spec/jobs/reprocess_mets_job_spec.rb

Rename the IngestableFile 'copyable' attribute to 'copy_before_ingest'

---

app/adapters/indexing_adapter.rb
app/change_set_persisters/change_set_persister/create_deletion_marker.rb
app/change_set_persisters/change_set_persister/delete_members.rb
app/change_sets/deletion_marker_change_set.rb
app/controllers/catalog_controller.rb
app/controllers/deletion_markers_controller.rb
app/decorators/deletion_marker_decorator.rb
app/indexers/deletion_marker_indexer.rb
app/jobs/delete_member_job.rb
app/models/deletion_marker.rb
app/models/search_builder.rb
app/services/deletion_marker_service.rb
app/views/catalog/_admin_controls_deletion_marker.html.erb
app/views/catalog/_deleted_resources_home.html.erb
app/views/catalog/_home_text.html.erb
config/initializers/valkyrie.rb
config/routes.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/controllers/catalog_controller_spec.rb
spec/controllers/deletion_markers_controller_spec.rb
spec/factories/deletion_marker.rb
spec/features/catalog_spec.rb
spec/features/deletion_marker_spec.rb
spec/views/catalog/_home_text.html.erb_spec.rb
spec/wayfinders/wayfinder_spec.rb

Index and display DeletionMarkers

---

app/models/playlist.rb
spec/controllers/catalog_controller_spec.rb

Fix playlists for staff users.

---

app/values/csv_report.rb
spec/values/csv_report_spec.rb

Work towards #5631, might be useful for a more generic report generator.

Create CSV Report Generator.

---

app/assets/stylesheets/components/inputs.scss
app/controllers/bulk_edit_controller.rb
app/javascript/figgy/figgy_boot.js
app/jobs/bulk_update_job.rb
app/views/bulk_edit/resources_edit.html.erb
spec/features/bulk_edit_spec.rb

Allow bulk edit and removal of embargo date

---

config/locales/en.yml
spec/graphql/figgy_schema_spec.rb

Add blank target to harmful content links

---

app/services/geo_discovery/document_builder/wxs.rb
spec/features/vector_resource_spec.rb
spec/services/geo_discovery/document_builder/wxs_spec.rb

Generate correct WMS and WFS layer urls for geo resources

---

app/change_sets/numismatics/accession_change_set.rb
app/decorators/numismatics/accession_decorator.rb
app/validators/accession_date_validator.rb
spec/change_sets/numismatics/accession_change_set_spec.rb
spec/controllers/numismatics/accessions_controller_spec.rb
spec/decorators/numismatics/accession_decorator_spec.rb
spec/decorators/numismatics/coin_decorator_spec.rb
spec/factories/numismatics/numismatic_accession.rb
spec/models/numismatics/coin_feature_spec.rb

Numismatic accessions date validation

---

app/values/csv_report.rb
spec/values/csv_report_spec.rb

Add support for collections and file_count to CSVReport.

---

app/decorators/numismatics/citation_decorator.rb
spec/decorators/numismatics/accession_decorator_spec.rb
spec/decorators/numismatics/citation_decorator_spec.rb
spec/decorators/numismatics/coin_decorator_spec.rb
spec/decorators/numismatics/issue_decorator_spec.rb
spec/factories/numismatics/numismatic_reference.rb
spec/models/numismatics/coin_feature_spec.rb
spec/models/numismatics/issues_feature_spec.rb
spec/services/orangelight_document_spec.rb

Use full indexed reference title in Orangelight document citation

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/cleanup_pdf_derivatives.rb
spec/change_set_persisters/change_set_persister/cleanup_pdf_derivatives_spec.rb

Delete PDF derivative files when a PDF is deleted.

---

app/decorators/numismatics/citation_decorator.rb
spec/decorators/numismatics/citation_decorator_spec.rb

Return nil if citation has no related reference

---

app/change_set_persisters/change_set_persister/preserve_resource.rb
spec/change_set_persisters/change_set_persister_spec.rb

Always preserve in the background

---

app/change_sets/ephemera_folder_change_set_base.rb
app/change_sets/ephemera_term_change_set.rb
app/change_sets/ephemera_vocabulary_change_set.rb
app/decorators/ephemera_folder_decorator.rb
spec/change_sets/ephemera_box_change_set_spec.rb
spec/change_sets/ephemera_folder_change_set_spec.rb
spec/change_sets/ephemera_term_change_set_spec.rb
spec/change_sets/ephemera_vocabulary_change_set_spec.rb

- Test EphemeraBox and EphemeraFolder preservation
- Ensure EphemeraVocabulary and EphemeraTerm resources preserve
Closes #3454
Closes #3456

Ephemera preservation

---

app/characterization_services/gdal_characterization_service.rb
app/characterization_services/imagemagick_characterization_service.rb
app/characterization_services/mediainfo_characterization_service.rb
app/characterization_services/pdf_characterization_service.rb
app/characterization_services/tika_file_characterization_service.rb
app/jobs/ingest_intermediate_file_job.rb
app/jobs/recharacterize_job.rb
spec/characterization_services/geo_characterization_service_spec.rb
spec/characterization_services/imagemagick_characterization_service_spec.rb
spec/characterization_services/mediainfo_characterization_service_spec.rb
spec/characterization_services/pdf_characterization_service_spec.rb
spec/characterization_services/tika_file_characterization_service_spec.rb
spec/rails_helper.rb
spec/support/fixture_file_upload.rb

Closes #5728 
Characterizes all three primary file types if they exist on the FileSet.

Characterize original_file, preservation_file, and intermediate_file

---

app/decorators/file_set_decorator.rb
app/jobs/local_fixity_job.rb
app/models/file_set.rb
app/queries/deep_local_fixity_count.rb
spec/decorators/file_set_decorator_spec.rb
spec/jobs/local_fixity_job_spec.rb
spec/wayfinders/wayfinder_spec.rb

Check local fixity on all primary file types

---

app/services/pdf_generator/cover_page_generator.rb
spec/services/pdf_generator_spec.rb

PDF Coversheet should inherit some parent metadata for MVWs.

---

config/puma.rb

When updating puma it looks like this config option went away.

Fix Puma for rails s

---

app/assets/images/health-report-graphic.svg
app/assets/stylesheets/components/header.scss
app/assets/stylesheets/components/show.scss
app/decorators/valkyrie/resource_decorator.rb
app/helpers/application_helper.rb
app/helpers/fixity_dashboard_helper.rb
app/values/health_report.rb
app/values/health_report/cloud_fixity_check.rb
app/values/health_report/local_fixity_check.rb
app/views/catalog/_health_status.html.erb
app/views/catalog/_health_status_check.html.erb
app/views/catalog/_member_resources.html.erb
app/views/catalog/_resource_attributes_default.html.erb
app/views/catalog/show.html.erb
config/initializers/assets.rb
config/locales/en.yml
package.json
spec/controllers/catalog_controller_spec.rb
spec/decorators/scanned_resource_decorator_spec.rb
spec/values/health_report_spec.rb
spec/views/catalog/_members_multi_volume_work.html.erb_spec.rb
spec/views/catalog/_resource_attributes_default.html.erb_spec.rb
yarn.lock

Closes #5644 
Success: 
In progress: 
Failure:

Health Report

---

app/services/manifest_builder.rb
spec/factories/file_set.rb
spec/services/manifest_builder_spec.rb

refs #5391
This PR results in the following for the item under test, as minimally replicated in my local instance:
```json
"structures": [
{
"@type": "sc:Range",
"@id": "http://localhost:3000/concern/scanned_resources/05fb1c4a-4918-4688-ba1d-73135dfef570/manifest/range/r74d78bd3-0c9a-47b5-a0f0-589302256f8c",
"label": "Logical",
"viewingHint": "top",
"ranges": [
"http://localhost:3000/concern/scanned_resources/05fb1c4a-4918-4688-ba1d-73135dfef570/manifest/range/r51f566da-8d16-43d9-b09b-d44511877e40"
],
"canvases": []
},
{
"@type": "sc:Range",
"@id": "http://localhost:3000/concern/scanned_resources/05fb1c4a-4918-4688-ba1d-73135dfef570/manifest/range/r51f566da-8d16-43d9-b09b-d44511877e40",
"label": {
"@language": "ar",
"@value": "فائدة"
},
"ranges": [],
"canvases": [ …
```

Use imported language for structure label when rtl detected

---

app/services/file_appender.rb
spec/change_set_persisters/change_set_persister_spec.rb

Allow FileAppender to fail for derivatives.

---

Gemfile.lock
app/services/cloud_fixity.rb
config/initializers/sidekiq.rb

Fix CloudFixityJob queueing and update sidekiq-pro

---

Gemfile.lock

Fixes issue with redis version on staging and production machines.

Revert sidekiq-pro update

---

config/initializers/sidekiq.rb
config/redis.yml

Adds database number (set in FIGGY_REDIS_DB variable) to Redis url.

Add database to redis url

---

app/graphql/types/numismatics/monogram_type.rb
spec/graphql/types/numismatics/monogram_type_spec.rb

Add label to graphql Types::Numismatics::MonogramType

---

app/models/controlled_vocabulary.rb
app/services/pdf_generator/cover_page_generator.rb
spec/services/pdf_generator_spec.rb

Add holding location contact info to the cover page.

---

app/views/shared/_analytics.html.erb

Update Analytics to GA4

---

app/derivative_services/pdf_derivative_service.rb
spec/change_set_persisters/change_set_persister_spec.rb

Don't run cleanup_derivatives if there's no parent

---

.irbrc
.rubocop.yml

Add an irbrc file to turn off autocomplete in console

---

app/assets/stylesheets/viewer.scss

Prevents clipping of download option in UV when tabs are displayed

---

app/queries/find_fixity_events.rb

closes #5788
I tried this on staging. It didn't make a difference, but staging wasn't slow to begin with. The explain analyze looks really promising so I think it's worth merging and trying in production.

Combine all metadata query filters into one

---

app/services/event_generator/geoblacklight_event_generator.rb
spec/services/event_generator/geoblacklight_event_generator_spec.rb

Rescue document generation exceptions in GeoBlacklightEventGenerator

---

app/change_set_persisters/change_set_persister/create_deletion_marker.rb
spec/change_set_persisters/change_set_persister_spec.rb

Ensure deletion markers have titles

---

app/controllers/bulk_ingest_controller.rb
app/views/bulk_ingest/show.html.erb
spec/controllers/bulk_ingest_controller_spec.rb
spec/views/bulk_ingest/show.html.erb_spec.rb

Add rights statement to bulk ingest

---

app/change_sets/numismatics/reference_change_set.rb
spec/services/deletion_marker_service_spec.rb

They weren't being preserved.
Closes #5847

Fix restoring Numismatic::References

---

app/values/health_report/cloud_fixity_check.rb
app/values/health_report/local_fixity_check.rb
spec/values/health_report_spec.rb

Health report should do EphemeraProject shallowly.

---

app/values/ark.rb
spec/change_set_persisters/change_set_persister/apply_remote_metadata_spec.rb
spec/fixtures/files/catalog/99125494961606421.jsonld

Closes #5860
I had to remake the resource to make this work, but I confirmed it does!

Strip /pdf from the end of imported ARKs

---

app/queries/find_by_property.rb
app/services/image_report_generator.rb
app/services/image_report_generator/collection_report.rb
spec/queries/find_by_property_spec.rb
spec/services/image_report_generator_spec.rb

Relates to #5780, #5677, and #5627

Add a report generator for image counts.

---

app/jobs/cloud_fixity_job.rb
spec/jobs/cloud_fixity_job_spec.rb

Only query on child_id for binary nodes.

---

app/change_sets/ephemera_field_change_set.rb
spec/services/deletion_marker_service_spec.rb

Fix restoring EphemeraFields from preservation.

---

app/wayfinders/numismatics/artist_wayfinder.rb
app/wayfinders/numismatics/citation_wayfinder.rb
app/wayfinders/numismatics/provenance_wayfinder.rb
spec/factories/numismatics/numismatic_artist.rb
spec/factories/numismatics/numismatic_provenance.rb
spec/wayfinders/numismatics/artist_wayfinder_spec.rb
spec/wayfinders/numismatics/citation_wayfinder_spec.rb
spec/wayfinders/numismatics/provenance_wayfinder_spec.rb

Ensure numismatics wayfinders return nil instead of raising error

---

app/change_sets/collection_change_set.rb
spec/services/deletion_marker_service_spec.rb

Preserve collections

---

app/services/manifest_builder.rb
app/wayfinders/scanned_map_wayfinder.rb
spec/factories/file_set.rb
spec/factories/scanned_map.rb
spec/services/manifest_builder_spec.rb

Allow download of geotiff from scanned map with single raster child

---

.circleci/config.yml

By hard coding a version of chrome that doesn't 404

Fix the build

---

app/javascript/viewer/uv_manager.js

Fixes the hidden footer by making the function that adds tabs asynchronous.
closes #5709

Fixes hidden footer in UV when tabs are present

---

app/jobs/cloud_fixity_job.rb

Clarify preserved resource from preservation object in notice and code

---

README.md

I think I wrote these things while debugging some stuff with @sdellis. They might be helpful.

Add TiTiler stuff to readme

---

app/jobs/cloud_fixity_job.rb

Clear out previous violations of unique constraint on current events

---

config/initializers/valkyrie.rb
spec/services/preserver_spec.rb

Closes #5905
Draft until I get https://figgy-staging.princeton.edu/catalog/parent/052b7642-032f-4ad6-ab23-0403c3a84e2c/eed98fc1-0141-426e-bf52-d5f44c7aec41 all set up to test this.
Edit: Marked as ready for review - the above item preserved successfully only after this PR was deployed.

Set GCS timeout to be really high.

---

app/decorators/file_set_decorator.rb
app/helpers/fixity_dashboard_helper.rb
app/nested_resources/file_metadata.rb
app/views/catalog/_file_detail.html.erb
spec/features/file_set_spec.rb
spec/helpers/fixity_dashboard_helper_spec.rb
spec/nested_resources/file_metadata_spec.rb
spec/support/capybara_selenium.rb

Closes: #5685 
The "Test Manually" feature implementation has been split out into a separate ticket: https://github.com/pulibrary/figgy/issues/5916

Fileset Fixity UI Implementation

---

app/controllers/ephemera_terms_controller.rb
spec/change_set_persisters/change_set_persister/cleanup_terms_spec.rb
spec/controllers/ephemera_terms_controller_spec.rb

Prevent deletion of EphemeraTerm if used in EphemeraFolder

---

app/controllers/ephemera_vocabularies_controller.rb
app/wayfinders/ephemera_vocabulary_wayfinder.rb
spec/controllers/ephemera_vocabularies_controller_spec.rb

Do not allow deletion of vocabularies with members

---

app/controllers/ephemera_projects_controller.rb
spec/controllers/ephemera_projects_controller_spec.rb

Do not allow deletion of ephemera projects with members

---

spec/services/deletion_marker_service_spec.rb

Add tests for resource restoration scenarios

---

app/change_sets/change_set.rb
spec/change_sets/scanned_resource_change_set_spec.rb

Preserve flagged resources

---

app/services/geo_discovery/abstract_document.rb
app/services/geo_discovery/document_builder/references_builder.rb
app/services/geo_discovery/document_builder/wxs.rb
app/services/geo_discovery/geoblacklight_document.rb
spec/services/geo_discovery/document_builder_spec.rb

Remove WMS and WCS references from raster resource documents

---

app/change_sets/change_set_workflow.rb
app/controllers/resources_controller.rb
app/javascript/figgy/figgy_boot.js
app/views/layouts/application.html.erb
app/views/shared/_confetti.html.erb
package.json
spec/features/scanned_resource_spec.rb
spec/support/shared/workflow_specs.rb
yarn.lock

This was a feature request from Lauren Bell and others in the studio. It's to celebrate the moment when a resource becomes accessible to users, which studio techs have said is the most rewarding part of working in figgy.

Make figgy explode with confetti when objects are marked complete

---

app/services/box_mover.rb
lib/tasks/bulk.rake
spec/services/box_mover_spec.rb

Add a rake task to move boxes.

---

config/locales/en.yml

Add health status repairing translation

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/delete_referenced.rb
spec/change_sets/preservation_object_change_set_spec.rb
spec/models/cdl/resource_charge_list_spec.rb

Delete events when PreservationObjects are deleted.

---

app/values/health_report/cloud_fixity_check.rb
spec/features/file_set_spec.rb
spec/values/health_report_spec.rb

Add spec for file set cloud fixity failure and get shallow status

---

.lando.yml

Use redis 7

---

docs/technical/preservation/deletion.md

Document deletion behavior w/r/t preservation

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/append_to_parent.rb
app/change_set_persisters/change_set_persister/propagate_ocr_language.rb
spec/change_set_persisters/change_set_persister/propagate_ocr_language_spec.rb

Propagate OCR for Multi-Volume Works

---

.lando.yml
README.md
spec/support/capybara_selenium.rb

I couldn't get selenium/webdrivers working locally, and this takes local environment out of the equation.

Use Selenium Standalone instead of Webdrivers

---

app/models/preservation_object.rb
app/services/preserver.rb
spec/services/preserver_spec.rb

Add lock token to preservation object as `metadata_version`

---

app/assets/stylesheets/components/file_manager.scss
app/helpers/file_manager_helper.rb
app/javascript/figgy/derivative_form.js
app/queries/deep_cloud_fixity_count.rb
app/queries/deep_local_fixity_count.rb
app/views/base/_file_manager_member.html.erb
app/views/raster_resources/_geo_extract_metadata.html.erb
app/views/scanned_maps/_geo_extract_metadata.html.erb
app/views/vector_resources/_geo_extract_metadata.html.erb
app/wayfinders/base_wayfinder.rb
spec/factories/event.rb
spec/features/file_manager_spec.rb
spec/views/scanned_resources/file_manager.html.erb_spec.rb

Adds error notifications to File Manager files

---

.github/ISSUE_TEMPLATE/bad-tiff.md

Created a new template for Bad TIFFs, to help make tickets more actionable.

Update issue templates - Bad TIFF

---

app/jobs/cloud_fixity_job.rb
spec/jobs/cloud_fixity_job_spec.rb

Confirm the lock token for the resource matches the metadata version on the PreservationObject

---

app/controllers/catalog_controller.rb
app/helpers/catalog_helper.rb
app/models/search_builder.rb
app/views/catalog/_display_children_widget.html.erb
app/views/shared/_site_search.html.erb
config/locales/blacklight.en.yml
spec/controllers/catalog_controller_spec.rb
spec/helpers/catalog_helper_spec.rb

Fixes DeletionMarker search and improves UI.
Closes #6030 
---

Show children in search results with parameter rather than facet

---

app/services/preserver/preservation_checker.rb
lib/tasks/preservation.rake
spec/services/preservation_status_reporter_spec.rb

Preservation Status Reporter fails for unsynced preservation objects

---

spec/features/file_manager_spec.rb

Add a feature spec for FileSet restoration.

---

app/change_set_persisters/change_set_persister/create_deletion_marker.rb
spec/change_set_persisters/change_set_persister_spec.rb

Don't create DeletionMarkers for events.

---

app/jobs/cloud_fixity_job.rb
spec/jobs/cloud_fixity_job_spec.rb

Don't check metadata version if there's no lock token.

---

app/change_set_persisters/change_set_persister/create_deletion_marker.rb
app/change_sets/deletion_marker_change_set.rb
app/decorators/deletion_marker_decorator.rb
app/indexers/collection_indexer.rb
app/models/deletion_marker.rb
spec/models/collection_indexer_spec.rb

Index DeletionMarker deleted resource collection titles

---

app/services/migrations/metadata_represerver.rb
app/services/preserver.rb
spec/services/migrations/metadata_represerver_spec.rb

Add a MetadataPreserver to re-preserve metadata for everything in Figgy.

---

app/derivative_services/geo_derivatives/processors/gdal.rb

Set GeoTIFF derivate output to Byte data type

---

app/controllers/playlists_controller.rb
app/controllers/scanned_resources_controller.rb
spec/controllers/playlists_controller_spec.rb
spec/controllers/scanned_resources_controller_spec.rb

Prevent deletion of playlist with tracks  and recordings with tracks in playlist

---

app/javascript/components/issue_monograms.vue
spec/features/nusimatic_issue_spec.rb

Fix javascript to allow detaching monograms

---

.circleci/config.yml
.tool-versions
app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/viewer/leaflet_viewer.js

Update to Node 18.

---

README.md
bin/setup
bin/setup_asdf

updated setup script to work better with new M1 Mac processors

Updated setup script and readme

---

.circleci/config.yml
app/views/shared/_brand_bar.html.erb
spec/features/root_spec.rb
spec/support/capybara_selenium.rb

Add a documentation link to the homepage 

---

app/change_sets/ephemera_folder_change_set_base.rb
spec/features/ephemera_folder_spec.rb
spec/support/shared/ephemera_folder_change_set_specs.rb

This is all it takes in Figgy. I'm gonna look at how dpul responds; keeping it in draft for now.
closes #5886

Make description multi-valued for ephemera folders

---

lib/tasks/migrate.rake

Update collection_members_with_children task to run on a single collection

---

app/queries/memory_efficient_all_query.rb
app/services/preservation_status_reporter.rb
lib/tasks/preservation.rake
spec/services/preservation_status_reporter_spec.rb

Add CSV path param to  PreservationStatusReporter

---

docs/technical/incident_scenarios/isilon_failure.md

Document Isilon Failure Recovery Strategy

---

app/services/manifest_builder/logo_builder_v3.rb
app/services/manifest_builder/manifest_service_locator_v3.rb
spec/services/manifest_builder_spec.rb

Make logo an array for iiif3 manifests 

---

app/services/manifest_builder/canvas_rendering_builder.rb
app/services/manifest_builder/start_canvas_builder.rb
spec/services/manifest_builder/canvas_builder_v3_spec.rb
spec/services/manifest_builder_spec.rb

Use cached parent in canvas builder

---

lib/tasks/report.rake

Use new Ephemera Subjects vocab label

---

app/services/preservation_status_reporter.rb
spec/services/preservation_status_reporter_spec.rb

Replace birthtime method with mtime

---

.eslintrc.js
Gemfile.lock
app/javascript/components/OrderManager.vue
app/javascript/components/OrderManagerControls.vue
app/javascript/components/OrderManagerFilesetForm.vue
app/javascript/components/OrderManagerFilesetsForm.vue
app/javascript/components/OrderManagerResourceForm.vue
app/javascript/components/OrderManagerToolbar.vue
app/javascript/components/ajax-select.vue
app/javascript/components/document_adder.vue
app/javascript/components/file-uploader.vue
app/javascript/components/file_browser/directory_contents.vue
app/javascript/components/file_browser/file_browser.vue
app/javascript/components/issue_monograms.vue
app/javascript/components/playlist_member.vue
app/javascript/components/playlist_members.vue
app/javascript/test/viewer/cdl_timer.spec.js
app/javascript/test/viewer/leaflet_viewer.spec.js
app/javascript/test/viewer/uv_manager.spec.js
package.json
yarn.lock

Work towards #4482 
- Update vite and vitest
- Update npm
- Fix javascript tests
- Update eslint

Update vite, npm, and eslint to resolve security issues

---

app/services/preserver/preservation_checker.rb

Make preserved? method more resilient.

No errors when token is missing

---

app/characterization_services/null_characterization_service.rb
spec/characterization_services/null_characterization_service_spec.rb

Run GenerateChecksumJob in NullCharacterizationService

---

app/services/cloud_fixity.rb
spec/services/cloud_fixity_spec.rb

Re-enable cloud fixity checks

---

app/models/remote_record.rb
spec/models/remote_record_spec.rb

changed dots to dashes in finding aids links

---

app/services/cloud_fixity.rb
spec/services/cloud_fixity_spec.rb

Reverts pulibrary/figgy#6140
It's still costing ~ $300/day.
This is deployed to prod.

Revert "Re-enable cloud fixity checks"

---

app/jobs/create_derivatives_job.rb
spec/change_set_persisters/change_set_persister/preserve_resource_spec.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/derivative_services/external_metadata_derivative_service_spec.rb

Closes https://github.com/pulibrary/figgy/issues/6150

Fix resource metadata going out of sync w/ preservation from creating derivatives.

---

docs/technical/preservation/audits.md
lib/tasks/preservation.rake

Document the preservation audit process

---

.circleci/config.yml
Gemfile
Gemfile.lock
spec/support/capybara_selenium.rb

- Update browser-tools orb and stop specifying chrome version
- Remove webdrivers and user selenium-webdriver, update capybara
closes #6173

Use more sustainable google chrome install / webdriver setup

---

app/change_set_persisters/change_set_persister/mint_identifier.rb
app/services/identifier_service.rb
spec/change_set_persisters/change_set_persister/mint_identifier_spec.rb

Mock EZ Identifier service when in development

---

app/controllers/catalog_controller.rb
app/indexers/facet_indexer.rb
app/nested_resources/file_metadata.rb
spec/factories/file_set.rb
spec/indexers/facet_indexer_spec.rb

- Add file type facet for resources with video files
- Add file type facet for resources with audio files
- Add file type facet for raster mosaics
Closes #6188

Add file type facet

---

architecture-decisions/0013-captions-attach.md
docs/ux/use_cases.md

Attaching captions ADR

---

docs/technical/storage-locations.md

Document all of Figgy's storage & backup locations.

---

.rubocop.yml
app/models/file_set.rb
app/nested_resources/file_metadata.rb
app/services/file_appender.rb
spec/factories/scanned_resource.rb
spec/fixtures/files/caption.vtt
spec/models/file_set_spec.rb

This sets up future AV PRs by adding a factory for us to use in them.

Add a factory for Videos w/ Transcripts

---

.rubocop.yml
app/change_sets/caption_change_set.rb
app/controllers/file_metadata_controller.rb
app/helpers/application_helper.rb
app/nested_resources/file_metadata.rb
app/views/catalog/_members_file_set.html.erb
app/views/file_metadata/_form.html.erb
app/views/records/edit_fields/_caption_language.html.erb
app/views/records/edit_fields/_file.html.erb
config/routes.rb
spec/controllers/file_metadata_controller_spec.rb
spec/factories/scanned_resource.rb
spec/features/file_set_spec.rb
spec/routing/file_set_spec.rb

Attach Caption UI

---

app/nested_resources/file_metadata.rb
app/views/catalog/_members_file_set.html.erb
spec/features/file_set_spec.rb

Add language label to caption display.

---

app/change_sets/caption_change_set.rb
app/nested_resources/file_metadata.rb
app/views/records/edit_fields/_original_language_caption.html.erb
spec/features/file_set_spec.rb

Add original_language_caption property to Caption form.

---

app/views/catalog/_members_file_set.html.erb
spec/features/file_set_spec.rb

Add "Attach Caption" button to file set show page.

---

app/nested_resources/file_metadata.rb
app/views/catalog/_members_file_set.html.erb
spec/features/file_set_spec.rb

Display "(Original)" in UI when it's original language.

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/cleanup_deleted_files.rb
app/change_set_persisters/change_set_persister/remove_file_metadata.rb
app/change_sets/file_set_change_set.rb
app/controllers/file_metadata_controller.rb
app/validators/deleted_file_metadata_validator.rb
app/views/catalog/_file_detail.html.erb
app/views/catalog/_members_file_set.html.erb
config/routes.rb
spec/controllers/file_metadata_controller_spec.rb
spec/factories/file_set.rb
spec/features/file_set_spec.rb

Add "Delete" to Captions.

---

app/assets/stylesheets/components/file_manager.scss
app/models/file_set.rb
app/views/base/_file_manager_member.html.erb
spec/factories/file_set.rb
spec/models/file_set_spec.rb
spec/views/scanned_resources/file_manager.html.erb_spec.rb

Closes https://github.com/pulibrary/figgy/issues/6179

Add "Attach Missing Captions" link. 

---

config/deploy/production.rb
config/deploy/staging.rb

Migrate to Jammy

---

docs/technical/harvesting-figgy.md

I thought I had written a detailed set of instructions for navigating IIIF to harvest content from Figgy. But these instructions were much briefer than I remembered.
This PR expands the instructions to give more guidance about what info are available.

Harvesting from Figgy using IIIF

---

Gemfile
Gemfile.lock
app/checks/aspace_status.rb
app/checks/solr_status.rb
config/initializers/health_monitor.rb
config/routes.rb
spec/checks/solr_status_spec.rb
spec/requests/health_check_spec.rb

Add health endpoint

---

config/environments/production.rb

Use memcached from figgy-web-prod1

---

.rubocop.yml
app/graphql/types/embed_type.rb
app/models/file_set.rb
app/services/embed.rb
spec/graphql/figgy_schema_spec.rb
spec/graphql/types/scanned_resource_type_spec.rb

Lets us query for videos.
Closes #6233

Add media_type to the Embed GraphQL type.

---

app/services/manifest_builder/logo_builder_v3.rb
app/services/manifest_builder_v3/manifest_service_locator.rb
app/services/manifest_builder_v3/see_also_builder.rb
spec/services/manifest_builder_spec.rb
spec/services/manifest_builder_v3/see_also_builder_spec.rb

Work in process.
Work towards #6243

Fixes to IIIF v3 manifests

---

app/decorators/caption_decorator.rb
app/values/hls_manifest/primary.rb
spec/controllers/downloads_controller_spec.rb
spec/controllers/file_metadata_controller_spec.rb
spec/factories/scanned_resource.rb

Make HLS manifest caption default, name values accurate

---

spec/support/capybara_selenium.rb

Fix RUN_IN_BROWSER=true

---

app/change_sets/change_set.rb
app/change_sets/file_set_change_set.rb
app/change_sets/video_file_set_change_set.rb
app/models/file_set.rb
app/views/records/edit_fields/_captions_required.html.erb
spec/features/file_set_spec.rb

Add captions_required field to FileSet and Video FileSet forms

---

app/decorators/valkyrie/resource_decorator.rb
app/models/ability.rb
app/queries/find_uncaptioned_members.rb
spec/models/ability_spec.rb
spec/queries/find_uncaptioned_members_spec.rb

Hide uncaptioned videos.

---

app/javascript/test/viewer/uv_manager.spec.js
app/javascript/viewer/uv_manager.js
app/services/embed.rb
spec/graphql/types/scanned_resource_type_spec.rb

Fixes issue where tilejson is checked for even when not a mosaic:

Leaflet viewer mosaic only

---

app/views/bulk_ingest/show.html.erb
app/views/records/edit_fields/_captions_required.html.erb
package.json
spec/features/file_set_spec.rb
spec/support/capybara_selenium.rb
yarn.lock

- Add video caption requirement help modal
- Use same lux icon for bulk ingest tooltip
closes #6187

Add video caption requirement help modal

---

app/models/file_set.rb
spec/change_set_persisters/change_set_persister_spec.rb

Preserve Captions

---

.rubocop.yml
app/services/manifest_builder/canvas_rendering_builder.rb
spec/services/manifest_builder_spec.rb

Add rendering for AV materials to the manifest builder.

---

app/derivative_services/hocr_derivative_service.rb
app/jobs/run_ocr_job.rb
spec/derivative_services/hocr_derivative_service_spec.rb
spec/jobs/run_ocr_job_spec.rb

Don't run OCR for file sets that don't have ocr_language

---

app/services/manifest_builder.rb
config/config.yml
config/initializers/figgy.rb
spec/figgy_config_spec.rb
spec/services/manifest_builder_spec.rb

Enable video manifests in Production.

---

app/checks/rabbit_mq_status.rb
app/services/messaging_client.rb
config/initializers/health_monitor.rb
spec/requests/health_check_spec.rb
spec/support/stub_rabbit.rb

Monitor RabbitMQ

---

app/checks/smtp_status.rb
config/initializers/health_monitor.rb
spec/requests/health_check_spec.rb

References pulibrary/lae-blacklight#381

Add pony express monitor.

---

app/checks/file_watcher_status.rb
config/initializers/health_monitor.rb
spec/requests/health_check_spec.rb

Add pdf file watcher health status check

---

app/channels/application_cable/channel.rb
app/channels/application_cable/connection.rb
app/javascript/channels/consumer.js
config/cable.yml
package.json
spec/channels/application_cable/channel_spec.rb
spec/channels/application_cable/connection_spec.rb
vite.config.ts
yarn.lock

Install ActionCable.

---

app/change_set_persisters/change_set_persister.rb
app/change_set_persisters/change_set_persister/cleanup_mosaic.rb
app/services/tile_metadata_service.rb
spec/change_set_persisters/change_set_persister/cleanup_mosaic_spec.rb
spec/change_set_persisters/change_set_persister_spec.rb
spec/factories/raster_resource.rb
spec/factories/scanned_map.rb

Cleanup mosaic.json files on resource delete

---

app/javascript/viewer/uv_manager.js
package.json
yarn.lock

See: https://github.com/samvera-labs/clover-iiif/pull/191

Update Clover to 2.7.0 for canvas auto height improvement

---

app/controllers/concerns/pdfable.rb
app/services/pdf_service.rb
app/views/layouts/download.html.erb
config/config.yml
config/initializers/figgy.rb
spec/shared_specs/controllers/concerns/pdfable.rb

Add a feature flipper for backgrounding PDF generation.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/pdf.scss
app/controllers/concerns/pdfable.rb
app/views/base/pdf.html.erb
spec/shared_specs/controllers/concerns/pdfable.rb

Add layout for PDF loading page.

---

app/views/catalog/_home_text.html.erb

add audio and video to scanned resources description on home page

---

app/javascript/figgy/download_notifier.js
app/javascript/figgy/figgy_boot.js
app/javascript/test/download_notifier.spec.js
app/views/base/pdf.html.erb

Add Javascript to update the progress bar for UI messages and redirect.

---

app/channels/generate_file_notification_channel.rb
app/javascript/figgy/download_notifier.js
app/jobs/generate_pdf_job.rb
app/services/pdf_generator.rb
app/views/layouts/download.html.erb
config/cable.yml
config/config.yml
config/deploy.rb
config/environments/production.rb
config/environments/staging.rb
spec/channels/generate_file_notification_channel_spec.rb
spec/jobs/generate_pdf_job_spec.rb
spec/rails_helper.rb

Broadcast messages on PDF Generation

---

app/controllers/concerns/pdfable.rb
config/config.yml
config/environments/staging.rb
config/initializers/figgy.rb
spec/requests/catalog_spec.rb
spec/requests/scanned_map_spec.rb
spec/requests/scanned_resource_spec.rb
spec/shared_specs/controllers/concerns/pdfable.rb

Don't enqueue PDF generation twice.

---

config/deploy/production.rb

Fixes background PDF generation in Figgy production.
Fixes https://app.honeybadger.io/projects/53391/faults/106575613

Workers need assets to generate PDFs

---

app/services/migrations/child_resource_collection_migrator.rb
lib/tasks/migrate.rake
spec/services/migrations/child_resource_collection_migrator_spec.rb

Optimize and test child collection members migration task

---

config/initializers/health_monitor.rb

removed honeybadger health monitor notification

---

app/adapters/retrying_disk_adapter.rb
config/initializers/valkyrie.rb
spec/adapters/retrying_disk_adapter_spec.rb
spec/controllers/bulk_ingest_controller_spec.rb

Disk adapter should retry on mount errors up to 5 times.

---

spec/services/manifest_builder/by_resource_type/manifest_builder_collection_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_ephemera_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_mvw_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_numismatic_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_maps_spec.rb
spec/services/manifest_builder/by_resource_type/manifest_builder_video_spec.rb
spec/services/manifest_builder_spec.rb

 split up more manifest builder specs

---

app/jobs/bulk_update_job.rb
app/mailers/collections_mailer.rb
app/services/cdl/charge_manager.rb
app/views/collections_mailer/owner_report.html.erb
lib/tasks/figgy.rake
spec/jobs/bulk_update_job_spec.rb
spec/mailers/collections_mailer_spec.rb
spec/mailers/previews/collections_mailer_preview.rb

Closes #6332
- **Deliver BulkUpdateMailers later**
- **Deliver CollectionsMailers later**
- **Deliver CDL:HoldMailers later**

Background emails

---

Gemfile.lock
spec/services/manifest_builder_spec.rb

refs #5747
There is probably a bit more to do here.

Reorganize manifest_builder_spec for clarity

---

app/checks/file_watcher_status.rb
spec/requests/health_check_spec.rb

Only fail file watcher health check for valid files

---

app/adapters/retrying_disk_adapter.rb
spec/adapters/retrying_disk_adapter_spec.rb

We saw more errors here:
https://app.honeybadger.io/projects/53391/faults/105517424/01HW7WJ9QY1PT4HDXSWM7P9T2B?page=1
More follow on from #6338

Retry file upload on EIO errors.

---

app/queries/all_mms_resources_query.rb
app/queries/find_by_source_metadata_identifier.rb
app/services/ark_mismatch_reporter.rb
config/initializers/valkyrie.rb
lib/tasks/report.rake
spec/queries/all_mms_resources_query_spec.rb
spec/services/ark_mismatch_reporter_spec.rb
spec/services/image_report_generator_spec.rb

Add report for resources with an alma source metadata id but a finding aids ark target

---

docs/technical/preservation/audits.md

Add answer to "will there be output?" in audits.md

---

app/services/identifier_service.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/services/identifier_service_spec.rb

Allow modifying the ark whenever metadata is updated

---

app/javascript/figgy/save_and_ingest_handler.js
app/views/base/_form_progress.html.erb

Proof of concept of Find Ingest Folder.

---

app/derivative_services/pdf_derivative_service.rb
spec/derivative_services/pdf_derivative_service_spec.rb

Clear error messages if pdf derivative generation is successful

---

app/views/catalog/_health_status_check.html.erb

Fix health check spinner

---

app/views/reports/collection_item_and_image_count.html.erb
spec/features/reports_spec.rb

Fix collection report id input and date picker

---

README.md
bin/setup
bin/setup_asdf

- **Add asdf python plugin to setup script**
- **Add M-series processor instructions for PGGSSENCMODE**
- **Install correct bundler version in setup**
- **Update language on new mac processors**

Update setup scripts and instructions

---

app/assets/stylesheets/components/file_manager.scss
app/assets/stylesheets/components/form.scss

updated styling of buttons related to vue3 upgrades

---

app/assets/stylesheets/application.scss
app/javascript/components/ajax-select.vue
app/javascript/entrypoints/application.js
app/javascript/helpers/setup_ajax_select.js
package.json
spec/features/nusimatic_issue_spec.rb
yarn.lock

Closes #6423
Issues are related to Vue3 upgrade and new version of vue-select componenet.

Fix Vue components in numismatics forms

---

config/environments/production.rb

Fix Mail TLS for Production

---

app/controllers/users_controller.rb
spec/controllers/users_controller_spec.rb

Add user shouldn't guess an email for guest users.

---

app/controllers/scanned_resources_controller.rb
app/services/manifest_builder.rb
spec/controllers/scanned_resources_controller_spec.rb

Scanned resources need to generate V3 manifests if it has an AV file set member.
Closes #6451

Fix Video manifests

---

app/controllers/ephemera_folders_controller.rb
spec/controllers/ephemera_folders_controller_spec.rb

Support video manifests for videos.

---

config/environments/production.rb

The new one isn't sending mail reliably.

Revert mailer to use old Pony Express server.

---

Gemfile.lock
config/initializers/honeybadger_downtime_hook.rb
spec/honeybadger_check_spec.rb

Add honeybadger downtime hook

---

Gemfile.lock
app/models/concerns/linked_data/linked_ephemera_folder.rb
spec/controllers/catalog_controller_spec.rb
spec/models/linked_data/linked_ephemera_folder_spec.rb

update emphemera folders to display height width in cm

---

app/services/cdl/eligible_item_service.rb
config/config.yml
config/initializers/figgy.rb
spec/services/cdl/eligible_item_service_spec.rb

Disable CDL via feature flag.

---

app/javascript/viewer/uv_manager.js
config/locales/en.yml
spec/graphql/figgy_schema_spec.rb

update harmful content link

---

app/javascript/viewer/uv_manager.js

update rights and permissions url

---

app/models/controlled_vocabulary.rb
spec/fixtures/files/holding_locations_http.json
spec/models/controlled_vocabulary/holding_location_spec.rb

Bibdata suddenly started showing http:// instead of https://, and broke a bunch of resources. This makes it so Figgy won't care.

Disregard protocol for holding location.

---

app/assets/stylesheets/base/typography.scss
app/components/breadcrumb_component.html.erb

Closes #6502
Screenshots taken in Firefox.

Set font to be verdana for RTL in forms/breadcrumb.

---

app/assets/stylesheets/base/typography.scss

Don't increase size of text in boxes.

---

app/services/file_set_service.rb
lib/tasks/file_sets.rake
spec/services/file_set_service_spec.rb

Add service and task to delete all file sets from a resource

---

Gemfile.lock
app/monitors/aspace_status.rb
config/initializers/health_monitor.rb
spec/requests/health_monitor_spec.rb

They've asked us to reduce our traffic.
see also pulibrary/pulfalight#1452

Remove aspace health monitor

---

app/change_sets/change_set.rb
app/change_sets/ephemera_box_change_set.rb
app/change_sets/numismatics/coin_change_set.rb
app/change_sets/numismatics/issue_change_set.rb
app/change_sets/raster_resource_change_set.rb
app/change_sets/recording_change_set.rb
app/change_sets/scanned_resource_change_set.rb
app/change_sets/simple_change_set.rb
app/change_sets/vector_resource_change_set.rb
spec/change_sets/raster_resource_change_set_spec.rb
spec/change_sets/recording_change_set_spec.rb
spec/change_sets/vector_resource_change_set_spec.rb
spec/shared_specs/change_sets/change_set.rb

Update default rights statement for all resources

---

app/jobs/bulk_update_job.rb
app/views/bulk_edit/resources_edit.html.erb
spec/features/bulk_edit_spec.rb

Add downloadable to bulk edit.

---

app/queries/all_mms_resources_query.rb
spec/queries/all_mms_resources_query_spec.rb

Add created_at range to all_mms_resources query

---

app/services/local_ingester.rb

Don't check catalog for record success on bulk ingest

---

app/values/tile_path.rb
spec/controllers/tile_metadata_controller_spec.rb
spec/services/geo_discovery/document_builder_spec.rb
spec/values/tile_path_spec.rb

Update TiTiler URLs

---

config/environments/production.rb

This reverts commit 0d16215503ef41743e5a28be14abc88cdcbf5c98.
It broke login :(
This has been deployed to staging and I'm currently deploying it to prod.

Revert "Don't force ssl"

---

config/environments/production.rb
config/initializers/new_framework_defaults.rb

Exclude health checks from force_ssl

---

.github/ISSUE_TEMPLATE/standard-issue-template-for-devs.md

Add a developer-centric issue template

---

app/assets/stylesheets/viewer.scss
app/javascript/viewer/uv_manager.js

Change viewer link and link text

---

app/assets/stylesheets/viewer.scss
app/javascript/viewer/uv_manager.js
config/locales/en.yml
spec/graphql/figgy_schema_spec.rb

Updates to content wording.
Related tickets:
Closes #6587 
Closes #6588

Wording Updates

---

config/deploy/staging.rb

staging1 is fixed; add it back as a deploy target

---

config/deploy/production.rb

Add groups for partial deployment to Figgy.

---

app/models/ability.rb
spec/models/ability_spec.rb

Allow download of video captions when not logged in

---

Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/schedule.rb

Run cleanup job on worker box

---

app/controllers/resources_controller.rb
spec/support/shared/workflow_specs.rb

Don't show confetti if resource has content warning.

Don't show confetti if resource has content warning

---

.circleci/config.yml

Use ci image for ci

---

docs/technical/preservation/audits.md

Would having these code samples be helpful next time?
closes #6627

Add more code examples to audit documentation

---

app/queries/memory_efficient_all_query.rb
spec/queries/memory_efficient_all_query_spec.rb

Memory Efficient All query should skip nil resources it finds.

---

app/controllers/downloads_controller.rb
spec/controllers/downloads_controller_spec.rb

Update CORS for audio and video streams

---

app/jobs/mosaic_job.rb
spec/jobs/mosaic_job_spec.rb

Closes #6634 
Tested on staging.

Fix MosaicJob Sidekiq query

---

config/initializers/health_monitor.rb
spec/requests/health_monitor_spec.rb

Increase sidekiq retries threshold to 22

---

app/change_sets/scanned_resource_change_set.rb
spec/controllers/scanned_resources_controller_spec.rb
spec/graphql/figgy_schema_spec.rb

Add content warning box to Scanned Resources.

---

lib/tasks/cdl.rake

Disable CDL rake tasks unless feature flag enabled.

---

lib/tasks/cdl.rake

Don't use return in Rake, it causes a LocalJumpError

---

app/indexers/project_indexer.rb
spec/indexers/project_indexer_spec.rb

Closes #6664
After this is done, do https://github.com/pulibrary/figgy/issues/6666

Index project for boxless folders.

---

config/environments/production.rb

refs pulibrary/princeton_ansible#5988

Move to new mail server

---

app/mailers/application_mailer.rb
spec/mailers/bulk_update_mailer_spec.rb
spec/mailers/collections_mailer_spec.rb

Update from address to be supported by new mail relay.

---

app/values/health_report/derivative_check.rb
app/values/health_report/video_caption_check.rb
spec/values/health_report_spec.rb

Don't check members for Ephemera Project health reports.

---

app/monitors/mount_status.rb
spec/requests/health_monitor_spec.rb

Monitor the correct illiad mount locations

---

app/controllers/numismatics/monograms_controller.rb
app/controllers/playlists_controller.rb
app/controllers/resources_controller.rb
app/controllers/scanned_resources_controller.rb
spec/change_sets/ephemera_folder_change_set_spec.rb
spec/controllers/collections_controller_spec.rb
spec/controllers/ephemera_folders_controller_spec.rb
spec/controllers/numismatics/monograms_controller_spec.rb
spec/controllers/playlists_controller_spec.rb
spec/requests/scanned_resource_spec.rb

Validate controller resource class

---

.gitignore
Gemfile
Gemfile.lock
app/adapters/fallback_disk_adapter.rb
app/adapters/retrying_disk_adapter.rb
config/config.yml
config/initializers/valkyrie.rb
spec/adapters/fallback_disk_adapter_spec.rb
spec/controllers/bulk_ingest_controller_spec.rb

This will allow us to change the name of our Isilon directory and swap to Tigerdata while files are copying.
Work towards #6699 
This also gets my personal dev environment working, my homebrew is all kinds of messed up.

Add a FallbackDiskAdapter

---

config/config.yml
config/deploy/staging.rb
config/initializers/valkyrie.rb

Add fallbacks for streaming & derivatives.

---

config/config.yml

Add fallback location for staging.

---

app/jobs/server_upload_job.rb
spec/jobs/server_upload_job_spec.rb

Don't retry ServerUploadJobs when the database disconnects

---

docs/technical/incident_scenarios/tigerdata_freeze.md

Add documentation about what to do when Tigerdata freezes up.

---

app/services/local_ingester.rb
spec/controllers/bulk_ingest_controller_spec.rb

Bulk ingest should queue into its own queue below default.

---

config/deploy.rb

Use bulk workers service

---

app/derivative_services/vips_derivative_service.rb
spec/derivative_services/vips_derivative_service_spec.rb

Clsoes #6790 
- **Reduce derivative image size more accurately**
- **Increase derivative image size if original image is smaller than pyramidal tile size**
- **Refactor image resizing**

Increase derivative image size if original image is smaller than pyramidal tile size

---

app/decorators/numismatics/coin_decorator.rb
app/services/nomisma.rb
lib/tasks/report.rake
spec/services/nomisma_spec.rb

Closes #6838 
First full Nomisma dump for review:
[princeton-nomisma.rdf.zip](https://github.com/user-attachments/files/22729426/princeton-nomisma.rdf.zip)

Generate rdf xml more efficiently
